### ISSUE TITLE
How to deal with multiple Indentify typedefs

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#10]
In Light app_main.cpp VSCode is complaining that type Identify is ambiguous. The compiler processes this without complaint.
Unfortunately VSCode does not show me the alternative definitions.  Maybe something to do with CHIP being part of project. Now esp-matter and CHIP namespaces both active.

![image](https://user-images.githubusercontent.com/14943/181825117-29048be4-f6c3-4131-84d6-e66219bb8be8.png)

**Comment by jonsmirl** [comment]
This is part of the problem:

static void on_identify_trigger_effect(Identify *identify)
{
    ESP_LOGI(TAG, "currenr identify trigger effect id: %d", identify->mCurrentEffectIdentifier);
}
using namespace chip::app::Clusters;

If you declare the namespace after on_identify_trigger_effect() it works. Move it in front and it becomes ambiguous.  I have not dug deep enough into this to understand why it is ambiguous.

using namespace chip::app::Clusters;
static void on_identify_trigger_effect(Identify *identify)
{
    ESP_LOGI(TAG, "currenr identify trigger effect id: %d", identify->mCurrentEffectIdentifier);
}

**Comment by chiragatal** [comment]
Ideally the namespace should have been at the top with others. I think this would be a problem of not rebasing before merging.

Regarding the ambiguity, I am not sure where it could be coming from. esp-matter has `identify` namespace for the cluster and attribute, but it is all lower case.

**Comment by jonsmirl** [comment]
This name space, 'using namespace chip::app::Clusters;' is also declaring Identity.

Move the that line above the trigger function and you can't compile anymore.

```
/home/jonsmirl/aosp/esp-matter/connectedhomeip/connectedhomeip/zzz_generated/app-common/app-common/zap-generated/cluster-enums.h:30:11: note: candidates are: 'namespace chip::app::Clusters::Identify { }'
 namespace Identify {
           ^~~~~~~~
In file included from /home/jonsmirl/aosp/esp-matter/components/esp_matter_identify/esp_matter_identify.h:18,
                 from /home/jonsmirl/aosp/esp-matter/examples/jds/main/app_main.cpp:15:
/home/jonsmirl/aosp/esp-matter/connectedhomeip/connectedhomeip/src/app/clusters/identify-server/identify-server.h:23:8: note:                 'struct Identify'
 struct Identify
        ^~~~~~~~
/home/jonsmirl/aosp/esp-matter/examples/jds/main/app_main.cpp:35:50: error: 'identify' was not declared in this scope
 static void on_identify_trigger_effect(Identify *identify)
                                                  ^~~~~~~~
/home/jonsmirl/aosp/esp-matter/examples/jds/main/app_main.cpp:35:50: note: maximum limit of 1000 namespaces searched for 'identify'
/home/jonsmirl/aosp/esp-matter/examples/jds/main/app_main.cpp:35:50: note: suggested alternative:
In file included from /home/jonsmirl/aosp/esp-matter/components/esp_matter/esp_matter.h:22,
                 from /home/jonsmirl/aosp/esp-matter/examples/jds/main/app_main.cpp:13:
/home/jonsmirl/aosp/esp-matter/components/esp_matter/esp_matter_attribute.h:194:11: note:   'esp_matter::cluster::identify'
 namespace identify {
           ^~~~~~~~
/home/jonsmirl/aosp/esp-matter/examples/jds/main/app_main.cpp: In function 'void app_main()':
/home/jonsmirl/aosp/esp-matter/examples/jds/main/app_main.cpp:111:30: error: 'on_identify_trigger_effect' was not declared in this scope
                              on_identify_trigger_effect);
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jonsmirl/aosp/esp-matter/examples/jds/main/app_main.cpp:111:30: note: maximum limit of 1000 namespaces searched for 'on_identify_trigger_effect'
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
```

**Comment by dhrishi** [comment]
Can you please confirm if you face issues with the latest code? Please close the issue if you don't.
