### ISSUE TITLE
Do i need to use  Access Control Cluster.xml in my PICS? (CON-1244)

### ISSUE THREAD

**Issue by FMistrorigo** [espressif/esp-matter#1000]
**Description**
In my project i defined the root node in this way:
![image](https://github.com/espressif/esp-matter/assets/159234713/e077c8ff-6cfe-48ba-8780-c869b0ff7aac)

node::config_t, in my esp_matter version, is defined inside esp_matter_endpoint in this way:
![image](https://github.com/espressif/esp-matter/assets/159234713/c660d680-e48c-4135-b320-239624bd8595)

endpoint::root_node::config_t root_node creates an endpoint with these clusters:
![image](https://github.com/espressif/esp-matter/assets/159234713/8a31fe3b-b97e-4b0d-bd12-941560ee9404)

As you can see the cluster access_control is defined, do i have to implement the Access Control Cluster.xml in my PICS even if I don't use it?

The access control is defined only with the cluster _revision attribute:
So in the test, when it tryes to read the attribute AccessContorlEntryChanged that is obviously not implemented but is Mandatory in the PICS if the Access Control Cluster as Server(ACL.S) is defined.
![image](https://github.com/espressif/esp-matter/assets/159234713/0de66d3a-7443-494b-9d62-efc36eb4ac80)

**Comment by VaishaliAvhale** [comment]
If you are performing Access Control or Access Control Enforcement Cluster's test case then you need to use Access Control Cluster.xml 

>>The access control is defined only with the cluster _revision attribute:

It is header file. 
You will get the actual implementation of the Access Control Cluster in [esp_matter_cluster.cpp ](https://github.com/espressif/esp-matter/blob/f0f94acb1071c6b4a707981ab31ddafdf2924012/components/esp_matter/esp_matter_cluster.cpp#L187)file.

**Comment by FMistrorigo** [comment]
Ok, so if the Access Control Cluster is defined but I **don't** implement it, I don't need to do the test with the Access Control Cluster.xml right?

**Comment by VaishaliAvhale** [comment]
The Root Node is mandatory for all device types, and the Access Control Cluster is a mandatory cluster of the Root Node. Therefore, it must be supported.

>> Root Node: This endpoint is akin to a "read me first" endpoint that describes itself and the other endpoints that make up the node.

**Comment by FMistrorigo** [comment]
Do I have to do the test or not?

The test checks all the mandatory attributes, but the SDK doesn't implement all of them.
![image](https://github.com/user-attachments/assets/7855d767-5369-43e9-b692-4b401425337f)

Di I need to implement all of them or can I skip the test?

**Comment by VaishaliAvhale** [comment]
Hi @FMistrorigo, It is a header file. You will find the actual implementation of the Access Control Cluster in the [esp_matter_cluster.cpp](https://github.com/espressif/esp-matter/blob/f0f94acb1071c6b4a707981ab31ddafdf2924012/components/esp_matter/esp_matter_cluster.cpp#L187) file.

All mandatory clusters, attributes, features, events, and commands are implemented in esp-matter. If you create a device type, you don't need to implement these mandatory elements yourself.

**Comment by dhrishi** [comment]
@FMistrorigo Please close this if your questions are answered

**Comment by FMistrorigo** [comment]
Thanks, I found the implementation and wrote some code to see the attribute of every cluster of every endpoint to check if the mandatory ones are present and now is fine.
