### ISSUE TITLE
is it possible to make a matter bridge with esp32 and control other devices with it ? (CON-1261)

### ISSUE THREAD

**Issue by Jeodus** [espressif/esp-matter#1014]
for example: ı want to add my two light to a matter bridge and add others to another mather bridge and ı want to control them with bridges.

lights should be any company.

**Comment by shubhamdp** [comment]
May be for general information about Matter bridge please check this [medium article](https://blog.espressif.com/matter-bridge-for-non-matter-devices-d3b7f003a004).

Back to your original question: Yes, it is possible to make Matter bridge with ESP32, few bridge examples here: [blemesh-bridge](https://github.com/espressif/esp-matter/tree/main/examples/bridge_apps/blemesh_bridge), [esp-now-bridge](https://github.com/espressif/esp-matter/tree/main/examples/bridge_apps/esp-now_bridge_light), and [zigbee-bridge](https://github.com/espressif/esp-matter/tree/main/examples/bridge_apps/zigbee_bridge).

You will have to develop the firmware as per your Light, eg: if you have a blemesh light then you can start with blemesh-bridge, and start customising as per your need.

Or, not sure if you are looking for Matter Controller, which can control any Matter accessory(eg: any Matter enabled Light), then you can find that example here: https://github.com/espressif/esp-matter/tree/main/examples/controller

---
Edits:
1. Updated the links in ƒor the apps

**Comment by dhrishi** [comment]
Closing as the questions are answered and references provided

**Comment by Sarika1544** [comment]
@shubhamdp 

> May be for general information about Matter bridge please check this [medium article](https://blog.espressif.com/matter-bridge-for-non-matter-devices-d3b7f003a004).
> 
> Back to your original question: Yes, it is possible to make Matter bridge with ESP32, few bridge examples here: [blemesh-bridge](https://github.com/espressif/esp-matter/tree/main/examples/blemesh_bridge), [esp-now-bridge](https://github.com/espressif/esp-matter/tree/main/examples/esp-now_bridge_light), and [zigbee-bridge](https://github.com/espressif/esp-matter/tree/main/examples/zigbee_bridge).
> 
> You will have to develop the firmware as per your Light, eg: if you have a blemesh light then you can start with blemesh-bridge, and start customising as per your need.
> 
> Or, not sure if you are looking for Matter Controller, which can control any Matter accessory(eg: any Matter enabled Light), then you can find that example here: https://github.com/espressif/esp-matter/tree/main/examples/controller

Hi @shubhamdp ,
The links you have provided are not opening I am facing 404 - page not found when i click on these links [blemesh-bridge](https://github.com/espressif/esp-matter/tree/main/examples/blemesh_bridge), [esp-now-bridge](https://github.com/espressif/esp-matter/tree/main/examples/esp-now_bridge_light), and [zigbee-bridge](https://github.com/espressif/esp-matter/tree/main/examples/zigbee_bridge).

**Comment by shubhamdp** [comment]
@Sarika1544 you can find these examples at `examples/bridge_apps/...` (Ref: https://github.com/espressif/esp-matter/tree/main/examples/bridge_apps)

**Comment by Sarika1544** [comment]
@shubhamdp i have flased the blemesh_bridge code but after flashing that code in esp32s3 i am unable to do the commissioning with chip-tool can you please tell me what is issue ?
And by flashing blemesh_bridge can i add any ble device in bridge and then control that non-matter ble-device via chip-tool?

**Comment by shubhamdp** [comment]
@Sarika1544 did you follow the steps outlined in https://github.com/espressif/esp-matter/blob/main/examples/bridge_apps/blemesh_bridge/README.md? Can you share the failures that you encountered? I'd suggest raising another issue with information that would help debug it.

**Comment by Sarika1544** [comment]
> [@Sarika1544](https://github.com/Sarika1544) did you follow the steps outlined in https://github.com/espressif/esp-matter/blob/main/examples/bridge_apps/blemesh_bridge/README.md? Can you share the failures that you encountered? I'd suggest raising another issue with information that would help debug it.

Hi @shubhamdp as you said i have raised another seperate issue [https://github.com/espressif/esp-matter/issues/1522#issue-3340455849](url) can you please help me to solve my issue?
