### ISSUE TITLE
Led have a glitch with light and light_switch example (CON-1265)

### ISSUE THREAD

**Issue by Eliostrim** [espressif/esp-matter#1017]
Hello there,

I made a Matter network with some ESP32 and everything works fine.

But i notice something strange. When i'm using the switch (ESP32 with light_switch example), the ESP32 (with light example) have a glitch when it turn on. (On -> Off -> On)

I see in the logs of the ESP32 with light example there is many cluster and attribute is used like onoff (0x6) and levelcontrol (0x8). This is that why there is this glitch.

I would like to avoid this glitch but i didn't find in theses examples where it's doing theses writing in attribute.

So, there is my question, how can I avoid this glitch ?

There is some logs
[turnlight.txt](https://github.com/user-attachments/files/16265632/turnlight.txt)

(don't worry about the purple/pink color)

Turn on -> 87137 to 90287
Turn off -> 158897 to 162027

I hope i give all the information.
If someone know how to solve it, feel free to share !

**Comment by jadhavrohit924** [comment]
@Eliostrim From the logs, I can see OnOff cluster is being updated only after receiving toggle command. See at 87227 and 159067.

**Comment by Eliostrim** [comment]
@jadhavrohit924 Yes, that's right, but there is also levelcontrol cluster updated at 87277,87357 and 159017. I think this glitch happen because both onoff and levelcontrol is called. I try to avoid that because i just want to use the onoff cluster without level control like if we push the on board button.

**Comment by Eliostrim** [comment]
Solved.

In app_driver.cpp, in fct appdriver_attribute_update

Maybe this is not the best way to do that but it's work. Hope it's help. There is my func



````
static bool ledState, ledPreviousState;
static uint8_t brightValue;
esp_err_t app_driver_attribute_update(app_driver_handle_t driver_handle, uint16_t endpoint_id, uint32_t cluster_id,
                                      uint32_t attribute_id, esp_matter_attr_val_t *val)
{
    esp_err_t err = ESP_OK;
    if (endpoint_id == light_endpoint_id) {
        
        led_indicator_handle_t handle = (led_indicator_handle_t)driver_handle;
        if (cluster_id == OnOff::Id) {
            if (attribute_id == OnOff::Attributes::OnOff::Id) {
                ledState = val->val.b;
                ledPreviousState = !ledState;
                //err = app_driver_light_set_power(handle, val);
                
                if(ledState){
                    val->val.u8 = brightValue;
                    err = app_driver_light_set_brightness(handle, val);
                }else{
                    val->val.u8 = 0;
                    err = app_driver_light_set_brightness(handle, val);
                }
            }
        } else if (cluster_id == LevelControl::Id) {
            if (attribute_id == LevelControl::Attributes::CurrentLevel::Id) {
                if(ledState && ledPreviousState){
                    err = app_driver_light_set_brightness(handle, val);
                    brightValue = val->val.u8;
                }
                ledPreviousState = !ledPreviousState;
            }
        } else if (cluster_id == ColorControl::Id) {
            if (attribute_id == ColorControl::Attributes::CurrentHue::Id) {
                if(ledState){
                    err = app_driver_light_set_hue(handle, val);
                }
            } else if (attribute_id == ColorControl::Attributes::CurrentSaturation::Id) {
                if(ledState){
                    err = app_driver_light_set_saturation(handle, val);
                }
                
            } else if (attribute_id == ColorControl::Attributes::ColorTemperatureMireds::Id) {
                if(ledState){
                    err = app_driver_light_set_temperature(handle, val);
                }
            }
        }        
    }
   return err;
}
