### ISSUE TITLE
How can ı use aggregator endpoint to bind it 2 or more device  (CON-1280)

### ISSUE THREAD

**Issue by Jeodus** [espressif/esp-matter#1030]
I’m very new to the Matter protocol.
 I’m using the Google Home app to control devices. I want to create an aggregator node and bind two or more different devices to it 
ı want to see all the devices collectively under the aggregator.

can someone lead me the way like how can ı begin. thanks  

I am a student and I want to improve myself in this field.

**Comment by jadhavrohit924** [comment]
@Jeodus Please look into the [blemesh bridge](https://github.com/espressif/esp-matter/tree/main/examples/blemesh_bridge) example.

**Comment by Jeodus** [comment]
![Screenshot from 2024-08-01 11-25-12](https://github.com/user-attachments/assets/21d0b3f2-0125-4ad8-a470-c6bf40b5c3fb)
thank you but my devices list like this ı want to saw my light under sw named bridge.

**Comment by Jeodus** [comment]
![WhatsApp Image 2024-08-01 at 14 13 01](https://github.com/user-attachments/assets/26b3fa4e-d118-4cf6-83b5-e6d3bda89152)
Thank you but my devices list like this. ı want to see my light device under sw named bridge.

**Comment by jadhavrohit924** [comment]
It should be under sw named bridge. Which commissioner are you using?

**Comment by Jeodus** [comment]
google home

**Comment by shubhamdp** [comment]
blemesh_bridge in esp-matter only works with on_off blemesh model, If you'd like please check the [readme](https://github.com/espressif/esp-matter/tree/main/examples/blemesh_bridge#ble-mesh-bridge) and give a try with blemesh on-off example from esp-idf.

**Comment by shubhamdp** [comment]
@Jeodus any update on this?

**Comment by dhrishi** [comment]
Closing this now
