### ISSUE TITLE
 matter How many Endpoints can theoretically be added dynamically in the official bridge-app example? (CON-1286)

### ISSUE THREAD

**Issue by WOLEN6914183** [espressif/esp-matter#1036]
I want to use the official briage-app example to implement many dynamic Endpoints, but after adding 16, the following error appears. What should I modify?

I (2033) chip[DL]: Added device Channel1 to dynamic endpoint 4 (index=0)
I (2043) chip[DL]: Added device Channel2 to dynamic endpoint 5 (index=1)
I (2053) chip[DL]: Added device Channel3 to dynamic endpoint 6 (index=2)
I (2053) chip[DL]: Added device Channel4 to dynamic endpoint 7 (index=3)
I (2063) chip[DL]: Added device Channel5 to dynamic endpoint 8 (index=4)
I (2073) chip[DL]: Added device Channel6 to dynamic endpoint 9 (index=5)
I (2073) chip[DL]: Added device Channel7 to dynamic endpoint 10 (index=6)
I (2083) chip[DL]: Added device Channel8 to dynamic endpoint 11 (index=7)
I (2093) chip[DL]: Added device Channel9 to dynamic endpoint 12 (index=8)
I (2103) chip[DL]: Added device Channel10 to dynamic endpoint 13 (index=9)
I (2103) chip[DL]: Added device Channel11 to dynamic endpoint 14 (index=10)
I (2113) chip[DL]: Added device Channel12 to dynamic endpoint 15 (index=11)
I (2123) chip[DL]: Added device Channel13 to dynamic endpoint 16 (index=12)
I (2133) chip[DL]: Added device Channel14 to dynamic endpoint 17 (index=13)
I (2143) chip[DL]: Added device Channel15 to dynamic endpoint 18 (index=14)
I (2143) chip[DL]: Added device Channel16 to dynamic endpoint 19 (index=15)
I (2153) chip[DL]: Failed to add device Channel17 to dynamic endpoint 20 with error 137
I (2163) chip[DL]: Failed to add device Channel18 to dynamic endpoint 20 with error 137
I (2173) chip[DL]: Failed to add device Channel19 to dynamic endpoint 20 with error 137
I (2183) chip[DL]: Failed to add device Channel20 to dynamic endpoint 20 with error 137
I (2183) chip[DL]: Failed to add device Channel21 to dynamic endpoint 20 with error 137
I (2193) chip[DL]: Failed to add device Channel22 to dynamic endpoint 20 with error 137
I (2203) chip[DL]: Failed to add device Channel23 to dynamic endpoint 20 with error 137

**Comment by shubhamdp** [comment]
bridge-app is configured with 16 dynamic endpoints hence you are seeing this error, Please check https://github.com/project-chip/connectedhomeip/blob/master/examples/bridge-app/esp32/CMakeLists.txt#L32 and change `-DCHIP_DEVICE_CONFIG_DYNAMIC_ENDPOINT_COUNT=16` to the number that you'd like to configure

**Comment by WOLEN6914183** [comment]
Thank
