### ISSUE TITLE
Realization of Zigbee Bridge + Controller on the same devkit (CON-1290)

### ISSUE THREAD

**Issue by Shivi-6** [espressif/esp-matter#1039]
**Describe the question/query that you have**
I have the ESP zigbee gateway dev kit (ESP32-S3 + ESP32-H2).

Is it possible to use the same kit as a controller + bridge at the same time?

**Additional context**
I tried the controller example with esp32-s3 and it was working. I then flashed the zigbee bridge example.
Now I want to have both on the same kit.
...

**Comment by wqx6** [comment]
Yes, you can integrate Zigbee bridge and controller on the same devkit. Note that the controller example is a client-only commissioner and the bridge should be a server, so you need to enable the server instance for that controller. 
```
CONFIG_ESP_MATTER_ENABLE_MATTER_SERVER=y
```

**Comment by Shivi-6** [comment]
I have already enabled the matter server and the matter controller in menuconfig.
But how does it work? Can I use the device console to commission both matter and zigbee end devices?

**Comment by wqx6** [comment]
If you are using Matter server as the controller + zigbee bridge, the you need to commission the controller to a Matter fabric and assign the admin privilege to it so that it can control other matter device. As for commissioning zigbee end devices, currently the zigbee bridge is using steering to add zigbee end-devices to its zigbee network.

**Comment by dhrishi** [comment]
@Shivi-6 Any updates you can share? Please close the issue if resolved

**Comment by Shivi-6** [comment]
@dhrishi Currently I have zigbee devices that use install-code so I am not able to test this. I will close the issue and once I test, I will update or if any issue persists, I will open a new issue.
