### ISSUE TITLE
Thermostat failed to write to Dry mode (CON-1318)

### ISSUE THREAD

**Issue by MaplestoryAlen** [espressif/esp-matter#1067]
I can read and write the cooling and heating modes in the thermostat, but I cannot read and write the dry mode. However, I noticed that there is a dry mode in the 'ThermostatSystemMode Type', why can't it be used? How can I support Dry mode?

matter V1.2
IDF:5.2.1
chip:esp32s3

![image](https://github.com/user-attachments/assets/c41093a5-cc54-47b6-949d-177b2dbaeffa)

**Comment by jadhavrohit924** [comment]
@MaplestoryAlen Thanks for the report, we will fix it soon.
