### ISSUE TITLE
TOF Matter Cluster (CON-1320)

### ISSUE THREAD

**Issue by gustavof04** [espressif/esp-matter#1069]
**Describe the question/query that you have**
Is there a Matter cluster related to TOF (Time-Of-Flight) sensors?

**Additional context**
We have a hardware with TOF(Time-Of-Flight) sensors and we need a appropriate clusters for guide our implementation in a project

We research about it in many sites and repositories but we had no success..

**Comment by jadhavrohit924** [comment]
@gustavof04 No, there is no such cluster.

**Comment by dhrishi** [comment]
You can download and check the latest released specifications from [here](https://csa-iot.org/developer-resource/specifications-download-request/) for the supported device types and clusters.
