### ISSUE TITLE
Heating/Cooling unit device type (ID: 0x0300) is missing in SDK

### ISSUE THREAD

**Issue by amit-iota** [espressif/esp-matter#107]
Under HVAC category only thermostat and fan controller device types are available. Heating / Cooling Unit device type (ID: 0x0300) is not there.

**Comment by dhrishi** [comment]
AFAIK, Heating/Cooling Unit Device Type is marked as provisional in v1.0 specification. It means that it is not certifiable at this stage.

**Comment by dhrishi** [comment]
Closing this as the original question is answered
