### ISSUE TITLE
Matter Certification Help built with Sample application  (CON-1335)

### ISSUE THREAD

**Issue by bilalmalik76** [espressif/esp-matter#1083]
Are there additional implementations required to be added to the samples other than factory data for Matter certification? For example, we have built a matter light using one of the samples available in esp-matter sdk and added our factory data using our official PID, etc. We are able to comission device and control it from Google and Apple home apps. What else is required for certification before we send our device to ATL?

**Comment by dhrishi** [comment]
@bilalmalik76 Please check this section https://docs.espressif.com/projects/esp-matter/en/latest/esp32/certification.html#matter-certification

**Comment by bilalmalik76** [comment]
@dhrishi Hi, we are already able to add everything related to certification available on this link:
https://docs.espressif.com/projects/esp-matter/en/latest/esp32/certification.html#matter-certification

I just wanted to ask if we need to add anything else related to mandatory clusters or others in application, we built our light device using light sample available in esp-matter sdk.

**Comment by dhrishi** [comment]
@bilalmalik76 It is advisable to execute the certification tests at your end before you send the products to the ATL

**Comment by bilalmalik76** [comment]
@dhrishi Ok I will do but generally when we build using based solution, we add missing core clusters but what is difference with esp-matter considering it uses models and wrappers on top of connected home ip stack.

**Comment by dhrishi** [comment]
@bilalmalik76 Ideally the mandatory clusters (core and application) should be present for a selected device types. So, you need not require anything in there. If there are any specific issues that you observe, you can raise then and we will fix :-)

**Comment by bilalmalik76** [comment]
@dhrishi Sure I will start executing certification tests and raise issues if face any. Thanks
