### ISSUE TITLE
Create distributed compliance ledger test account (CON-1338)

### ISSUE THREAD

**Issue by JoseAntonioMG** [espressif/esp-matter#1086]
I have several Esp32 devices that I have configured with Matter and Thread, they work perfectly and are integrated into the same network through an ETBR (Thread border router).
I am testing OTA updates with the sample driver provided on github OTA-Provider, however I need to access "distributed compliance ledger test" (https://testnet.iotledger.io) to create an account and upload the OTA files, and I can't create an account. Is it possible to create an account on testnet.iotledger.io without being a company or home device retailer? If so, how can I create an account to test OTA updates on DCL?

Thanks.

**Comment by wqx6** [comment]
> Is it possible to create an account on testnet.iotledger.io without being a company or home device retailer?

No, you must be a member of CSA so that you can create an account on testnet DCL and upload the OTA image url.
