### ISSUE TITLE
Matter controller TLV parsing issue    (CON-1340)

### ISSUE THREAD

**Issue by pavel808** [espressif/esp-matter#1088]
I am using the Matter controller example to send a command to a custom cluster I have an an ESP32-C6 end device. 

Node ID is 1515. Endpoint ID is 1. Cluster ID is 320601088. Command ID is 0. Command data is 1 : 

`matter esp controller invoke-cmd 1515 0x1 320601088  0 "{\"0:U16\": 1}" `

This gets to my device but fails in my `app_main `function on trying to get the TLV data with  `tlv_data.Get` . Here is my code : 

```
uint16_t value;

CHIP_ERROR chip_err = tlv_data.Get(protocol_data.value);

if (chip_err != CHIP_NO_ERROR)
{
    ESP_LOGI(TAG, "ERROR! Unable to get TLV Data for protocol. Error : %d");
    return ESP_FAIL;
}
```
What is wrong with my controller command? If I would send the equivalent command using chip-tool as follows, it works fine : 

`chip-tool any command-by-id 320601088  0x0 0x1 1515 0x1`

**Comment by sayondeep** [comment]
@pavel808 Can you please share more information with the successfull logs with chip-tool and unsuccessfull logs with controller. 
Also, can you please share more information about the changes in the app_main and custom cluster implementation.

**Comment by pavel808** [comment]
> @pavel808 Can you please share more information with the successfull logs with chip-tool and unsuccessfull logs with controller and the end device logs as well. Also, can you please share more information about the changes in the app_main and custom cluster implementation.
> 
> It would be great if you can share the patch for me to test it on my side.

Hi @sayondeep. Thanks for your reply. Attached is a zip containing my modified `app_driver.cpp` and `app_main.cpp` files which have been modified. 

I firstly commission the device using the Matter controller as follows : 

`matter esp controller pairing ble-thread 1515 0e080000000000010000000300001135060004001fffe00208782e413e1b5a59c00708fd4397689a751a420510386d0687a3427476540f88d18064410d030f4f70656e5468726561642d663662660102f6bf0410f06225d3c5eff0e0eb72e0821067591d0c0402a0f7f8 20202021 3840 
`

All looks ok.

Then I try to send a command to set my protocol as follows. 

`matter esp controller invoke-cmd 1515 0x1 320601088  0 "{\"0:U16\": 1}" `

The command reaches the device, but fails on parsing TLV, as can be seen in the device-output-matter-controller.log file.

Next I erased the flash in the device, and re-flashed it with the same application. I re-commissioned the device using chip-tool as follows using a different Node ID of  0x6767

`chip-tool pairing code-thread 0x6767 hex:0e080000000000010000000300001135060004001fffe00208782e413e1b5a59c00708fd4397689a751a420510386d0687a3427476540f88d18064410d030f4f70656e5468726561642d663662660102f6bf0410f06225d3c5eff0e0eb72e0821067591d0c0402a0f7f8 34970112332`

All looks ok.

Then I send the command to update my protocol using chip-tool s follows : 

`chip-tool any command-by-id 320601088 0x0 0x1 0x6767 0x1`

From the log file device-output-chip-tool.log we can see that this is successful. 

[commissioning_files.zip](https://github.com/user-attachments/files/17145601/commissioning_files.zip)

**Comment by sayondeep** [comment]
@pavel808 

This is the modified code:

```
static esp_err_t set_protocol_callback(const ConcreteCommandPath &command_path, TLVReader &tlv_data,
                                                           void *opaque_ptr)
{
	/* Get ids */
	uint16_t endpoint_id = command_path.mEndpointId;
	uint32_t cluster_id = command_path.mClusterId;
	uint32_t command_id = command_path.mCommandId;
	uint32_t attribute_id = protocol_attribute_id;

	/* Return if this is not the rainmaker sign_data command */
	if (endpoint_id != light_endpoint_id || cluster_id != ir_cluster_id || command_id != set_protocol_id) {
		ESP_LOGE(TAG, "ERROR! set_protocol_callback has incorrect ids for endpoint, cluster or command");
		return ESP_FAIL;
	}

	ESP_LOGI(TAG, "set_protocol_callback : type  %d", tlv_data.GetType());

	// struct ProtocolDecodableType protocol_data;

    uint16_t protocol_data;

	// CHIP_ERROR chip_err = tlv_data.Get(protocol_data.value);

        /* Parse the tlv data */

    if (chip::TLV::kTLVType_Structure != tlv_data.GetType()) {
        return ESP_FAIL;
    }
    chip::TLV::TLVType mOuter;
    if (CHIP_NO_ERROR != tlv_data.EnterContainer(mOuter)) {
        return ESP_FAIL;
    }
    if (CHIP_NO_ERROR != tlv_data.Next()) {
        return ESP_FAIL;
    }
    chip::TLV::Tag tag = tlv_data.GetTag();
    if (!IsContextTag(tag)) {
        return ESP_FAIL;
    }
    // check tag number, since this has only one argument, checking against 0
    if (0 != TagNumFromTag(tag)) {
        return ESP_FAIL;
    }

    CHIP_ERROR chip_err = chip::app::DataModel::Decode(tlv_data, protocol_data);

	if (chip_err != CHIP_NO_ERROR)
	{
		ESP_LOGI(TAG, "ERROR! Unable to get TLV Data for protocol");
		return ESP_FAIL;

	}

	ESP_LOGI(TAG, "set_protocol_callback - Protocol value received : %u", protocol_data);

	esp_matter_attr_val_t val;
	val.type = ESP_MATTER_VAL_TYPE_UINT16;
	val.val.u16 = protocol_data;

	// Update attribute

	esp_err_t err = attribute::update(endpoint_id, cluster_id, attribute_id, &val);

	if (err != ESP_OK )
	{
		ESP_LOGI(TAG, "ERROR! Unable to update protocol attribute with value %u", val.val.u16);
		return ESP_FAIL;
	}

    return ESP_OK;
}
```

Thie chip-tool command ` chip-tool any command-by-id 320601088 0x0 0x1 0x6767 0x1 ` is incorrect as the command data is always expected to be a json-encoded string. 
You can find more about it by running ` chip-tool any command-by-id `.

The correct chip-tool command would be ` chip-tool any command-by-id 320601088  0x0 '{"0x0":0}' 0x7700 0x1 ` .

The modified code should be able to parse the tlv data correctly from controller as well as chip-tool.

Please see [here ](https://github.com/espressif/esp-matter/blob/e6dcadadfaea7b917268b91bfd80884061960c7c/components/esp_matter_rainmaker/esp_matter_rainmaker.cpp#L220) for reference.
