### ISSUE TITLE
Esp32-s2 support matter or not?  How to  support commissioning over soft-AP?

### ISSUE THREAD

**Issue by samsonhuang20221028** [espressif/esp-matter#109]
Esp32-s2 support matter or not?  How to  support commissioning over soft-AP?

**Comment by dhrishi** [comment]
@samsonhuang20221028 ESP32-S2 is supported for Matter. But, SoftAP based commissioning is not as it is not a part of Matter v1.0 release. Instead you will have to perform on-network commissioning. That is, the device should receive the Wi-Fi connectivity using some mechanism and then the commissioning could be done over the Wi-Fi network

**Comment by dhrishi** [comment]
Steps to try out: https://github.com/espressif/esp-matter/issues/76#issuecomment-1299587379

**Comment by dhrishi** [comment]
Thanks for confirming. Can you please close the issue if your question is addressed

**Comment by samsonhuang20221028** [comment]
the device should receive the Wi-Fi connectivity using some mechanism and then the commissioning could be done over the Wi-Fi network.

**Comment by samsonhuang20221028** [comment]
" But, SoftAP based commissioning is not as it is not a part of Matter v1.0 release." Is there some official document about this thing?  And is there a schedule to support SoftAP based commissioning? Thanks.

**Comment by dhrishi** [comment]
It is in the specification but the implementation is not present in the [upstream SDK](https://github.com/project-chip/connectedhomeip/) and hence it is not a part of v1.0 release. It is planned to be supported in the next release, mostly v1.1.

**Comment by liming-2015** [comment]
> It is in the specification but the implementation is not present in the [upstream SDK](https://github.com/project-chip/connectedhomeip/) and hence it is not a part of v1.0 release. It is planned to be supported in the next release, mostly v1.1.

Hello，When is the matter v1.1 expected to be released? Thanks.

**Comment by dhrishi** [comment]
It should be around early Q2 2023

**Comment by RohitRaval26** [comment]
Is still matter supported for esp32-s2 ?

**Comment by RohitRaval26** [comment]
I have been trying to download it but still getting errors
