### ISSUE TITLE
Провери хубаво този код.  (CON-1342)

### ISSUE THREAD

**Issue by Ivo0o0o** [espressif/esp-matter#1090]
**Describe the question/query that you have**
A clear and concise description of what you want to ask.

**Additional context**
...

**Comment by me-no-dev** [comment]
@Ivo0o0o нищо не може да се разбере от така попълнен репорт. Моля да го затвориш и да ползваш Английски за комуникация.

EN: Nothing can be understood from the issue report as-is. Please close it and use English for communication in the future.
