### ISSUE TITLE
How can I force esp-idf to use sdkconfig.defaults.c6_thread for Thread building? (CON-1343)

### ISSUE THREAD

**Issue by lboue** [espressif/esp-matter#1091]
**Describe the bug**
I am trying to build the [Multiple On Off plugin unit](https://github.com/espressif/esp-matter/tree/main/examples/multiple_on_off_plugin_units) example for Thread but it build for Matter over WiFi.

By default it loads [sdkconfig.defaults.esp32c6](https://github.com/espressif/esp-matter/blob/main/examples/multiple_on_off_plugin_units/sdkconfig.defaults.esp32c6).
How can I force esp-idf to use [sdkconfig.defaults.c6_thread](https://github.com/espressif/esp-matter/blob/main/examples/multiple_on_off_plugin_units/sdkconfig.defaults.c6_thread)?

**Environment**
- ESP-Matter Commit Id: 131c1ae7f787c24d103459efa62d486c3d045936
- ESP-IDF Commit Id: 3b8741b172dc951e18509698dee938304bcf1523
- SoC (eg: ESP32 or ESP32-C3):
- Device Logs (Please attach the log file):

- Host Machine OS: Ubuntu 22.04.5 LTS
- Host Machine Python version :Python 3.10.12
- Commissioner app and versions if present: N/A
- Home hub app and versions if present: N/A
- Commissioner's logs if present: N/A

**Any additional details**

```
cd ~/esp-matter/examples/multiple_on_off_plugin_units
idf.py set-target esp32c6
idf.py menuconfig
```

**Comment by shubhamdp** [comment]
This is the use case of [building with custom sdkconfig](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/build-system.html#custom-sdkconfig-defaults).

What you can do is use `-DSDKCONFIG_DEFAULTS` option to build you application, eg:
```
idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.defaults.c6_thread" set-target esp32c6 build
```

The same method is mentioned in https://github.com/espressif/esp-matter/issues/1008#issuecomment-2249289022

**Comment by lboue** [comment]
Thanks
