### ISSUE TITLE
The callback function cannot get the target value

### ISSUE THREAD

**Issue by shun-dgut** [espressif/esp-matter#110]
## Use the WindowCovering example with the following modifications

components/esp_matter/esp_matter_cluster.cpp
```
    feature::lift::add(cluster, &(config->lift));
    feature::tilt::add(cluster, &(config->tilt));
    feature::position_aware_lift::add(cluster, &(config->position_aware_lift));
    feature::position_aware_tilt::add(cluster, &(config->position_aware_tilt));
    feature::absolute_position::add(cluster, &(config->absolute_position));
```
components/esp_matter/esp_matter_cluster.h
```
    feature::lift::config_t  lift;
    feature::tilt::config_t  tilt;
    feature::position_aware_lift::config_t  position_aware_lift;
    feature::position_aware_tilt::config_t  position_aware_tilt;
    feature::absolute_position::config_t    absolute_position;
```

## Log
![image](https://user-images.githubusercontent.com/31812214/206401175-7fddbef3-57f1-47f2-a7b5-2e08f2fbbf4a.png)

When I modify the TargetPositionLiftPercent100ths value of the curtain, I receive an illegal value

As shown in the figure below, I understand that the value will be passed to the application normally
![image](https://user-images.githubusercontent.com/31812214/206401728-f1baf933-0122-4639-aaf4-e6b02b7db8c9.png)

**Comment by jadhavrohit924** [comment]
Can you please point me to code file?? Or you are trying to set TargetPositionLiftPercent100ths ?

Please note : TargetPositionLiftPercent100ths is read only attribute.

**Comment by shun-dgut** [comment]
> I didn’t get the above log. What are you trying to do? Can you please share more detailed steps?
> 
> Please note : TargetPositionLiftPercent100ths is read only attribute.
I want to get the data in the application layer, but I can't get the value in the callback function.

![image](https://user-images.githubusercontent.com/31812214/206833747-eacbb28a-57fe-4b57-91cb-a093f6902f26.png)
