### ISSUE TITLE
Endpoints (CON-1393)

### ISSUE THREAD

**Issue by Nezaemmy** [espressif/esp-matter#1131]
Hi, I use esp32s3 as matter device, I tried to add 21 endpoints on it but it seems like it can not support more than 15 endpoints.

I want to ask you, is there a way to increase the number of endpoints more than 15 with one Matter device?

**Comment by shubhamdp** [comment]
> I want to ask you, is there a way to increase the number of endpoints more than 15 with one Matter device?

Yes, there is a way to increase the number of endpoints, `CONFIG_ESP_MATTER_MAX_DYNAMIC_ENDPOINT_COUNT=16`, by default it is configured to 16.

You can adjust the dynamic endpoint count as described in the [programming guide](https://docs.espressif.com/projects/esp-matter/en/latest/esp32/optimizations.html#adjust-the-dynamic-endpoint-count). (NOTE: It reduces it from 16 to 4 for optimization purpose. But, you can bump it up as per your need.

**Comment by Nezaemmy** [comment]
thank you
