### ISSUE TITLE
Binding table size and groups (CON-1396)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#1134]
What is the difference between these two config variables?
CONFIG_MAX_BINDINGS=8
CONFIG_ESP_MATTER_BINDING_TABLE_SIZE=100

I am running into a constraint somewhere trying to increase the number of bindings we support.

Are groups constrained somehow?
We have two GroupKeys
But then up to 25 GroupIds using those two keys.

**Comment by shubhamdp** [comment]
@jonsmirl can we close if the question is answered.
