### ISSUE TITLE
How to show that the bridge device is offline？ (CON-1397)

### ISSUE THREAD

**Issue by LinKvFM** [espressif/esp-matter#1135]
There are many bridge devices in the bridge, but not all of them are online. How can I inform the bridge devices that have been powered off?
Currently included bridge device types: light，occupancy sensor, window covering,

**Comment by jonsmirl** [comment]
Attribute 0x11 on the Bridge Basic Info cluster is Reachable.

The Reachable attribute SHALL be used to indicate whether the bridged device is reachable by the
bridge over the non-Matter network, so a Matter Node which wants to communicate with a bridged
device can get an indication that this might fail (when the attribute is False). Determination of
reachability MAY not be perfect (e.g. depending on technology employed), so the Matter Node
SHOULD be aware of the risk of false positives and negatives on reachability determination. For
example, a bridged device MAY be marked as unreachable while it could actually be reached, and
vice-versa.

9.13.5.2. ReachableChanged Event
This event SHALL be generated when there is a change in the Reachable attribute. Its purpose is to
provide an indication towards interested parties that the reachability of a bridged device (over the
non-Matter network) has changed, so they MAY take appropriate action.
After (re)start of a bridge this event MAY be generated.
