### ISSUE TITLE
where CHIP_DEVICE_CONFIG_ENABLE_THREAD is defined (CON-1402)

### ISSUE THREAD

**Issue by Buddhika93n** [espressif/esp-matter#1140]
in esp_matter example ICD_APP #if CHIP_DEVICE_CONFIG_ENABLE_THREAD
ESP_LOGI(TAG, "CHIP_DEVICE_CONFIG_ENABLE_THREAD"); this line is printing so CHIP_DEVICE_CONFIG_ENABLE_THREAD is defined somewhere  cannot find it. please help me

**Comment by shripad621git** [comment]
@Buddhika93n , the option `CHIP_DEVICE_CONFIG_ENABLE_THREAD` is defined [here](https://github.com/espressif/connectedhomeip/blob/17b1a38e909e7874593bcb87c31be03a5866f1d4/src/platform/ESP32/CHIPDevicePlatformConfig.h#L51) where the option is mapped to `CONFIG_ENABLE_MATTER_OVER_THREAD` in ESP32.
The thread support is enabled by enabling `CONFIG_ENABLE_MATTER_OVER_THREAD`   through idf.py menuconfig.
The option is defined [here](https://github.com/espressif/connectedhomeip/blob/17b1a38e909e7874593bcb87c31be03a5866f1d4/config/esp32/components/chip/Kconfig#L779).

**Comment by shripad621git** [comment]
@Buddhika93n , can you please close the issue if it is addressed.
