### ISSUE TITLE
Descriptor cluster is missing feature list (CON-1403)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#1141]
Implementing devices with multiple, identical endpoints requires "Duplicate Condition" to be satisfied.

![image](https://github.com/user-attachments/assets/22674ebc-8178-4c98-b83f-011aa95bd4fc)

Descriptor cluster is missing support for the TAGLIST feature.

![image](https://github.com/user-attachments/assets/3caa9165-82ca-4951-8b34-9cbc79cbe051)

**Comment by jonsmirl** [comment]
decriptor::create() is missing the feature list as the last parameter.  I need to enable the feature list.
https://github.com/espressif/esp-matter/blob/main/components/esp_matter/esp_matter_cluster.h#L67
![image](https://github.com/user-attachments/assets/e96cdcc8-3fe0-474c-91b9-bcbd55983947)
should look like this:
cluster_t *create(endpoint_t *endpoint, config_t *config, uint8_t flags, uint32_t features);

**Comment by jadhavrohit924** [comment]
Okay. You can use the `tagList::add()` API to enable the feature.

**Comment by jadhavrohit924** [comment]
We will fix the `create` API.
