### ISSUE TITLE
How to create a multi-button switch as a bridge device？ (CON-1406)

### ISSUE THREAD

**Issue by LinKvFM** [espressif/esp-matter#1144]
How to create a multi-button switch as a bridge device？
How can I create a multi-button switch and display it in Apple Home as shown below?

![截屏 2024-11-06 10 16 04](https://github.com/user-attachments/assets/afef21e2-d65d-4f0b-b96f-86b77d1185eb)

**Comment by jonsmirl** [comment]
They are doing thing which are not part of the Matter spec to make those.

**Comment by jadhavrohit924** [comment]
@LinKvFM From the image that you have shared, 3 switch endpoints are created on the bridged device. You can do the same for your multi-button switch.
