### ISSUE TITLE
How to add and remove supporterd attributes of a cluster though esp-matter without using ZAP (CON-1421)

### ISSUE THREAD

**Issue by bilalmalik76** [espressif/esp-matter#1159]
How to add and remove supporterd attributes of a cluster though esp-matter without using ZAP? Considering esp-matter provide non-zap based APIs, how to find enabled attributes information and how to enable and disbale specific?

**Comment by shubhamdp** [comment]
To check if attribute/cluster present or not there are `get()` APIs. If the API returns `nullptr` then the attribute is not present on the node.

For cluster: https://github.com/espressif/esp-matter/blob/main/components/esp_matter/esp_matter_core.h#L397-L407
For Attribute: https://github.com/espressif/esp-matter/blob/main/components/esp_matter/esp_matter_core.h#L567-L578

To add, we have `::create()` APIs listed in [esp_matter_attribute.h](https://github.com/espressif/esp-matter/blob/main/components/esp_matter/esp_matter_attribute.h).

We do not have APIs to remove the already present attributes. But, we only add the mandatory attributes/events when creating the device type, so I think you should consider only adding the optional clusters/attributes/events.

**Comment by bilalmalik76** [comment]
@shubhamdp What I understood is that all mandatory attributes for a specific cluster of a sepcific device type are already available in esp-matter and we only need to add optional if required?

**Comment by shubhamdp** [comment]
@bilalmalik76 Yes, thats right. When adding new device type, we ensure and only add the mandatory bits from the specification.

**Comment by bilalmalik76** [comment]
Thanks where I can find the list of mandatory attributes available in esp-matter?

**Comment by shubhamdp** [comment]
[esp_matter_cluster.cpp](https://github.com/espressif/esp-matter/blob/main/components/esp_matter/esp_matter_cluster.cpp) contains the list of attributes/commands/events which are mandatory for a cluster.

**Comment by shubhamdp** [comment]
@bilalmalik76 any updates on this? Please close the issue if your question is answered.

**Comment by bilalmalik76** [comment]
I am closing this and will reopen if needed.
