### ISSUE TITLE
Reading the Thread TLVS dataset  (CON-1423)

### ISSUE THREAD

**Issue by pavel808** [espressif/esp-matter#1161]
It's possible to read the Thread TLVS dataset with the following Matter esp cli command : 

`matter esp ot_cli dataset active -x `

How is it possible to read this value from within application code? \

I have a C++ Matter controller application running on the ESP Thread BR device and currently I am hard-coding the dataset tlvs value there for commissioning. It would be much better to be able to read this directly from the TBR into the application instead if possible. Thanks in advance.

**Comment by shubhamdp** [comment]
You can get the active dataset using `otDatasetGetActiveTlvs()` API.

Please find the documentation here: https://openthread.io/reference/group/api-operational-dataset#otdatasetgetactivetlvs

Please find the usage here (this is what gets executed when you hit `matter esp ot_cli dataset active -x`): https://github.com/openthread/openthread/blob/main/src/cli/cli_dataset.cpp#L698

**Comment by shubhamdp** [comment]
@pavel808 any updates on this? Please close the issue if your question is answered.

**Comment by pavel808** [comment]
> @pavel808 any updates on this? Please close the issue if your question is answered.

Apologies for the delay. This solves my problem. Many thanks.
