### ISSUE TITLE
“zigbee_bridge “ repeatedly restart (CON-1427)

### ISSUE THREAD

**Issue by MaplestoryAlen** [espressif/esp-matter#1165]
IDF：V5.2.1
Matter:V1.2

     Example  'zigbee-bridge' repeatedly restarts automatically and cannot be used，The original program I used has never been changed, but I have been unable to use it. The same applies to the development board "ESP Thread Border Router/Zigbee Gateway Board"
 
 ESP32H2 ：esp_zigbee_rcp
 ESP32S3 :   zigbee-bridge

  ESP32-S3 Pin  | ESP32-H2 Pin |
|----------------|--------------|
|   GND          |    GND       |
|   GPIO4        |    TX        |
|   GPIO5        |    RX        |
 

log:

SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3810,len:0x178c
load:0x403c9700,len:0x4
load:0x403c9704,len:0xcbc
load:0x403cc700,len:0x2da0
entry 0x403c9914
I (31) boot: ESP-IDF v5.2.1 2nd stage bootloader
I (31) boot: compile time Nov 20 2024 16:59:40
I (31) boot: Multicore bootloader
I (34) boot: chip revision: v0.1
I (38) boot.esp32s3: Boot SPI Speed : 80MHz
I (43) boot.esp32s3: SPI Mode       : DIO
I (48) boot.esp32s3: SPI Flash Size : 4MB
I (52) boot: Enabling RNG early entropy source...
I (58) boot: Partition Table:
I (61) boot: ## Label            Usage          Type ST Offset   Length
I (69) boot:  0 esp_secure_cert  unknown          3f 06 0000d000 00002000
I (76) boot:  1 nvs              WiFi data        01 02 00010000 0000e000
I (84) boot:  2 nvs_keys         NVS keys         01 04 0001e000 00001000
I (91) boot:  3 otadata          OTA data         01 00 0001f000 00002000
I (98) boot:  4 phy_init         RF data          01 01 00021000 00001000
I (106) boot:  5 ota_0            OTA app          00 10 00030000 001d0000
I (114) boot:  6 ota_1            OTA app          00 11 00200000 001d0000
I (121) boot:  7 fctry            WiFi data        01 02 003d0000 00006000
I (129) boot:  8 zb_storage       Unknown data     01 81 003d6000 00020000
I (136) boot:  9 zb_fct           Unknown data     01 81 003f6000 00000400
I (144) boot: End of partition table
I (148) esp_image: segment 0: paddr=00030020 vaddr=3c140020 size=3c950h (248144) map
I (201) esp_image: segment 1: paddr=0006c978 vaddr=3fc9a500 size=036a0h ( 13984) load
I (204) esp_image: segment 2: paddr=00070020 vaddr=42000020 size=13636ch (1270636) map
I (436) esp_image: segment 3: paddr=001a6394 vaddr=3fc9dba0 size=018a4h (  6308) load
I (438) esp_image: segment 4: paddr=001a7c40 vaddr=40374000 size=163f4h ( 91124) load
I (471) boot: Loaded app from partition at offset 0x30000
I (471) boot: Disabling RNG early entropy source...
I (483) cpu_start: Multicore app
I (492) cpu_start: Pro cpu start user code
I (492) cpu_start: cpu freq: 160000000 Hz
I (492) cpu_start: Application information:
I (495) cpu_start: Project name:     zigbee_bridge
I (501) cpu_start: App version:      1.0
I (505) cpu_start: Compile time:     Nov 20 2024 16:59:10
I (511) cpu_start: ELF file SHA256:  29f2fc278...
I (517) cpu_start: ESP-IDF:          v5.2.1
I (521) cpu_start: Min chip rev:     v0.0
I (526) cpu_start: Max chip rev:     v0.99 
I (531) cpu_start: Chip rev:         v0.1
I (536) heap_init: Initializing. RAM available for dynamic allocation:
I (543) heap_init: At 3FCB5900 len 00033E10 (207 KiB): RAM
I (549) heap_init: At 3FCE9710 len 00005724 (21 KiB): RAM
I (555) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
I (561) heap_init: At 600FE010 len 00001FD8 (7 KiB): RTCRAM
I (569) spi_flash: detected chip: generic
I (572) spi_flash: flash io: dio
W (576) spi_flash: Detected size(8192k) larger than the size in the binary image header(4096k). Using the size in the binary image header.
I (591) sleep: Configure to isolate all GPIO pins in sleep state
I (596) sleep: Enable automatic switching of GPIO sleep configuration
I (603) coexist: coex firmware version: 77cd7f8
I (609) coexist: coexist rom version e7ae62f
I (614) main_task: Started on CPU0
I (624) main_task: Calling app_main()
I (664) pp: pp rom version: e7ae62f
I (664) net80211: net80211 rom version: e7ae62f
I (674) wifi:wifi driver task: 3fcc2748, prio:23, stack:6656, core=0
I (674) wifi:wifi firmware version: a9f5b59
I (674) wifi:wifi certification version: v7.0
I (674) wifi:config NVS flash: enabled
I (684) wifi:config nano formating: disabled
I (684) wifi:Init data frame dynamic rx buffer num: 32
I (694) wifi:Init static rx mgmt buffer num: 5
I (694) wifi:Init management short buffer num: 32
I (694) wifi:Init dynamic tx buffer num: 32
I (704) wifi:Init static tx FG buffer num: 2
I (704) wifi:Init static rx buffer size: 1600
I (714) wifi:Init static rx buffer num: 10
I (714) wifi:Init dynamic rx buffer num: 32
I (714) wifi_init: rx ba win: 6
I (724) wifi_init: tcpip mbox: 32
I (724) wifi_init: udp mbox: 6
I (734) wifi_init: tcp mbox: 6
I (734) wifi_init: tcp tx win: 5760
I (734) wifi_init: tcp rx win: 5760
I (744) wifi_init: tcp mss: 1440
I (744) wifi_init: WiFi IRAM OP enabled
I (754) wifi_init: WiFi RX IRAM OP enabled
I (774) chip[DL]: NVS set: chip-counters/reboot-count = 20 (0x14)
ble select commissioning ...
I (774) chip[DL]: Real time clock set to 946684800 (0100/00/01 00:00:00 UTC)
I (774) BLE_INIT: BT controller compile version [30b57c4]
I (784) BLE_INIT: Bluetooth MAC: 34:85:18:52:51:c6
I (784) phy_init: phy_version 640,cd64a1a,Jan 24 2024,17:28:12
I (844) NimBLE: GAP procedure initiated: stop advertising.

I (844) NimBLE: Failed to restore IRKs from store; status=8

I (844) CHIP[DL]: BLE host-controller synced
I (1354) chip[DL]: Configuring CHIPoBLE advertising (interval 25 ms, connectable)
I (1354) NimBLE: GAP procedure initiated: advertise; 
I (1354) NimBLE: disc_mode=2
I (1354) NimBLE:  adv_channel_map=0 own_addr_type=1 adv_filter_policy=0 adv_itvl_min=40 adv_itvl_max=40
I (1364) NimBLE: 

I (1374) chip[DL]: CHIPoBLE advertising started
I (1374) chip[DL]: Starting ESP WiFi layer
I (1384) wifi:mode : sta (34:85:18:52:51:c4)
I (1384) wifi:enable tsf
W (1384) wifi:Haven't to connect to a suitable AP now!
I (1394) chip[DL]: Done driving station state, nothing else to do...
W (1394) wifi:Haven't to connect to a suitable AP now!
I (1404) chip[DL]: Done driving station state, nothing else to do...
I (1414) chip[SVR]: Initializing subscription resumption storage...
I (1414) chip[SVR]: Server initializing...
I (1424) chip[TS]: Last Known Good Time: 2023-10-14T01:16:48
I (1424) chip[DMG]: AccessControl: initializing
I (1434) chip[DMG]: Examples::AccessControlDelegate::Init
I (1434) chip[DMG]: AccessControl: setting
I (1444) chip[DMG]: DefaultAclStorage: initializing
I (1454) chip[DMG]: DefaultAclStorage: 0 entries loaded
I (1474) chip[ZCL]: Using ZAP configuration...
I (1474) esp_matter_cluster: Cluster plugin init common callback
I (1474) chip[DMG]: AccessControlCluster: initializing
I (1474) chip[ZCL]: 0x3c1489b6ep 0 clus 0x0000_0030 attr 0x0000_0000 not supported
I (1484) chip[ZCL]: Initiating Admin Commissioning cluster.
I (1494) chip[DIS]: Updating services using commissioning mode 1
I (1504) chip[DIS]: CHIP minimal mDNS started advertising.
I (1504) chip[DIS]: Advertise commission parameter vendorID=65521 productID=32768 discriminator=3840/15 cm=1
I (1514) chip[DIS]: CHIP minimal mDNS configured as 'Commissionable node device'; instance name: DE7F656CF9CA7931.
I (1524) chip[DIS]: mDNS service published: _matterc._udp
I (1534) chip[IN]: CASE Server enabling CASE session setups
I (1544) chip[SVR]: Joining Multicast groups
I (1544) chip[SVR]: Server Listening...
I (1554) esp_matter_core: Dynamic endpoint 0 added
I (1554) esp_matter_core: Dynamic endpoint 1 added
I (1564) chip[DL]: WIFI_EVENT_STA_START
W (1564) wifi:Haven't to connect to a suitable AP now!
I (1564) chip[DL]: Done driving station state, nothing else to do...
I (1574) chip[DL]: Configuring CHIPoBLE advertising (interval 25 ms, connectable)
I (1584) chip[DL]: Device already advertising, stop active advertisement and restart
I (1594) NimBLE: GAP procedure initiated: stop advertising.

I (1604) NimBLE: GAP procedure initiated: advertise; 
I (1604) NimBLE: disc_mode=2
I (1604) NimBLE:  adv_channel_map=0 own_addr_type=1 adv_filter_policy=0 adv_itvl_min=40 adv_itvl_max=40
I (1614) NimBLE: 

I (1624) app_main: Commissioning window opened
I (1714) main_task: Returned from app_main()
                                                                                                                                   I (1754) esp_zboss: status: -1
I (1784) esp_zboss: Zigbee stack initialized
> I (31494) chip[DL]: Configuring CHIPoBLE advertising (interval 500 ms, connectable)
I (31494) chip[DL]: Device already advertising, stop active advertisement and restart
I (31514) NimBLE: GAP procedure initiated: stop advertising.

I (31514) NimBLE: GAP procedure initiated: advertise; 
I (31524) NimBLE: disc_mode=2
I (31524) NimBLE:  adv_channel_map=0 own_addr_type=1 adv_filter_policy=0 adv_itvl_min=800 adv_itvl_max=800
I (31534) NimBLE: 

I (38354) chip[DL]: I (38354) wifi:WIFI_EVENT_STA_STOPflush txq

I (38354) chip[DL]: I (38354) wifi:Starting ESP WiFi layerstop sw txq
E (38364) chip[DL�x����x�x�xxx��x��x�x��xx��x�xx�x�xxxx���xx��x�xxx�x���xx�xx�xxx�x��x�x�xx��xx��xx��xxx�xx�x��xxxxxxxx���x�x�x��xx�xx�x�x������������xx���x��x�x��x���x��xxx���x�x�xx��x�x��xxx��x���ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x4037d5de
--- 0x4037d5de: esp_cpu_wait_for_intr at /home/alen/esp-idf/components/esp_hw_support/cpu.c:145

**Comment by DejinChen** [comment]
Hi, could you try again with this patch.
[zigbee_bridge_patch.txt](https://github.com/user-attachments/files/17841294/zigbee_bridge_patch.txt)
We'll update the example soon.

**Comment by MaplestoryAlen** [comment]
> Hi, could you try again with this patch. I tested this patch on the release/v1.2 branch, commit [066791d](https://github.com/espressif/esp-matter/commit/066791d61fe1802be7f9b6fd925efdcf4cdd516a). [zigbee_bridge_patch.txt](https://github.com/user-attachments/files/17841294/zigbee_bridge_patch.txt) We'll update the example soon.

![image](https://github.com/user-attachments/assets/546a0ea6-e40e-4aa9-864d-767d3ed20574)
My current SDK branch is e9980eee13. I am planning to send this version for laboratory certification and do not intend to make any changes. I am afraid there may be other issues in the future. When will the official version be released to fix this problem?

**Comment by DejinChen** [comment]
Sorry, i copied the wrong commit id. I tested the patch on esp-matter/release/v1.2 branch, commit 7b9d69aa, the connectedhomeip commit is e9980eee13 too.

**Comment by dhrishi** [comment]
@MaplestoryAlen is #1154 the same issue?

**Comment by MaplestoryAlen** [comment]
> @MaplestoryAlen is #1154 the same issue?

yes! It's the same problem
May I ask if I use the Matter V13 protocol, will there be such a restart issue?

**Comment by DejinChen** [comment]
"host mode uart not supported"#1163 may occur in the zigbee bridge example on  release v1.3. The issue has fixed on the master branch. The backport is on going.
You can try the patch in previous comments https://github.com/espressif/esp-matter/issues/1165#issuecomment-2490243384

**Comment by MaplestoryAlen** [comment]
> "host mode uart not supported"#1163 may occur in the zigbee bridge example on release v1.3. The issue has fixed on the master branch. The backport is on going. You can try the patch in previous comments [#1165 (comment)](https://github.com/espressif/esp-matter/issues/1165#issuecomment-2490243384)

Okay, thank you for your answer
