### ISSUE TITLE
The use of PICS-generator (CON-1434)

### ISSUE THREAD

**Issue by 2522957270** [espressif/esp-matter#1172]
I want to use PICS-generator to generate the PICS files required for device authentication, and this is an error that occurs during use.How to solve?
![PICS-error](https://github.com/user-attachments/assets/eaff0365-f936-44d7-a949-5092eb325bd8)
This is the command template I use:
python3 PICSGenerator.py --pics-template <pathToPicsTemplateFolder> --pics-output <outputPath> --commissioning-method on-network --discriminator <DESCRIMINATOR> --passcode <PASSCODE>

**Comment by VaishaliAvhale** [comment]
Please provide the complete logs from the DUT and the PICSGenerator script. Additionally, could you specify the version for which you are trying to generate the PICS?

**Comment by 2522957270** [comment]
ESP32C6;This is my printed log, similar to the one in the picture;Yes, I want to do matter-v1.3 certification;
[PICS-generator.log](https://github.com/user-attachments/files/17942297/PICS-generator.log)

**Comment by VaishaliAvhale** [comment]
@2522957270,

The PICSGenerator tool development is still in progress, and hence it is not currently recommended for use as per CSA's guidance. Please generate the PICS manually for now. Once the tool is ready, we will notify you.

**Comment by 2522957270** [comment]
> @2522957270,
> 
> The PICSGenerator tool development is still in progress, and hence it is not currently recommended for use as per CSA's guidance. Please generate the PICS manually for now. Once the tool is ready, we will notify you.

How to generate PICS manually? Do you manually select the PICS required for the development device by referring to the PICS required for other certified devices?

**Comment by 2522957270** [comment]
How to generate PICS manually? Do you manually select the PICS required for the development device by referring to the PICS required for other certified devices?

**Comment by VaishaliAvhale** [comment]
Please refer this document to generate PICS file manually: 
[PICS_Generation_Guide.pdf](https://github.com/user-attachments/files/17972056/PICS_Generation_Guide.pdf)

**Comment by 2522957270** [comment]
Thanks！
