### ISSUE TITLE
Restart BLE advertising after device is de-commissioned  (CON-1436)

### ISSUE THREAD

**Issue by pavel808** [espressif/esp-matter#1174]
I am working on a Matter end device application on an ESP32-C6. It is based on the Matter light example. 

Whenever a Matter controller unpairs / de-commissions the end device from the Matter / Thread network, it doesn't start to advertise again over BLE again until I re-flash the device. 

On the Matter Controller side I am calling `controller_instance.get_commissioner()->UnpairDevice(devices.at(device_idx).nodeID)`. It appears from the logs that the fabric gets removed. In `app_main` on the end device, the `app_event_cb` function gets invoked with event `DeviceEventType::kFabricRemoved` , then it appears to open a commissioning window successfully. However it doesn't seem to be BLE advertising. 

What is the best way to force the end device to re-start advertising over BLE again after the fabric is removed, so that it can be commissioned again? Thanks.

**Comment by DejinChen** [comment]
Hi, to start BLE advertising, you can invoke `esp_matter::factory_reset()` directly when received `DeviceEventType::kFabricRemoved` event and the count of fabric is zero. 
Or you can change the parameter `kDnssdOnly` to `kAllSupported` for function `OpenBasicCommissioningWindow`.  But this option only works when config `CONFIG_USE_BLE_ONLY_FOR_COMMISSIONING` is disabled.

**Comment by pavel808** [comment]
> Hi, to start BLE advertising, you can invoke `esp_matter::factory_reset()` directly when received `DeviceEventType::kFabricRemoved` event and the count of fabric is zero. Or you can change the parameter `kDnssdOnly` to `kAllSupported` for function `OpenBasicCommissioningWindow`. But this option only works when config `CONFIG_USE_BLE_ONLY_FOR_COMMISSIONING` is disabled.

@DejinChen Thanks or this. Changing  `kDnssdOnly `to `kAllSupported `works in my case perfectly, and I can then commission again. 

Regarding the timeout parameter for `OpenBasicCommissioningWindow`, if I set this to zero, then the commissioning window should not close at all?

**Comment by shubhamdp** [comment]
@pavel808 according to Core Matter specification, Section `5.4.2.3. Announcement Duration`, there is minimum and maximum duration for advertisement. Minimum is 3 min and max is 15 and in case of extended advertisement, it can be extended to 48 Hrs.

**Comment by pavel808** [comment]
> @pavel808 according to Core Matter specification, Section `5.4.2.3. Announcement Duration`, there is minimum and maximum duration for advertisement. Minimum is 3 min and max is 15 and in case of extended advertisement, it can be extended to 48 Hrs.

@shubhamdp Ok thanks. 

It's a bit off topic, but let's take the Matter light example, for example.

The Matter core gets started initially with the call :` esp_matter::start(app_event_cb)` . 300 seconds is the default advertising window duration set within the SDK. 

How can we set the advertising window duration from our application initially before any `kFabricRemoved` event ?

**Comment by shubhamdp** [comment]
@pavel808 SDK uses the 15 minutes timeout and not 300 seconds, and if the extended advertisement is enabled then it is 48 Hrs.

If you'd like to not open the commissioning window on boot, you can disable [CONFIG_ CHIP_ENABLE_PAIRING_AUTOSTART](https://github.com/shubhamdp/connectedhomeip/blob/master/config/esp32/components/chip/Kconfig#L319-L324) option and open the commissioning window as per your convenience.

**Comment by shubhamdp** [comment]
@pavel808 can you please close the issue if your question is answered.
