### ISSUE TITLE
Matter test harness: Test cases failing on show test logs (CON-1446)

### ISSUE THREAD

**Issue by bilalmalik76** [espressif/esp-matter#1183]
Matter test hardness: Test cases failing on show test logs

Environment

ESP-Matter Commit Id:origin/release/v1.3

ESP-IDF Commit Id:5.2.2

SoC: ESP32-S3

Device Logs (Please attach the log file):
[UI_Test_Run_2024_12_02_16_18_32.log](https://github.com/user-attachments/files/17977253/UI_Test_Run_2024_12_02_16_18_32.log)

Host Machine OS:

Commissioner's logs if present:
![image](https://github.com/user-attachments/assets/6c42097c-b75a-4be8-b74c-a91772a6e740)

**Comment by VaishaliAvhale** [comment]
Could you please share the Test Harness version or the commit ID you are currently using?

**Comment by bilalmalik76** [comment]
@VaishaliAvhale I am using this branch v2.10.2+spring2024

**Comment by bilalmalik76** [comment]
@VaishaliAvhale any update on this please?

**Comment by VaishaliAvhale** [comment]
I'm looking into it and will get back to you soon.

**Comment by bilalmalik76** [comment]
@VaishaliAvhale I also tried this but still no success:
![image](https://github.com/user-attachments/assets/30948f3c-823e-4d12-b22f-270fdd00f99a)

**Comment by bilalmalik76** [comment]
I am able to resolve this issue by disabling logs and executing onboarding tests before running Python automated tests.
