### ISSUE TITLE
Expanding Thermostat Functionality in the room_air_conditioner Example (CON-1460)

### ISSUE THREAD

**Issue by dusikasss** [espressif/esp-matter#1197]
I'm using the room_air_conditioner example from the ESP Matter repository. The firmware compiles and flashes successfully. After adding the device to Home Assistant, I see that only on/off, heating, and cooling functions are available for my thermostat.

As I understand it, in Matter devices, the feature_map attribute is responsible for indicating the presence of functionality for a particular cluster. When reading the value using the command through the device console:
`matter esp attribute get 0x1 0x00201 0x00fffc`

I receive the response:
`esp_matter_attribute: ********** R : Endpoint 0x0001's Cluster 0x00000201's Attribute 0x0000FFFC is 3 **********`

I'm unable to set any value using the set command.

Questions:

1. Is it possible to change the feature_map value through the device console?
2. What needs to be done in the project to add full thermostat functionality and change the value of the feature_map attribute?

I've learned how to add an additional cluster for the room air conditioner endpoint:

```
// Adding Fan Control cluster
fan_control::config_t fan_control_config;
cluster_t *cluster_fan_control = fan_control::create(endpoint, &fan_control_config, CLUSTER_FLAG_SERVER);
```

I want to enable all the functionality for the thermostat to see what I will observe in Home Assistant, and then exclude the functions I don't need. 

Additional Information:
ESP-IDF version: 5.2.3
ESP Matter version: 1.3
Board used: esp-32

Thank you for your help!

**Comment by dhrishi** [comment]
@dusikasss 
1. No. It is not possible to change the feature map value through the console. You will have to enable the required features while you create the device type
2. Reference example for enabling a feature [here](https://github.com/espressif/esp-matter/blob/release/v1.3/examples/generic_switch/main/app_main.cpp#L179-#L188)
