### ISSUE TITLE
Linker Error: Cannot Find -lbtdm_app With ESP32C5 (CON-1483)

### ISSUE THREAD

**Issue by Miaojianyu** [espressif/esp-matter#1215]
**Description:**
I encountered a linker error while building the project with esp32c5 target. The error message indicates that the linker cannot find the -lbtdm_app library. This issue arises in the CMakeList.txt(connectedhomeip/connectedhomeip/config/esp32/components/chip)

**Steps to Reproduce:**
1. Ensure that the CONFIG_BT_ENABLED option is enabled in the project configuration.
2. Attempt to build the project using the command with esp32c5: idf.py build.
3. Observe the linker error stating: cannot find -lbtdm_app.

**Solution:**
In the CMakeList.txt(connectedhomeip/connectedhomeip/config/esp32/components/chip) file, at line 434 add (target_name STREQUAL "esp32c5")
![esp32c5](https://github.com/user-attachments/assets/0793c1d9-95be-4fa5-b385-dce042c42f7f)

**Comment by shripad621git** [comment]
@Miaojianyu , is there any specific requirement for using esp32c5?
