### ISSUE TITLE
What is the ESP_LOGE in esp_matter_core.cpp complaining about? (CON-1489)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#1221]
https://github.com/espressif/esp-matter/blob/main/components/esp_matter/esp_matter_core.cpp#L1723

Looks to me like it will get called everytime with a cluster of zero since there is a calloc right in front of it.

**Comment by shubhamdp** [comment]
@jonsmirl Thanks for pointing out, looks like the debug print was left as is, will clean it up.
