### ISSUE TITLE
Adding three child devices does not respond (CON-243)

### ISSUE THREAD

**Issue by shun-dgut** [espressif/esp-matter#127]
iphone  ios 16.2 + homepod mini 16.2
use app_bridge_create_bridged_device function to create ble mesh sub-devices, creating three different sub-devices.
Adding a device using home shows no response.

If I reduce to two devices, then it is possible to display the response,and send and receive data normally

**Comment by wqx6** [comment]
Hi, Can you provide your device log of adding three child devices on blemesh bridge? I did not get the error of no-responding when I add three child-endpoints to to aggregator endpoint. My test environment is iphone-xr with IOS16.1 and homepod mini 16.2. Also I have tested the bridge app with the chip-tool and got no error.

**Comment by shun-dgut** [comment]
> Hi, Can you provide your device log of adding three child devices on blemesh bridge? I did not get the error of no-responding when I add three child-endpoints to to aggregator endpoint. My test environment is iphone-xr with IOS16.1 and homepod mini 16.2. Also I have tested the bridge app with the chip-tool and got no error.


I used the newly added door_lock device

```
esp_matter_bridge.cpp 

case ESP_MATTER_DOOR_LOCK_DEVICE_TYPE_ID:{
        door_lock::config_t door_lock_conf;
        bridged_device->endpoint = door_lock::add(bridged_device->endpoint, &door_lock_conf);
        break;
    }
```

**Comment by jonsmirl** [comment]
this could be related to: https://github.com/espressif/esp-matter/issues/77

**Comment by shun-dgut** [comment]
> Hi, Can you provide your device log of adding three child devices on blemesh bridge? I did not get the error of no-responding when I add three child-endpoints to to aggregator endpoint. My test environment is iphone-xr with IOS16.1 and homepod mini 16.2. Also I have tested the bridge app with the chip-tool and got no error.

This is the log.
[3 lock dev.txt](https://github.com/espressif/esp-matter/files/10264222/3.lock.dev.txt)

**Comment by shun-dgut** [comment]
[3 lock dev chiptool.txt](https://github.com/espressif/esp-matter/files/10264436/3.lock.dev.chiptool.txt)
This is chip tool log

**Comment by wqx6** [comment]
Have you defined override functions for `emberAfPluginDoorLockOnDoorLockCommand` and `emberAfPluginDoorLockOnDoorUnlockCommand` which are weakly defined [here](https://github.com/project-chip/connectedhomeip/blob/master/src/app/clusters/door-lock-server/door-lock-server-callback.cpp#L49-L61)? You need to define your callbacks otherwise the `lockdoor` and `unlockdoor` commands will always return failure.

**Comment by wqx6** [comment]
I suggest you to add these functions in main component instead of the `door-lock-server.cpp`. And you can also create class [`LockEndpoint`](https://github.com/project-chip/connectedhomeip/blob/master/examples/lock-app/linux/src/LockEndpoint.cpp) and class [`LockManager`](https://github.com/project-chip/connectedhomeip/blob/master/examples/lock-app/linux/src/LockManager.cpp) like the upstream linux door-lock app.

**Comment by shun-dgut** [comment]
> I suggest you to add these functions in main component instead of the `door-lock-server.cpp`. And you can also create class [`LockEndpoint`](https://github.com/project-chip/connectedhomeip/blob/master/examples/lock-app/linux/src/LockEndpoint.cpp) and class [`LockManager`](https://github.com/project-chip/connectedhomeip/blob/master/examples/lock-app/linux/src/LockManager.cpp) like the upstream linux door-lock app.

Ok, I'll try this, but I can add a door_lock device and control it.

**Comment by shun-dgut** [comment]
> I suggest you to add these functions in main component instead of the `door-lock-server.cpp`. And you can also create class [`LockEndpoint`](https://github.com/project-chip/connectedhomeip/blob/master/examples/lock-app/linux/src/LockEndpoint.cpp) and class [`LockManager`](https://github.com/project-chip/connectedhomeip/blob/master/examples/lock-app/linux/src/LockManager.cpp) like the upstream linux door-lock app.


It is not possible for me to use the following code

```
  app_bridge_create_bridged_device(node, aggregator_endpoint_id, ESP_MATTER_WINDOW_COVERING_DEVICE_TYPE_ID,
                                                 ESP_MATTER_BRIDGED_DEVICE_TYPE_BLEMESH,
                                                 app_bridge_blemesh_address(0x0012));
    app_bridge_create_bridged_device(node, aggregator_endpoint_id, ESP_MATTER_DOOR_LOCK_DEVICE_TYPE_ID,
                                                 ESP_MATTER_BRIDGED_DEVICE_TYPE_BLEMESH,
                                                 app_bridge_blemesh_address(0x0013));        
    app_bridge_create_bridged_device(node, aggregator_endpoint_id, ESP_MATTER_ON_OFF_LIGHT_DEVICE_TYPE_ID,
                                                 ESP_MATTER_BRIDGED_DEVICE_TYPE_BLEMESH,
                                                 app_bridge_blemesh_address(0x0014));
```

The following code is ok

```
app_bridge_create_bridged_device(node, aggregator_endpoint_id, ESP_MATTER_DOOR_LOCK_DEVICE_TYPE_ID,
                                                 ESP_MATTER_BRIDGED_DEVICE_TYPE_BLEMESH,
                                                 app_bridge_blemesh_address(0x0012));
    app_bridge_create_bridged_device(node, aggregator_endpoint_id, ESP_MATTER_DOOR_LOCK_DEVICE_TYPE_ID,
                                                 ESP_MATTER_BRIDGED_DEVICE_TYPE_BLEMESH,
                                                 app_bridge_blemesh_address(0x0013));        
    app_bridge_create_bridged_device(node, aggregator_endpoint_id, ESP_MATTER_DOOR_LOCK_DEVICE_TYPE_ID,
                                                 ESP_MATTER_BRIDGED_DEVICE_TYPE_BLEMESH,
                                                 app_bridge_blemesh_address(0x0014));  
```

**Comment by shun-dgut** [comment]
Three light sub-settings are acceptable, three lock sub-settings are also normal, and three windowcovering sub-settings are also normal.

**Comment by wqx6** [comment]
@shun-dgut So problem will happen if you add three endpoints with different device type on one node? Then it could be the issue of the homepod mini or Apple Home app.

**Comment by shun-dgut** [comment]
> @shun-dgut So problem will happen if you add three endpoints with different device type on one node? Then it could be the issue of the homepod mini or Apple Home app.

will not appear. Can you provide an example of creating lock and curtain?

**Comment by wqx6** [comment]
> Can you provide an example of creating lock and curtain?

@shun-dgut We provided an example for doorlock manage [here](https://github.com/project-chip/connectedhomeip/tree/master/examples/platform/esp32/lock) in upstream repo.

> The problem only occurs with Apple home with Google home working fine

@stefano055415 Then it could be the issue of Apple software component. We will test that later.

**Comment by dhrishi** [comment]
@shun-dgut  @wqx6 Is anything pending here? Or it can be closed if it's not an issue on the device side?

**Comment by dhrishi** [comment]
Closing this. Please re-open in case of anything
