### ISSUE TITLE
How to add a contact senser and change its state?

### ISSUE THREAD

**Issue by Firesuiry** [espressif/esp-matter#128]
I use the following code but when I connect it with my iPhone, I can not see this device.
```
    contact_sensor::config_t contact_senser_config;
    contact_senser_config.boolean_state.state_value = false;
    endpoint_t *endpoint3 = contact_sensor::create(node, &contact_senser_config, ENDPOINT_FLAG_NONE, 0);

    if(!endpoint3){
        ESP_LOGE(TAG, "Test contact_sensor creation failed");
    }
    light_endpoint3_id = endpoint::get_id(endpoint3);
    ESP_LOGI(TAG, "Test contact_sensor created with endpoint_id %d", light_endpoint3_id);
```
the log is:
```
I (557) app_main: Test contact_sensor created with endpoint_id 3
```

what is more, how to change the state of the senser?

**Comment by jadhavrohit924** [comment]
Hi @Firesuiry, could you please share what iPhone is showing? If you have screenshot that will be helpful.

**Comment by jonsmirl** [comment]
The endpoint number is 3, he likely has other endpoints.  IOS does not currently understand multiple endpoints and he should get Matter Device Unsupported icon. Might work as expected if contact sensor is the only end point.

**Comment by dhrishi** [comment]
@Firesuiry I added your code to the existing light example. Note that, the contact sensor is created at endpoint 2 in this case (0: root node, 1: color temperature light 2: contact sensor). I was able to commission the device using Apple Home.

Post that, I could see the sensor under the "Security" tab with 1 alert: Sensor Open

![Sensor_Open](https://user-images.githubusercontent.com/5638177/208644874-65e1d642-4681-45e9-8be6-e78d399f9bbe.png)

Then, I changed the state of the StateValue attribute of the Boolean State cluster to true (update attribute locally using the device CLI) and the security section changed to no alerts

```
> matter esp attribute set 0x0002 0x0045 0x0000 1

where: 0x0002 - endpoint id, 0x0045 - cluster id for Boolean State, 0x0000 - attribute id for StateValue, 1 - new value (true)
```


![Sensor_Close](https://user-images.githubusercontent.com/5638177/208645207-9363688d-9783-4262-9857-7bf696968c32.png)

Can you please give it a try and check if you see something similar?

**Comment by dhrishi** [comment]
@Firesuiry Please close this if your issue is resolved

**Comment by Firesuiry** [comment]
ok, because im not at home, i will try to solve it later.



---Original---
From: "Hrishikesh ***@***.***&gt;
Date: Thu, Dec 22, 2022 20:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [espressif/esp-matter] How to add a contact senser and change itsstate? (Issue #128)




 
@Firesuiry Please close this if your issue is resolved

**Comment by Firesuiry** [comment]
Thank you for your help! @jonsmirl @jadhavrohit924 @dhrishi 
I delete other endpoint and the screenshot is as follows:
![image0](https://user-images.githubusercontent.com/30189673/209753575-85749d6e-d389-43c2-8d39-5107c70b590d.png)

the code is:
```
    contact_sensor::config_t contact_senser_config;
    contact_senser_config.boolean_state.state_value = false;
    endpoint_t *endpoint3 = contact_sensor::create(node, &contact_senser_config, ENDPOINT_FLAG_NONE, 0);

    if(!endpoint3){
        ESP_LOGE(TAG, "Test contact_sensor creation failed");
    }
    light_endpoint3_id = endpoint::get_id(endpoint3);
    ESP_LOGI(TAG, "Test contact_sensor created with endpoint_id %d", light_endpoint3_id);
```
I try matter esp attribute set and it seems success.
```
> matter esp attribute set 0x0001 0x0045 0x0000 1
I (357833) esp_matter_attribute: ********** Endpoint 0x0001's Cluster 0x0045's Attribute 0x0000 is 1 **********
Done
> matter esp attribute set 0x0001 0x0045 0x0000 0
I (363003) esp_matter_attribute: ********** Endpoint 0x0001's Cluster 0x0045's Attribute 0x0000 is 0 **********
Done
```

**Comment by Firesuiry** [comment]
my iOS version is 16.2.

**Comment by Firesuiry** [comment]
![image0 (1)](https://user-images.githubusercontent.com/30189673/209754441-10201147-c4b2-4589-b34f-a3f2f0486900.png)
I do not have a Security tab in Home App.

**Comment by Firesuiry** [comment]
I update the version of matter sdk and the problem is solved!
Thank you all of you~
