### ISSUE TITLE
Devices are showing offline with google home

### ISSUE THREAD

**Issue by SYESHASWINI** [espressif/esp-matter#129]
I have flashed matter light example to Esp32c3 board and added the device to google home. It is successfully added, but the device is showing offline. I have factory reset the nest hub,  updated google home and tried, but nothing worked. Requesting for the suggestions.

Board: esp32c3
Nest Hub version: 1.56.324896

![WhatsApp Image 2022-12-20 at 15 09 02](https://user-images.githubusercontent.com/59026832/208634807-35332c28-2bf6-4a9f-9651-598542700dd0.jpeg)

Thank You.

**Comment by dhrishi** [comment]
@SYESHASWINI Do you still see any issue with the latest codebase? We can get it to work as expected

**Comment by sidhoo2** [comment]
@dhrishi Is there any commits for this issue? i found the device hv not get the ipv6 addr when the Google Home show Offline
