### ISSUE TITLE
Matter device showing offline in apple homekit

### ISSUE THREAD

**Issue by SYESHASWINI** [espressif/esp-matter#130]
I have flashed matter Light example to Esp32c3 board and added the device to apple homekit. It is successfully added, but the device is showing offline. I'm using home pod to control the device. I have factory reset and updated home pod, but nothing worked. Requesting for the suggestions.

Board: esp32c3
Home pod version:16.2
![IMG_0017](https://user-images.githubusercontent.com/59026832/208640633-c675f1e8-9db1-4503-9a32-acc554d6adb0.PNG)

**Comment by shubhamdp** [comment]
@SYESHASWINI I tried three scenarios and device is reachable in all three.
1. Homepod, Phone, and ESP32C3 in same network and connected to internet
2. Homepod, phone, and ESP32C3 in same network and no internet connectivity
3. Homepod and ESP32 in different wifi network and connected to internet. Phone in different wifi network and connected to internet.

Can you try flashing the matter light example from here: https://espressif.github.io/esp-launchpad/?flashConfigURL=https://espressif.github.io/esp-matter/launchpad.toml

**Comment by SYESHASWINI** [comment]
@shubhamdp With launchpad its working fine. When I flash the code using terminal/cmd the devices are showing offline. Is there any other approach for it to make device reachable.

Thank You

**Comment by dhrishi** [comment]
@SYESHASWINI The binaries on the Launchpad are based on the local codebase. So, those are the the default ones.

Can you please follow the steps below:

```
$ cd /path/to/esp-matter/examples/light
$ rm -rf sdkconfig sdkconfig.old build/
$ idf.py set-target esp32c3
$ idf.py erase-flash
$ idf.py build flash monitor
```

**Comment by SYESHASWINI** [comment]
@dhrishi I tried this, but after may trails the device is reachable. The device is not reachable everytime

**Comment by SYESHASWINI** [comment]
@dhrishi I have tried as you said, but after many trials the device is reachable.  Everytime I flash the device, very often the device is unreachable only few times its reachable. 

I have made few changes in the sdk so that it have 4 endpoints. Sometimes the device is added with only 3 endpoints.
Any solutions for this.

**Comment by SYESHASWINI** [comment]
@dhrishi I have tried as you said, but after many trials the device is reachable. Everytime I flash the device, very often the device is unreachable only few times its reachable.

I have made few changes in the sdk so that it have 4 endpoints. Sometimes the device is added with only 3 endpoints.
Any solutions for this.

**Comment by dhrishi** [comment]
@SYESHASWINI Please close this issue and create a new one with the details of the changes you've done (patch)
