### ISSUE TITLE
error 13 in install.sh immediately closes wsl2 window

### ISSUE THREAD

**Issue by fkkjohn** [espressif/esp-matter#135]
I've finally gotten everything setup successfully until esp-matter, and as soon as I type in ". ./install.sh", my wsl2 window is closed by an error that can't be seen by the naked eye unless you run the file with "sh install.sh", then you can see there's error 13, source cannot be found. At least that's the error I got after going back in and trying without all of the exports. This is extremely frustrating because it closes all of my virtual environments with it. Now I have to go back in and re-export.sh matter and esp-idf just to try something else, at which point it will undoubtedly close my window again. I've searched the .sh files for an exit command and I can't find one. Why is it closing my window on a small error like this? What can we do to prevent such anti-user behavior?

**Comment by shubhamdp** [comment]
Install.sh script is supposed to be executed and not sourced. I see you have source it -> `. ./install.sh`.

**Comment by dhrishi** [comment]
@fkkjohn Please close the issue if this helps

**Comment by dhrishi** [comment]
Closing. Feel free to reopen in case of any issue
