### ISSUE TITLE
electrical measurement cluster

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#136]
I missed CHIP adding an electrical measurement cluster. I will need to use this:

commit 3d9fc15e2e766e37d0eb510bd2d8a5b080057844
Author: eve-cxrp <[80681009+eve-cxrp@users.noreply.github.com](mailto:80681009%2Beve-cxrp@users.noreply.github.com)>
Date:   Sat Jul 3 04:16:15 2021 +0200

    support for electrical measurement cluster (#7953)
   
    * add electrical measurement cluster to controller-clusters.zap

**Comment by dhrishi** [comment]
Electrical measurement cluster does not seem to be a part of v1.0 specification
