### ISSUE TITLE
how to get config wifi ssid and password

### ISSUE THREAD

**Issue by shun-dgut** [espressif/esp-matter#139]
I want to get the wifi information configured by the device through Matter in the main function. Can you provide an example?

**Comment by dhrishi** [comment]
`esp_wifi_sta_get_ap_info`, usage [here](https://github.com/espressif/connectedhomeip/blob/87bee4de25886ba00f1a177cd0f8791a48528a1f/src/platform/ESP32/DiagnosticDataProviderImpl.cpp#L271)

**Comment by dhrishi** [comment]
@shun-dgut Please close the issue if your question is answered
