### ISSUE TITLE
[API consult] where can i find the matter ble adv api?

### ISSUE THREAD

**Issue by sidhoo2** [espressif/esp-matter#140]
cause i need to pair both matter and my own app，so can i open two ble adv ?

**Comment by dhrishi** [comment]
@sidhoo2 APIs are:
`ble_gap_adv_set_data()` usage [here](https://github.com/espressif/connectedhomeip/blob/87bee4de25886ba00f1a177cd0f8791a48528a1f/src/platform/ESP32/nimble/BLEManagerImpl.cpp#L738) followed by `ble_gap_adv_start` usage [here](https://github.com/espressif/connectedhomeip/blob/87bee4de25886ba00f1a177cd0f8791a48528a1f/src/platform/ESP32/nimble/BLEManagerImpl.cpp#L1222)

**Comment by jonsmirl** [comment]
You should not be pairing Matter and then your own app with a separate BT protocol.  There is a standard pairing procedure on both IOS and Android which will pair both your app and Apple/Google Home all in a single step.  After that your app should implement a vendor specific, Matter endpoint/cluster to do custom setup.

**Comment by sidhoo2** [comment]
@dhrishi thanks, Is there any api to add anothor ble slave ?

**Comment by sidhoo2** [comment]
@jonsmirl yes, using the matter pairing procedure is ok, but my project needs to transfer different data within the ble protocol, so,  is there any way to establish two ble connections ?

**Comment by dhrishi** [comment]
@sidhoo2 Why do you need 2 BLE connections? When do you want to exchange the data over BLE? Will post-commissioning be okay? As for Matter, you would not need BLE anytime after the first commissioning is done

**Comment by sidhoo2** [comment]
@dhrishi post-commissioning ?  such as the ble mesh example?

**Comment by dhrishi** [comment]
@sidhoo2 Yes. Depending on your usecase. That's why I want to know:

>When do you want to exchange the data over BLE?  

Also, if you can share the purpose of this BLE data transfer, it will help

**Comment by dhrishi** [comment]
Closing as the original question is answered. Please share details for any further help.
