### ISSUE TITLE
Pressure cluster

### ISSUE THREAD

**Issue by slompf18** [espressif/esp-matter#146]
I tried to implement a pressure sensor endpoint by forking this repository. But I'm ending in Homekit saying the device is not supported. Are pressure sensors not supported in Homekit or am I missing something?

You can have a look [here](https://github.com/slompf18/esp-matter-pressure). Essentially I copied endpoint, cluster and attributes from the temperature sensor. It has the same mandatory attributes. The app I'm testing with is working fine with a temperature sensor.

**Comment by jadhavrohit924** [comment]
Pressure sensor is not supproted in HomeKit.

**Comment by slompf18** [comment]
Thank you for the information. Is there an overview, what is supported?

**Comment by jadhavrohit924** [comment]
Apple supported devices [here](https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/darwin.md#testing-your-matter-device-with-apple-home)

**Comment by slompf18** [comment]
Thanks
