### ISSUE TITLE
ESP32 RAINMAKER + MATTER CODE EXAMPLE NOT FOUND. (CON-264)

### ISSUE THREAD

**Issue by emangler** [espressif/esp-matter#149]
NOT ABLE TO LOCATE AN ESP32 RAINMAKER + MATTER CODE EXAMPLE. WHEN WILL A ESP32 RAINMAKER + MATTER CODE EXAMPLE BE AVAILABLE?

**Comment by dhrishi** [comment]
@emangler RainMaker + Matter example is under review and will be made available soon in the [esp-rainmaker](https://github.com/espressif/esp-rainmaker/) repository

**Comment by emangler** [comment]
Thank you very much. I appreciate your quick response. I am looking forward to testing the RainMaker + Matter Example and incorporating it into our products.

**Comment by dhrishi** [comment]
@emangler Do you need RainMaker for remote control or device management (OTA, insights etc.) or for both? It will help, if you can provide some details about your usecase.

**Comment by emangler** [comment]
Hello. Sorry for the late response. Our company makes Motorized Gate Operators. You can check out our products at http://www.allomatic.netWe need RainMaker for both remote control and device management (OTA, insights etc.)Thank you.
-------- Original message --------From: Hrishikesh Dhayagude ***@***.***> Date: 1/24/23  8:44 PM  (GMT-08:00) To: espressif/esp-matter ***@***.***> Cc: emangler ***@***.***>, Mention ***@***.***> Subject: Re: [espressif/esp-matter] ESP32 RAINMAKER + MATTER CODE EXAMPLE NOT FOUND. (Issue #149) 
@emangler Do you need RainMaker for remote control or device management (OTA, insights etc.) or for both? It will help, if you can provide some details about your usecase.

**Comment by dhrishi** [comment]
@emangler The RainMaker + Matter example is now available in the esp-rainmaker repository, here: https://github.com/espressif/esp-rainmaker/tree/master/examples/matter
