### ISSUE TITLE
connectedhomeip - New released tag v1.0.0.2

### ISSUE THREAD

**Issue by El-Mango** [espressif/esp-matter#150]
It would be better to move to V1.0.0.2

[V1.0.0.1 Bug Fix Release](https://github.com/project-chip/connectedhomeip/releases/tag/V1.0.0.1) Pre-release
Do not ship this release
Please use https://github.com/project-chip/connectedhomeip/releases/tag/v1.0.0.2 instead. This release is not backwards-compatible with the 1.0 release.

**Comment by dhrishi** [comment]
@El-Mango Thanks for the information. We will update to v1.0.0.2 soon

**Comment by dhrishi** [comment]
@El-Mango Fixed with https://github.com/espressif/esp-matter/commit/98391d901d601d6d15d246c585cd2dccca18588d
