### ISSUE TITLE
Unable to generate correct QR code

### ISSUE THREAD

**Issue by shun-dgut** [espressif/esp-matter#159]
custom flow  does not know why it is specified，without specifying ble

![image](https://user-images.githubusercontent.com/31812214/211494902-674fecb1-04ba-4f14-90de-3bf041b67b07.png)

**Comment by dhairyashah1** [comment]
@shun-dgut 
The `custom flow` is defined and governed by the `commissioning mode` parameter. 
![81152204-9a02-4447-8615-b7ede120b451](https://user-images.githubusercontent.com/64425805/211528178-2f212bbc-a075-4f29-8c71-714e3b4c5b75.jpg)

Custom flow value field can have three values - `0, 1 or 2`. This is mentioned in the `Matter_Core_V1.0_Specification` -
![Screenshot from 2023-01-10 16-04-54](https://user-images.githubusercontent.com/64425805/211529020-2f433b90-f99b-4e8b-9db6-1a06298a4f52.png)

**Comment by shun-dgut** [comment]
> @shun-dgut The `custom flow` is defined and governed by the `commissioning mode` parameter. ![81152204-9a02-4447-8615-b7ede120b451](https://user-images.githubusercontent.com/64425805/211528178-2f212bbc-a075-4f29-8c71-714e3b4c5b75.jpg)
> 
> Custom flow value field can have three values - `0, 1 or 2`. This is mentioned in the `Matter_Core_V1.0_Specification` - ![Screenshot from 2023-01-10 16-04-54](https://user-images.githubusercontent.com/64425805/211529020-2f433b90-f99b-4e8b-9db6-1a06298a4f52.png)
> 
> Since you have set `commissioning mode -> 2` what exactly do you want/desire to do with the custom flow?

Thanks ，If I want to set Discovery Bitmask what parameters do I need

![image](https://user-images.githubusercontent.com/31812214/211530984-b3303c6a-2dcb-4b55-bdc8-1136d9c10044.png)

**Comment by dhairyashah1** [comment]
@shun-dgut 
1. The discovery bitmask can be set using the `--rendezvous` option present in the command,
![image](https://user-images.githubusercontent.com/64425805/211558524-f84479a5-ddbf-4047-b896-594f4a1d8b9b.png)

2. Usage - 
`  ./chip-tool payload generate-qrcode [--existing-payload] [--discriminator] [--setup-pin-code] [--version] [--vendor-id] [--product-id] [--commissioning-mode] [--allow-invalid-payload] [--rendezvous] [--tlvBytes]`

3. 
![image](https://user-images.githubusercontent.com/64425805/211560376-6e02b212-427b-4b0f-bdc0-cc38c1491c91.png)

**Comment by shun-dgut** [comment]
Thanks
