### ISSUE TITLE
Garage Door Endpoint

### ISSUE THREAD

**Issue by mgoeller** [espressif/esp-matter#160]
Is it correct that Matter so far supports the endpoint "door lock" but that should be only used for a typical building / apartment door?

Is there no endpoint "garage door" available yet?

**Comment by jakubdybczak** [comment]
Nope, there isn't such device as "Garage Door" in Matter spec v.1.0. You can view it here: https://csa-iot.org/developer-resource/specifications-download-request/

And yes, Door Lock does **not** fit with this use case (Door Lock does not allow partly opened doors, for example). I hope that we will get such device (and some Gate device) support in future...
