### ISSUE TITLE
how to set window_covering device calibration mode (CON-227)

### ISSUE THREAD

**Issue by shun-dgut** [espressif/esp-matter#184]
How do I set the Needs Calibration flag for the window_covering device, and also how can I test that the Needs Calibration flag for the device is set correctly?

**Comment by shun-dgut** [comment]
```
window_covering_device::config_t window_covering_conf;
window_covering_conf.window_covering.type = 0x04;
window_covering_conf.window_covering.mode = 0x01;
bridged_device->endpoint = window_covering_device::add(bridged_device->endpoint, &window_covering_conf);
```

**Comment by jadhavrohit924** [comment]
@shun-dgut Spec say 1 bit should be set of `mode`. Can you try setting mode value to `0x02`.

**Comment by dhrishi** [comment]
@shun-dgut Please close this issue if your question is answered

**Comment by dhrishi** [comment]
Closing this. Feel free to re-open in case of any issue
