### ISSUE TITLE
The dac generated using the generated tool cannot be configured by chiptool, but the one using the default code can. (CON-228)

### ISSUE THREAD

**Issue by shun-dgut** [espressif/esp-matter#185]
Using the generated dac can be added via iphone home, but cannot be configured by chiptool

Using the code default dac can be added by iphone home and can be configured by chiptool.

The logs that cannot be configured are as follows

[chiptool log.txt](https://github.com/espressif/esp-matter/files/10535424/chiptool.log.txt)

**Comment by shubhamdp** [comment]
```
Failed in verifying 'Attestation Information' command received from the device: err 604
```
https://github.com/project-chip/connectedhomeip/blob/master/src/credentials/attestation_verifier/DeviceAttestationVerifier.h#L72

Looks like the vendor Id in DAC, CD, and the one reported by basic cluster is not matching.

You will have to make sure the VID and PID in all these three must match if you are using different VID/PID

**Comment by shubhamdp** [comment]
You can use https://github.com/project-chip/connectedhomeip/blob/master/src/tools/chip-cert/README.md#gen-cd command to generate the test certification declaration with desired VID/PID

**Comment by shun-dgut** [comment]
> You can use https://github.com/project-chip/connectedhomeip/blob/master/src/tools/chip-cert/README.md#gen-cd command to generate the test certification declaration with desired VID/PID

use cmd gen dac 
```
./mfg_tool.py -cn "xxxx" -v 0xFFF2 -p 0x8001 --pai \
   -k ~/Matter_Pro/esp-matter/connectedhomeip/connectedhomeip/credentials/test/attestation/Chip-Test-PAI-FFF2-8001-Key.pem \
   -c ~/Matter_Pro/esp-matter/connectedhomeip/connectedhomeip/credentials/test/attestation/Chip-Test-PAI-FFF2-8001-Cert.pem \
   -cd ~/Matter_Pro/esp-matter/connectedhomeip/connectedhomeip/credentials/test/certification-declaration/Chip-Test-CD-FFF2-8001.der
```

**Comment by shubhamdp** [comment]
Can you please share the `sdkconfig` generated for this build, since you are reading stuff from the factory partition, below options shall be enabled.
```
CONFIG_ENABLE_ESP32_FACTORY_DATA_PROVIDER=y
CONFIG_FACTORY_PARTITION_DAC_PROVIDER=y
CONFIG_ENABLE_ESP32_DEVICE_INSTANCE_INFO_PROVIDER=y
```

Can you also specify the address that was used to flash the factory partition? It should be the address of value specified in `CONFIG_CHIP_FACTORY_NAMESPACE_PARTITION_LABEL` option.

**Comment by shun-dgut** [comment]
> Can you please share the `sdkconfig` generated for this build, since you are reading stuff from the factory partition, below options shall be enabled.
> 
> ```
> CONFIG_ENABLE_ESP32_FACTORY_DATA_PROVIDER=y
> CONFIG_FACTORY_PARTITION_DAC_PROVIDER=y
> CONFIG_ENABLE_ESP32_DEVICE_INSTANCE_INFO_PROVIDER=y
> ```
> 
> Can you also specify the address that was used to flash the factory partition? It should be the address of value specified in `CONFIG_CHIP_FACTORY_NAMESPACE_PARTITION_LABEL` option.
![image](https://user-images.githubusercontent.com/31812214/215716455-5147215b-28c9-487a-8288-f662e6a7d24d.png)
![image](https://user-images.githubusercontent.com/31812214/215716545-78492471-e217-41f0-b545-407f36a49149.png)

I've set these parameters, but it still doesn't work.

I can add devices using homekit

**Comment by shubhamdp** [comment]
Hi, can you enable `CONFIG_FACTORY_PARTITION_DAC_PROVIDER=y` and `CONFIG_ENABLE_ESP32_DEVICE_INSTANCE_INFO_PROVIDER=y` options?

First one is for reading DACs from the factory partition and second one is for reading vid/pid from the factory partition.

Also, I assume you are flashing the generated partition at the address of `fctry` partition.

**Comment by shun-dgut** [comment]
> Hi, can you enable `CONFIG_FACTORY_PARTITION_DAC_PROVIDER=y` and `CONFIG_ENABLE_ESP32_DEVICE_INSTANCE_INFO_PROVIDER=y` options?
> 
> First one is for reading DACs from the factory partition and second one is for reading vid/pid from the factory partition.
> 
> Also, I assume you are flashing the generated partition at the address of `fctry` partition.

Thanks，CONFIG_ENABLE_ESP32_DEVICE_INSTANCE_INFO_PROVIDER = y is Ok
