### ISSUE TITLE
All examples state "not responding" in Home app (CON-237)

### ISSUE THREAD

**Issue by JonathanWitthoeft** [espressif/esp-matter#188]
I am using an ESP32-WROOM-32E
esp-idf 4.4.3
esp-matter [e5d7cac] (latest commit as of now)
iOS version 16.3

I have built both bridge examples and the standard light example. They all commission fine in the Home app, but the accessory is never reachable. I also tried via google and it reported a "network error". Any ideas?

**Comment by JonathanWitthoeft** [comment]
If I close and open the Home App, it tries to read the accessory status again and at that moment I get a 
`W (160518) ROUTE_HOOK: Ignore invalid ICMP packet`
```
I (4498) chip[DL]: IP_EVENT_STA_GOT_IP
I (4498) chip[DL]: IPv4 address changed on WiFi station interface: 22.22.22.230/255.255.255.0 gateway 22.22.22.2
I (4508) chip[DL]: IPv4 Internet connectivity ESTABLISHED
I (4528) app_main: Interface IP Address Changed
I (4528) chip[DIS]: Updating services using commissioning mode 0
I (4538) chip[DIS]: CHIP minimal mDNS started advertising.
I (4538) chip[DIS]: Advertise operational node BE29425A822B6019-000000001B701638
I (4548) chip[DIS]: CHIP minimal mDNS configured as 'Operational device'; instance name: BE29425A822B6019-000000001B701638.
I (4568) chip[DIS]: mDNS service published: _matter._tcp
I (4568) chip[DIS]: Advertise operational node 85A15C378BDB3B16-000000007643929A
I (4578) chip[DIS]: CHIP minimal mDNS configured as 'Operational device'; instance name: 85A15C378BDB3B16-000000007643929A.
I (4588) chip[DIS]: mDNS service published: _matter._tcp
I (5998) chip[DL]: IP_EVENT_GOT_IP6
I (5998) chip[DL]: IPv6 addr available. Ready on WIFI_STA_DEF interface: fe80:0000:0000:0000:963c:c6ff:fecd:d040
I (6008) app_main: Interface IP Address Changed
I (6018) chip[DIS]: Updating services using commissioning mode 0
I (6018) chip[DIS]: CHIP minimal mDNS started advertising.
I (6048) chip[DIS]: Advertise operational node BE29425A822B6019-000000001B701638
I (6048) chip[DIS]: CHIP minimal mDNS configured as 'Operational device'; instance name: BE29425A822B6019-000000001B701638.
I (6068) chip[DIS]: mDNS service published: _matter._tcp
I (6068) chip[DIS]: Advertise operational node 85A15C378BDB3B16-000000007643929A
I (6068) chip[DIS]: CHIP minimal mDNS configured as 'Operational device'; instance name: 85A15C378BDB3B16-000000007643929A.
I (6098) chip[DIS]: mDNS service published: _matter._tcp
I (6098) ROUTE_HOOK: Hook already installed on netif, skip...
W (115968) ROUTE_HOOK: Ignore invalid ICMP packet
W (160518) ROUTE_HOOK: Ignore invalid ICMP packet
```

**Comment by shubhamdp** [comment]
Can you please share the complete logs? Also, I assume there is a Apple Homepod in the network when commissioning using Apple Home app.

**Comment by wqx6** [comment]
The ROUTE_HOOK warning is not related to this issue, This warning only means that the ESP32 drops the invalid Router Advertisement packets.

**Comment by JonathanWitthoeft** [comment]
I didn't think a HomePod mini was required if it was matter over IP, but I added one and got the same result.
I created a separate network with a HomePod mini, my iPhone, and this WiFi matter light. 
Here are the full logs including commissioning. 
[full_logs_wifi_light.txt](https://github.com/espressif/esp-matter/files/10548035/full_logs_wifi_light.txt)

**Comment by JonathanWitthoeft** [comment]
This must be an issue with Apple cloud, iOS on iPhone mini 13, or multiple Homes.

**iPhone 13 mini with iOS 16.3, multiple Homes (different networks) with multiple HomePod minis (5):**
Accessory is commissioned but always get "no response"

**iPhone XR with iOS 16.3, 1 default Home ("My Home"), 1 HomePod mini:**
Accessory both commissions and responds.

**Comment by ph2355** [comment]
I have the same problem. I am able to commission a device in the Home app, but it is not responding. 
Is a matter hub required to control a device with the Home app? I was not able to find a definitive answer on this.

**Comment by shubhamdp** [comment]
@ph2355 Yes, for Apple Home app, Homepod or Apple TV is required to commission and control. For Google Home app, you can commission the device using just phone app but Nest Hub is required to control the device
