### ISSUE TITLE
about Multi-admin，Passcode how is it generated (CON-247)

### ISSUE THREAD

**Issue by shun-dgut** [espressif/esp-matter#191]
Run a command similar to the following, the tool will return the setup payload and manual code. I only pass the discriminator, how the passcode is generated
```
./chip-tool pairing open-commissioning-window <node_id> <option> <window_timeout> <iteration> <discriminator>
```

**Comment by wqx6** [comment]
The Passcode is generated randomly with the spake2+ verifier at https://github.com/project-chip/connectedhomeip/blob/master/src/controller/CommissioningWindowOpener.cpp#L110

**Comment by dhrishi** [comment]
Closing as the question is answered
