### ISSUE TITLE
esp-idf installation for esp-matter not working (CON-248)

### ISSUE THREAD

**Issue by rhr407** [espressif/esp-matter#192]
I am getting the following error while installing esp-idf for esp-matter by following [these](https://docs.espressif.com/projects/esp-matter/en/main/esp32/developing.html) steps:

![image](https://user-images.githubusercontent.com/26026993/216067636-55c4d055-966f-4a64-a2f0-7c55a3ce9f23.png)

**Comment by igrr** [comment]
Please try removing `~/.espressif/idf-env.json` file and running the installation process again: https://github.com/espressif/esp-idf/issues/9837.

**Comment by dhrishi** [comment]
@rhr407 Can you please close the issue if the above suggestion helped?

**Comment by rhr407** [comment]
Thanks
