### ISSUE TITLE
Session resumption and chip-tool

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#20]
Please adjust the documentation to reflect using chip-tool in interactive mode:
./chip-tool interactive start

Also explain that first time session is made it takes about 5 seconds, then if you keep the session open subsequent command run in 1.1 to 1.5 seconds.   This needs to be explained to ensure customers come to the right conclusion on ESP Matter performance.

This avoids doing the session setup and tear down on each command. That setup takes about 4 seconds on a C3.

In interactive mode, to toggle light:
ESP32 240Mhz -- 1.14 seconds
ESP32C3 -- 1.52 seconds

**Comment by dhrishi** [comment]
Yes, we will update the instructions soon.

**Comment by dhrishi** [comment]
Documentation updated
