### ISSUE TITLE
Unable to add the latest light example device with the Apple Home APP and homepodmini (CON-263)

### ISSUE THREAD

**Issue by VivekPalle** [espressif/esp-matter#204]
Hi,

I just clone the latest sdk and built the **light** example, but unable to add the device to the Apple Home APP with Homepod mini.
Please help with the same. Please find the attached log for your reference.
[fail-to-add log2.txt](https://github.com/espressif/esp-matter/files/10663042/fail-to-add.log2.txt)

**Comment by dhrishi** [comment]
@VivekPalle Do you have any update to share? Please close the issue if it works fine

**Comment by dhrishi** [comment]
Closing this. Please try with Launchpad as the first step and create a new issue if you still face problems.

**Comment by suktry** [comment]
Hello, may I ask how you resolved it? I'm facing the same issue, please advise.
