### ISSUE TITLE
Detecting multiple endpoints in Alexa app (CON-278)

### ISSUE THREAD

**Issue by antonio2904** [espressif/esp-matter#213]
Is there a way to register multiple devices in Alexa app? I have 2 endpoints both of which are on_off_plugin_unit. It is controllable from the device console. But only the first endpoint is shown in Alexa app when commissioned.

**Comment by jonsmirl** [comment]
Check and see what it does in both Google and Apple Home. Both Google and Apple handle devices with multiple endpoints.  If it works in Google and Apple Home complain to Amazon. If it doesn't work on Goog/Apple, something is not right on your end.

**Comment by VaishaliAvhale** [comment]
We checked with Alexa and see the same problem. While other ecosystem apps (Google, Apple) support multiple endpoints.

**Comment by dhrishi** [comment]
@antonio2904 Can we close this as this seems to be an issue with a specific commissioner phone app?
