### ISSUE TITLE
ENABLE_CHIP_SHELL

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#22]
If I turn on ENABLE_CHIP_SHELL in the ble bridge example, it won't link.  But the light and light_switch examples have it turned on and they do link. What is the difference?

**Comment by InfiniteYuan** [comment]
because of ble mesh bridge example use external platform, does not support shell. PTAL: https://docs.espressif.com/projects/esp-matter/en/main/esp32/developing.html?highlight=custom#advanced-setup

**Comment by jonsmirl** [comment]
I'll close this, but it would be nice to be able to turn the Matter console on in the ble router. I am combining the BLE router into a standard Matter device.
