### ISSUE TITLE
Commission 2 esp32 boards with chip-tool into Matter network (CON-289)

### ISSUE THREAD

**Issue by SergiSoler8** [espressif/esp-matter#221]
Hi,

My question is how i commision 2 LOLIN D32 boards with chip-tool into Matter network.

Regards, thank you.

**Comment by dhrishi** [comment]
@SergiSoler8 Please follow the documentation here: https://docs.espressif.com/projects/esp-matter/en/latest/esp32/developing.html#developing-with-the-sdk

You can compile and flash the light example on both of the devices. To commission them, you need to use different node ids in the commissioning command from the chip-tool.

**Comment by dhrishi** [comment]
Closing this as the question is answered
