### ISSUE TITLE
BLE-mesh demo and BLE beacons (CON-295)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#226]
Can the BLE Mesh code in the BLE-mesh demo also see nearby BLE beacons? As in not using the mesh, if the beacon is near the blemesh-bridge will the bridge BLE code report seeing it? Like iBeacon or Eddystone, not special mesh beacons.

**Comment by InfiniteYuan** [comment]
blemesh-bridge example don't report these beacons now, only report the unprovisioned beacon for ble-mesh.
