### ISSUE TITLE
Color in the light example (CON-298)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#229]
BTW, support for XY color in Extend_Color_Light is mandatory and Hue/Saturation is optional. I have not checked all of the controllers, does Amazon use XY or HS? The example isn't implementing the mandatory XY support.

Here is the needed math.
https://gist.github.com/popcorn245/30afa0f98eea1c2fd34d

**Comment by dhrishi** [comment]
> The example isn't implementing the mandatory XY support.

@jonsmirl The light example implements Matter Color Temperature Light device type and not Extended Color Light. In that device type, XY is not mandatory and hence not added.
