### ISSUE TITLE
ESP32C3 Matter

### ISSUE THREAD

**Issue by Mallik-Tarigopula** [espressif/esp-matter#23]
Hi Espressif team,
   I started working on Matter Protocol on ESP32C3 dev Kit.
   I am able to setup ESP-IDF on ubuntu 20.04 system.
   I am able to load example 'light' on the module. While commissioning the device using 'Espressif-Matter' App available on App store it got failed. Please find the attached screens for your reference. Please look into it ad guide me how to proceed.
   Also How will I know the Node-ID assigned to my device?
   To verify Matter on Wi-Fi do I need two modules? or I can test even with single Module also. I would like to use chip-tool on ubuntu PC to control 'light' (example code). If I am wrong let me know how to proceed
[matter_log2.txt](https://github.com/espressif/esp-matter/files/9268643/matter_log2.txt)
[matter_log1.txt](https://github.com/espressif/esp-matter/files/9268644/matter_log1.txt)
.

**Comment by ajay-gantayet** [comment]
Hi @Mallik-Tarigopula,  I was able to successfully commission the light example from the esp-matter repo using the Espressif-Matter App Store app and the following commit IDs for esp-matter and connectedhomeip.

esp-matter: f61e804313a3084dfff5e4755fa5df21eda1bb21
submodule connectedhomeip:  c1d543182fccd0c37c03379602a86fddadff68b1

Could you please test using the above commit IDs? PFA the commissioning logs.

[Commissioning.log](https://github.com/espressif/esp-matter/files/9269648/Commissioning.log)

**Comment by dhrishi** [comment]
>Also How will I know the Node-ID assigned to my device?

If you are using the iOS phone app, why do you specifically need the node id?

>To verify Matter on Wi-Fi do I need two modules? or I can test even with single Module also. I would like to use chip-tool on ubuntu PC to control 'light' (example code). If I am wrong let me know how to proceed

Yes, you need only one module/devkit and can use the host-based chip-tool to commission and control it. You can follow the instructions [here](https://docs.espressif.com/projects/esp-matter/en/main/esp32/developing.html#development-setup)

**Comment by dhrishi** [comment]
@Mallik-Tarigopula Do you have any updates to share?

**Comment by dhrishi** [comment]
Closing this. Feel free to reopen
