### ISSUE TITLE
Generating unique QR code for the project (CON-305)

### ISSUE THREAD

**Issue by SYESHASWINI** [espressif/esp-matter#233]
Here for every matter sample code is commissioned using same QR. Can we generate unique qr code for each devices.
Where can we change and select the product and vendor id of the devices. 
Can anyone please suggest the way to get those resolved.

Thank You.

**Comment by dhrishi** [comment]
@SYESHASWINI Please refer to [Production Considerations](https://docs.espressif.com/projects/esp-matter/en/latest/esp32/production.html#production-considerations) section in the documentation. Section `4.3 Manufacturing` should be helpful
