### ISSUE TITLE
private data in app_event_cb(const ChipDeviceEvent *event, intptr_t arg) (CON-313)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#240]
that call supports private data, but err = esp_matter::start(app_event_cb); does not allow you to pass it in. Internally it uses a NULL for the private data. This is easy to work around with a global variable, I just noticed that it was inconsistent.

**Comment by shubhamdp** [comment]
Thanks Jon, for pointing it out, will fix this.
