### ISSUE TITLE
Light example setup using the Programming Guide difficulties (CON-317)

### ISSUE THREAD

**Issue by ocrox** [espressif/esp-matter#244]
I have tried installing and configuring the matter examples for 3 months.

What I wanted to create was a Matter device and a Matter controller, preferably both each on an ESP32.
I started with the Matter device using the 'esp-matter' repo by Espressif and wanted to continue with the 'all-clusters-app' in the 'connectedhomeip' repo.
In the end, I built the light example from the 'esp-matter' repo and used the CHIP Tool from the 'connectedhomeip' repo.
My problem was that some requirements were seemingly omitted and some were quite hidden (for example the 'requirements.txt' was barely mentioned), expected to be found if you knew what you were looking for.

Enough ranting. After quite some headaches and a lot of testing, it seems part of the problem was my own computer and the components and packages already installed on it.
I used my own Ubuntu systems, which was continually upgraded from Ubuntu 16 or 18 (i don't even know anymore at this point). I did install all requirements and reinstalled the entire esp-matter repo several times.
My best guess what the problem might be conflicting calls when having both packages 'python' and 'python3' installed.
The solution for me was to start with a clean system and i have also compiled a step-by-step plan to set up and configure the examples, tried it and succeeded.

I have seen changes to the repos in the meantime, so part of the problem could also be when the required ESP-IDF version was changed from 4.4.1 to 4.4.2 in November, as I started in the end of October.
Also, I might have been blind, but I did not find the guides by Espressif System, now linked in this repo, or the guide by Nordic Semiconductors during my struggle. I started with the guide by Mr. Dhayagude (hats off, this guide got me started with my Matter implementation), but was not able to replicate it.

I want to share my troubles and suspicion, that the packages 'python' and 'python3' might be conflicting when recreating the light example and CHIP Tool. 

I have 2 questions and a request after my successful setup:

1. Can anyone confirm the conflict between the two python packages? I will also try to replicate this error.

2. I have found the pip-requirements in the 'requirements.txt' file to be necessary, but they are listed in case of an error. Installing the requirements has solved errors of missing dependencies listed in the requirements file, but I did not get the listed error. Could the requirements be necessary?

The request is, I want to add several things to the Programming Guide:

- Add to the ESP-IDF setup how to add the user to the 'dialout' group, for ESP-IDF beginners and to make this guide more complete.
- The recursive clones take ages, but I wanted more than the shallow clones. I want to add how to clone with several threads with the git command flag -j.
- I think adding a setup guide for the CHIP Tool before a guide on its commands makes sense, especially when it is possible to use the 'connectedhomeip' submodule. I would like to do so.
- In case someone wants/needs to install the pip-requirements, I want to add a mention that the export scripts, to set up the python environment, need to be added.
(- I will try to replicate the errors in my two questions and will want to add either a mention or a correction) 

Thank you

Ocr

**Comment by dhrishi** [comment]
@ocrox Thank you for the feedback. We will review the requests and the questions posted and add/update the documentation wherever necessary.
cc @shubhamdp
