### ISSUE TITLE
qrcode device category (CON-318)

### ISSUE THREAD

**Issue by stefano055415** [espressif/esp-matter#245]
How is it possible to generate a qrcode that also contains the information of the device category

With apple home, if you scan the qrcode generated, the app shows me a generic accessory.

![IMG_3165](https://user-images.githubusercontent.com/4798738/222119815-a20ebeb2-d32f-49b3-b5fd-fab7911abdf0.jpg)

I wish he would show me the correct category, in my case a light.

I've tried other devices matter that show it

![IMG_8EECF1981CC9-1](https://user-images.githubusercontent.com/4798738/222119858-cd83b151-e5c1-467b-8294-614b8112126c.jpeg)

but using mfg_tool I don't see a parameter to set this setting

**Comment by dhrishi** [comment]
@stefano055415 

>How is it possible to generate a qrcode that also contains the information of the device category

QR code does not contain the device type/category

>I wish he would show me the correct category, in my case a light.

If the product model (including the vid, pid and other details) is uploaded in the DCL, then the correct category would be shown by the Apple Home. It reaches to the DCL to check if there's an entry for that device after scanning the QR code

> I've tried other devices matter that show it

Please check the vid of the device that is showing this and it should be present [here](https://webui.dcl.csa-iot.org/models)

**Comment by stefano055415** [comment]
@dhrishi  ok i understand thanks
