### ISSUE TITLE
Device name Apple home (CON-319)

### ISSUE THREAD

**Issue by stefano055415** [espressif/esp-matter#246]
When I add an accessory to Apple home, the default name is always Matter Accessory.

![IMG_4EE35A2052A6-1](https://user-images.githubusercontent.com/4798738/222121916-544d273d-d478-40fd-8abc-ac097ec20415.jpeg)

I tried to use the fixed_label, common_name, product_name,... with mfg_tool, but the result doesn't change

Can someone help me?

Thank you

**Comment by dhrishi** [comment]
@stefano055415 

>When I add an accessory to Apple home, the default name is always Matter Accessory.

As per our observations -- This name, similar to https://github.com/espressif/esp-matter/issues/245#issuecomment-1450368745, is pre-populated or set as default to the Product Name field in the DCL model, if the entry is present for that particular vid and pid. If not, it is set as Matter Accessory.

**Comment by stefano055415** [comment]
@dhrishi  ok i understand thanks
