### ISSUE TITLE
Matter Test-Harness (CON-325)

### ISSUE THREAD

**Issue by stefano055415** [espressif/esp-matter#251]
I have a problem with TH version 2.6

If I load the PICS files the correct tests are not selected

Steps to reproduce it
Modify the project by uploading the Pics file:

<img width="932" alt="Screenshot 2023-03-02 at 16 28 36" src="https://user-images.githubusercontent.com/4798738/222474313-08193057-8e48-443f-890e-61199d417c2e.png">

I press on Run Test:

<img width="1299" alt="Screenshot 2023-03-02 at 16 29 12" src="https://user-images.githubusercontent.com/4798738/222474367-69fe95e9-47d9-4568-bb53-c867b9ac18cf.png">

I create a new test:

<img width="1303" alt="Screenshot 2023-03-02 at 16 29 29" src="https://user-images.githubusercontent.com/4798738/222474401-ea262115-f4a2-495b-ba0f-567609e0d9c1.png">

But the selected tests do not match those of the pics file

what am I doing wrong thanks

this is the pics file

[On-Off Cluster Test Plan.xml.zip](https://github.com/espressif/esp-matter/files/10872949/On-Off.Cluster.Test.Plan.xml.zip)

**Comment by PSONALl** [comment]
@stefano055415 
Can you reboot your test harness and then try again? follow these steps:
1. ./chip-certification-tool/scripts/stop.sh
2. ./chip-certification-tool/scripts/start.sh

**Comment by stefano055415** [comment]
@PSONALl 

I installed test-harness on a raspberry pi4 and tried to reinstall it several times but with the same result I also tried to use version 2.5 but I have the same problem

**Comment by stefano055415** [comment]
From project-chip repository, they suggested me to write on this repository 

[https://github.com/CHIP-Specifications/chip-certification-tool ](https://github.com/CHIP-Specifications/chip-certification-tool )

but being private I can't access it, does anyone know how I can request access?

**Comment by dhrishi** [comment]
@stefano055415 chip-certification-tool is under CHIP-Specifications which is not open. If you/your company are a member of CSA then you can request them for access
