### ISSUE TITLE
Issue while integrating Matter code with BLE  (CON-333)

### ISSUE THREAD

**Issue by SYESHASWINI** [espressif/esp-matter#257]
I have added necessary header files in the code and calling the BLE function from matter code. I'm getting header file errors while building which are not getting resolved.  Attaching the error log please have a look at it.

[err.txt](https://github.com/espressif/esp-matter/files/10887603/err.txt)

**Comment by dhrishi** [comment]
@SYESHASWINI Please provide a patch on top of the main branch to recreate the issue

**Comment by dhrishi** [comment]
>Can you share useful resources for using BLE (bluedroid).

https://docs.espressif.com/projects/esp-idf/en/v4.4.3/esp32/api-reference/bluetooth/bt_le.html
