### ISSUE TITLE
More concise syntax

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#26]
Instead of...
```
    node_t *node = node::get();
    endpoint_t *endpoint = endpoint::get(node, endpoint_id);
    cluster = cluster::get(endpoint, LevelControl::Id);
    attribute = attribute::get(cluster, LevelControl::Attributes::CurrentLevel::Id);
    attribute::get_val(attribute, &val);
```
this would be much more convenient
```
 val = node::get().endpoint(endpoint_id).cluster(LevelControl).attribute(CurrentLevel).value();
```
Something along those lines.  This current syntax is very verbose. Maybe
```
  val = node::get(endpoint_id, LevelControl, CurrentLevel)
  node::set(endpoint_id, LevelControl, CurrentLevel, val)
```
I've forgotten my C++ can you pass types like this? I can in Kotlin.

Or will this introduce a base class that then causes all of the dependent classes to get linked in even if you don't reference them? AWS C++ lib has that problem. Use a single API and the linker brings in 22MB of garbage.

**Comment by chiragatal** [comment]
I think something like the second option you mentioned can be done pretty easily (but with the namespaced IDs for cluster and attribute). They would just be wrapper APIs to the current APIs, and you can just call this 1 API instead of the current 4.
