### ISSUE TITLE
ModeSelect cluster support missing (CON-336)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#260]
esp-matter support for the ModeSelect cluster support is missing.

**Comment by MartinPArmstrong** [comment]
I've noticed this myself, since we need this cluster for a project. If support isn't added we'll probably have to add it ourselves.

**Comment by dhrishi** [comment]
@jonsmirl @MartinPArmstrong We will add the support of ModeSelect cluster soon.

**Comment by jonsmirl** [comment]
Dhrishi will know better, but I suspect it will be done within week.

**Comment by dhrishi** [comment]
@MartinPArmstrong It should be done within this week

**Comment by jadhavrohit924** [comment]
@jonsmirl @MartinPArmstrong We are working on it. It will take a bit longer to add Mode Support in component.

**Comment by MartinPArmstrong** [comment]
@jadhavrohit924 Can we perhaps expect it next week instead then?

**Comment by jadhavrohit924** [comment]
@MartinPArmstrong It will be done ASAP!!

**Comment by markusp00** [comment]
@jadhavrohit924 Any updates on the issue?

**Comment by jonsmirl** [comment]
Did CHIP 1.0 ship without ANY vendor implementing ModeSelect?

**Comment by jonsmirl** [comment]
What is update on this? I don't see mode_select in esp_matter yet.

**Comment by jadhavrohit924** [comment]
@jonsmirl It will be added soon.

**Comment by itavero** [comment]
I was trying to add it manually, but got stuck when trying to define the Supported Modes attribute (not sure how to create the list of ModeOptionStruct instances).

**Comment by jonsmirl** [comment]
Any progress on this?

**Comment by jadhavrohit924** [comment]
Hi @jonsmirl @itavero @markusp00 @MartinPArmstrong, sorry for the delay. It was blocked due to some dependency. We are unblocked now. Support of mode select cluster is in internal review, it will be merged soon :)

**Comment by jadhavrohit924** [comment]
Its merged in commit [43fa905](https://github.com/espressif/esp-matter/commit/43fa90571765e6caca3f5fdd655ed54a585d80cf) please pull the latest code. Here is the documentation for link https://docs.espressif.com/projects/esp-matter/en/latest/esp32/developing.html#mode-select Please close the issue.
