### ISSUE TITLE
Endpoint names in apps like Google Home (CON-340)

### ISSUE THREAD

**Issue by MartinPArmstrong** [espressif/esp-matter#263]
When commissioning my application with multiple endpoints into Google Home all the endpoints get the name TEST_PRODUCT as shown in the picture below. Is there a way to change these names in the code? Or is this a Google Home related issue.

![Screenshot_20230304-153052](https://user-images.githubusercontent.com/31541069/223228183-c6052d05-38a0-4340-81bc-0cc020c09dbd.png)

**Comment by MartinPArmstrong** [comment]
And If this is simply tied to manufacturer information, is there a way to have different name for the endpoints?

**Comment by jonsmirl** [comment]
For development I am setting the device characteristics like this:
~~~
message(STATUS "Vendor ID: " ${CONFIG_DEVICE_VENDOR_ID})
message(STATUS "Vendor Name: " ${CONFIG_DEVICE_VENDOR_NAME})
message(STATUS "Product ID: " ${CONFIG_DEVICE_PRODUCT_ID})
message(STATUS "Product Name: " ${CONFIG_DEVICE_PRODUCT_NAME})
message(STATUS "SW Version String: " ${CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING})
idf_build_set_property(COMPILE_OPTIONS "-DCHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID=${CONFIG_DEVICE_VENDOR_ID}" APPEND)
idf_build_set_property(COMPILE_OPTIONS -DCHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME="${CONFIG_DEVICE_VENDOR_NAME}" APPEND)
idf_build_set_property(COMPILE_OPTIONS "-DCHIP_DEVICE_CONFIG_DEVICE_PRODUCT_ID=${CONFIG_DEVICE_PRODUCT_ID}" APPEND)
idf_build_set_property(COMPILE_OPTIONS -DCHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME="${CONFIG_DEVICE_PRODUCT_NAME}" APPEND)
~~~

There are the Fixed Label and User Label clusters for setting names. But... I don't know what Google will do with them on random endpoints.

**Comment by dhrishi** [comment]
@MartinPArmstrong 

>When commissioning my application with multiple endpoints into Google Home all the endpoints get the name TEST_PRODUCT as shown in the picture below.

This is the product name that is set on the device.

> Is there a way to change these names in the code?

Yes. You can use the [mfg_tool](https://github.com/espressif/esp-matter/tree/main/tools/mfg_tool#manufacturing-partition-generator-utility) to configure the product name of your choice. Once you setup the tool, please use `./tools/mfg_tool/mfg_tool.py --help` to see the available options.
