### ISSUE TITLE
This accessory is not currently supported by the Home app. in the Home app. (CON-356)

### ISSUE THREAD

**Issue by vaemc** [espressif/esp-matter#273]
Hello:

Run [generic_switch](https://github.com/espressif/esp-matter/tree/matter_1_1/te1/examples/generic_switch) example on the esp32c2 

The home app shows the Add this matter device, but says "Not Supported".

My apple ios version is 16.3.1

May I ask what is the reason

![e61227858b2eece23dc2d82c99032cd](https://user-images.githubusercontent.com/16460137/224908565-9ddda640-d59f-4ff7-8b0a-6385fe48125b.png)

**Comment by shubhamdp** [comment]
Hi @vaemc, by default this example implements [latching switch](https://github.com/espressif/esp-matter/blob/matter_1_1/te1/examples/generic_switch/main/Kconfig.projbuild#L5) and that is shows as unsupported matter accessory in Apple Home.

Momentary switch are supported in Apple Home. You will have to enable `CONFIG_ GENERIC_SWITCH_TYPE_MOMENTARY ` using menuconfig, it can be found in menu path: `(Top) -> Demo -> Generic Switch Type`

**Comment by vaemc** [comment]
@shubhamdp Thanks for the quick response！ 
I try to change it to `CONFIG_GENERIC_SWITCH_TYPE_MOMENTARY`, it still doesn't support

**Comment by shubhamdp** [comment]
Please check the attached screenshot if it's any help. My Hompod is on Version 16.3.2

<img width="1080" alt="Screenshot 2023-01-19 at 3 54 03 PM png" src="https://user-images.githubusercontent.com/17616551/225013173-557be677-3983-4c3d-823a-8129da86fef7.png">

**Comment by dhrishi** [comment]
@vaemc Please close the issue if you are able to see the momentary switch in the Home app.

**Comment by vaemc** [comment]
Thank you very much for your enthusiastic help, it should be my problem, I will try again
