### ISSUE TITLE
ESP-IDF v5.xx for matter enabled product development (CON-366)

### ISSUE THREAD

**Issue by aggaddam** [espressif/esp-matter#283]
Hi, 

My company is planning to start development for matter-enabled IOT products. We want to start off our development with IDF v5.xx instead of v4.xx and our development will get completed in the next year i.e. 2024. Considering long-term support till 2025 by espressif for IDF v5.xx, we would like to start matter development with v5.xx instead of v4.xx  

I would like to hear some suggestions from this team regarding IDF versions

EspressIf IDF Release Support

![image](https://user-images.githubusercontent.com/94963960/227215575-f8aed0bd-f618-471c-ad20-1aa9298f2da1.png)

**Comment by shubhamdp** [comment]
@aggaddam We have recently released the support of esp-matter branch on IDF v5.xx. Latest `main` branch of esp-matter supports IDF commit [bb9200ace](https://github.com/espressif/esp-idf/tree/bb9200ace) in branch `release/v5.1` and main branch will continue to keep updating support for IDF v5.xx.

In a nutshell, you can start off your development with esp-matter main branch with IDF commit bb9200ace from `release/v5.1` branch.

**Comment by aggaddam** [comment]
@shubhamdp  Thanks for the update. 

When is the official release planned for IDF v5.1?
When is the official release planned for ESP-Matter SDK?

**Comment by dhrishi** [comment]
@aggaddam

ESP IDF v5.1 release is planned around end of May this year.

ESP Matter v1.0 release will soon be created from release/v1.0 branch which is based of upstream v1.0.0.2

ESP Matter v1.1 is now the main branch. This will be released after official release of Matter v1.1 from upstream, which isn't done yet.

**Comment by dhrishi** [comment]
Closing this as the original question is answered.
