### ISSUE TITLE
use esp32_matter sdk to generate QRcode (CON-379)

### ISSUE THREAD

**Issue by jiuyuec** [espressif/esp-matter#288]
not of using mfg_tool, use esp32_matter sdk to generate QRcode.  Do you need to download DAC PAI to the chip?Is there any documentation for this?

**Comment by shubhamdp** [comment]
@jiuyuec Can you elaborate more on your problem? Matter qrcode and DAC/PAI is sort of different things.

Matter QRCode can be generated using either chip-tool or using [python tool](https://github.com/project-chip/connectedhomeip/blob/master/src/setup_payload/python/README.md).
