### ISSUE TITLE
Light Example Build Issue with ESP -IDF v5.1 (CON-380)

### ISSUE THREAD

**Issue by aggaddam** [espressif/esp-matter#289]
I am unable to build ESP matter Light example code which is available under esp-matter/examples/light. I am getting the below error 

![image](https://user-images.githubusercontent.com/94963960/228513020-9eda098b-7cef-40e9-acf2-0a0158412680.png)

ESP Matter SDK: release/v1.0
ESP IDF version: release/v5.1

**Comment by shubhamdp** [comment]
> ESP Matter SDK: release/v1.0
ESP IDF version: release/v5.1

@aggaddam This combination is not tested, we only support idf v4.4.3 on esp-matter release/v1.0 branch.

Please use the esp-matter main branch with idf release/v5.1 branch.

**Comment by dhrishi** [comment]
release/v1.0 branch (Matter v1.0.0.2) does not support ESP IDF v5.x for ESP32, ESP32-C3, ESP32-S3.

Please try with main vrancg
