### ISSUE TITLE
Clusters used in the Project (CON-382)

### ISSUE THREAD

**Issue by SYESHASWINI** [espressif/esp-matter#291]
Hello, Is there any way to find all the clusters used in the matter project and resources related to it through which we can generate a PICS file with the cluster information.
Thank You In advance.

**Comment by jadhavrohit924** [comment]
@SYESHASWINI We don’t have any mechanisms to do so. We are working on it.

**Comment by SYESHASWINI** [comment]
@jadhavrohit924 Where can we find the cluster information which are default to the specific device types like: on/off light, Switch etc.

**Comment by jadhavrohit924** [comment]
@SYESHASWINI esp-matter adds only default/mandatory clusters of all device types. If you are using chip-tool, you can use command 
`./out/debug/chip-tool descriptor read server-list <destination-id> <endpoint-ids>`
