### ISSUE TITLE
error: format '%X' expects argument of type 'unsigned int', but argument 7 has type 'uint32_t' (CON-387)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#296]
My app is getting hundreds of this compiler error after switching to IDF 5.1.
this is on esp32s3
~~~
/home/jonsmirl/aosp/esp-matter/components/esp_matter/esp_matter_attribute_utils.cpp: In function 'void esp_matter::attribute::val_print(uint16_t, uint32_t, uint32_t, esp_matter_attr_val_t*)':
/home/jonsmirl/esp/esp-idf/components/log/include/esp_log.h:265:27: error: format '%X' expects argument of type 'unsigned int', but argument 7 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
  265 | #define LOG_COLOR(COLOR)  "\033[0;" COLOR "m"
~~~
[esp51.log](https://github.com/espressif/esp-matter/files/11117872/esp51.log)

**Comment by shubhamdp** [comment]
This is expected, I see a lot of format specifier mismatch there. Will fix this.

**Comment by jonsmirl** [comment]
I need to add this until fixed:
~~~
target_compile_options(${COMPONENT_LIB} PRIVATE "-Wno-format")
~~~

**Comment by brad-colbert** [comment]
> I need to add this until fixed:
> 
> ```
> idf_build_set_property(COMPILE_OPTIONS "-Wno-format-nonliteral;-Wno-format-security;-Wformat=0" APPEND)
> ```

Where did you add this?
