### ISSUE TITLE
ESP_MATTER_PATH

### ISSUE THREAD

**Issue by AchimPieters** [espressif/esp-matter#30]
Hello All,

**Running Docker:** `espressif/idf: v4.4.1`

**Running local:** `~/esp-matter`

**execute:** `docker run -it -v ~/ESP-MATTER:/project -w /project espressif/idf:v4.4.1`

**run:** ` idf.build`

**error:** 

`Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DCCACHE_ENABLE=1 /project/examples/light"...`
`CMake Error at CMakeLists.txt:6 (message):`
`Please set ESP_MATTER_PATH to the path of esp-matter repo`

Does anyone knows how to set the path correctly, i.c.w. docker?

**Comment by chshu** [comment]
```
cd <esp-matter>;
. ./export.sh;
```

You may refer to the esp-matter setup docs: https://docs.espressif.com/projects/esp-matter/en/main/esp32/developing.html

**Comment by dhrishi** [comment]
>But unfortunately that doesn't work as I'm running Docker: espressif/idf: v4.4.1

@AchimPieters The `. ./export.s h` @chshu mentioned above is to be executed in the local `esp-matter` repository. It should solve your issue. Please close this if it does

**Comment by dhrishi** [comment]
Closing this as it should work. Feel free to reopen in case you still face the issue. Also, we have now moved to ESP-IDF release v4.4.2 now.

**Comment by AchimPieters** [comment]
Unfortunately that doesn't work either, I also tried to run the export.sh when started the docker, see attached image.
![Screenshot 2022-09-11 at 17 46 15](https://user-images.githubusercontent.com/16034588/189536674-09578e4e-4dd2-446f-abc8-b4ca9e8027c3.png)

**Comment by dhrishi** [comment]
Can you please try to use `source export.sh` or `. ./export.sh` instead of `bash export.sh`. That should help because, I think, source operates in the current shell and affects variables in the same shell too.

**Comment by AchimPieters** [comment]
Okay,`source export.sh` looks to be working, but it sure takes it sweet time....
![Screenshot 2022-09-11 at 18 45 41](https://user-images.githubusercontent.com/16034588/189539301-4619a4d6-aee5-4a4e-b199-56f598e68c2d.png)

**Comment by AchimPieters** [comment]
Okay step by step it's doing something, but now run into this one:
![Screenshot 2022-09-12 at 16 55 39](https://user-images.githubusercontent.com/16034588/189687060-5d4cf0bb-a3e8-420d-9893-53e27f5ede3f.png)

**Comment by jonsmirl** [comment]
You are likely missing the gn tool.    cd into esp-matter/connectedhomeip/connectedhomeip  and 'source scripts/bootstrap.sh'
you only need to do that once. That will install all of the needed tools into the image.

**Comment by AchimPieters** [comment]
I already did that through the i`nstall.sh` file in the `esp-matter` folder. but try it again as you described.
![Screenshot 2022-09-12 at 17 24 51](https://user-images.githubusercontent.com/16034588/189693495-b5accc5c-88bc-41c5-b9df-cb9e7fbd6fba.png)

**Comment by jonsmirl** [comment]
Instructions for VSCode with container on Mac directly using CHIP...
https://github.com/project-chip/connectedhomeip/blob/master/docs/VSCODE_DEVELOPMENT.md

Then go into the CHIP example directories and build ESP support there.  You don't have to use esp-matter.
You could try to get that working first and then add in esp-matter if you really want it.
