### ISSUE TITLE
Failed to post event to CHIP Platform event queue (CON-404)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#313]
I keep getting these errors, is there some way to make this queue longer?
~~~
E (92049) chip[DL]: Failed to post event to CHIP Platform event queue
E (92049) chip[CSL]: Failed to queue CHIP System Layer lambda event: 1000000
I (92049) esp_matter_attribute: ********** Endpoint 0x0003's Cluster 0x001E's Attribute 0xFFFD is 1 **********
E (92049) chip[DMG]: Error retrieving data from clusterId: 0x0000_001E, err = b
E (92059) chip[DL]: Failed to post event to CHIP Platform event queue
E (92059) chip[CSL]: Failed to queue CHIP System Layer lambda event: 1000000
E (92069) chip[DL]: Failed to post event to CHIP Platform event queue
E (92069) chip[CSL]: Failed to queue CHIP System Layer lambda event: 1000000
I (92069) chip[EM]: <<< [E:36347r S:43590 M:117479787 (Ack:121440306)] (S) Msg TX 
~~~

**Comment by jonsmirl** [comment]
So does CONFIG_MAX_EVENT_QUEUE_SIZE end up in CHIP_DEVICE_CONFIG_MAX_EVENT_QUEUE_SIZE?

**Comment by jonsmirl** [comment]
Setting CONFIG_MAX_EVENT_QUEUE_SIZE to 50 instead of 25 seems to have made it go away. I also noticed that my commissioning was significantly faster. I guess it was dropping items from that queue and then having to trigger slow network retries
[fabric.log](https://github.com/espressif/esp-matter/files/11174382/fabric.log)

**Comment by shubhamdp** [comment]
> So does CONFIG_MAX_EVENT_QUEUE_SIZE end up in CHIP_DEVICE_CONFIG_MAX_EVENT_QUEUE_SIZE?

Yes, https://github.com/project-chip/connectedhomeip/blob/master/src/platform/ESP32/CHIPDevicePlatformConfig.h#L39

Increasing it to 50 would have increased the static DRAM usage by (25 * sizeof([ChipDeviceEvent](https://github.com/project-chip/connectedhomeip/blob/master/src/include/platform/CHIPDeviceEvent.h#L373)))

**Comment by jonsmirl** [comment]
I have 2MB of free PSRAM. Can we push it into PSRAM?

**Comment by shubhamdp** [comment]
Right now I don't see any direct option for this. But, we can do a workaround.

Set `CONFIG_MAX_EVENT_QUEUE_SIZE` to higher value (say 50 as per your suggestion).

Set [`CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL`](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#config-spiram-malloc-alwaysinternal) to some value (eg: 1K), please make sure to set it to less than `50 * sizeof(ChipDeviceEvent)` bytes.

By this method, all the allocations more than configured value will be from PSRAM.

**Comment by stefano055415** [comment]
@jonsmirl @shubhamdp 

I too encounter the same problem

even on the light example

Has anyone solved it?

**Comment by jonsmirl** [comment]
Set CONFIG_MAX_EVENT_QUEUE_SIZE higher. I ended up at 32 instead of 50. So it just needed a little more,

Something inside of chip probably should be blocking when the queue is full and then work to empty it before generating more entries.

**Comment by stefano055415** [comment]
@jonsmirl 

Thanks, I tried and it actually works, I hope they fix it

**Comment by jonsmirl** [comment]
More recent version of this issue: https://github.com/espressif/esp-matter/issues/656

**Comment by jonsmirl** [comment]
More recent version of this issue: https://github.com/espressif/esp-matter/issues/656
