### ISSUE TITLE
generic switch example needs to include command to make mfg_binaries (CON-405)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#314]
How is the mfg_binaries file generated including the test certs?

**Comment by shubhamdp** [comment]
mfg_tool's [readme](https://github.com/espressif/esp-matter/tree/main/tools/mfg_tool#usage-examples) mentions few sample usage and there's one more example in [programming guide](https://docs.espressif.com/projects/esp-matter/en/latest/esp32/certification.html#generating-factory-partition-binary-files). Also, `./tools/mfg_tool/mfg_tool.py -h` has quite a verbose details about each parameters.

Are you looking for something specific?

**Comment by jonsmirl** [comment]
How are you including the test certificates in that binary?

**Comment by jonsmirl** [comment]
This is all sorted out now.
