### ISSUE TITLE
WindowCovering showing 'no response' in Apple Home App (CON-413)

### ISSUE THREAD

**Issue by jzwyssig** [espressif/esp-matter#322]
This still seems to be an issue:
I added a bridged window covering with the latest esp-matter changes and idf 4.4.4 according to your code @stefano055415. It works perfectly with Google Home, but still not with Apple's Home app (HomePod & iPad are up to date with version 16.4). Strangely, the iPad shows the correct percentage of the roller shade and it is even possible to adjust the level of the shade and it is correctly synced with Google. Therefore, I guess it is still an Apple Home problem. Does it work for you?

_Originally posted by @jzwyssig in https://github.com/espressif/esp-matter/issues/168#issuecomment-1488878622_

**Comment by jadhavrohit924** [comment]
Hi @jzwyssig , I was able to control window covering with homekit apple. 
With Home pod version 16.4.1 and  iPadOS 16.4.1.
![IMG_5AE3727C9D86-1](https://user-images.githubusercontent.com/69809379/234479703-f4e0d80d-940c-4385-9197-acb264007c04.jpeg)



Could you please try again by updating versions if not updated?

**Comment by svenehlers** [comment]
This might be related to #343

**Comment by dhrishi** [comment]
That's right. It should help. @jzwyssig Closing this. Please re-open if you face issues after following #343
