### ISSUE TITLE
Opening commsioning window on demand? (CON-415)

### ISSUE THREAD

**Issue by MartinPArmstrong** [espressif/esp-matter#324]
Is there an API call or function of some sort to open the commsioning windows on demand instead of automatically on matter startup? If no such feature is available through the Espressif API, is it easily accessible through connectedhomeip?

**Comment by wqx6** [comment]
Here is the API to close the commissioning window in upstream connectedhomeip repo, it might help. https://github.com/project-chip/connectedhomeip/blob/master/src/app/server/CommissioningWindowManager.h#L94

**Comment by dhrishi** [comment]
@MartinPArmstrong We have showcased using it in the Light example [here](https://github.com/espressif/esp-matter/blob/main/examples/light/main/app_main.cpp#L75). You can open the [basic commissioning window](https://github.com/project-chip/connectedhomeip/blob/master/src/app/server/CommissioningWindowManager.h#L74-#L80) or [enhanced commissioning window](https://github.com/project-chip/connectedhomeip/blob/master/src/app/server/CommissioningWindowManager.h#L82-#L92) as per the requirement. You may want to check the section `5.7. Device Commissioning Flows` in the Matter specification that is related to opening commissioning window at various times

**Comment by dhrishi** [comment]
I will close this issue now as the question is answered
