### ISSUE TITLE
Maybe typo? (CON-417)

### ISSUE THREAD

**Issue by YOGYUI** [espressif/esp-matter#326]
Code: [esp_matter_attribute_utils.h](https://github.com/espressif/esp-matter/blob/main/components/esp_matter/esp_matter_attribute_utils.h)
Line: 39

```c
/* Nullable base for nullable attribute */
#define ESP_MATTER_VAL_NULLANLE_BASE 0x80
```

I think correct naming is **ESP_MATTER_VAL_NULLABLE_BASE**.

**Comment by dhrishi** [comment]
@YOGYUI That's right. It is a typo. Thanks for notifying. We will fix it.
