### ISSUE TITLE
How do I run the certification tests for the esp-matter Light example?

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#33]
What are the CHIP commands to do a certification test using the Light example as a testing target? I don't care if it passes, I would like to know exactly how to run the tests using a physical device.

**Comment by dhrishi** [comment]
Currently, the certification tests are a combination of automated and manual tests. The automated tests have a dependency on test harness to be the controller/commissioner for a commissionee DUT. The manual tests need to be executed step by step as per the test case execution document. In short, there aren't any test utilities or test applications on the DUT to run certification tests, as of now.
