### ISSUE TITLE
Fails the matter test case [TC-OO-2.3] (CON-431)

### ISSUE THREAD

**Issue by maenkai** [espressif/esp-matter#336]
esp-idf: v4.4.2
esp-matter: commit-id fde2c7ea84fee46d4dfa8a874d63a054229ceee6
Out of three tests, one succeeded and two failed
The following tests cannot be passed using the Matter Test Harness(V2.6)

```shell
TC-O-2.3
12b: Reads OffWaitTime attribute from DUT
21b: Reads OffWaitTime attribute from DUT

**Comment by maenkai** [comment]
FAIL:
![截图 2023-04-12 16-12-18](https://user-images.githubusercontent.com/106250124/233032886-849902df-c081-42cf-9748-17e0d48d1d28.png)

TH-V2.6 LOG
[UI_Test_Run_2023_4_19_17_36_28.txt](https://github.com/espressif/esp-matter/files/11271535/UI_Test_Run_2023_4_19_17_36_28.txt)

**Comment by wqx6** [comment]
Can you please disable the log and test again? The log output might affect the attribute value.

**Comment by maenkai** [comment]
> Can you please disable the log and test again? The log output might affect the attribute value.

I have modified the configuration item, but still failed
CONFIG_LOG_DEFAULT_LEVEL_NONE=y

**Comment by stefano055415** [comment]
@maenkai @wqx6 

I also have the same problem but I use esp-idf: v5.0.1 and esp-matter_ commit 1b95fcf66793c2ead7df933d8d80eefd7f8f6b95 

did you find a solution?

Thank you

**Comment by maenkai** [comment]
> @maenkai @wqx6
> 
> I also have the same problem but I use esp-idf: v5.0.1 and esp-matter_ commit [1b95fcf](https://github.com/espressif/esp-matter/commit/1b95fcf66793c2ead7df933d8d80eefd7f8f6b95)
> 
> did you find a solution?
> 
> Thank you

Using menuconfig to turn off the log reduces the chance of failure, but this is not a complete solution

**Comment by stefano055415** [comment]
@maenkai 

I tried disabling logging, but out of ten tests only one passed without errors, error reduction is minimal

hope it gets fixed soon

Thank you

**Comment by stefano055415** [comment]
@maenkai 

I have noticed that the problem occurs systematically on tests 14c 20b 23c and 24c

always: reads OnWaitTime attribute from DUT

maybe it can help

**Comment by maenkai** [comment]
https://github.com/espressif/esp-matter/issues/131
It seems to be similar to the problem. When will it be solved

**Comment by maenkai** [comment]
@wqx6 I am going to do the test certification, please help solve the problem

**Comment by VaishaliAvhale** [comment]
[On-Off Cluster Test Plan.zip](https://github.com/espressif/esp-matter/files/11786999/On-Off.Cluster.Test.Plan.zip)
please update your PICS file and retest the test case.

**Comment by dhrishi** [comment]
@maenkai Can you please confirm if the above PICS helped you?

**Comment by maenkai** [comment]
> @maenkai Can you please confirm if the above PICS helped you?

Still failing, what does the failure of the project have to do with it, maybe I can optimize from the application layer

**Comment by VaishaliAvhale** [comment]
I have tested above test case using  the same PICS file which I shared with you and It is passed
About the steps which are failing in your test case are not applicable . Check it in attached Test Report!
If your facing diffrent issue please share it's logs and Test Report
also which TH version you are using? Please use updated TH version (Version: v2.9-beta1)
[Test Report.pdf](https://github.com/espressif/esp-matter/files/11965388/Test.Report.pdf)

**Comment by VaishaliAvhale** [comment]
I have tested above test case using  the same PICS file which I shared with you and It is passed
About the steps which are failing in your test case are not applicable . Check it in attached Test Report!
If your facing diffrent issue please share it's logs and Test Report
also which TH version you are using? Please use updated TH version (Version: v2.9-beta1)
[Test Report.pdf](https://github.com/espressif/esp-matter/files/11965388/Test.Report.pdf)

**Comment by maenkai** [comment]
> I have tested the above test case using the same PICS file which I shared with you and It is passed The steps which are failing in your test case are not applicable. Check it in the attached Test Report! If you're facing a different issue please share its logs and Test Report also which TH version you are using? Please use the updated TH version (Version: v2.9-beta1) [Test Report.pdf](https://github.com/espressif/esp-matter/files/11965419/Test.Report.pdf)

My version is 2.6, only 2.7 can be found on the official website, please tell me how to get the next version 2.9, thank you!

**Comment by VaishaliAvhale** [comment]
Follow the below TH upgrade instructions:

cd chip-certification-tool
git pull
git checkout release/2.9-TE1
./scripts/update.sh
./scripts/ubuntu/update-sample-apps.sh
./scripts/ubuntu/update-paa-certs.sh
./scripts/stop.sh
./scripts/build-no-cache.sh
./scripts/start.sh
