### ISSUE TITLE
window covering + homekit apple no response (CON-439)

### ISSUE THREAD

**Issue by ronny-antoon** [espressif/esp-matter#343]
I am trying to make Window Covering Matter Accessory and use it in Apple HomeKit (Home app).
i want the simplest code using esp_matter to do that.
iam new in this codeing and tried this code and didnt work. i can bind it but then i have a no response in the home app.

`// sudo chmod 666 /dev/ttyUSB0

#include <nvs_flash.h>
#include <esp_matter.h>
#include <app/server/CommissioningWindowManager.h>
#include <app/server/Server.h>

static const char *TAG = "app_main";
constexpr auto k_timeout_seconds = 300;

static void app_event_cb(const ChipDeviceEvent *event, intptr_t arg)
{
    switch (event->Type)
    {
    case chip::DeviceLayer::DeviceEventType::kCommissioningSessionStarted:
        ESP_LOGI(TAG, "Commissioning session started");
        break;

    case chip::DeviceLayer::DeviceEventType::kCommissioningSessionStopped:
        ESP_LOGI(TAG, "Commissioning session stopped");
        break;

    case chip::DeviceLayer::DeviceEventType::kCommissioningWindowOpened:
        ESP_LOGI(TAG, "Commissioning window opened");
        break;

    case chip::DeviceLayer::DeviceEventType::kCommissioningWindowClosed:
        ESP_LOGI(TAG, "Commissioning window closed");
        break;
    case chip::DeviceLayer::DeviceEventType::kFabricRemoved:
    {
        ESP_LOGI(TAG, "Fabric removed successfully");
        if (chip::Server::GetInstance().GetFabricTable().FabricCount() == 0)
        {
            chip::CommissioningWindowManager &commissionMgr = chip::Server::GetInstance().GetCommissioningWindowManager();
            constexpr auto kTimeoutSeconds = chip::System::Clock::Seconds16(k_timeout_seconds);
            if (!commissionMgr.IsCommissioningWindowOpen())
            {
                /* After removing last fabric, this example does not remove the Wi-Fi credentials
                 * and still has IP connectivity so, only advertising on DNS-SD.
                 */
                CHIP_ERROR err = commissionMgr.OpenBasicCommissioningWindow(kTimeoutSeconds,
                                                                            chip::CommissioningWindowAdvertisement::kDnssdOnly);
                if (err != CHIP_NO_ERROR)
                {
                    ESP_LOGE(TAG, "Failed to open commissioning window, err:%" CHIP_ERROR_FORMAT, err.Format());
                }
            }
        }
        break;
    }
    default:
        break;
    }
}

extern "C" void app_main()
{
    nvs_flash_init();

    esp_matter::node::config_t node_config;
    esp_matter::node_t *node = esp_matter::node::create(&node_config, NULL, NULL);

    esp_matter::endpoint::window_covering_device::config_t window_config;
    esp_matter::endpoint_t *endpoint = esp_matter::endpoint::window_covering_device::create(node, &window_config, esp_matter::endpoint_flags::ENDPOINT_FLAG_NONE, NULL);

    esp_matter::cluster_t *cluster = esp_matter::cluster::get(endpoint, chip::app::Clusters::WindowCovering::Id);
    esp_matter::cluster::window_covering::feature::lift::config_t lift;
    esp_matter::cluster::window_covering::feature::position_aware_lift::config_t position_aware_lift;
    esp_matter::cluster::window_covering::feature::absolute_position::config_t absolute_position;
    esp_matter::cluster::window_covering::feature::lift::add(cluster, &lift);
    esp_matter::cluster::window_covering::feature::position_aware_lift::add(cluster, &position_aware_lift);
    esp_matter::cluster::window_covering::feature::absolute_position::add(cluster, &absolute_position);

    esp_matter::start(app_event_cb);
}
`

**Comment by jadhavrohit924** [comment]
Hi @ronny-antoon, I was able to control window covering with homekit apple. 
With Home pod version 16.4.1 and  iPadOS 16.4.1.
![IMG_5AE3727C9D86-1](https://user-images.githubusercontent.com/69809379/234479703-f4e0d80d-940c-4385-9197-acb264007c04.jpeg)



Could you please try again?

**Comment by ronny-antoon** [comment]
I have the last ios software on all my devices, and i want the simplest code ever.

`
extern "C" void app_main()
{
    nvs_flash_init();
    esp_matter::node::config_t node_config;
    esp_matter::node_t *node = esp_matter::node::create(&node_config, NULL, NULL);
    esp_matter::endpoint::window_covering_device::config_t window_config;
    esp_matter::endpoint_t *endpoint = esp_matter::endpoint::window_covering_device::create(node, &window_config, esp_matter::endpoint_flags::ENDPOINT_FLAG_NONE, NULL);
    esp_matter::start(app_event_cb);
}
`

this should work? 
in this code i can bind and add the matter accessory to home and it display as blind, but it is always "no response".
can you write simple code that do nothing and work in Home?

**Comment by jadhavrohit924** [comment]
> this should work?

You need to add either `lift` or `tilt` feature since window covering should support either `lift` or `tilt`. This would work.

> but it is always "no response"

I would suggest, tryout with updating your homePod and iOs.

**Comment by ronny-antoon** [comment]
> You need to add either `lift` or `tilt` feature since window covering should support either `lift` or `tilt`. This would work.

my code now :-

`extern "C" void app_main()
{
nvs_flash_init();
esp_matter::node::config_t node_config;
esp_matter::node_t *node = esp_matter::node::create(&node_config, NULL, NULL);
esp_matter::endpoint::window_covering_device::config_t window_config;
esp_matter::endpoint_t *endpoint = esp_matter::endpoint::window_covering_device::create(node, &window_config, esp_matter::endpoint_flags::ENDPOINT_FLAG_NONE, NULL);
esp_matter::cluster_t *cluster = esp_matter::cluster::get(endpoint, chip::app::Clusters::WindowCovering::Id);
esp_matter::cluster::window_covering::feature::lift::config_t lift;
esp_matter::cluster::window_covering::feature::lift::add(cluster, &lift);
esp_matter::start(app_event_cb);
}`

> I would suggest, tryout with updating your homePod and iOs.

my version on all devices is 16.4.1


![WhatsApp Image 2023-04-26 at 17 53 29 (2)](https://user-images.githubusercontent.com/90724911/234617969-f2d49625-f0d6-420e-a818-21b4bff97ffa.jpeg)
![WhatsApp Image 2023-04-26 at 17 53 29 (1)](https://user-images.githubusercontent.com/90724911/234617976-a6213775-a3f8-49ef-a2bf-adb46ab7594d.jpeg)
![WhatsApp Image 2023-04-26 at 17 53 29](https://user-images.githubusercontent.com/90724911/234617981-4441740a-9563-4ff0-ab2f-f9baa7020978.jpeg)

**Comment by jadhavrohit924** [comment]
Is your device and homePod are close? I saw this problem when device and homePod are apart from each other!!

**Comment by ronny-antoon** [comment]
> Is your device and homePod are close? I saw this problem when device and homePod are apart from each other!!

Thier is one wall between the two devices, but when i run matter accessory light it is working perfect. Can you show me the code working for window covering.!?

**Comment by jadhavrohit924** [comment]
This is the code I'm using. But I suspect there is no problem with the code. Its with the apple home. Could you please try by keeping homePod and device closer in the same room? 
```
esp_matter::endpoint::window_covering_device::config_t window_config;
esp_matter::endpoint_t *endpoint = esp_matter::endpoint::window_covering_device::create(node, &window_config, esp_matter::endpoint_flags::ENDPOINT_FLAG_NONE, NULL);

esp_matter::cluster_t *cluster = esp_matter::cluster::get(endpoint, chip::app::Clusters::WindowCovering::Id);
esp_matter::cluster::window_covering::feature::lift::config_t lift;
esp_matter::cluster::window_covering::feature::position_aware_lift::config_t position_aware_lift;
esp_matter::cluster::window_covering::feature::absolute_position::config_t absolute_position;
esp_matter::cluster::window_covering::feature::lift::add(cluster, &lift);
esp_matter::cluster::window_covering::feature::position_aware_lift::add(cluster, &position_aware_lift);
esp_matter::cluster::window_covering::feature::absolute_position::add(cluster, &absolute_position);
```

**Comment by ronny-antoon** [comment]
@jadhavrohit924 
i tried to put the device and homepod close an face each other, still no response in home app,

**Comment by ronny-antoon** [comment]
still cant make it work

**Comment by svenehlers** [comment]
I have the same problem with a basic code which is similar to yours @ronny-antoon but i dont have a solution yet.
I have all mandatory window covering features in my code. 
The firmware of home pod and iPhone is at 16.4.1 .
I have installed the Matter profile in iPhone and homepod.
The iPhone is in developer mode.

I will test around with some of the status bits in some window covering attributes which could be related to this problem.

**Comment by jadhavrohit924** [comment]
@ronny-antoon @svenehlers 
We have tried window covering several times with apple using the same code mentioned above. Sometimes it works sometimes it doesn’t :(

**Comment by ronny-antoon** [comment]
i will try that @svenehlers
