### ISSUE TITLE
Unrecognized cert format (CON-442)

### ISSUE THREAD

**Issue by SYESHASWINI** [espressif/esp-matter#346]
We running the below command, it is showing as unrecognized cert format.

./chip-cert gen-cd -C credentials/test/certification-declaration/Chip-Test-CD-Signing-Cert.pem -K credentials/test/certification-declaration/Chip-Test-CD-Signing-Key.pem --out cd.bin -f 1 -V 105E -p 49DA -d 010A -c "ZIG0000000000
000000" -l 0 -i 0 -n 0001 -t 0

**the error:**
Unrecognized Cert Format in the Input Argument: credentials/test/certification-declaration/Chip-Test-CD-Signing-Cert.pem

**Comment by jadhavrohit924** [comment]
@SYESHASWINI Please make sure you give the correct path of the `Cert.pem` and `Key.pem`. [Here](https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/esp32/secure_cert_partition.md) is the documentation with commands to generate esp secure cert partition.

```
./chip-cert gen-cd -C ../../credentials/test/certification-declaration/Chip-Test-CD-Signing-Cert.pem -K ../../credentials/test/certification-declaration/Chip-Test-CD-Signing-Key.pem --out cd.bin -f 1 -V 105E -p 49DA -d 010A -c "ZIG0000000000000000" -l 0 -i 0 -n 0001 -t 0
```
This would work.
