### ISSUE TITLE
Add humidity sensor implementation (CON-447)

### ISSUE THREAD

**Issue by Gonta01** [espressif/esp-matter#351]
Humidity sensor is described in Matter specification and it is implemented in Matter SDK. Why is it not implemented in Espressif's SDK for Matter? It seems to me that implementation can be similar to any other sensor device types (temperature sensor, pressure sensor etc.)

**Comment by dhrishi** [comment]
@Gonta01 It was already in progress on our side. I have just pushed the support to Github. See https://github.com/espressif/esp-matter/commit/f6a2f5c5b38dd9dbf7802eb6d91ef1d6e0a1f45f
