### ISSUE TITLE
apple home successfully created fabric, but pair failed (CON-448)

### ISSUE THREAD

**Issue by sidhoo2** [espressif/esp-matter#352]
IDF:4.4.3  
esp-matter:
commit 9bb410d995b6ae81e2025467e5d5bbf494c1e6b1 (HEAD -> release/v1.0)
Merge: 80a22dc 83c25e9
Author: Hrishikesh Dhayagude <[hrishi@espressif.com](mailto:hrishi@espressif.com)>
Date:   Fri Mar 31 12:25:30 2023 +0800
[01-ios  pair failed.log](https://github.com/espressif/esp-matter/files/11339326/01-ios.log.log)

**Comment by dhrishi** [comment]
@sidhoo2 Please do not paste the logs, instead upload the complete log file. The logs indicate that the Wi-Fi network connectivity wasn't established. Can you please check the SSID and passphrase, if correct.

Also, the application seems to be different than the standard examples. Please provide any patch/diff on top of an existing example for us to recreate the issue.

**Comment by sidhoo2** [comment]
@dhrishi  ok, i will pay attention next time.  you are right , but it can paired sucessful some time with this SSID.

**Comment by dhrishi** [comment]
@sidhoo2 Please check if the AP is far away from the device. Also, if possible, please reset to factory the ESP32 and upload the commissioning logs from the new boot in case of a failure.

**Comment by dhrishi** [comment]
@sidhoo2 Any updates here? Please close the issue if resolved

**Comment by sidhoo2** [comment]
okay,  can't find the reason, and i hv never meet this issue these days.
