### ISSUE TITLE
chip-tool commissioning issue (CON-453)

### ISSUE THREAD

**Issue by SYESHASWINI** [espressif/esp-matter#355]
I tried commissioning the device using chip-tool using the commands and Mdns failed occured. Attached the error log.
command: sudo chip-tool pairing onnetwork 110 20202021
[chip-tool-log.txt](https://github.com/espressif/esp-matter/files/11350460/chip-tool-log.txt)

**Comment by VaishaliAvhale** [comment]
For onnetwork commissioning, you must connect the device to the wifi network using CLI. After the device is on the network you can do onnetwork commissioning successfully.

**Comment by dhrishi** [comment]
@SYESHASWINI Please try with the above suggestion, if should just work
