### ISSUE TITLE
Device name after connection in Home Assistant (CON-454)

### ISSUE THREAD

**Issue by Gonta01** [espressif/esp-matter#356]
I've successfully connected [matter lighting app](https://nabucasa.github.io/matter-example-apps/) to Home assistant. As I understand the product name is already displayed on the screen. When I try to connect my devices (other six devices on the screenshot below) with my custom product name it isn't displayed on the screen. How can I achieve this?
![image](https://user-images.githubusercontent.com/127857320/235090432-c65fc0df-8223-418d-92a3-895c2b63e183.png)

**Comment by shubhamdp** [comment]
Hi @Gonta01 I never tried esp-matter with Home Assistant, I've asked someone from Home Assistant to take a look into this.

**Comment by Gonta01** [comment]
I have changed a Product name and Vendor name by using a mfg tool, but it hasn't been represented in the Home Assistant.

**Comment by agners** [comment]
I am not familiar with the mfg tool I am sorry. But the "M5STAMP Lightning App" string definitly originates from the CHIPProjectConfig.h https://github.com/NabuCasa/matter-example-apps/blob/main/lighting-app-example/esp32-c3-m5stamp/0001-Add-Project-configuration-for-M5-Stamp.patch.

**Comment by shubhamdp** [comment]
@agners `mfg_tool.py` is a python based tool to generate the factory partition which would contain discriminator, verifier, vid, pid, and some more informations that is expected to go into factory partition.

If you are familiar with [generate_esp32_chip_factory_bin.py](https://github.com/project-chip/connectedhomeip/blob/master/scripts/tools/generate_esp32_chip_factory_bin.py), its same but with some more changes.

**Comment by agners** [comment]
Ok I see.

> I have changed a Product name and Vendor name by using a mfg tool,

Well, it seems that this tool also allows to change product/vendor name then? I guess the question is what is different to the method I've used (adjusting the upstream Matter `CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME` and `CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME` configs) and that mfg tool.

@Gonta01 after using the mfgtool, did you remove and readd that device to Home Assistant?

**Comment by Gonta01** [comment]
> @Gonta01 after using the mfgtool, did you remove and readd that device to Home Assistant?

Yes I did. The result is the same.

**Comment by rfortunatov** [comment]
@Gonta01 Hi, had this problem too, solved it by manually setting NodeLabel attribute of basic cluster, code snippet follows, hope it would help you
```
auto endpoint = esp_matter::endpoint::get(node, 0);
auto cluster = esp_matter::cluster::get(endpoint, chip::app::Clusters::BasicInformation::Id);
auto attribute = esp_matter::attribute::get(cluster, chip::app::Clusters::BasicInformation::Attributes::NodeLabel::Id);
std::string data = "Test Bench";
auto val = esp_matter_char_str(data.data(), data.length());
esp_matter::attribute::set_val(attribute, &val);
```

**Comment by Gonta01** [comment]
@rfortunatov thanks for your reply, your answer helped. I close this issue.
