### ISSUE TITLE
ERROR:root:ESP_MATTER_PATH environment variable is not set (CON-458)

### ISSUE THREAD

**Issue by viethoang171** [espressif/esp-matter#359]
I created Attestation Certificate, I want to generate factory partitions by using mfg_tool. Then it had a bug like:
Link image perform bug: https://drive.google.com/file/d/1SAgULrYF-drHhgB4R_uKZghgaCqUyYlG/view?usp=share_link
Can you help me?
Thank you!

**Comment by dhrishi** [comment]
@viethoang171 Did you source export.sh in the esp-matter repository? See here: https://docs.espressif.com/projects/esp-matter/en/latest/esp32/developing.html#configuring-the-environment

**Comment by dhrishi** [comment]
This should ideally fix the issue. Closing this
