### ISSUE TITLE
Can ESP HomeKit Wifi devices be OTA upgraded to ESP Matter WiFi devices? (CON-474)

### ISSUE THREAD

**Issue by Focalcrest-Madi** [espressif/esp-matter#373]
Can ESP HomeKit Wifi devices be OTA upgraded to ESP Matter WiFi devices?

**Comment by shubhamdp** [comment]
Hi @Focalcrest-Madi, sorry for the delayed response. Yes, HomeKit WiFi devices can be OTA upgraded to Matter WiFi devices.

Matter Specification v1.0,  section `5.8. In-field Upgrade to Matter` has more details about it.

**Comment by shubhamdp** [comment]
@Focalcrest-Madi If the question is answered, please close this issue.
