### ISSUE TITLE
halCommonSetIndexedToken, halCommonGetIndexedToken

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#38]
Are these implemented from cluster/scenes/scene.h?
EMBER_AF_PLUGIN_SCENES_USE_TOKENS
To make the OnWithRecallGlobalScene, otherwise it stores the state to RAM and then forgets it.

Not clear if anyone in the Matter world has ever turned this command on.

**Comment by jonsmirl** [comment]
https://github.com/project-chip/connectedhomeip/issues/3275

Looks like they are punting on this.

**Comment by dhrishi** [comment]
Scenes cluster is marked as provisional for v1.0 Matter release. So there's a chance that it is not supported right now.

**Comment by jonsmirl** [comment]
Not implementing halCommonGetToken/halCommonSetToken also disables part of the on/off cluster.
OnWithRecallGlobalScene and OffWithEffect

**Comment by jonsmirl** [comment]
Closing since this is a core Matter problem. They are not going to look at this until after 1.0
