### ISSUE TITLE
Is it possible to pre define scenes? (CON-486)

### ISSUE THREAD

**Issue by stage-01** [espressif/esp-matter#381]
When going through the definition of the scenes cluster it is unclear to me where the attribute values are stored. Is it saved on the device that the cluster is implemented on? Or is only a scene ID saved on the device? 

And would it be possible to create pre-defined scenes on the device?  For example a movie night scene where you set a low brightness and a dark colour

**Comment by dhrishi** [comment]
@stage-01  The attribute values should ideally be stored on the node running the server cluster, just like any other cluster.

Just note that the Scenes cluster is provisional, for now. It means that it isn't certifiable at this point in time and also it is not supported by the ecosystem apps too.
