### ISSUE TITLE
Request for Endpoint Window Covering Controller  (CON-502)

### ISSUE THREAD

**Issue by svenehlers** [espressif/esp-matter#393]
Hi,

is there any plan to add the endpoint "Window Covering Controller" in the near future?

**Comment by dhrishi** [comment]
@svenehlers The `Window Covering Controller` has primarilly a Window Covering client cluster. In general, the client clusters are not supported in the ecosystem apps as of now. As a result, it is not added yet.

**Comment by dhrishi** [comment]
@svenehlers Do you know any commissioner that supports this device type? If yes, we can consider supporting this in the near future

**Comment by svenehlers** [comment]
@dhrishi Sry for my late reply. No i dont know any app which does support it for now but we try to be future proofed. Since it seems like it is using the already existing Window Covering Cluster (But as a Client) i will try to write my own code to implement it on Top/beside the Espressif matter SDK. 
At the moment i struggle at finding the window covering client cluster implementation in the CHIP SDK.

Is the on_off client cluster also not implemented in apple home and the others?

**Comment by dhrishi** [comment]
@svenehlers 

>Is the on_off client cluster also not implemented in apple home or other apps?

No. It is not implemented AFAIK. You can quickly try out the `light_switch` example which has the OnOff cluster client with any of the apps
