### ISSUE TITLE
Test Harness TC-CADMIN-1.20

### ISSUE THREAD

**Issue by falconeta** [espressif/esp-matter#395]
Hi,
during the multi fabric cluster test the device fails TC-CADMIN-1.20 (manual test), in details:
when the test asks to pair until the CommissionedFabrics is equal to SupportedFabrics (default 5) the DUT fail during the 5th commissioning with error `GeneralCommissioning: Failed to commit pending fabric data: 5001105`

the commands used to exec the test are:

- ./chip-tool pairing ble-wifi 0x1 test-matter2 test1234 12345678 3800 --paa-trust-store-path /var/paa-root-certs

- ./chip-tool administratorcommissioning open-basic-commissioning-window 500 1 0  --timedInteractionTimeoutMs 1000
-  ./chip-tool pairing onnetwork 2 12345678  --commissioner-name beta --paa-trust-store-path /var/paa-root-certs

-  ./chip-tool administratorcommissioning open-basic-commissioning-window 500 1 0  --timedInteractionTimeoutMs 1000
-  ./chip-tool pairing onnetwork 3 12345678  --commissioner-name gamma --paa-trust-store-path /var/paa-root-certs

- ./chip-tool administratorcommissioning open-basic-commissioning-window 500 1 0  --timedInteractionTimeoutMs 1000
-  ./chip-tool pairing onnetwork 4 12345678  --commissioner-name 4 --paa-trust-store-path /var/paa-root-certs

- ./chip-tool administratorcommissioning open-basic-commissioning-window 500 1 0  --timedInteractionTimeoutMs 1000
-  ./chip-tool pairing onnetwork 5 12345678  --commissioner-name 5 --paa-trust-store-path /var/paa-root-certs

test harness version: 2.7 official

[TC-CADMIN-1.20.TH.txt](https://github.com/espressif/esp-matter/files/11500287/TC-CADMIN-1.20.TH.txt)

[TC-CADMIN-1.20.DUT.txt](https://github.com/espressif/esp-matter/files/11500283/TC-CADMIN-1.20.DUT.txt)

**Comment by wqx6** [comment]
The error code is platform error 0x1105(ESP_ERR_NVS_NOT_ENOUGH_SPACE), https://github.com/espressif/esp-matter/commit/ef2c3e4d8bdb307803218db41294c158f6734ddd this commit might help. And you can also increase the size of nvs partition.

**Comment by falconeta** [comment]
Thank you for the quick response, after increase the nvs partition the issue is resolved. 
I close the issue.
