### ISSUE TITLE
How to use with ESP32-H2-BETA-1?

### ISSUE THREAD

**Issue by marciogranzotto** [espressif/esp-matter#397]
I'm trying to run the examples for an ESP32-H2-WROOM-1 (beta 1), but I can't figure out which branch/commit I need for this project and for the IDF.

Any guidance?

**Comment by wqx6** [comment]
ESP32-H2 beta1 is not supported for current esp-matter as it is a so early beta version. You can use ESP32-H2 MP version for matter examples and get them in https://www.espressif.com/en/contact-us/get-samples.

**Comment by dhrishi** [comment]
Closing as the question is answered
