### ISSUE TITLE
Test Harness 

### ISSUE THREAD

**Issue by stefano055415** [espressif/esp-matter#398]
Version: v2.9-development
Sha: 3fc4eee

After updating the TH it seems that it no longer uses the PAA certificate

E (24785) chip[SVR]: Failsafe timer expired
I (24785) chip[SC]: SecureSession[0x3ffcac80]: Moving from state 'kActive' --> 'kPendingEviction'
E (24795) chip[SVR]: Commissioning failed (attempt 1): 32
I (24805) chip[BLE]: Releasing end point's BLE connection back to application.
I (24815) chip[DIS]: Updating services using commissioning mode 1
I (24815) chip[DIS]: CHIP minimal mDNS started advertising.
I (24825) chip[DIS]: Advertise commission parameter vendorID=5137 productID=1 discriminator=1863/07 cm=1
I (24835) chip[DIS]: CHIP minimal mDNS configured as 'Commissionable node device'; instance name: 54BC8ECEA13EAD56.
I (24845) chip[DIS]: mDNS service published: _matterc._udp
E (24845) chip[ZCL]: OpCreds: Got FailSafeTimerExpired
I (24855) chip[DL]: E (24855) chip[ZCL]: Confirm received for CHIPoBLE TX characteristic indication (con 0) status= 14 OpCreds: Proceeding to FailSafeCleanup on fail-safe expiry!

I (24875) chip[TS]: Pending Last Known Good Time: 2023-05-19T08:42:25
I (24875) chip[DL]: Write request/command received for CHIPoBLE TX CCCD characteristic (con 0 ) indicate = 0
I (24885) chip[TS]: I (24895) chip[DL]: Previous Last Known Good Time: 2023-05-19T08:42:25CHIPoBLE unsubscribe received

I (24905) chip[TS]: Reverted Last Known Good Time to previous value
I (24905) esp_matter_attribute: ********** W : Endpoint 0x0000's Cluster 0x00000030's Attribute 0x00000000 is 0 **********
I (24925) app_main: Commissioning failed, fail safe timer expired
I (24925) chip[FS]: Fail-safe cleanly disarmed
I (24935) chip[DL]: Configuring CHIPoBLE advertising (interval 25 ms, connectable)
E (24945) chip[DL]: ble_gap_adv_start() failed: Error CHIP:0x0000000B
E (24945) chip[DL]: Start advertising failed: Error CHIP:0x0000000B
E (24955) chip[DL]: Disabling CHIPoBLE service due to error: Error CHIP:0x0000000B
I (24965) app_main: Commissioning window opened 0
E (24965) chip[BLE]: no endpoint for BLE sent data ack
E (24975) chip[BLE]: no endpoint for unsub recvd
I (27045) chip[DL]: BLE GAP connection terminated (con 0 reason 0x213)

[UI_Test_Run_2023_05_19_09_53_11.log](https://github.com/espressif/esp-matter/files/11514799/UI_Test_Run_2023_05_19_09_53_11.log)

**Comment by wqx6** [comment]
Please follow this step to use vendor's PAA cert in TH. https://docs.espressif.com/projects/esp-matter/en/latest/esp32/certification.html#using-vendor-s-paa-in-test-harness-th

**Comment by stefano055415** [comment]
@wqx6 

it is the same procedure that I used with the TH 2.7 version and with that it worked, but with the TH 2.9 it seems not to copy the certificates in the docker container

**Comment by wqx6** [comment]
Could you enter the docker container when you are pairing the device and find whether the PAA `CN = Freedompro, 1.3.6.1.4.1.37244.2.1 = 1411` is in the `/paa-root-certs`? The PAI cert and DAC cert in the device looks OK from the log.

**Comment by stefano055415** [comment]
@wqx6 

I found the problem in version 2.9 the ./scripts/tests/yalm/chiptool.py file is used
where the --paa-trust-store-path option was not added and the test always takes never uses the certificate
