### ISSUE TITLE
esp-matter支持Windows11上编译吗  (CON-505)

### ISSUE THREAD

**Issue by king592** [espressif/esp-matter#403]

**Comment by king592** [comment]
是我移植出错了吗，还是不支持windows11上编译呢

**Comment by wqx6** [comment]
matter 只能在ubuntu 或者macos环境中编译，不支持windows，但你可以考虑使用WSL，参考https://docs.espressif.com/projects/esp-matter/en/latest/esp32/developing.html#windows-10，或者使用虚拟机

**Comment by king592** [comment]
@wqx6 后续会考虑支持windows吗

**Comment by wqx6** [comment]
@king592 这个不是我们能决定的, esp-matter 是基于matter repo的，而matter repo目前只支持ubuntu 20.04 及以上的版本，和MacOS，后续大概不会加对windows的支持。

**Comment by dhrishi** [comment]
Closing this issue
