### ISSUE TITLE
OTA Failed  (CON-498)

### ISSUE THREAD

**Issue by SYESHASWINI** [espressif/esp-matter#404]
While the ota process is happening, after downloading few packets it throws the error as:
>E (375507) chip[EM]: Failed to Send CHIP MessageCounter:121761502 on exchange 10803i sendCount: 4 max retries: 4

**Comment by Jerry-ESP** [comment]
> While the ota process is happening, after downloading few packets it throws the error as:
> 
> > E (375507) chip[EM]: Failed to Send CHIP MessageCounter:121761502 on exchange 10803i sendCount: 4 max retries: 4

The error log means that a message send failed.  Did this happen only once or every OTA process? 
And which chip do you use ? Please upload all logs for the OTA process.

**Comment by SYESHASWINI** [comment]
@Jerry-ESP sorry for the delay. Attaching the error log.
[ota_error.txt](https://github.com/espressif/esp-matter/files/11574318/ota_error.txt)

**Comment by Jerry-ESP** [comment]
> @Jerry-ESP sorry for the delay. Attaching the error log. [ota_error.txt](https://github.com/espressif/esp-matter/files/11574318/ota_error.txt)

Please tell me your idf version, esp-matter version, develop board version and ota test platform

**Comment by SYESHASWINI** [comment]
idf version: ESP-IDF v4.4.2-dirty
esp-matter version: v1.0
dev board: esp32c3
ota test platform: Chip-tool

**Comment by dhrishi** [comment]
@SYESHASWINI Please use ESP-IDF v5.0.1 or v4.4.4 if you are using the main branch.

**Comment by shubhamdp** [comment]
@SYESHASWINI As we are already tracking OTA issues in https://github.com/project-chip/connectedhomeip/issues/26346 can you please close this one
