### ISSUE TITLE
couldn't access to device console (CON-500)

### ISSUE THREAD

**Issue by glennmullerar** [espressif/esp-matter#406]
Hello, 

I want to create a controller and in order to understand how it works I want to access the device console. 

However, I can't do it, but I can access the monitor correctly (from vscode cmd+i+m or from my terminal idf.py monitor). 
It is very likely that I am doing something wrong. 

I would be grateful if you have an idea of how to solve my problem. 

PS: I'm try to run controller and light_switch examples

**Comment by ph2355** [comment]
If you have two usb ports on your devkit, make sure that you are using the UART interface. That worked for me.

**Comment by shubhamdp** [comment]
@glennmullerar Which chip are you using? C3 has the USB's (D+/-) pins so you just have to enable `ESP_CONSOLE_USB_SERIAL_JATG` config option in order to USB console.

**Comment by glennmullerar** [comment]
Thank's it works.
