### ISSUE TITLE
Bridge basic information When to support Manufacturer and other information (CON-509)

### ISSUE THREAD

**Issue by shun-dgut** [espressif/esp-matter#410]

**Comment by shun-dgut** [comment]
![image](https://github.com/espressif/esp-matter/assets/31812214/d9e31923-7f86-485f-847d-81c2f7e79315)
If it needs to be implemented, do I need to add information to this structure.

**Comment by wqx6** [comment]
You could call `esp_matter::attribute::create()` after you call `esp_matter_bridge::create_device()` to create optional attributes for a specific cluster.

**Comment by dhrishi** [comment]
Closing as the question is answered
