### ISSUE TITLE
If my lock is blocked, how should I set the matter information. (CON-511)

### ISSUE THREAD

**Issue by shun-dgut** [espressif/esp-matter#412]
I want to set the stall information of the lock, can you tell me how to do it?
![image](https://github.com/espressif/esp-matter/assets/31812214/51a7d662-22ef-45a3-a032-9b3350e0740a)

**Comment by shun-dgut** [comment]
I use the following function, but how do I actually test that the setup works?

DoorLockServer::Instance().SendLockAlarmEvent(endpoint_id, DlAlarmCode::kLockJammed);

**Comment by jadhavrohit924** [comment]
@shun-dgut What are you trying to do. Can you please explain a bit?

**Comment by jadhavrohit924** [comment]
Hi @shun-dgut, do you have any updates? Please close the issue if problem is resolved.

**Comment by dhrishi** [comment]
@shun-dgut I've closed this now. Please re-open with details as requested
