### ISSUE TITLE
The production information and serial number of the device that is bridged on homekit are not displayed properly (CON-514)

### ISSUE THREAD

**Issue by maenkai** [espressif/esp-matter#415]
esp-matter: commit-id = 99bd741a09b03f70a70d9cead637840a1aa17d30

![20230526-124435](https://github.com/espressif/esp-matter/assets/106250124/f912f440-0da7-455a-9679-2d1aa034f6e5)

code
```c

  // product name
  char       name[]  = "传感器";
  cluster_t *cluster = cluster::get(device->endpoint, BridgedDeviceBasicInformation::Id);
  attribute::create(cluster, BridgedDeviceBasicInformation::Attributes::NodeLabel::Id, (ATTRIBUTE_FLAG_WRITABLE | ATTRIBUTE_FLAG_NONVOLATILE),
                    esp_matter_char_str(name, strlen(name)));
  attribute::create(cluster, BridgedDeviceBasicInformation::Attributes::ProductName::Id, (ATTRIBUTE_FLAG_WRITABLE | ATTRIBUTE_FLAG_NONVOLATILE),
                    esp_matter_char_str(name, strlen(name)));

  // label
  char pidlabel[] = "20X1";
  attribute::create(cluster, BridgedDeviceBasicInformation::Attributes::ProductLabel::Id, (ATTRIBUTE_FLAG_WRITABLE | ATTRIBUTE_FLAG_NONVOLATILE),
                    esp_matter_char_str(pidlabel, strlen(pidlabel)));

  // serial
  char serial[] = "1122233344";
  attribute::create(cluster, BridgedDeviceBasicInformation::Attributes::SerialNumber::Id, (ATTRIBUTE_FLAG_WRITABLE | ATTRIBUTE_FLAG_NONVOLATILE),
                    esp_matter_char_str(serial, strlen(serial)));

  // sofe version
  char Version[] = "1.0.0";
  attribute::create(cluster, BridgedDeviceBasicInformation::Attributes::SoftwareVersionString::Id, (ATTRIBUTE_FLAG_WRITABLE | ATTRIBUTE_FLAG_NONVOLATILE),
                    esp_matter_char_str(Version, strlen(Version)));

  // vid 
  char lipro[] = "lipro";
  attribute::create(cluster, BridgedDeviceBasicInformation::Attributes::VendorName::Id, (ATTRIBUTE_FLAG_WRITABLE | ATTRIBUTE_FLAG_NONVOLATILE),
                    esp_matter_char_str(lipro, strlen(lipro)));

  attribute::create(cluster, BridgedDeviceBasicInformation::Attributes::VendorID::Id, (ATTRIBUTE_FLAG_WRITABLE | ATTRIBUTE_FLAG_NONVOLATILE),
                    esp_matter_uint16(0x1398));

  // manual
  char data[] = "hello lipro";
  attribute::create(cluster, BridgedDeviceBasicInformation::Attributes::ManufacturingDate::Id, (ATTRIBUTE_FLAG_WRITABLE | ATTRIBUTE_FLAG_NONVOLATILE),
                    esp_matter_char_str(data, strlen(data)));

**Comment by Jerry-ESP** [comment]
I think you can't create the attribus twice, they had been created when you call ***node_t *node = node::create(&node_config, app_attribute_update_cb, NULL);*** 
Can you paste all your app_main.cpp file that in order for us to analyze

**Comment by maenkai** [comment]
1. The source code here is added in set_device_type in esp-matter-bridge.cpp
2. This is the bridge endpoint, so there are no duplications. These properties can be read normally using "chip-tool"
3. I wonder if the red box in the picture says "unknow" is a problem with IOS and homepod, or because I'm missing some attributes

**Comment by maenkai** [comment]
> * The source code here is added in set_device_type in esp-matter-bridge.cpp
> * This is the bridge endpoint, so there are no duplications. These properties can be read normally using "chip-tool"
> * I wonder if the red box in the picture says "unknow" is a problem with IOS and homepod, or because I'm missing some attributes

1.The source code here is added in set_device_type in esp-matter-bridge.cpp
2.This is the bridge endpoint, so there are no duplications. These properties can be read normally using "chip-tool"
3.I wonder if the red box in the picture says "unknow" is a problem with IOS and homepod, or because I'm missing some attributes

**Comment by maenkai** [comment]
> I think you can't create the attribus twice, they had been created when you call ***node_t _node = node::create(&node_config, app_attribute_update_cb, NULL);_** Can you paste all your app_main.cpp file that in order for us to analyze

1.The source code here is added in set_device_type in esp-matter-bridge.cpp
2.This is the bridge endpoint, so there are no duplications. These properties can be read normally using "chip-tool"
3.I wonder if the red box in the picture says "unknow" is a problem with IOS and homepod, or because I'm missing some attributes

**Comment by YOGYUI** [comment]
I also have a same problem.
Before iOS 16.5, below attributes of 'BridgedDeviceBasicInformation' cluster are well displayed on Home app.
- BridgedDeviceBasicInformation::Attributes::VendorName::Id
- BridgedDeviceBasicInformation::Attributes::SerialNumber::Id
- ...
But after updating iOS 16.5, vendorName, SerialNumber and Model are displayed as 'Unknown' like your figure.
I guess this issue is related to Home app architecture, but I'm not sure.

**Comment by jadhavrohit924** [comment]
This looks like an issue of apple. Have you guys tried same with Google?

**Comment by shubhamdp** [comment]
@maenkai @YOGYUI any update here?

**Comment by shripad621git** [comment]
I have tried the Brigde example on the latest main with your provided patch and it works fine on the home app.I am able to see the serial number and production information correctly. The  ipad os version used is ios 16.6.Can you please give it a try on the latest main and the specified ios version.

![IMG_0004](https://github.com/espressif/esp-matter/assets/79364691/0d19493d-4d22-417a-9bd4-7cd7481fd840)

**Comment by maenkai** [comment]
The latest version has indeed been fixed, but now the remaining bridge names are not displayed properly, as shown below

![20230815-100636](https://github.com/espressif/esp-matter/assets/106250124/06ca1cf3-36e3-48f1-b663-75da6a63e879)
![20230815-100712](https://github.com/espressif/esp-matter/assets/106250124/8b5df69c-55ad-4ddc-975e-dd2ee420d369)

**Comment by shripad621git** [comment]
@maenkai you can read the node label set using chip-tool.But it does not get reflected as the bridge name in homekit.
If you want to have a name for the bridge, the matter accessory label above is editable in the UI and you can set the name from there itself for identification purposes.

**Comment by shripad621git** [comment]
@maenkai any updates on the issue faced . Please close this if the issue is solved.

**Comment by maenkai** [comment]
> @maenkai you can read the node label set using chip-tool.But it does not get reflected as the bridge name in homekit. If you want to have a name for the bridge, the matter accessory label above is editable in the UI and you can set the name from there itself for identification purposes.

I used homeAPP to pair the gateway on the market, the default name is not matter accessory, how do I do that

**Comment by maenkai** [comment]
This name is from DCL 
problem view https://github.com/project-chip/connectedhomeip/issues/26110
