### ISSUE TITLE
How do I get homekit to synchronize endpoint lists in a timely manner

### ISSUE THREAD

**Issue by maenkai** [espressif/esp-matter#417]
When I create an endpoint dynamically on the bridge device, I want homekit to show it in real time

**Comment by jonsmirl** [comment]
The new endpoint creation should be modifying the Partslist in the Descriptor cluster of the Aggregate Endpoint to include the new endpoint. Apple will have a subscription watching that cluster and should see the change.  The esp-matter bridge code should be doing this for you.

**Comment by maenkai** [comment]
> The new endpoint creation should be modifying the Partslist in the Descriptor cluster of the Aggregate Endpoint to include the new endpoint. Apple will have a subscription watching that cluster and should see the change. The esp-matter bridge code should be doing this for you.

During the test,ios APP always fails to refresh in time. Is there any way to make firmware actively push information

**Comment by jonsmirl** [comment]
The refresh period is under control of IOS, you can't impact it.

**Comment by maenkai** [comment]
I would like to know how to proactively report the offline status to the ios APP

**Comment by maenkai** [comment]
Is there any way esp can cause homekit to trigger a refresh mechanism

**Comment by dhrishi** [comment]
>Is there any way esp can cause homekit to trigger a refresh mechanism.

That is not possible as per the current specification
