### ISSUE TITLE
Refresh subscribe sync timer every 2 seconds & power consumption (CON-519)

### ISSUE THREAD

**Issue by albrownwood** [espressif/esp-matter#419]
Every two seconds I see the following message in log:

```
I (82397) chip[DMG]: Refresh Subscribe Sync Timer with min 0 seconds and max 2 seconds
I (82577) chip[EM]: >>> [E:37823i S:63435 M:112798178 (Ack:224703142)] (S) Msg RX from 1:00000000AAD711B8 [50B6] --- Type 0001:01 (IM:StatusResponse)
I (82587) chip[IM]: Received status response, status is 0x00
I (82607) chip[EM]: <<< [E:37823i S:63435 M:224703143 (Ack:112798178)] (S) Msg TX to 1:00000000AAD711B8 [50B6] --- Type 0000:10 (SecureChannel:StandaloneAck)
I (82607) chip[IN]: (S) Sending msg 224703143 on secure session with LSID: 63435
I (84397) chip[DMG]: Refresh subscribe timer sync after 2 seconds
I (84417) chip[EM]: <<< [E:37824i S:63435 M:224703144] (S) Msg TX to 1:00000000AAD711B8 [50B6] --- Type 0001:05 (IM:ReportData)
I (84417) chip[IN]: (S) Sending msg 224703144 on secure session with LSID: 63435
```

What is the purpose of this operation? It looks like some messages are exchanged which consumes power. Can the delay be increased between each refresh? I am trying to decrease power consumption as much as possible for a battery powered device.

**Comment by shubhamdp** [comment]
Most of the ecosystems subscribes to all the attributes of all the clusters  on all the endpoint, so that whenever there is a change that can be displayed on their apps.

In Matter Spec v1.0, section 2.9. Sleepy End Device (SED), has some details around it. I'll check and get back more details around implementation
