### ISSUE TITLE
How to add on/off clusters for a thermostat device type in esp-matter sdk ? Any references ? (CON-525)

### ISSUE THREAD

**Issue by aggaddam** [espressif/esp-matter#424]
Hi, I would like to create a thermostat device node and want to add the on/off clusters to it. Anyone tried creating a thermostat device node ?

**Comment by stage-01** [comment]
Why do you want to add the on/off cluster to the thermostat?

The thermostat cluster has an attribute called SystemMode 0x001c. This attribute has a couple different values, you can find them all on page 180 of the application cluster specification. It is used to turn the thermostat off (0), or put it in one of the available modes like cool (3) or heat (4).

This value can then be used in the same way as in the color light example:
if ( endpoint_id == thermostat_endpoint_id){
        if (cluster_id == Thermostat::Id) {
            if (attribute_id == Thermostat::Attributes::SystemMode::Id) {
                ESP_LOGI(TAG, "SystemMode = %i", val->val.i);
                ThermostatOnOffControl(val->val.i);
            }
        }
    }

In the above example when the thermostat is turned off, or in one of the available modes, from any of the available platforms a function I call ThermostatOnOffControl is called and the integer(enum) value of the system mode is given with it.
