### ISSUE TITLE
How to create a custom cluster？ (CON-529)

### ISSUE THREAD

**Issue by Focalcrest-Madi** [espressif/esp-matter#427]
I want to create a custom cluster, is there any relevant documentation or demo reference?
Does the ESP Matter device have an API to check which clusters the device has created?

**Comment by dhrishi** [comment]
@Focalcrest-Madi Please see an example of creating a custom cluster [here](https://github.com/espressif/esp-matter/blob/main/components/esp_matter_rainmaker/esp_matter_rainmaker.cpp#L219). You can use the chip-tool to read the attributes of descriptor cluster on that endpoint to see the clusters added. Additionally, you can use `any` cluster provided by chip-tool to perform any read/write operations.
