### ISSUE TITLE
ESP Zero Code Bridge module (CON-533)

### ISSUE THREAD

**Issue by stage-01** [espressif/esp-matter#430]
As a manufacturer of products that sell limited quantities it is very hard to justify the testing and certification costs that Matter brings with it. For those cases the Zero Code modules would be a great option. How it's currently advertised is not really suitable for every situation however.

Wouldn't it be a better solution for Epressif to create a "Zero Code" module that is programmed as a matter bridge. And via a serial interface you would be able to select your device and pass the Matter messages through.

This way as a product developer you would only have to add a bridge module to your device and configure it, making the entire Matter certification part go away. (Or only rebranding/white labeling would be necessary)

Asking about this through ESP customer support didn't give me any response so I thought maybe somebody here would know anything about this.

**Comment by dhrishi** [comment]
@stage-01 Please reach out to us at ezc-support@espressif.com for better assistance
