### ISSUE TITLE
Commissioning window Open fail  (CON-547)

### ISSUE THREAD

**Issue by Focalcrest-Madi** [espressif/esp-matter#444]
I flash the Factory Partition Binary to the ESP Matter device, but the Commissioning window was not opened when the device started.

ESP-IDF version is v4.4.3
esp-matter version is release/v1.0

I configured the device as follows:
1、Enable ESP32 Factory Data Provider
![image](https://github.com/espressif/esp-matter/assets/58587489/87969a4b-71e2-47e4-8165-69a4957c4f67)
2、Enable ESP32 Device Instance Info Provider
![image](https://github.com/espressif/esp-matter/assets/58587489/d8c78b37-3ba0-4914-b26e-f5ac7513189d)
3、Enable Attestation - Factory
![image](https://github.com/espressif/esp-matter/assets/58587489/be22a941-a187-4633-b99a-36523c9373f5)
4、Set chip-factory namespace partition label
![image](https://github.com/espressif/esp-matter/assets/58587489/529bb388-fb96-41c0-952d-4293f5b3ab01)

The Matter certificate generation command I use is as follows：
1、Generate the Test CD file
./out/host/chip-cert gen-cd --format-version 1 --vendor-id 0x130C --product-id 0x1 --device-type-id 0x010c --certificate-id CSA00000SWC00000-01 --security-level 0 --security-info 0 --version-number 1 --certification-type 1 --key credentials/test/certification-declaration/Chip-Test-CD-Signing-Key.pem --cert credentials/test/certification-declaration/Chip-Test-CD-Signing-Cert.pem --out ~/esp/matter-proj/credentials/test/test-CD.der

2、Generating PAA Certificate
./out/host/chip-cert gen-att-cert --type a --subject-cn "EVVR PAA CN" --subject-vid 0x130C --valid-from "2023-06-06 14:38:50" --lifetime 4294967295 --out-key ~/esp/matter-proj/credentials/test/test-PAA_key.pem --out ~/esp/matter-proj/credentials/test/test-PAA_cert.pem

3、Generating Factory Partition Binary Files
./mfg_tool.py -cn EVVR --paa -c ~/esp/matter-proj/credentials/test/test-PAA_cert.pem -k ~/esp/matter-proj/credentials/test/test-PAA_key.pem -cd ~/esp/matter-proj/credentials/test/test-CD.der -v 0x130C --vendor-name EVVR -p 0x01 --product-name Smart-Plug --hw-ver 1 --hw-ver-str v1.2

The command to flash the Factory Partition Binary is： esptool.py -p /dev/tty.usbserial-143210 write_flash 0x10000 ~/esp/esp-matter/tools/mfg_tool/out/130c_1/f05695fa-85e8-45d4-b23e-162288d881fa/f05695fa-85e8-45d4-b23e-162288d881fa-partition.bin
The device partition table information is as follows:
![image](https://github.com/espressif/esp-matter/assets/58587489/b4d0b641-71c4-4ca8-bb50-2fdfc52c216b)

The device log is as follows：
[device.log](https://github.com/espressif/esp-matter/files/11663403/device.log)

**Comment by shubhamdp** [comment]
@Focalcrest-Madi please take a look at https://github.com/espressif/esp-matter/issues/443#issuecomment-1578555455, I have replied there.

**Comment by dhrishi** [comment]
@Focalcrest-Madi Ideally that should fix your issue. Please give it a try and close this
