### ISSUE TITLE
How to test the OTA function of ESP32 Matter device (CON-551)

### ISSUE THREAD

**Issue by Focalcrest-Madi** [espressif/esp-matter#448]
How to test the OTA function of ESP32 Matter device？

**Comment by Focalcrest-Madi** [comment]
How to check the checksum and checksum type of OTA image？

**Comment by shubhamdp** [comment]
@Focalcrest-Madi please refer https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/esp32/ota.md

There is an issue in the docs as well https://github.com/project-chip/connectedhomeip/issues/26364

**Comment by shubhamdp** [comment]
@Focalcrest-Madi as you filed #460 this is not an issue anymore right? Can you please close this one?
