### ISSUE TITLE
generic_switch cannot be displayed on apple home (CON-557)

### ISSUE THREAD

**Issue by shun-dgut** [espressif/esp-matter#454]
The code is as follows
```
generic_switch::config_t generic_switch_conf;
bridged_device->endpoint = generic_switch::add(bridged_device->endpoint, &generic_switch_conf);

cluster_t *cluster = cluster::get(bridged_device->endpoint, chip::app::Clusters::Switch::Id);
// cluster::switch_cluster::feature::latching_switch::add(cluster);
cluster::switch_cluster::feature::momentary_switch::add(cluster);
```

**Comment by jonsmirl** [comment]
Don't know what is wrong, but I will confirm that generic switch has worked for me in the past on Apple Home. I have not tried it recently.

**Comment by VaishaliAvhale** [comment]
The generic_switch was not directly added in Home View, You will find it in your specified room where you have added the generic_switch device.

**Comment by dhrishi** [comment]
@shun-dgut We are able to see the generic_switch in Apple Home and also handle the single press event
