### ISSUE TITLE
Startup failure if default event loop was already initialised (CON-559)

### ISSUE THREAD

**Issue by rfortunatov** [espressif/esp-matter#456]
https://github.com/espressif/esp-matter/blob/915405c0ab9f339710b85027ff587b594e9eb686/components/esp_matter/esp_matter_core.cpp#L944

From my understanding at this line we can just check if creation was successful or underlying method returned ESP_ERR_INVALID_STATE which means that event loop is already created. Am I right or there's some specific reason we need a freshly created event loop to function?

**Comment by shubhamdp** [comment]
@rfortunatov That can be done, thanks for pointing it out,`ESP_ERR_INVALID_STATE` is returned when default event loop is already created.

**Comment by rfortunatov** [comment]
Exactly, so, should I open a PR?
