### ISSUE TITLE
Get Node ID (Peer ID) in OnAttributeData callback (CON-562)

### ISSUE THREAD

**Issue by glennmullerar** [espressif/esp-matter#459]
Hello,

I'm trying to implement a monitoring system with Matter. 

To retrieve and process data, I subscribe to the attributes I'm interested in. Then I process the values in the ```OnAttributeData``` callback, however I would also like to retrieve the node id of the emitter.

Unfortunately, I can't figure out how to do this with the arguments passed to the function.

Do you have any idea how to do this?

**Comment by PSONALl** [comment]
Attribute Path  can be passed as a argument like this:
https://github.com/project-chip/connectedhomeip/blob/6b99adbc3e82095f79822ba497bdb5a5fcd12842/examples/chip-tool/commands/clusters/ReportCommand.h#L34
And you can get node Id from the Attribute path see here: (https://github.com/project-chip/connectedhomeip/blob/6b99adbc3e82095f79822ba497bdb5a5fcd12842/src/app/MessageDef/AttributePathIB.h#L41)

**Comment by dhrishi** [comment]
@glennmullerar Please close this if your issue is resolved

**Comment by glennmullerar** [comment]
Sorry for not giving any news.

I didn't understand exactly what @PSONALl means.

Should I change the declaration of the ```OnAttributeData``` function to receive ```AttributePathIB``` as a parameter instead of ```ConcreteDataAttributePath```?

Or is there a way to obtain the Node ID from ```ConcreteDataAttributePath```, similar to ```AttributePathIB```?

PS: I haven't found anything like that in the ```connectedhomeip/src/app/ConcreteAttributePath.h``` file.

**Comment by PSONALl** [comment]
@glennmullerar You can change the declaration of the OnAttributeData function to receive AttributePathIB 
OR you can use GetNodeId() API from here:  https://github.com/project-chip/connectedhomeip/blob/a9773c943efd9c2dd840bad17b859c31a95ebb3c/src/lib/core/PeerId.h#L37C12-L37C21

**Comment by dhrishi** [comment]
You can use the API `GetNodeId` as mentioned above. Please re-open in case of any issue
