### ISSUE TITLE
OTA Provider write acl error: 0x87 (CONSTRAINT_ERROR) (CON-563)

### ISSUE THREAD

**Issue by Focalcrest-Madi** [espressif/esp-matter#460]
I using Linux OTA Provider, 0x87 (CONSTRAINT_ERROR) error occurs when writing ACL to OTA provider device.
The log information is as follows：
[ota_provider.log](https://github.com/espressif/esp-matter/files/11730543/ota_provider.log)
[device_write.log](https://github.com/espressif/esp-matter/files/11730544/device_write.log)
[device_paring.log](https://github.com/espressif/esp-matter/files/11730545/device_paring.log)

**Comment by wqx6** [comment]
SPEC says that it is invalid if an AccessControlTarget Entry includes `Endpoint`, `Cluster`, and `DeviceType` at the same time. So please remove the `deviceType` in your command of writing ACL. The document will be updated later.
