### ISSUE TITLE
Failed to connect to OTA provider Node (CON-565)

### ISSUE THREAD

**Issue by Focalcrest-Madi** [espressif/esp-matter#462]
I am testing the matter OTA function, and the ESP Matter device has an error of "Failed to connect to OTA provider Node".
The OTA test log is as follows：
[chip-tool-pair-requestor.log](https://github.com/espressif/esp-matter/files/11732202/chip-tool-pair-requestor.log)
[ota_provider2.log](https://github.com/espressif/esp-matter/files/11732204/ota_provider2.log)
[chip-tool-pair-provider.log](https://github.com/espressif/esp-matter/files/11732203/chip-tool-pair-provider.log)
[write_acl.log](https://github.com/espressif/esp-matter/files/11732207/write_acl.log)
[start_ota.log](https://github.com/espressif/esp-matter/files/11732209/start_ota.log)

**Comment by wqx6** [comment]
Could you please provide the device log so that we can know why the requestor cannot connect to the provider?

**Comment by Focalcrest-Madi** [comment]
@wqx6  
I removed the parameter "deviceType" of the write ACL command, and when the command is executed, it prompts that the "deviceType" parameter is required

[ota_write_acl.log](https://github.com/espressif/esp-matter/files/11732946/ota_write_acl.log)

**Comment by Focalcrest-Madi** [comment]
@wqx6 The problem has been solved, it is the problem of the computer firewall.
