### ISSUE TITLE
How can I use ntp to get time (CON-566)

### ISSUE THREAD

**Issue by moculll** [espressif/esp-matter#463]
I'm using esp32-h2, it's a matter-over-thread device, how can I get UTC-time in this non-wifi device?T T

**Comment by wqx6** [comment]
To make a Thread device support ntp/sntp, the Thread BR should support NAT64 feature. We support this [nat64](https://docs.espressif.com/projects/esp-thread-br/en/latest/esp32/codelab/nat64.html) feature on our Thread BR. We can now visit the IPv4 HTTP servers with this feature but the APIs of sntp are still not supported for thread device.

**Comment by wqx6** [comment]
Here are a example to use sntp on thread device. 
Firstly, you should register a event handler for `OPENTHREAD_EVENT_SET_DNS_SERVER`. This event will be post after the thread device gets its NAT64 prefix.
And in the event handler you should set the sntp server by `sntp_setserver()`. The sntp server address should be an IPv6 address with a NAT64 prefix which can be obtained by `esp_openthread_get_nat64_prefix()`. Then call the `sntp_init()`.

```
static void openthread_set_dns_server_handler(void* arg, esp_event_base_t event_base, int32_t event_id, void* event_data)
{
    ip_addr_t sntp_server;
    time_t now = 0;
    struct tm timeinfo = { 0 };
    char strftime_buf[64];

    sntp_server.type = IPADDR_TYPE_V6;
    esp_openthread_get_nat64_prefix(&sntp_server.u_addr.ip6);
    sntp_server.u_addr.ip6.zone = IP6_NO_ZONE;
    ip4_addr_t ip4_addr;
    IP4_ADDR(&ip4_addr, 209, 58, 185, 100); // IPv4 address for pool.ntp.org. It can be other IPv4 address for other sntp server.
    sntp_server.u_addr.ip6.addr[3] = ip4_addr.addr;
    sntp_setserver(0, &sntp_server);
    sntp_init();

    setenv("TZ", "CST-8", 1);
    tzset();
    while (1) {
        vTaskDelay(5000/portTICK_PERIOD_MS);
        time(&now);
        localtime_r(&now, &timeinfo);
        strftime(strftime_buf, sizeof(strftime_buf), "%c", &timeinfo);
        ESP_LOGI(TAG, "The current date/time in Shanghai is: %s", strftime_buf);
    }
}
......
esp_event_handler_register(OPENTHREAD_EVENT, OPENTHREAD_EVENT_SET_DNS_SERVER, openthread_set_dns_server_handler, NULL);
......
```
But there are some issues on APIs like `sntp_setservername()`. So the sntp APIs in `esp_netif` will also fail as esp_netif APIs will use `sntp_setservername()` . Maybe we need a hook to map the IPv4 address to IPv6 address for this function after the DNS resolving. But now we don't have any plans to fix it.

**Comment by moculll** [comment]
> Here is an example to use sntp on thread device. Firstly, you should register an event handler for `OPENTHREAD_EVENT_SET_DNS_SERVER`. This event will be post after the thread device gets its NAT64 prefix. And in the event handler you should set the sntp server by `sntp_setserver()`. The sntp server address should be an IPv6 address with a NAT64 prefix which can be obtained by `esp_openthread_get_nat64_prefix()`. The last 32 bits for this address should be the IPv4 address of sntp server. Then call the `sntp_init()`.
> 
> ```
> #include "esp_openthread_dns64.h"
> #include "lwip/apps/sntp.h"
> 
> static void openthread_set_dns_server_handler(void* arg, esp_event_base_t event_base, int32_t event_id, void* event_data)
> {
>     ip_addr_t sntp_server;
>     time_t now = 0;
>     struct tm timeinfo = { 0 };
>     char strftime_buf[64];
> 
>     sntp_server.type = IPADDR_TYPE_V6;
>     esp_openthread_get_nat64_prefix(&sntp_server.u_addr.ip6);
>     sntp_server.u_addr.ip6.zone = IP6_NO_ZONE;
>     ip4_addr_t ip4_addr;
>     IP4_ADDR(&ip4_addr, 209, 58, 185, 100); // IPv4 address for pool.ntp.org. It can be other IPv4 address for other sntp server.
>     sntp_server.u_addr.ip6.addr[3] = ip4_addr.addr;
>     sntp_setserver(0, &sntp_server);
>     sntp_init();
> 
>     setenv("TZ", "CST-8", 1);
>     tzset();
>     while (1) {
>         vTaskDelay(5000/portTICK_PERIOD_MS);
>         time(&now);
>         localtime_r(&now, &timeinfo);
>         strftime(strftime_buf, sizeof(strftime_buf), "%c", &timeinfo);
>         ESP_LOGI(TAG, "The current date/time in Shanghai is: %s", strftime_buf);
>     }
> }
> ......
> esp_event_handler_register(OPENTHREAD_EVENT, OPENTHREAD_EVENT_SET_DNS_SERVER, openthread_set_dns_server_handler, NULL);
> ......
> ```
> 
> But there are some issues on APIs like `sntp_setservername()`. So the sntp APIs in `esp_netif` component will also fail as esp_netif APIs use `sntp_setservername()` . Maybe we need a hook to map the IPv4 address to IPv6 address for this function after the DNS resolving. But now we don't have any plans to fix it.

Thank you so much！！！T T LOVE ya

**Comment by shubhamdp** [comment]
@moculll If query is answered, please close the issue.

**Comment by dhrishi** [comment]
Closing this now
