### ISSUE TITLE
Matter How the device invokes the ACL (CON-572)

### ISSUE THREAD

**Issue by maenkai** [espressif/esp-matter#469]
1. If I am a matter device, can I write ACLs to another matter device?
2. I want to control another matter device in this way without having to operate the acl through the Matter APP

**Comment by wqx6** [comment]
1. Yes, you can, but the `matter device` must have administrator access privilege to `another matter device`
2. You can use the CAT Id. The Matter APP will hold a NOC with a CAT Id subject DN and Matter-Device-A will hold another NOC with the same CAT Id subject DN. If the initial admin subject on the Matter-Device-B is this CAT Id, Matter-Device-A can control the Device-B without changing the ACL of Device-B.

**Comment by jonsmirl** [comment]
This is far easier if you start off using CAT ids. After you get things working with CAT ids then you can try making specific ACLs. CAT ids effectively turn every node into an administrator disable the protections of the ACL. I'm using CAT ids currently to avoid having to mess with restrictive ACLs which can be quite a pain to set up.

**Comment by dhrishi** [comment]
Closing as the questions are answered

**Comment by maenkai** [comment]
> This is far easier if you start off using CAT ids. After you get things working with CAT ids then you can try making specific ACLs. CAT ids effectively turn every node into an administrator disabling the protections of the ACL. I'm using CAT ids currently to avoid having to mess with restrictive ACLs which can be quite a pain to set up. After I get everything stable using CAT ids, I will look into using ACLs.
> 
> CAT = CASE Authenticated Token

Could you please show me examples by chip-tool? Thank you very much
