### ISSUE TITLE
Group multicast and AP selection fail when multiple AP with same SSID

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#47]
Using the esp-matter light demo unchanged...
[group.zip](https://github.com/espressif/esp-matter/files/9465087/group.zip)

It is restoring the multicast group on line 149/150
But wifi does not manage to connect to the AP until line 327.
A related question, why is my ESP having so much trouble connecting to the AP? There are several APs in the area with the same SSID. I don't understand why it is connecting to AP 100ft away with -63 rssi, when it is sitting 4ft away from AP with same SSID/PW and rssi  of -29.

I have chip-tool interactive session running. I create the group as in the end of this bug report.
https://github.com/project-chip/connectedhomeip/issues/20979
I verified that I can toggle the LED on/off a few time.
Then I rebooted the ESP device
After reboot you get the log from above.
Trying to toggle the light bulb does not generate any output on the ESP device.
I suspect this is because the Multicast group is not there.

----
I changed the SSID on my nearby AP to be unique.   Groups now work as expected. This also demonstrates that my nearby AP works with the ESP.

So my guess this has something to do with multiple APs and then the ESP deciding to use the distant one instead of the one four feet away.  Maybe when it changed target APs the group didn't transition?

----
Next test, I set AP back to its normal name.

I reenter all of the chip-tool commands.
I start wireshark sniffing on wifi
I verify that group on/off is working
I verify that wireshark is capturing the multicast packet.
I reboot ESP
send command from chip-tool
wireshark sees the packet
the ESP does not see it.

**Comment by jonsmirl** [comment]
[group2.zip](https://github.com/espressif/esp-matter/files/9465864/group2.zip)

Log from second test.  I can see the packet on Wireshark, but ESP does not see it.

----
# Packet 5 from /tmp/wireshark_wlp2s0NSD9Q1.pcapng
- 828
- 99.352372317
- 2600:4040:51b3:fb00:cbcd:199d:793a:dd0f
- ff35:40:fd00::100:1
- UDP
- 128
- 58055 → 5540 Len=66

**Comment by jonsmirl** [comment]
Something about rebooting with multiple APs is breaking the ESP listening for multicast.

**Comment by jadhavrohit924** [comment]
I could able to use group multicast after reboot. Also I can see logs on ESP device.
[groups.txt](https://github.com/espressif/esp-matter/files/9469414/groups.txt)

**Comment by jonsmirl** [comment]
I have no trouble with multicast where there is single AP nearby.  

The failure is when there is network of APs. In my case the ESP is able to see four or five APs with the same SSID and varying RSSI. Something in the process of deciding which of these AP to connect to seems to break multicast.

**Comment by dhrishi** [comment]
This is a known issue in the Wi-Fi code, discussed [here](https://github.com/espressif/esp-idf/issues/8269) and being worked upon.

**Comment by jonsmirl** [comment]
There may be layers to this problem. Once they have fixed the wifi code to connect to the strongest AP, you will need to verify that the AP selection process is not breaking that Multicast listen which was set up before the AP was chosen.  From what I am observing it appears that the AP selection process is not preserving the Multicast setup.

**Comment by jonsmirl** [comment]
Note that these multi-AP networks are common in US houses now due to Amazon (eero) and Ubiquiti selling home mesh networks. This has to work correctly before ESP Matter devices can be shipped.

https://www.amazon.com/Introducing-eero-mesh-WiFi-system-3-pack-/dp/B07WMLPSRL/ref=sr_1_1_sspa

**Comment by jonsmirl** [comment]
How do I tell? They are all on a single IPv4 subnet.  I think they are all on single IPv6 subnet too. They are not routing, they are bridged APs.

**Comment by jonsmirl** [comment]
If IPv6 broken on router, Matter should fallback to IPv4.  Normal consumer does not understand this level of problem.

**Comment by chshu** [comment]
You may try this: connect PC to one of the APs, and use wireshark to sniffer the packets, then check whether the PC could receivce the multicast message from the chip-tool under another AP.

**Comment by jonsmirl** [comment]
It is not simple to tell which AP these devices are attaching to since they all have the same SSID.  But I believe the PC had attached to the one 4ft away from me, and the ESP had attached to the one 100ft away.  All of my APs are not identical, so there could be issue at the one 100ft away. When I changed the SSID of the one 4ft away so that the ESP will use it, multicast works.

Another complication, all the Linux development machines are wired Ethernet desktops.   I need to build CHIP onto a Windows or Mac laptop, or Rasp Pi to be able to move it around.

**Comment by jonsmirl** [comment]
I'm in the process of building CHIP on a RaspPi so that I can move it around.   A better solution for testing this would be an Android/IOS phone app.   I run something on my desktop injecting IPv6 multicast packets into the network over Ethernet. And then I walk around with the phone set to wifi mode and make sure I can receive them everywhere.

**Comment by dhrishi** [comment]
I will close this as it looks like a generic issue and is added here https://github.com/project-chip/connectedhomeip/issues/22380
