### ISSUE TITLE
Creating a Sleepy End Device with ESP32-C6 with deep sleep (CON-581)

### ISSUE THREAD

**Issue by marciogranzotto** [espressif/esp-matter#478]
Looking for a way to create a Sleepy End Device (SED) with deep sleep on ESP32-C6 (using the dev kit).

If I set the `CHIP_DEVICE_CONFIG_ENABLE_SED` flag, I see OpenThread sleep logs, but I don't think that this is enabling deep sleep while on the "inactive" state

**Comment by chshu** [comment]
Will track the issue here: https://github.com/espressif/esp-matter/issues/366#issuecomment-1605931323

**Comment by dhrishi** [comment]
@marciogranzotto As this will be tracked i #366 , I will close the issue here
