### ISSUE TITLE
Build fail with GCC 13 (CON-584)

### ISSUE THREAD

**Issue by elektro-NIK** [espressif/esp-matter#481]
With GCC 13 (host compiler) install.sh script fall with unknown uint8_t symbol. It causes because: https://gcc.gnu.org/gcc-13/porting_to.html

"Some C++ Standard Library headers have been changed to no longer include other headers that were being used internally by the library. As such, C++ programs that used standard library components without including the right headers will no longer compile."

For fixing, just need to explicitly include `cstdint`.

Errors:

> In file included from ../../src/app/tests/suites/pics/PICSBooleanExpressionParser.cpp:19:
> ../../src/app/tests/suites/pics/PICSBooleanExpressionParser.h:46:107: error: ‘uint8_t’ has not been declared
>    46 |     static bool EvaluateExpression(std::vector<std::string> & tokens, std::map<std::string, bool> & PICS, uint8_t & index);
>       |                                                                                                           ^~~~~~~
> ../../src/app/tests/suites/pics/PICSBooleanExpressionParser.h:47:110: error: ‘uint8_t’ has not been declared
>    47 |     static bool EvaluateSubExpression(std::vector<std::string> & tokens, std::map<std::string, bool> & PICS, uint8_t & index);
>       |                                                                                                              ^~~~~~~
> ../../src/app/tests/suites/pics/PICSBooleanExpressionParser.cpp: In static member function ‘static bool PICSBooleanExpressionParser::Eval(std::string, std::map<std::__cxx11::basic_string<char>, bool>&)’:
> ../../src/app/tests/suites/pics/PICSBooleanExpressionParser.cpp:30:45: error: cannot bind non-const lvalue reference of type ‘int&’ to a value of type ‘uint8_t’ {aka ‘unsigned char’}
>    30 |     return EvaluateExpression(tokens, PICS, index);
>       |                                             ^~~~~
> ../../src/app/tests/suites/pics/PICSBooleanExpressionParser.h:46:117: note:   initializing argument 3 of ‘static bool PICSBooleanExpressionParser::EvaluateExpression(std::vector<std::__cxx11::basic_string<char> >&, std::map<std::__cxx11::basic_string<char>, bool>&, int&)’
>    46 |     static bool EvaluateExpression(std::vector<std::string> & tokens, std::map<std::string, bool> & PICS, uint8_t & index);
>       |                                                                                                           ~~~~~~~~~~^~~~~
> ../../src/app/tests/suites/pics/PICSBooleanExpressionParser.cpp: At global scope:
> ../../src/app/tests/suites/pics/PICSBooleanExpressionParser.cpp:97:6: error: no declaration matches ‘bool PICSBooleanExpressionParser::EvaluateExpression(std::vector<std::__cxx11::basic_string<char> >&, std::map<std::__cxx11::basic_string<char>, bool>&, uint8_t&)’
>    97 | bool PICSBooleanExpressionParser::EvaluateExpression(std::vector<std::string> & tokens, std::map<std::string, bool> & PICS,
>       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../../src/app/tests/suites/pics/PICSBooleanExpressionParser.h:46:17: note: candidate is: ‘static bool PICSBooleanExpressionParser::EvaluateExpression(std::vector<std::__cxx11::basic_string<char> >&, std::map<std::__cxx11::basic_string<char>, bool>&, int&)’
>    46 |     static bool EvaluateExpression(std::vector<std::string> & tokens, std::map<std::string, bool> & PICS, uint8_t & index);
>       |                 ^~~~~~~~~~~~~~~~~~
> ../../src/app/tests/suites/pics/PICSBooleanExpressionParser.h:28:7: note: ‘class PICSBooleanExpressionParser’ defined here
>    28 | class PICSBooleanExpressionParser
>       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../../src/app/tests/suites/pics/PICSBooleanExpressionParser.cpp:129:6: error: no declaration matches ‘bool PICSBooleanExpressionParser::EvaluateSubExpression(std::vector<std::__cxx11::basic_string<char> >&, std::map<std::__cxx11::basic_string<char>, bool>&, uint8_t&)’
>   129 | bool PICSBooleanExpressionParser::EvaluateSubExpression(std::vector<std::string> & tokens, std::map<std::string, bool> & PICS,
>       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../../src/app/tests/suites/pics/PICSBooleanExpressionParser.h:47:17: note: candidate is: ‘static bool PICSBooleanExpressionParser::EvaluateSubExpression(std::vector<std::__cxx11::basic_string<char> >&, std::map<std::__cxx11::basic_string<char>, bool>&, int&)’
>    47 |     static bool EvaluateSubExpression(std::vector<std::string> & tokens, std::map<std::string, bool> & PICS, uint8_t & index);
>       |                 ^~~~~~~~~~~~~~~~~~~~~
> ../../src/app/tests/suites/pics/PICSBooleanExpressionParser.h:28:7: note: ‘class PICSBooleanExpressionParser’ defined here
>    28 | class PICSBooleanExpressionParser
>       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
>

**Comment by maxkondor** [comment]
Same issue. On GCC 13 undeclared types like `uint8_t` etc. Fix It by adding `#include <cstdint>` please.

**Comment by elektro-NIK** [comment]
The [current](https://github.com/espressif/esp-matter/commit/2832857748b46ddf3fa2fe42a902822298e26bda) version compiles successfully with GCC 13.
