### ISSUE TITLE
Matter Binding between ESP32-S3 and other Manufacturer board (CON-585)

### ISSUE THREAD

**Issue by varshilglide** [espressif/esp-matter#482]
Hello,
I have a bit of doubt that right now I have one Matter Enabled board of ESP32-S3. And I have one more Matter Enabled board from Different Manufacturer so If I want to Communication between that board or I would say Matter binding between that board so can ESP32 Support it?

**Comment by shubhamdp** [comment]
Binding is a feature in Matter Specification, and ESP32 does support it.

**Comment by varshilglide** [comment]
Okay Thank you @shubhamdp
