### ISSUE TITLE
Unable to add matter devices to apple home (CON-586)

### ISSUE THREAD

**Issue by SYESHASWINI** [espressif/esp-matter#483]
Hi, I recently updated my IOS version, from then my matter devices are unable to add to apple home. Could anyone help me with this. Versions I'm using are:
Home Pod: (MJ23HN/A(v 16.5)
iOS version - 16.5.1

**Comment by dhrishi** [comment]
@SYESHASWINI We will not be able to debug or analyze the problem unless you provide us with the complete logs. Please do the same and then re-open this issue

**Comment by SYESHASWINI** [comment]
@dhrishi attaching the log while commissioning.
[apple_issue1.txt](https://github.com/espressif/esp-matter/files/11945891/apple_issue1.txt)

**Comment by VaishaliAvhale** [comment]
I tried out this and it is working at my side.

**Comment by VaishaliAvhale** [comment]
For further details please share iPad side logs.
