### ISSUE TITLE
OpenThread CLI doesn't work (CON-589)

### ISSUE THREAD

**Issue by Gonta01** [espressif/esp-matter#486]
I use esp-idf v5.1 with ESP32C6. Successfully commissioned my device and see logs but I can't use any cli commands. I have activated it in sdkconfig.defaults CONFIG_OPENTHREAD_CLI=y. 
For example, I want to use commands: dataset active -x or scan to research Thread network.

**Comment by chshu** [comment]
OpenThread CLI is not available in Matter example, the matter application takes over the Thread network configuration.

You can play with ot_cli with this example:
https://github.com/espressif/esp-idf/tree/master/examples/openthread/ot_cli

**Comment by Gonta01** [comment]
Get it. Thank you
