### ISSUE TITLE
Full end device vs Router Eligible End Device vs Minimal end device in Thread network (CON-591)

### ISSUE THREAD

**Issue by Gonta01** [espressif/esp-matter#487]
In configuration file it is possible to choose Full Thread Device, Minimal Thread Device or Radio Only Device.
When Full Thread Device option was chosen the device acts like Router Eligible End Device. In the logs is written that it is child and than its role is changed into router. How to configure device to be Full Thread Device (so that it can't change role into router)?
Also it isn't clear what is the difference between Full end device and Minimal end device.

**Comment by wqx6** [comment]
You can use `otThreadSetLinkMode(otInstance *aInstance, otLinkModeConfig aConfig)` to set `mRxOnWhenIdle`, `mDeviceType`, and `mNetworkData` to 1. And use `otThreadSetRouterEligible(otInstance *aInstance, bool aEligible)` to set `Eligible` to 0. You can find the difference in https://openthread.io/guides/thread-primer/node-roles-and-types

**Comment by Gonta01** [comment]
Thank you.
