### ISSUE TITLE
ESP32-C6 Light example doesn't control light (CON-602)

### ISSUE THREAD

**Issue by avidNewb** [espressif/esp-matter#496]
The ESP32-C6 has an onboard WS2812B.  The light example is configured to use pin 8 which is the data pin for the WS2812B but it is using ledc commands instead of RMT.  The result is that the WS2812B turns on to full white but is not controllable.

**Comment by wqx6** [comment]
The [led_type](https://github.com/espressif/esp-matter/blob/main/device_hal/device/esp32c6_devkit_c/esp_matter_device.cmake#L7) for esp32c6_devkit_c is WS2812. Can you check it and test again?

**Comment by sayondeep** [comment]
I am able to commission and control the onboard led on esp32-c6. Switch on/off , colour change and brightness control everything works fine.

**Comment by dhrishi** [comment]
Closing this as the C6 devkitC is controllable
