### ISSUE TITLE
Failed to get wifi scan results while Matter started (CON-616)

### ISSUE THREAD

**Issue by eme-bennytang** [espressif/esp-matter#505]
In my code I would like to trigger a wifi scan to see the RSSI of the specific AP.
Normally without matter, I can just call 

esp_wifi_init()
esp_wifi_set_mode(WIFI_MODE_STA)
esp_wifi_start()

esp_wifi_scan_start
esp_wifi_scan_get_ap_num
esp_wifi_scan_get_ap_records

But after starting matter, I realize the wifi layer is controlled by matter stack
(ConnectivityManagerImpl_WIFI & NetworkCommissioningDriver)
So I instead, just call the scan start function
I got WIFI_EVENT_SCAN_DONE on the event callback sometime later
Then I call the get results functions
But I found that the RSSI information in the ap records is always 0

How can I get this RSSI like what I would do normally?

IDF 5.0.2
Matter SDK: release v1.1 commit 548ef58b604ef1df208e4a040803a4218e213103

**Comment by wqx6** [comment]
https://github.com/project-chip/connectedhomeip/pull/27161 this PR fixed the issue but it is not added to release v1.1 branch. You can try the latest main branch. The issue should be fixed in that branch.

**Comment by dhrishi** [comment]
@eme-bennytang The above issue is merged into upstream and the submodule in esp-matter is updated to include that
