### ISSUE TITLE
Failed to Setup Environment for Matter  (CON-618)

### ISSUE THREAD

**Issue by manaam216** [espressif/esp-matter#507]
After Cloning the repo in WSL, and updating the submodules when I run install.sh it throws an following error.
![image](https://github.com/espressif/esp-matter/assets/57254363/5cd55d0c-0e22-467b-8c67-c93c4e1623a6)

I have tried cloning the gn repo from google but failed

**Comment by dhrishi** [comment]
@manaam216 Please share the exact set of steps you've followed for the setup. Are the prerequisites for Matter done, as mentioned here: https://docs.espressif.com/projects/esp-matter/en/latest/esp32/developing.html#host-setup ?

**Comment by shubhamdp** [comment]
@manaam216 If your issue is resolved please close it.
