### ISSUE TITLE
switch_on_off like light_on_off  (CON-619)

### ISSUE THREAD

**Issue by stefano055415** [espressif/esp-matter#508]
is it possible to create an object of type switch that controls two gpio?

that has the same behavior as the light_switch example, but display as a generic switch?

**Comment by jonsmirl** [comment]
Sure, use strip the light example down to just OnOff (get rid of color and level control). Then make two OnOff endpoints, one for each GPIO. The switch side does not need to change. Just bind the switch to one of the two endpoints.

**Comment by stefano055415** [comment]
@jonsmirl 


Hi, maybe I explained it wrong.

I would like to create a switch similar to the homekit one

which does not read the inputs but switches an output on and off


![IMG_946AC320A8CA-1](https://github.com/espressif/esp-matter/assets/4798738/93d4d32a-0c61-4b8d-9df6-46ce324930c7)

**Comment by jonsmirl** [comment]
That is the light_switch example in the example folder.

**Comment by AshishESP** [comment]
Does this mean your hardware does not have any input buttons?
and you want to operate the switch only using App or voice(alexa)?

**Comment by jonsmirl** [comment]
If you want to do this in an app, you can look at the Google sample app
https://github.com/google-home/sample-app-for-matter-android

Here is where it sends the on/off commands
https://github.com/google-home/sample-app-for-matter-
android/blob/main/app/src/main/java/com/google/homesampleapp/chip/ClustersHelper.kt#L481

**Comment by shubhamdp** [comment]
@stefano055415 any updates on this?

**Comment by dhrishi** [comment]
Closing now. Please re-open in case of anything
