### ISSUE TITLE
Data model without ESP-Matter (CON-626)

### ISSUE THREAD

**Issue by Gonta01** [espressif/esp-matter#515]
There are examples of esp32 device in connectedhomeip repository (for example, lighting-app). Also there is an example zap-light in esp-matter repository. It isn't clear how Data model is configured in these cases. 
Are there any information about that or can someone explain?

**Comment by wqx6** [comment]
For examples except zap-light example in esp-matter, the date model is dynamically generated when running the examples. We will call `node::create()` and `endpoint::create()` to create the data model. And for zap-light and all the examples in connectedhomeip repository, the data model is statically generated by ZAP when building the examples. we will use `chip_app_component_codegen` and `chip_app_component_zapgen` to generate the data model codes in [CMake file](https://github.com/espressif/esp-matter/blob/main/examples/zap_light/main/CMakeLists.txt#L10-L11).

**Comment by Gonta01** [comment]
Thank you for answer. How to create own data model using ZAP? Should files .matter and .zap somehow changed?

**Comment by wqx6** [comment]
Yes, you should change the `.matter` and `.zap` files to create own data model.

**Comment by Gonta01** [comment]
They cannot be modified manually. Right? ZAP tool is used to generate `.zap`. What tool is used to generate `.matter`?
Are there anywhere a step-by-step guide?

**Comment by wqx6** [comment]
https://github.com/project-chip/connectedhomeip/blob/master/docs/code_generation.md Here is the code-generation doc.

**Comment by Gonta01** [comment]
@wqx6 thank you!
