### ISSUE TITLE
Setting up light example to commission with Thread AND Wifi (CON-629)

### ISSUE THREAD

**Issue by switchless-team** [espressif/esp-matter#517]
Would there be any way to set up the configs to allow a device, i.e. light example on ESP32C6, to commission via thread unless the hub didn't support Thread, causing it to be commissioned via wifi instead? How would this be done? I have tried combining the configurations from the C6 and the C3 with regards to the networking settings but it still will only commission via thread. Thank you.

**Comment by dhrishi** [comment]
@switchless-team It is technically feasible and is already supported on EP32-C6. See the [commit](https://github.com/project-chip/connectedhomeip/commit/0ce378a897dd14a35a50fc6c46006ffa94faf39d) in the upstream connectedhomeip and the documentation [here](https://github.com/espressif/connectedhomeip/blob/master/docs/guides/esp32/build_app_and_commission.md#esp32-application-usage-guide).

Currently, the Matter specification does not define the support of multiple interfaces clearly. As a result, the phone apps do not support it. You can test the example using chip-tool, by using `ble-wifi` and `ble-thread` pairing.

If you want, you can check the specification issue where this is being discussed: https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/4608
