### ISSUE TITLE
Descriptor read command lists

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#53]
These commands don't appear to be implemented on the descriptor cluster

read
  | * generated-command-list                                                            |
  | * accepted-command-list

**Comment by dhrishi** [comment]
These should be handled internally. AFAIK, they aren't supported in the upstream repo.

**Comment by VaishaliAvhale** [comment]
Descriptor cluster does not generate and accept server or client side commands. As a result it gives 0 entries of generated-command-list and accepted-command-list.
