### ISSUE TITLE
issue ble commissioning with chip-tool: 42594 abort (CON-648)

### ISSUE THREAD

**Issue by albrownwood** [espressif/esp-matter#533]
host is macOS Ventura, the tool seems to crash without going very far in the procedure, see log attached

[chip-tool_pairing.txt](https://github.com/espressif/esp-matter/files/12142239/chip-tool_pairing.txt)

**Comment by jonsmirl** [comment]
The Apple guide is here: https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/darwin.md

**Comment by albrownwood** [comment]
thanks for the pointer @jonsmirl, my issue came from not giving iTerm bluetooth permissions!
