### ISSUE TITLE
Finding Matter Version (CON-655)

### ISSUE THREAD

**Issue by SYESHASWINI** [espressif/esp-matter#539]
Is there any parameter to find the matter version whether it is v1.0/v1.1 apart from the branch chosen.

**Comment by shubhamdp** [comment]
@SYESHASWINI Do you mean in the firmware or in the repository?

**Comment by HARRYhelenH** [comment]
@shubhamdp the repos version. As it is said release/v1.0 is matter v1.0 where can we find the version related details.

**Comment by SYESHASWINI** [comment]
@shubhamdp yes, repo version. As release/v1.0 matter v1.0 can we find the matter version in any of the configuration details.

**Comment by shubhamdp** [comment]
@SYESHASWINI We do not have the branch name at someplace in the repo. Tracking by the branch name seems to be a viable option right now.

**Comment by SYESHASWINI** [comment]
Okay, Thank You
