### ISSUE TITLE
Aggregator Endpoint

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#54]
What is this and how do I use it?

So dimmer has EPs:
1 Dimmable Light
2 Dimmer Switch
3 Generic Switch

Apparently it also needs to say these are pieces of single device.
Aggregator EP  (1, 2, 3)

**Comment by chshu** [comment]
Please refer to spec 9.12, Aggregator is a spec device type for bridge device, which has a Descriptor cluster with a PartsList attribute containing all the endpoints representing those Bridged Devices.

The example:

![image](https://user-images.githubusercontent.com/20312411/189020955-b0e706c8-ca1d-47c7-9a36-c519124f0488.png)

**Comment by jonsmirl** [comment]
Boris telling me to use this in a non-bridge device.  This is a new use of aggregator I am not familiar with.

**Comment by jonsmirl** [comment]
This is the actual issue
https://github.com/espressif/esp-matter/issues/73
