### ISSUE TITLE
chip-tool commissioning error: Failed to verify peer's MAC (CON-676)

### ISSUE THREAD

**Issue by albrownwood** [espressif/esp-matter#556]
The device is already commissioned and part of an Apple fabric, my understanding is that I can pair this same device using chip-tool so it becomes part of a second fabric. When doing so I get the message "Failed to verify peer's MAC" in chip-tool console.

[chip_tool_commissioning_issue.txt](https://github.com/espressif/esp-matter/files/12265326/chip_tool_commissioning_issue.txt)

[device_commissioning_issue.txt](https://github.com/espressif/esp-matter/files/12265329/device_commissioning_issue.txt)

**Comment by dhrishi** [comment]
@albrownwood Did you open the commissioning window using Apple Home? If yes, it would have generated a new QR code/manual code (enhanced commissioning). You can then use the following command from chip-tool:

```
chip-tool pairing code <new-node-id> <code-from-Apple-Home>
```

**Comment by albrownwood** [comment]
@dhrishi yes the commissioning window was opened with Apple home, pairing was successful with your indications, thanks!

**Comment by gautam1joshi** [comment]
hello @albrownwood ,
which release of esp-IDF are you using because i get error when i try to commission the device over wifi?
your help will be appreciated.
