### ISSUE TITLE
Update documentation to fix two issues with WSL (CON-677)

### ISSUE THREAD

**Issue by Kampi** [espressif/esp-matter#557]
Please reference the [Prerequisites](https://github.com/espressif/connectedhomeip/blob/v1.0.0.2/docs/guides/BUILDING.md#installing-prerequisites-on-linux) during the SDK setup when using WSL and Ubuntu. I wasn´t able to run `install.sh` until I had installed the missing packages.

Also, I needed to run `install.sh` with `sudo` because of a permission issue.

**Comment by sayondeep** [comment]
@Kampi Thanks for the feedback.
`install.sh` should not required sudo privileges if the repo was cloned from within the WSL itself.
The requirement of sudo may arise if the repo was cloned in windows and accessed from inside WSL.
OR It was cloned as root in WSL and accessed by other user on WSL.
OR The installation directory of WSL was changed using `wsl --export`.

**Comment by dhrishi** [comment]
Closing this now
