### ISSUE TITLE
How loooooong after export.sh in esp-matter folder?

### ISSUE THREAD

**Issue by Zeni241** [espressif/esp-matter#56]
followed instructions on this page: 
https://docs.espressif.com/projects/esp-matter/en/main/esp32/developing.html

After I enter /export.sh in esp-matter folder I get bellow line in terminal:

 My traceroute [v0.95]
FUbuntu (127.0.0.1) -> localhost (127.0.0.1) 2022-09-08T21:15:39+0500
Keys: Help Display mode Restart statistics Order of fields quit
Packets Pings
|Host 		|	Loss% |	Snt 	 |  Last 	|Avg |	Best |	Wrst |	StDev|
|-------------------|----------------|----------|------------|-------|------------|------------|--------------|
|1. localhost 	|        0.0% |	6911 |    0.2 	|0.0 	  |    0.0 	 |     2.2 	 |        0.1   |

Value under Snt keep on increasing. Hours have past. How long does it take to complete? Is it a normal behaviour?

**Comment by dhrishi** [comment]
This seems a bit strange. It should terminate right away. `source export.sh` or `. ./export.sh` just exports the path of the repository to `ESP_MATTER_PATH` variable

**Comment by Zeni241** [comment]
Sorry, it was my fault. I was giving command "export.sh" at wrong path.
