### ISSUE TITLE
esp-idf release issue (CON-680)

### ISSUE THREAD

**Issue by gautam1joshi** [espressif/esp-matter#560]
hello i want to use esp-matter for esp32-c3 so which version of esp-idf is best for me to use matter over wifi?

**Comment by dhrishi** [comment]
@gautam1joshi https://github.com/espressif/esp-matter#supported-esp-idf-and-connectedhomeip-versions

**Comment by gautam1joshi** [comment]
hello i try to follow https://docs.espressif.com/projects/esp-matter/en/latest/esp32c3/developing.html this steps and when i start  esp-matter repository cloning steps of **./install.sh** then after it start installing and my terminal window close automatically.
