### ISSUE TITLE
How can I bind the Matter Light to the Light Switch on Zigbee to Matter Bridge? (CON-682)

### ISSUE THREAD

**Issue by LongND0105** [espressif/esp-matter#562]
I have a Matter Light application is running on ESP32. And I have a Light Switch on Zigbee to Matter Bridge. Can I bind Light to Light Switch? I have tried bind but chip-tool return CONSTRAINT_ERROR.
I defined Light Switch end point belike:
![bindingBridge](https://github.com/espressif/esp-matter/assets/133942344/887a2a1f-e561-4b30-8dfb-339e456b041e)

![image](https://github.com/espressif/esp-matter/assets/133942344/8f427273-1152-4439-97f7-d82eb3e9733a)

**Comment by dhrishi** [comment]
@LongND0105 Please upload the chip-tool log for the commands that you use for the commissioning, ACL, and binding

**Comment by LongND0105** [comment]
> @LongND0105 Please upload the chip-tool log for the commands that you use for the commissioning, ACL, and binding

These are the commands I used: node id of Light: 112, node id of bridge: 111

- Step 1: `accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects": [112233], "targets": null },{"fabricIndex": 1, "privilege": 3, "authMode": 2, "subjects": [111], "targets": null }]' 112 0`
- Step 2: `binding write binding '[{"fabricIndex": 1, "node":112, "endpoint":1, "cluster":6}]' 111 3`

**Comment by dhrishi** [comment]
@LongND0105 Can you please check if your usecase is similar to https://github.com/espressif/esp-matter/tree/main/examples/esp-now_bridge_light#esp-now-matter-bridge-light. In this example, we bind the esp-now button (presented as light switch in Matter) through the bridge to a Matter light.

**Comment by dhrishi** [comment]
Hi @LongND0105 Did this help?

**Comment by dhrishi** [comment]
@LongND0105 Please close if this helped and solved your issue

**Comment by dhrishi** [comment]
Closing this now. Please re-open in case of anything
