### ISSUE TITLE
Error: Unable to detect the device in ESP Lanchpad (CON-688)

### ISSUE THREAD

**Issue by varshilgandhi** [espressif/esp-matter#566]
Hi, Varshil here,
I am trying to flash the light bulb example code in ESP-C3 Board.
When I connect the Dev kit of ESP-C3 with the Laptop and then click on the connect button of ESP Launchpad.
When I click on the connect button it gives me unable to detect the device.
BUT I already connect board with system and for cross checking I type this command in terminal:
ls /dev/tty* 
and after run above code I can see my board is connected.
But ESP Launchpad shows that it is unable to detect.

![Screenshot from 2023-08-09 17-30-37](https://github.com/espressif/esp-matter/assets/76485639/b8ce9d4a-35a6-44f3-96b6-ab4b4124a81e)

![Screenshot from 2023-08-09 17-32-29](https://github.com/espressif/esp-matter/assets/76485639/a5466174-c26d-4ada-a9c0-9c88eb7bfef0)

**Comment by dhrishi** [comment]
@varshilgandhi Please raise the issue in https://github.com/espressif/esp-launchpad for better assistance

**Comment by varshilgandhi** [comment]
@dhrishi Okay Thank You.
