### ISSUE TITLE
Dead Front Feature add definition mismatch in esp_matter_feature.cpp and esp_matter_feature.h files (CON-691)

### ISSUE THREAD

**Issue by aggaddam** [espressif/esp-matter#569]
Mismatch in function definition and declaration

esp_matter_feature.cpp
`esp_err_t add(cluster_t *cluster, config_t *config)`

esp_matter_feature.h
`esp_err_t add(cluster_t *cluster);`

**Comment by dhrishi** [comment]
@aggaddam Thanks for reporting the issue. This has been fixed internally and will be synced to Github soon

**Comment by dhrishi** [comment]
Fixed with https://github.com/espressif/esp-matter/commit/e8ddc6459465cbe9a9a3788c508c40b1cdc6661c
