### ISSUE TITLE
Nonce in attestation (CON-695)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#572]
Who is making the attestation nonce? Is it Espressif code?
These failures are because the nonce is invalid in the attestation request.

https://github.com/google-home/sample-apps-for-matter-android/issues/156

**Comment by wqx6** [comment]
The Attestation Nonce is generated by the commissioner as a random 32 Bytes octet string, according to **SPEC 6.2.3. Device Attestation Procedure**.

**Comment by dhrishi** [comment]
Closing this as the nonce is generated by the commissioner
