### ISSUE TITLE
Could not update the attribute as it was not found from the endpoint id. (CON-696)

### ISSUE THREAD

**Issue by Okywan** [espressif/esp-matter#573]
Trying to update temperature and humidity measurements read from the sensor, there is an error saying it cannot be found, but the endpoint exists and the attribute should too...

This is the initialization:

` temperature_sensor::config_t tempSensorConfig;
    endpoint_t* tempSensorEndpoint = temperature_sensor::create(node, &tempSensorConfig, ENDPOINT_FLAG_NONE, NULL); // TODO: necesitamos el AC si no vamos a invocarle nada?

    if (tempSensorEndpoint) {
        ESP_LOGI(TAG_MATTER, "Created temp endpoint");
    }
    humidity_sensor::config_t humiditySensorConfig;
    endpoint_t* humiditySensorEndpoint = humidity_sensor::create(node, &humiditySensorConfig, ENDPOINT_FLAG_NONE, NULL); // TODO: necesitamos el AC si no vamos a invocarle nada?

    if (humiditySensorEndpoint) {
        ESP_LOGI(TAG_MATTER, "Created humidity endpoint");
    }`
    
    They are correctly created because they are shown on the iOS home app. However when trying to update it doesn't work with the errors shown:
    
    `
I (123044) ACMatterDriver: TEMP: esp_matter_attr_val_t value is 29.500000
I (123044) ACMatterDriver: HUM: esp_matter_attr_val_t value is 30.400000
I (123054) ACMatterDriver: Updating climate measurement
I (123054) esp_matter_attribute: ********** W : Endpoint 0x0002's Cluster 0x00000402's Attribute 0x00000001 is <invalid type: 0> **********
I (123064) ACMatterDriver: Could not update the attribute as it was not found from the endpoint id.
E (123084) esp_matter_attribute: Error updating Endpoint 0x0002's Cluster 0x00000402's Attribute 0x00000001 to matter: 0x1
I (123094) esp_matter_attribute: ********** W : Endpoint 0x0003's Cluster 0x00000405's Attribute 0x00000001 is <invalid type: 0> **********
I (123104) ACMatterDriver: Could not update the attribute as it was not found from the endpoint id.
E (123124) esp_matter_attribute: Error updating Endpoint 0x0003's Cluster 0x00000405's Attribute 0x00000001 to matter: 0x1
`

And here's the code used for update:

`

esp_matter_attr_val_t temp;
    temp.type = ESP_MATTER_VAL_TYPE_FLOAT;
    temp.val.f = *temperature;

    ESP_LOGI(TAG_MATTER, "TEMP: esp_matter_attr_val_t value is %f", temp.val.f);
    esp_matter_attr_val_t hum;
    hum.type = ESP_MATTER_VAL_TYPE_FLOAT;
    hum.val.f = *humidity;
    
    ESP_LOGI(TAG_MATTER, "HUM: esp_matter_attr_val_t value is %f", hum.val.f);

    ESP_LOGI(TAG_MATTER, "Updating climate measurement");
    //update values.
    esp_matter::attribute::update(tempSensorEndpointId, TemperatureMeasurement::Id, TemperatureMeasurement::Attributes::MeasuredValue::Id, &temp);
    esp_matter::attribute::update(humiditySensorEndpointId, RelativeHumidityMeasurement::Id, RelativeHumidityMeasurement::Attributes::MeasuredValue::Id, &hum);`

As you can see on the output, the esp_matter_attr_val_t structs are properly initialised as the values are there (overriding possible pointer issues). 

What am I doing wrong?

**Comment by shubhamdp** [comment]
`TemperatureMeasurement` cluster's [`MeasuredValue`](https://github.com/espressif/esp-matter/blob/main/components/esp_matter/esp_matter_attribute.cpp#L1854) attribute is of type nullable int16_t. 

`RelativeHumidityMeasurement`'s, [`MeasuredValue`](https://github.com/espressif/esp-matter/blob/main/components/esp_matter/esp_matter_attribute.cpp#L1878) attribute is of type nullable uint16_t.

You shall use the type as, `.type = ESP_MATTER_VAL_TYPE_NULLABLE_INT16` and `.type = ESP_MATTER_VAL_TYPE_NULLABLE_UINT16` respectively. For storing value, `temp.val.i16` and `temp.val.u16`.

**Comment by Okywan** [comment]
Adapted code as suggested but still getting the same error:



    esp_matter_attr_val_t temp;
    temp.type = ESP_MATTER_VAL_TYPE_NULLABLE_INT16;
    temp.val.u16 = static_cast<int>(*temperature + 0.5); // add 0.5 for rounding
    ESP_LOGI(TAG_MATTER, "TEMP: esp_matter_attr_val_t value is %i", temp.val.u16);
    esp_matter_attr_val_t hum;
    hum.type = ESP_MATTER_VAL_TYPE_NULLABLE_INT16;
    hum.val.u16 = static_cast<int>(*humidity + 0.5); // add 0.5 for rounding
    
    ESP_LOGI(TAG_MATTER, "HUM: esp_matter_attr_val_t value is %i", hum.val.u16);

    ESP_LOGI(TAG_MATTER, "Updating climate measurement");
    //update values.
    esp_matter::attribute::update(tempSensorEndpointId, TemperatureMeasurement::Id, TemperatureMeasurement::Attributes::MeasuredValue::Id, &temp);
    esp_matter::attribute::update(humiditySensorEndpointId, RelativeHumidityMeasurement::Id, RelativeHumidityMeasurement::Attributes::MeasuredValue::Id, &hum);


`
I (243174) main:: Hum: 31.6 Tmp: 28.3

I (243184) ACMatterDriver: TEMP: esp_matter_attr_val_t value is 28
I (243184) ACMatterDriver: HUM: esp_matter_attr_val_t value is 32
I (243194) ACMatterDriver: Updating climate measurement
I (243194) esp_matter_attribute: ********** W : Endpoint 0x0002's Cluster 0x00000402's Attribute 0x00000000 is 28 **********
I (243204) ACMatterDriver: Could not update the attribute as it was not found from the endpoint id.
E (243214) esp_matter_attribute: Error updating Endpoint 0x0002's Cluster 0x00000402's Attribute 0x00000000 to matter: 0x1
I (243234) esp_matter_attribute: ********** W : Endpoint 0x0003's Cluster 0x00000405's Attribute 0x00000000 is 32 **********
I (243244) ACMatterDriver: Could not update the attribute as it was not found from the endpoint id.
E (243254) esp_matter_attribute: Error updating Endpoint 0x0003's Cluster 0x00000405's Attribute 0x00000000 to matter: 0x1`

**Comment by Okywan** [comment]
Ok, turns out this error was actually my own code on the callback for handling updates. Since I'm not using those values not he program for anything it defaults to the error. Switching to the report API and fixing values worked.
