### ISSUE TITLE
Comissioning not finishing, chip[ZCL]: OpCreds: Failed CertificateChainRequest: 201 (CON-698)

### ISSUE THREAD

**Issue by Okywan** [espressif/esp-matter#574]
After generating the factory partition with mfg tool 

```
./mfg_tool.py -cn "My name" -v 0xFFF2 -p 0x8001 --pai \
   -k ~/esp-idf/tools/esp-matter/connectedhomeip/connectedhomeip/credentials/test/attestation/Chip-Test-PAI-FFF2-8001-Key.pem \
   -c ~/esp-idf/tools/esp-matter/connectedhomeip/connectedhomeip/credentials/test/attestation/Chip-Test-PAI-FFF2-8001-Cert.pem \
   -cd ~/esp-idf/tools/esp-matter/connectedhomeip/connectedhomeip/credentials/test/certification-declaration/Chip-Test-CD-FFF2-8001.der \
   --dac-in-secure-cert --target esp32 -n 2 --product-name "My name" --hw-ver-str "1.0" --vendor-name "My name"
```

Factory partition uploaded via esptool on factory offset properly, when scanning the QR code in `out` the commissioning fails at this point.

I'm guessing certificates need to be uploaded somewhere but can't find where or how. is this assumption correct? if so.. how? If it's not correct. What am I missing?

**Comment by jadhavrohit924** [comment]
@Okywan It would be really helpful if you provide us complete logs in file ( do not paste ). Also have you enabled config options mentioned in [readme](https://github.com/espressif/esp-matter/blob/main/tools/mfg_tool/README.md#configure-your-app) ? Along with set `ESP_MATTER_DAC_PROVIDER` and `ESP_MATTER_DEVICE_INSTANCE_INFO_PROVIDER`

**Comment by jadhavrohit924** [comment]
Thanks for the logs!! Are you using default QR code? If yes, commissioning will fail. You have to generate new QR code since discriminator and setup-pincode is change as you updated factory partition.

**Comment by Okywan** [comment]
Im using the qr code generated on /out/ by the mfg_tool

**Comment by jadhavrohit924** [comment]
Have you tried commissioning with chip-tool?

**Comment by Okywan** [comment]
No but, to what purpose? I'm able to commission with iOS Home App under default config without problems, what would indicate being able to commission with chip-tool?

**Comment by jadhavrohit924** [comment]
Purpose of testing with chip-tool is to verify that there is nothing wrong with the factory partition that you have generated. If commissioning fails with chip-tool, we can easily track why it is failing.

> I'm able to commission with iOS Home App under default config without problems.

You are able to commissioning with Apple. With which eco-system commissioning is failing for you?

**Comment by Okywan** [comment]
I meant, when using default settings, not partition, commissioning works fine. 

Maybe that's the thing then. Do I need to set up discriminator and codes in my program somehow? How?

**Comment by jadhavrohit924** [comment]
You can set discriminator and code using `mfg_tool`. You have to pass it as arguments.
```
./mfg_tool.py -cn "My name" -v 0xFFF2 -p 0x8001 --passcode PASSCODE --discriminator DISCRIMINATOR --pai \
   -k ~/esp-idf/tools/esp-matter/connectedhomeip/connectedhomeip/credentials/test/attestation/Chip-Test-PAI-FFF2-8001-Key.pem \
   -c ~/esp-idf/tools/esp-matter/connectedhomeip/connectedhomeip/credentials/test/attestation/Chip-Test-PAI-FFF2-8001-Cert.pem \
   -cd ~/esp-idf/tools/esp-matter/connectedhomeip/connectedhomeip/credentials/test/certification-declaration/Chip-Test-CD-FFF2-8001.der \
   --dac-in-secure-cert --target esp32 -n 2 --product-name "My name" --hw-ver-str "1.0" --vendor-name "My name"
```

And if you don’t pass, it will be randomly generated and you can find that in `out` directory in `.csv` file.

Please try out commissioning with correct discriminator and passcode. Device should commission.

**Comment by Okywan** [comment]
Read comment above please

**Comment by jadhavrohit924** [comment]
> @jadhavrohit924 im having problems commissioning with chip-tool, I believe my Mac won't allow BT connection for some reason
> 
> ```
> [1692286695387] [49327:2318822] [TOO] Command: pairing ble-wifi 0x7283 OKYLAN noteladigo 8240495 235 
> [1692286695389] [49327:2318863] [CTL] Stopping commissioning discovery over DNS-SD
> [1692286695389] [49327:2318863] [CTL] Setting attestation nonce to random value
> [1692286695389] [49327:2318863] [CTL] Setting CSR nonce to random value
> [1692286695393] [49327:2318863] [CTL] Generating NOC
> [1692286695396] [49327:2318863] [FP] Validating NOC chain
> [1692286695401] [49327:2318863] [FP] NOC chain validation successful
> [1692286695401] [49327:2318863] [FP] Updated fabric at index: 0x1, Node ID: 0x000000000001B669
> [1692286695401] [49327:2318863] [TS] Last Known Good Time: 2023-08-05T18:14:30
> [1692286695401] [49327:2318863] [TS] New proposed Last Known Good Time: 2021-01-01T00:00:00
> [1692286695401] [49327:2318863] [TS] Retaining current Last Known Good Time
> [1692286695402] [49327:2318863] [FP] Metadata for Fabric 0x1 persisted to storage.
> [1692286695403] [49327:2318863] [TS] Committing Last Known Good Time to storage: 2023-08-05T18:14:30
> [1692286695403] [49327:2318863] [CTL] Joined the fabric at index 1. Fabric ID is 0x0000000000000001 (Compressed Fabric ID: A74289E90D143FDD)
> [1692286695408] [49327:2318863] [BLE] NewConnection
> [1692286695408] [49327:2318863] [CTL] Setting wifi credentials from parameters
> [1692286695408] [49327:2318863] [CTL] Setting attestation nonce to random value
> [1692286695408] [49327:2318863] [CTL] Setting CSR nonce to random value
> [1692286695408] [49327:2318863] [CTL] Commission called for node ID 0x0000000000007283
> [1692286695442] [49327:2318863] [BLE] CBManagerState: ON
> [1692286695837] [49327:2318864] [BLE] Connecting to device 0x600002d78000 with discriminator: 235
> [1692286696092] [49327:2318863] [DIS] Closing all BLE connections
> [1692286696093] [49327:2318863] [IN] BleConnectionComplete: endPoint 0x10192da88
> [1692286696093] [49327:2318863] [BLE] ATT MTU = 256
> [1692286696093] [49327:2318863] [IN] SecureSession[0x600002a74000]: Allocated Type:1 LSID:21451
> [1692286696093] [49327:2318863] [SC] Assigned local session key ID 21451
> [1692286696094] [49327:2318864] [BLE] BLE:Error writing Characteristics in Chip service on the device: [The specified UUID is not allowed for this operation.]
> [1692286696095] [49327:2318863] [EM] <<< [E:54293i S:0 M:42714108] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:20 (SecureChannel:PBKDFParamRequest)
> [1692286696095] [49327:2318863] [IN] (U) Sending msg 42714108 to IP address 'BLE'
> [1692286696095] [49327:2318863] [IN] Message appended to BLE send queue
> [1692286696095] [49327:2318863] [SC] Sent PBKDF param request
> [1692286696095] [49327:2318863] [IN] Failed to establish BLE connection: src/platform/Darwin/BleConnectionDelegateImpl.mm:476: Ble Error 0x00000407: GATT write characteristic operation failed
> [1692286696095] [49327:2318863] [IN] Clearing BLE pending packets.
> [1692286696095] [49327:2318863] [BLE] Auto-closing end point's BLE connection.
> ```

Please checkout the same issue https://github.com/project-chip/connectedhomeip/issues/23435

**Comment by PSONALl** [comment]
@Okywan have you installed a Matter Profile as mentioned here: https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/darwin.md

**Comment by jadhavrohit924** [comment]
@Okywan Please close the issue if your problem is resolved, thanks.

**Comment by Okywan** [comment]
Still working it out tbh

**Comment by shubhamdp** [comment]
Hi @Okywan I see you have provided the `--dac-in-secure-cert` that means command would generate two partitions.

One, for storing device attestation information which contains DAC, DAC private key, and PAI certificate. You can find that at path `out/fff2_8001/<UUID>/<UUID>_esp_secure_cert.bin`.  Please flash this partition address 0xd000.
You will also have to set an option which read the DACs from the secure cert parititon. `(Top) → Component config → ESP Matter → DAC Provider options -> Attestation - Secure Cert`.

Two, for other Matter data, `out/fff2_8001/<UUID>/<UUID>_partition.bin`. Please flash this at appropriate factory partition address based on config option `CONFIG_CHIP_FACTORY_NAMESPACE_PARTITION_LABEL`.

**Comment by Okywan** [comment]
Right, this makes sense. Will try when I'm back home with the device.

**Comment by Okywan** [comment]
Problem solved, cert partition was missing.
