### ISSUE TITLE
Unable to add accessory in iOS

### ISSUE THREAD

**Issue by AchimPieters** [espressif/esp-matter#58]
When I try to connect trough HomeKit, I get the message: Unable to add accessory, pairing with accessory failed. See image.
At the monitor in the terminal, it shows this.

```
I (116391) chip[DL]: CHIPoBLE advertising started
I (178011) chip[DL]: BLE GAP connection established (con 0)
I (178011) chip[DL]: CHIPoBLE advertising stopped
I (178661) chip[DL]: BLE GAP connection terminated (con 0 reason 0x213)
I (178661) chip[DL]: Configuring CHIPoBLE advertising (interval 25 ms, connectable, device name MATTER-3840)
I (178681) NimBLE: GAP procedure initiated: advertise; 
I (178681) NimBLE: disc_mode=2
I (178681) NimBLE:  adv_channel_map=0 own_addr_type=1 adv_filter_policy=0 adv_itvl_min=40 adv_itvl_max=40
I (178691) NimBLE: 
```

![IMG_0822](https://user-images.githubusercontent.com/16034588/190706695-22831ab0-5634-4a31-8d8d-043221231c3d.png)

**Comment by dhrishi** [comment]
Can you please confirm the iOS version you are using on the phone as well as the gateway (HomePod or Apple TV). We have it working on the latest iOS release v16.1 beta1. 

Please give it a try and let us know in case of any issues.

**Comment by AchimPieters** [comment]
iPhone XR (MRY92ZD/A) IOS16.1 (20B5045d)

Gateway's:
HomePod mini (9MY5G2FN/A) OS 16.1 Latest
Apple TV 4K  OS 16.1 Latest
Apple TV HD OS 16.1 Latest

**Comment by jonsmirl** [comment]
You also need to install a profile for the Matter support...
https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/darwin.md

Once you get everything installed correctly it should work.

**Comment by AchimPieters** [comment]
@jonsmirl I have installed the profiles and the latest IOS Beta (16.1).
![IMG_0826](https://user-images.githubusercontent.com/16034588/190903208-1df432d3-1fa4-42cd-bad2-f3dc6077da8e.png)

**Comment by jonsmirl** [comment]
I also have this installed
https://download.developer.apple.com/iOS/iOS_Logs/EnableMatter_Instructions.pdf

**Comment by dhrishi** [comment]
@AchimPieters I am on https://github.com/espressif/esp-matter/commit/960517dc14ad797c1f54f87982e46b59a4d095b3 and I can commission and control Matter light with iOS 16.1 (20B5045d)

**Comment by jonsmirl** [comment]
I've confirmed that Apple broke IOS paring for a while. The update from Apple that I received yesterday fixed pairing.

**Comment by dhrishi** [comment]
Thanks @jonsmirl 

@AchimPieters Can you please try with the latest update? iOS 16.1 beta2 - https://developer.apple.com/documentation/ios-ipados-release-notes/ios-16_1-release-notes

**Comment by AchimPieters** [comment]
@dhrishi solved!
