### ISSUE TITLE
The requirements for OTA in Matter device? (CON-704)

### ISSUE THREAD

**Issue by law-ko** [espressif/esp-matter#580]
There are examples for [CHIP ESP32 OTA Requestor](https://github.com/project-chip/connectedhomeip/blob/master/examples/ota-requestor-app/esp32/README.md) and [CHIP ESP32 OTA Provider](https://github.com/project-chip/connectedhomeip/blob/master/examples/ota-provider-app/esp32/README.md), but is it necessary to include requestor in Wi-Fi based Matter devices? Or can we use our own OTA design or do we need to follow certain Matter requirements for OTA?

**Comment by dhrishi** [comment]
@law-ko Matter specification mentions that OTA is mandatory. It can either be Matter based OTA or manufacturer specific OTA.

**Comment by law-ko** [comment]
@dhrishi Matter based OTA means Requestor OTA that requires a Provider OTA device on the same network?

which means Matter based OTA does not have something that is similar to esp_http_ota?

**Comment by dhrishi** [comment]
@law-ko Yes. Matter based OTA is the one defined in the specification, that requires a OTA requestor and OTA provider

>which means Matter based OTA does not have something that is similar to esp_http_ota?

That's right

**Comment by law-ko** [comment]
@dhrishi Is there any way to show new OTA available in Apple Home app with HTTP-based OTA by Matter?
