### ISSUE TITLE
Matter bridge to expose ESP-Mesh devices? (CON-705)

### ISSUE THREAD

**Issue by erumnasir** [espressif/esp-matter#581]
Is there anything that prevents one from making a Matter bridge with this SDK and expose compatible device types such as switches and fans to Matter? With a single ESP-32 module?

**Comment by omarkamal** [comment]
I'm interested in knowing this too

**Comment by shubhamdp** [comment]
@erumnasir If you talking about the [Matter Bridge for Non-Matter Devices](https://blog.espressif.com/matter-bridge-for-non-matter-devices-d3b7f003a004), then we have three bridge [examples](https://github.com/espressif/esp-matter/tree/main/examples) implemented (blemesh, esp-now, and zigbee) in the SDK.

If not, can you please share more details.

**Comment by shubhamdp** [comment]
@erumnasir any update on this, if the above comment answers your question, please close the issue.
