### ISSUE TITLE
Callback implementation of wifi connectivity events after matter intiailization (CON-706)

### ISSUE THREAD

**Issue by aggaddam** [espressif/esp-matter#582]
My application needs to know the esp wifi connection events (like Wi-Fi connected/disconnected, IP address changes, getting disconnected reason etc..). Is there a way I can provide an application callback function during esp matter initialization? or is there any other recommendation to get these events back to the application code ?

I am planning to use this event 
`        case chip::DeviceLayer::DeviceEventType::kInterfaceIpAddressChanged:`

**Comment by shubhamdp** [comment]
@aggaddam you can use the [default event loop](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/esp_event.html#default-event-loop) and [register](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/esp_event.html#_CPPv426esp_event_handler_register16esp_event_base_t7int32_t19esp_event_handler_tPv) an event handler for [wifi events](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/wifi.html#esp32-wi-fi-event-description).

Here is an example for handling of events: https://github.com/project-chip/connectedhomeip/blob/master/src/platform/ESP32/ConnectivityManagerImpl_WiFi.cpp#L463
