### ISSUE TITLE
Proprietary update system, how to notify the Matter stack (CON-711)

### ISSUE THREAD

**Issue by albrownwood** [espressif/esp-matter#585]
Hello,
when implementing a custom fw update system that is not using the OTA provider defined in Matter, are there APis the application running on the accessory can call to inform the matter stack that a fw update is available/in progress/completed?

**Comment by albrownwood** [comment]
@shubhamdp sorry let me put it differently, the question is about being able to report the status of the proprietary fw update system (e.g. update available/ update in progress/ update completed) so it is displayed to the user in the iOS/Android native home app.

**Comment by shubhamdp** [comment]
Ahh, I just replied in https://github.com/espressif/esp-matter/issues/600#issuecomment-1698566765

**Comment by dhrishi** [comment]
@albrownwood Please close your issue if the question is answered

**Comment by dhrishi** [comment]
Closing this now
