### ISSUE TITLE
Why commision failed (CON-720)

### ISSUE THREAD

**Issue by maenkai** [espressif/esp-matter#594]
In the 30 matching process, commision failed twice, I want to know the reason and how to solve this problem
![commision-fail](https://github.com/espressif/esp-matter/assets/106250124/a3335bcb-1f45-48a6-8d31-5ef32e253fed)

**Comment by shubhamdp** [comment]
@maenkai Attach the log files for failed commissioning which would help in knowing the reason for failure and narrowing down on the problem. If you have commissioner logs that would help as well.

**Comment by dhrishi** [comment]
@maenkai Please upload the complete logs as requested

**Comment by maenkai** [comment]
Close the issue temporarily and wait for the log to be provided after this replay
