### ISSUE TITLE
Show OTA available in Apple Home? (CON-726)

### ISSUE THREAD

**Issue by law-ko** [espressif/esp-matter#600]
Hello,

If we are using HTTPs OTA instead of Matter Requestor method, is there any method to display there's OTA available and trigger OTA updates directly in Apple Home app?

**Comment by shubhamdp** [comment]
Communication between two Matter devices are strictly through clusters. OTA requestor cluster has the attributes which has has mechanism to notify the home app (Matter client). I don't think there is any provision right now. You can provision such things using manufacturer specific apps.

**Comment by dhrishi** [comment]
@law-ko Please close your issue if the question is answered

**Comment by law-ko** [comment]
@dhrishi can we use the requestor cluster to notify the Apple Home app and then trigger OTA update?

**Comment by shubhamdp** [comment]
@law-ko I'd suggest you to please go through section `11.19. Over-the-Air (OTA) Software Update` of Matter Specification for better understanding of how Matter OTA works.

**Comment by jonsmirl** [comment]
https://developers.home.google.com/matter/ota/test/vendors/espressif

**Comment by dhrishi** [comment]
If you are using a different OTA mechanism than the Matter OTA then, the Apple Home cannot be used for performing the upgrade.
