### ISSUE TITLE
Errors during initialization of the matter node for Room Air Conditioner in the example code  (CON-729)

### ISSUE THREAD

**Issue by aggaddam** [espressif/esp-matter#603]
Describe the bug
Observed few warnings/errors while running the matter room air conditioner example under esp-matter sdk

Environment :

- ESP-Matter Commit Id: https://github.com/espressif/esp-matter/commit/68e99de70266674ce172459136960bbb5c58dc0e

- ESP-IDF Commit Id: e088c3766ba440e72268b458a68f27b6e7d63986

- SoC (eg: ESP32 or ESP32-C3): ESP32-C3

- Device Logs (Please attach the log file): 

![image](https://github.com/espressif/esp-matter/assets/94963960/f30f313f-6d06-41a9-8119-d505f440c5c4)

- Host Machine OS: Linux

- Commissioner app and versions if present: 

- Commissioner's logs if present:

Any additional details
...

**Comment by PSONALl** [comment]
@aggaddam This problem has been fixed in internal repo, the fix will be available soon

**Comment by dhrishi** [comment]
@aggaddam This if fixed and pushed to Github

**Comment by aggaddam** [comment]
@dhrishi Which commit of ESP-matter has this fix?
