### ISSUE TITLE
ERROR: Failed building wheel for chip-rpc

### ISSUE THREAD

**Issue by longnv97** [espressif/esp-matter#62]
I got error when run install.sh, in the step Setting up Python environment, this error related chip-rpc.
I not find information about it.
I sure I installed the [Prerequisites](https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/BUILDING.md#prerequisites) for Matter.

Please help me check it.

this log in terminal:
 
longnv@MSI:/mnt/d/matter/esp-matter$ ./install.sh

Running Matter Setup

  WELCOME TO...

         █
         █
     ▄   █   ▄                                █     █
     ▀▀█████▀▀      ▄▀▀▀▄ ▄▀▀▀▄    ▄▀▀▀▀▄█  ▀▀█▀▀▀▀▀█▀▀   ▄▀▀▀▀▄    ▄▀▀
   ▀█▄       ▄█▀   █     █     █  █      █    █     █    █▄▄▄▄▄▄█  █
     ▀█▄   ▄█▀     █     █     █  █      █    █     █    █         █
  ▄██▀▀█   █▀▀██▄  █     █     █   ▀▄▄▄▄▀█    ▀▄▄   ▀▄▄   ▀▄▄▄▄▀   █
 ▀▀    █   █    ▀▀

  BOOTSTRAP! Bootstrap may take a few minutes; please be patient.

Downloading and installing packages into local source directory:

  Setting up CIPD package manager...done (4.0s)
  Setting up Python environment.....[-]
ninja: Entering directory `/mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/gn_out'
[1/9] python3 ../../third_party/pigweed/repo/pw_build/py/pw_build/python_runner.py --gn-root ../../ --current-path ../.. --default-toolchain=//build/toolchain/linux:linux_x64_gcc --current-toolchain=//third_party/pigweed/repo/pw_build/python_toolchain:python --touch python/gen/pip_install_matter_packages.pw_pystamp --capture-output --python-dep-list-files python/gen/pip_install_matter_packages_metadata_path_list.txt -- ../../third_party/pigweed/repo/pw_build/py/pw_build/pip_install_python_deps.py --python-dep-list-files python/gen/pip_install_matter_packages_metadata_path_list.txt --gn-packages //examples/common/pigweed/rpc_console:chip_rpc_distribution install --no-build-isolation --constraint ../../scripts/constraints.txt
FAILED: python/gen/pip_install_matter_packages.pw_pystamp
python3 ../../third_party/pigweed/repo/pw_build/py/pw_build/python_runner.py --gn-root ../../ --current-path ../.. --default-toolchain=//build/toolchain/linux:linux_x64_gcc --current-toolchain=//third_party/pigweed/repo/pw_build/python_toolchain:python --touch python/gen/pip_install_matter_packages.pw_pystamp --capture-output --python-dep-list-files python/gen/pip_install_matter_packages_metadata_path_list.txt -- ../../third_party/pigweed/repo/pw_build/py/pw_build/pip_install_python_deps.py --python-dep-list-files python/gen/pip_install_matter_packages_metadata_path_list.txt --gn-packages //examples/common/pigweed/rpc_console:chip_rpc_distribution install --no-build-isolation --constraint ../../scripts/constraints.txt
Processing ./python/obj/examples/common/pigweed/rpc_console/chip_rpc_distribution
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting googleapis-common-protos
  Using cached googleapis_common_protos-1.56.4-py2.py3-none-any.whl (211 kB)
Collecting mypy-protobuf==2.9
  Using cached mypy_protobuf-2.9-py3-none-any.whl (14 kB)
Collecting graphlib-backport
  Using cached graphlib_backport-1.0.3-py3-none-any.whl (5.1 kB)
Collecting types-pygments
  Using cached types_Pygments-2.13.1-py3-none-any.whl (16 kB)
Requirement already satisfied: ipython in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from chip-rpc==0.0.1+20220930005055) (7.24.1)
Collecting pyperclip
  Using cached pyperclip-1.8.2-py3-none-any.whl
Requirement already satisfied: pygments in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from chip-rpc==0.0.1+20220930005055) (2.9.0)
Requirement already satisfied: pyserial in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from chip-rpc==0.0.1+20220930005055) (3.5)
Requirement already satisfied: protobuf in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from chip-rpc==0.0.1+20220930005055) (3.17.3)
Collecting pygments-style-dracula
  Using cached pygments_style_dracula-1.2.5.1-py3-none-any.whl (4.0 kB)
Collecting pygments-style-tomorrow
  Using cached pygments_style_tomorrow-1.0.0.1-py3-none-any.whl (9.8 kB)
Requirement already satisfied: pyyaml in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from chip-rpc==0.0.1+20220930005055) (6.0)
Collecting types-pyyaml
  Using cached types_PyYAML-6.0.12-py3-none-any.whl (14 kB)
Collecting ptpython>=3.0.20
  Using cached ptpython-3.0.20-py2.py3-none-any.whl (61 kB)
Collecting types-protobuf
  Using cached types_protobuf-3.20.4-py3-none-any.whl (60 kB)
Requirement already satisfied: jinja2 in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from chip-rpc==0.0.1+20220930005055) (3.0.1)
Requirement already satisfied: prompt-toolkit in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from chip-rpc==0.0.1+20220930005055) (3.0.26)
Collecting grpcio-tools>=1.38.1
  Using cached grpcio_tools-1.49.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
Requirement already satisfied: wcwidth in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from prompt-toolkit->chip-rpc==0.0.1+20220930005055) (0.2.5)
Requirement already satisfied: six>=1.9 in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from protobuf->chip-rpc==0.0.1+20220930005055) (1.16.0)
Requirement already satisfied: jedi>=0.16.0 in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from ptpython>=3.0.20->chip-rpc==0.0.1+20220930005055) (0.18.0)
Requirement already satisfied: appdirs in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from ptpython>=3.0.20->chip-rpc==0.0.1+20220930005055) (1.4.4)
Requirement already satisfied: backcall in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from ipython->chip-rpc==0.0.1+20220930005055) (0.2.0)
Requirement already satisfied: matplotlib-inline in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from ipython->chip-rpc==0.0.1+20220930005055) (0.1.2)
Requirement already satisfied: setuptools>=18.5 in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from ipython->chip-rpc==0.0.1+20220930005055) (65.4.1)
Requirement already satisfied: pickleshare in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from ipython->chip-rpc==0.0.1+20220930005055) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from ipython->chip-rpc==0.0.1+20220930005055) (5.0.5)
Requirement already satisfied: decorator in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from ipython->chip-rpc==0.0.1+20220930005055) (5.0.9)
Requirement already satisfied: pexpect>4.3 in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from ipython->chip-rpc==0.0.1+20220930005055) (4.8.0)
Requirement already satisfied: MarkupSafe>=2.0 in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from jinja2->chip-rpc==0.0.1+20220930005055) (2.0.1)
Collecting types-setuptools
  Using cached types_setuptools-65.4.0.0-py3-none-any.whl (49 kB)
Collecting types-docutils
  Using cached types_docutils-0.19.1-py3-none-any.whl (16 kB)
Collecting grpcio>=1.49.1
  Using cached grpcio-1.49.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
Collecting grpcio-tools>=1.38.1
  Using cached grpcio_tools-1.48.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from jedi>=0.16.0->ptpython>=3.0.20->chip-rpc==0.0.1+20220930005055) (0.8.2)
Requirement already satisfied: ptyprocess>=0.5 in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from pexpect>4.3->ipython->chip-rpc==0.0.1+20220930005055) (0.7.0)
Requirement already satisfied: ipython-genutils in /mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (from traitlets>=4.2->ipython->chip-rpc==0.0.1+20220930005055) (0.2.0)
Building wheels for collected packages: chip-rpc
  Building wheel for chip-rpc (pyproject.toml): started
  Building wheel for chip-rpc (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Building wheel for chip-rpc (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      running bdist_wheel
      running build
      running build_py
      installing to build/bdist.linux-x86_64/wheel
      running install
      running install_lib
      running install_egg_info
      running egg_info
      writing chip_rpc.egg-info/PKG-INFO
      writing dependency_links to chip_rpc.egg-info/dependency_links.txt
      writing entry points to chip_rpc.egg-info/entry_points.txt
      writing requirements to chip_rpc.egg-info/requires.txt
      writing top-level names to chip_rpc.egg-info/top_level.txt
      reading manifest file 'chip_rpc.egg-info/SOURCES.txt'
      writing manifest file 'chip_rpc.egg-info/SOURCES.txt'
      removing 'build/bdist.linux-x86_64/wheel/chip_rpc-0.0.1+20220930005055-py3.8.egg-info' (and everything under it)
      Copying chip_rpc.egg-info to build/bdist.linux-x86_64/wheel/chip_rpc-0.0.1+20220930005055-py3.8.egg-info
      running install_scripts
      error: [('build/bdist.linux-x86_64/wheel/chip_rpc-0.0.1+20220930005055-py3.8.egg-info', 'build/bdist.linux-x86_64/wheel/chip_rpc-0.0.1+20220930005055.dist-info', "[Errno 13] Permission denied: 'build/bdist.linux-x86_64/wheel/chip_rpc-0.0.1+20220930005055.dist-info'")]
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for chip-rpc
Failed to build chip-rpc
ERROR: Could not build wheels for chip-rpc, which is required to install pyproject.toml-based projects

ninja: build stopped: subcommand failed.
['ninja', '-C', '/mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/gn_out', '-v', ':python_packages.install']

Traceback (most recent call last):
  File "/mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 327, in install_packages
    subprocess.check_call(ninja_cmd, stdout=outs, stderr=outs)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', '/mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/gn_out', '-v', ':python_packages.install']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 795, in <module>
    sys.exit(main())
  File "/mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 787, in main
    return EnvSetup(**vars(parse())).setup()
  File "/mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 457, in setup
    result = step(spin)
  File "/mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 606, in virtualenv
    if not virtualenv_setup.install(
  File "/mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 342, in install
    install_packages(gn_target)
  File "/mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 330, in install_packages
    raise subprocess.CalledProcessError(err.returncode, err.cmd,
subprocess.CalledProcessError: Command '['ninja', '-C', '/mnt/d/matter/esp-matter/connectedhomeip/connectedhomeip/.environment/gn_out', '-v', ':python_packages.install']' returned non-zero exit status 1.
longnv@MSI:/mnt/d/matter/esp-matter$

**Comment by dhrishi** [comment]
@longnv97 If this is still an issue, can you please provide the details about the host? And also the OS version

**Comment by longnv97** [comment]
I using Linux Subsystem ver 20.04 LTS on Windows 11, I got this error (related to chip-rpc). My laptop using intel core i5 gen 11.
I success when install esp_idf, but this error happen when run ./install.sh for esp_matter.
Please help me check it and share to me your experience.

**Comment by jonsmirl** [comment]
it looks like a permissions problem...
```
error: [('build/bdist.linux-x86_64/wheel/chip_rpc-0.0.1+20220930005055-py3.8.egg-info', 'build/bdist.linux-x86_64/wheel/chip_rpc-0.0.1+20220930005055.dist-info', "[Errno 13] Permission denied: 'build/bdist.linux-x86_64/wheel/chip_rpc-0.0.1+20220930005055.dist-info'")]
```

**Comment by dhrishi** [comment]
@longnv97 Were you able to resolve this issue? https://github.com/espressif/esp-matter/issues/88#issuecomment-1313440875 shows setting up esp-matter on Windows using WSL. Can you please check if it is helpful?

**Comment by alibukharai** [comment]
@longnv97 if the error still presists try this [method](https://github.com/alibukharai/Blogs/blob/main/ESP-Matter(Demo)/Getting_Started/getting_started_with_matter_esp.md)

**Comment by dhrishi** [comment]
Closing this now. Feel free to re-open in case of any issue.
