### ISSUE TITLE
[Thermostat] Groups Cluster Missing (CON-760)

### ISSUE THREAD

**Issue by emesamwong** [espressif/esp-matter#628]
**Describe the bug**
Matter Device Library V1.1 mentioned that the Thermostat Endpoint required the Groups cluster. The Groups cluster is mandatory for 'Awake' device, which a lot of thermostat devices are. 

However, the SDK **did not include** the Groups cluster in release/v1.1 for the Thermostat Endpoint.
![Screenshot from 2023-09-11 08-38-44](https://github.com/espressif/esp-matter/assets/142867756/35200d27-7578-484d-a355-393bcb985edc)
![Screenshot from 2023-09-11 08-50-33](https://github.com/espressif/esp-matter/assets/142867756/232268b2-7233-4e4c-98c8-04b01d6ca2cf)

In Window Covering Endpoint, Group is an optional cluster, but the SDK is still included.
![image](https://github.com/espressif/esp-matter/assets/142867756/3adc956f-d5cb-4845-abb1-734577a0a840)
![Screenshot from 2023-09-11 08-47-54](https://github.com/espressif/esp-matter/assets/142867756/191c867c-369c-4f14-985e-7d42af60671d)

So, could I copy the Groups cluster from the Window Covering Endpoint to the Thermostat Endpoint? like below:
![Screenshot from 2023-09-11 10-09-10](https://github.com/espressif/esp-matter/assets/142867756/156ea0bb-7078-4c6a-9c0e-af45d0a8dac2)

Thank you for your attention.

**Environment**
- ESP-Matter Commit Id: 548ef58b604ef1df208e4a040803a4218e213103
- ESP-IDF Commit Id: cbce221e88d52665523093b2b6dd0ebe3f1243f1
- SoC (eg: ESP32 or ESP32-C3): ESP32-S3
- Host Machine OS: Linux

**Comment by jonsmirl** [comment]
While you are waiting for a fix, you can add this cluster with one line of code in your app.
~~~
  groups::create(endpoint, &ext_config.groups, CLUSTER_FLAG_SERVER);
~~~
