### ISSUE TITLE
How do I return TLV from a custom command? (CON-764)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#631]
All of the examples only show sending TLV. How do I return it?

For example the ViewScene command is using AddReponse(). How do I do this in esp-matter?
~~~
    response.sceneName.SetValue(CharSpan(scene.mStorageData.mName, scene.mStorageData.mNameLength));
    Span<Structs::ExtensionFieldSet::Type> responseEFSSpan(responseEFSBuffer, deserializedEFSCount);
    response.extensionFieldSets.SetValue(responseEFSSpan);

    ctx.mCommandHandler.AddResponse(ctx.mRequestPath, response);
~~~

**Comment by PSONALl** [comment]
@jonsmirl The TLV types for commands are defined for different clusters and their commands in connectedhomeip, e.g The Response type for ViewScene command has kGroupID and kSceneID [reference](https://github.com/project-chip/connectedhomeip/blob/master/zzz_generated/app-common/app-common/zap-generated/cluster-objects.cpp#L1065)

So, The TLV type for a custom command needs to be defined in similar way

**Comment by jonsmirl** [comment]
How do I do AddResponse in the esp-matter model?

**Comment by PSONALl** [comment]
The ESP-Matter command callback API is designed to provide an abstraction to users, The TLV Writer's handling is expected to be done internally from connectedhomeip, Which is why it's not implemented currently in esp-matter

**Comment by jonsmirl** [comment]
This needs to be done using Matter APIs. I have implemented now using those APIs.
