### ISSUE TITLE
OSError: [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by sidhoo-root** [espressif/esp-matter#64]
Hi  espressif team:

    I hv meet a problem when i run ./install.sh , log as fllow:
```
xxxx:~/Work/esp-matter$ ./install.sh 

Running Matter Setup


  WELCOME TO...

         █
         █
     ▄   █   ▄                                █     █
     ▀▀█████▀▀      ▄▀▀▀▄ ▄▀▀▀▄    ▄▀▀▀▀▄█  ▀▀█▀▀▀▀▀█▀▀   ▄▀▀▀▀▄    ▄▀▀
   ▀█▄       ▄█▀   █     █     █  █      █    █     █    █▄▄▄▄▄▄█  █   
     ▀█▄   ▄█▀     █     █     █  █      █    █     █    █         █   
  ▄██▀▀█   █▀▀██▄  █     █     █   ▀▄▄▄▄▀█    ▀▄▄   ▀▄▄   ▀▄▄▄▄▀   █   
 ▀▀    █   █    ▀▀

  BOOTSTRAP! Bootstrap may take a few minutes; please be patient.

Downloading and installing packages into local source directory:

  Setting up CIPD package manager...Traceback (most recent call last):
  File "/home/sid/Work/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 795, in <module>
    sys.exit(main())
  File "/home/sid/Work/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 787, in main
    return EnvSetup(**vars(parse())).setup()
  File "/home/sid/Work/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 457, in setup
    result = step(spin)
  File "/home/sid/Work/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 546, in cipd
    cipd_client = cipd_wrapper.init(
  File "/home/sid/Work/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 357, in init
    bootstrap(client, silent, rosetta=rosetta)
  File "/home/sid/Work/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 311, in bootstrap
    tmp.write(client_bytes(rosetta))
  File "/home/sid/Work/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 240, in client_bytes
    conn.request('GET', path)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
```
1. the Prerequisites for Matter and espif (4.4.2) is ready. 
2. and i found that issue(https://github.com/project-chip/connectedhomeip/issues/2893) had beed fixed
3. ping www.google.com is ok
>~/Work/esp-matter$ ping www.google.com
PING www.google.com (142.250.204.36) 56(84) bytes of data.
64 bytes from hkg07s38-in-f4.1e100.net (142.250.204.36): icmp_seq=1 ttl=128 time=7.73 ms
64 bytes from hkg07s38-in-f4.1e100.net (142.250.204.36): icmp_seq=2 ttl=128 time=6.96 ms
64 bytes from hkg07s38-in-f4.1e100.net (142.250.204.36): icmp_seq=3 ttl=128 time=6.79 ms
64 bytes from hkg07s38-in-f4.1e100.net (142.250.204.36): icmp_seq=4 ttl=128 time=6.63 ms

hope you give me some advise, thank you

**Comment by dhrishi** [comment]
@sidhoo-root  This seems to be an issue with the upstream connectedhomeip repo. Can you please check: https://github.com/project-chip/connectedhomeip/issues/8810

**Comment by sidhoo-root** [comment]
@dhrishi ok ,thanks. and Is it related to using a virtual machine environment to install ?

**Comment by dhrishi** [comment]
@sidhoo-root Yes, it seems so

**Comment by sidhoo-root** [comment]
@dhrishi i had installed it on the Ubuntu machine, it still report this error.   and the host : chrome-infra-packages.appspot.com can be ping, does it means the CIPD_HOST = 'chrome-infra-packages.appspot.com'  works in  my env ?
>PING chrome-infra-packages.appspot.com (199.193.116.105) 56(84) bytes of data.
64 bytes from 199-193-116-105.static.hvvc.us (199.193.116.105): icmp_seq=1 ttl=128 time=220 ms
64 bytes from 199-193-116-105.static.hvvc.us (199.193.116.105): icmp_seq=2 ttl=128 time=218 ms
64 bytes from 199-193-116-105.static.hvvc.us (199.193.116.105): icmp_seq=3 ttl=128 time=219 ms
64 bytes from 199-193-116-105.static.hvvc.us (199.193.116.105): icmp_seq=4 ttl=128 time=220 ms
64 bytes from 199-193-116-105.static.hvvc.us (199.193.116.105): icmp_seq=5 ttl=128 time=218 ms

**Comment by sidhoo-root** [comment]
@dhrishi the problem was solved,  because the dns can't be parsed correctly in my office network

**Comment by dhrishi** [comment]
@sidhoo-root Good to know that the issue is identified and resolved.

**Comment by wivin001** [comment]
我也遇到这个问题了，使用虚拟机vmware15.0  ubuntu 22.10系统，已经翻墙了，但是依然会报这个错误，有没有解决办法？

**Comment by chuckrui** [comment]
> @dhrishi问题解决了，因为在我的办公网络中dns无法正确解析

您好，想问一下是如何解决的，我也遇到了这个问题，ping youtube 跟google都没有问题

**Comment by chuckrui** [comment]
> > @dhrishi问题解决了，因为在我的办公网络中dns无法正确解决
> 
> 您好，想问下是如何解决的，我也遇到了这个问题，ping youtube跟google都没有问题

![image](https://user-images.githubusercontent.com/76715008/225191323-f57f930b-c211-42bf-a2ec-aef5afc21dd0.png)
泪目了~终于搞定了，我就说怎么Ubuntu里面明明都可以访问外网，但是就是一直提示我有问题，不应该的啊，然后在命令行里面定义了一下IP就行了

**Comment by temp4gh** [comment]
> > > @dhrishi问题解决了，因为在我的办公网络中dns无法正确解决
> > 
> > 
> > 您好，想问下是如何解决的，我也遇到了这个问题，ping youtube跟google都没有问题
> 
> ![image](https://user-images.githubusercontent.com/76715008/225191323-f57f930b-c211-42bf-a2ec-aef5afc21dd0.png) 泪目了~终于搞定了，我就说怎么Ubuntu里面明明都可以访问外网，但是就是一直提示我有问题，不应该的啊，然后在命令行里面定义了一下IP就行了

Same issue,Could you please explain  how to '命令行里面定义了一下IP'?Thanx!

**Comment by chuckrui** [comment]
> > > > @dhrishi问题解决了，因为在我的办公网络中dns无法正确解决
> > > 
> > > 
> > > 您好，想问下是如何解决的，我也遇到了这个问题，ping youtube跟google都没有问题
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/76715008/225191323-f57f930b-c211-42bf-a2ec-aef5afc21dd0.png) 泪目了~终于搞定了，我就说怎么Ubuntu里面明明都可以访问外网，但是就是一直提示我有问题，不应该的啊，然后在命令行里面定义了一下IP就行了
> 
> Same issue,Could you please explain how to '命令行里面定义了一下IP'?Thanx!

sure，u can open the sofeware and the click here just as show in the picture as below.
![1678929498111](https://user-images.githubusercontent.com/76715008/225484820-15153196-4100-4839-b0a0-b21b9eb89f0a.png)
![1678929571123](https://user-images.githubusercontent.com/76715008/225484980-4c530479-ec5a-4bf1-85e2-6f1b76646d84.png)
copy that in terminal command line it will connect normally.

**Comment by temp4gh** [comment]
> > > > > @dhrishi问题解决了，因为在我的办公网络中dns无法正确解决
> > > > 
> > > > 
> > > > 您好，想问下是如何解决的，我也遇到了这个问题，ping youtube跟google都没有问题
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/76715008/225191323-f57f930b-c211-42bf-a2ec-aef5afc21dd0.png) 泪目了~终于搞定了，我就说怎么Ubuntu里面明明都可以访问外网，但是就是一直提示我有问题，不应该的啊，然后在命令行里面定义了一下IP就行了
> > 
> > 
> > Same issue,Could you please explain how to '命令行里面定义了一下IP'?Thanx!
> 
> sure，u can open the sofeware and the click here just as show in the picture as below. ![1678929498111](https://user-images.githubusercontent.com/76715008/225484820-15153196-4100-4839-b0a0-b21b9eb89f0a.png) ![1678929571123](https://user-images.githubusercontent.com/76715008/225484980-4c530479-ec5a-4bf1-85e2-6f1b76646d84.png) copy that in terminal command line it will connect normally.

Thanx for your reply!I will take a try.

**Comment by zplmcu** [comment]
@temp4gh, do you have a fix for it? Currently, I have encountered the same issue. Also, exported the proxy; 
Unfortunately, it doesn't work. (wifi network can go to Google, YouTube etc)

![Image](https://github.com/user-attachments/assets/79b207e6-148d-4285-8b5f-a7c6c7f7ec14)
