### ISSUE TITLE
Missing GetPrimaryMACAddress(MutableByteSpan buf) in ConfigurationManagerImpl.h (CON-780)

### ISSUE THREAD

**Issue by jzwyssig** [espressif/esp-matter#645]
In the file `esp-matter/connectedhomeip/connectedhomeip/src/platform/ESP32/ConfigurationManagerImpl.h` only the function `CHIP_ERROR GetPrimaryWiFiMACAddress(uint8_t * buf) override;` is defined and as the name suggests support for Ethernet is missing.

Please add the generic definition `CHIP_ERROR GetPrimaryMACAddress(MutableByteSpan buf) override;` and provide a default implementation for Ethernet. I solved the problem by adding this definition and overriding the function in my main application with the correct MAC address of the used Ethernet chip.

**Fix**
```
#include <platform/internal/GenericConfigurationManagerImpl.ipp>
namespace chip {
namespace DeviceLayer {

using namespace ::chip::DeviceLayer::Internal;
CHIP_ERROR ConfigurationManagerImpl::GetPrimaryMACAddress(MutableByteSpan buf)
{ 
    uint8_t *byte_mac = get_mac_address_from_ethernet_chip();
    memcpy((void*)buf.data(), (void*)byte_mac, 6);
    return CHIP_NO_ERROR;
}
```

**Environment**
- ESP-Matter Commit Id: https://github.com/espressif/esp-matter/commit/0a1d89d7235a5dc632edd488727814b9690b6270 (up to date)
- ESP-IDF Commit Id: e088c3766ba440e72268b458a68f27b6e7d63986 (5.1.1 stable)
- SoC: ESP32-S3
- Host Machine OS: Linux
- Device Log: E (9141) chip[DIS]: Failed to get primary mac address of device. Generating a random one.

**Comment by PSONALl** [comment]
@jzwyssig Yes you are right, I am implementing GetPrimaryMACAddress for ethernet. I will let you know once it is available

**Comment by dhrishi** [comment]
Update -
@jzwyssig This is merged in upstream now: https://github.com/project-chip/connectedhomeip/pull/29415
I will close this issue once the connectedhomeip submodule here is updated with the fix.

**Comment by jzwyssig** [comment]
That is perfect, thank you @dhrishi.
