### ISSUE TITLE
Esp Matter supports ESP Mesh Wifi?  (CON-795)

### ISSUE THREAD

**Issue by ahmed8812** [espressif/esp-matter#659]
Hi,

Does the esp-matter supports of adding esp wifi-mesh?

Thanks

**Comment by shubhamdp** [comment]
@ahmed8812 It can be supported using bridge device type. it is not supported out of the box and you will have implement a wifi-mesh bridge similar to the ones implemented in [esp-matter/examples](../tree/main/examples/).  (1. [blemesh_bridge](https://github.com/espressif/esp-matter/tree/main/examples/blemesh_bridge) 2. [esp-now_bridge_light](https://github.com/espressif/esp-matter/tree/main/examples/esp-now_bridge_light) 3. [zigbee_bridge](https://github.com/espressif/esp-matter/tree/main/examples/zigbee_bridge))

**Comment by ahmed8812** [comment]
Thanks, I close it for now
