### ISSUE TITLE
BasicInfo/NodeLabel corrupted on reboot via subscription (CON-796)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#660]
Using unaltered light demo....

1) Use my phone app to write BasicInfo/NodeLabel. The phone app gets the change properly reported via the subscription.
2) Restart phone app, BasicInfo/NodeLabel is still correctly reported via subscription. Note that this value was written to RAM and held there.
3) Reboot device.
a) The log shows proper retrieval of the NodeLabel
~~~
I (147625) esp_matter_attribute: ********** R : Endpoint 0x0000's Cluster 0x00000028's Attribute 0x00000005 is Office/Nine **********
~~~
b) But that string is not returned by the subscription. Instead it is getting NULL plus some binary data.

The bug: reboot device, start wildcard subscription, stored NodeLabel from flash is not reported correctly. It appears to be correctly in flash, but that value in flash is not getting correctly reported back out via the subscription.

Does the subscription code not understand the new compact attribute storage format in flash?
Or... is this bug messing up my subscriptions? https://github.com/espressif/esp-matter/issues/646

I added logging to report() nothing seems to be calling it.
https://github.dev/espressif/esp-matter/blob/6aa7601258b10eaa0cb3845c39f41109ac0bfbaf/components/esp_matter/esp_matter_attribute_utils.cpp#L1929-L1930

**Comment by shubhamdp** [comment]
https://github.com/espressif/esp-matter/blob/1cacb8b2fcd42c465e38317d3a63d0169460b397/components/esp_matter/private/esp_matter_nvs.cpp#L56-L59

Here's the culprit, we are corrupting the `val.val.a.t` by updating `val.val.a.s` before that. Ideally, `val.val.a.s` should be updated before `val.val.a.t`.

**Comment by jonsmirl** [comment]
Is fix coming soon?

**Comment by dhrishi** [comment]
@jonsmirl We have the fix available internally. Can you please confirm if this works for you?

**Comment by jonsmirl** [comment]
Where is the fix?

**Comment by shubhamdp** [comment]
Please try the below patch
```
curl https://github.com/shubhamdp/esp-matter/commit/28b37dea29476f1d6c27a02f02f130aaa31ecc1c.patch | git am
```
