### ISSUE TITLE
Concentration and air quality measurement (CON-802)

### ISSUE THREAD

**Issue by MichaelHeiser** [espressif/esp-matter#664]
Are there plans to implement Concentration measurement and air quality measurement as example apps?

https://github.com/project-chip/connectedhomeip/tree/master/src/app/clusters/air-quality-server
https://github.com/project-chip/connectedhomeip/tree/master/src/app/clusters/concentration-measurement-server

We want to build a device giving CO2 values to a Controller.

**Comment by PSONALl** [comment]
we have added internal MR to add support for these devices in the SDK, you can implement your sample example app from it easily

**Comment by MichaelHeiser** [comment]
Where do I find information how to do it?

**Comment by PSONALl** [comment]
Just take a reference of light example you have to mention your device type while creating endpoint in app_main.cpp and in app_driver.cpp you can write your driver functionality

**Comment by MichaelHeiser** [comment]
In https://github.com/espressif/esp-matter/blob/main/components/esp_matter/esp_matter_endpoint.h there is no endpoint for indoor air quality or concentration measurement defined. So I have to adjust not only the light example, I have also to add the endpoints and the corresponding handler behaviour. So is there any information on how to add this endpoint to esp-matter sdk?

**Comment by dhrishi** [comment]
@MichaelHeiser 

>we have added internal MR to add support for these devices in the SDK

The device type support is added internally and will soon be synced to Github. After that, you will be able to see it in `components/esp-matter` using which you can create an example.

**Comment by MichaelHeiser** [comment]
Thank you for the information!! Will close this issue!
