### ISSUE TITLE
Room Air Conditioner device type 0x0072 unexpected (CON-803)

### ISSUE THREAD

**Issue by adailydose** [espressif/esp-matter#665]
**Describe the bug**
I built and loaded the example for room air conditioner. When I test with the GHSAFM test app, I see Endpoint 0 and Endpoint 1. I expected Endpoint 1 to be the room air conditioner device type, but I see it shown as [0x0072] Unknown. I expected 0x0300 for Heating/Cooling Unit.

**Environment**
- ESP-Matter Commit Id: 1cacb8b2fcd42c465e38317d3a63d0169460b397
- ESP-IDF Commit Id: v5.1.1
- SoC (eg: ESP32 or ESP32-C3): esp32c6
- Device Logs (Please attach the log file): [room_air_conditioner_logs.txt](https://github.com/espressif/esp-matter/files/12753104/room_air_conditioner_logs.txt)
- Host Machine OS: MacOS
- Commissioner app and versions if present: GHSAFM v 1.4.1-default
- Commissioner's logs if present:

**Comment by PSONALl** [comment]
In the specifications, the device type ID for Room Air Conditioner  is 0x0072
Heating/Cooling unit is a different HVAC device type.
Room AC is not currently listed in the supported device types by Google Home: https://developers.home.google.com/matter/supported-devices
