### ISSUE TITLE
Should the Thermostat endpoint have a Fan Control cluster? (CON-811)

### ISSUE THREAD

**Issue by adailydose** [espressif/esp-matter#668]
Per Matter Device Library Specification R1.1, a Thermostat endpoint shall include a Fan Control cluster. However, in esp_matter_endpoint.cpp, I only see a thermostat cluster in the thermostat endpoint, and no fan control cluster. Is this something I should add myself, or am I misinterpreting the specification?

**Comment by jadhavrohit924** [comment]
@adailydose Fan control cluster is provisional and optional. You have to add it yourself, if you needed.
