### ISSUE TITLE
BLE-WiFi commissioning fails for ESP32 with PSRAM (CON-812)

### ISSUE THREAD

**Issue by jzwyssig** [espressif/esp-matter#669]
BLE-WiFi pairing fails when PSRAM is enabled. The same settings on a ESP32-S3 work perfectly fine. Does anyone have an idea what to try? MbedTLS, esp-matter and Bluetooth are set to allocate memory in PSRAM. Our firmware also overflows IRAM on ESP32 but not on ESP32-S3. That is why I enabled [CONFIG_ESP_SYSTEM_ESP32_SRAM1_REGION_AS_IRAM](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#config-esp-system-esp32-sram1-region-as-iram) which solved the issue. Everything else is working fine, except for commissioning.

**Environment**
- ESP-Matter Commit Id: https://github.com/espressif/esp-matter/commit/0a1d89d7235a5dc632edd488727814b9690b6270 (up to date)
- ESP-IDF Commit Id: e088c3766ba440e72268b458a68f27b6e7d63986 (5.1.1 stable)
- SoC: ESP32
- Host Machine OS: Linux
- Sdkconfig: [sdkconfig.esp32.txt](https://github.com/espressif/esp-matter/files/12795209/sdkconfig.esp32.txt)
- Logs of the device: [Terminal Saved Output.txt](https://github.com/espressif/esp-matter/files/12807101/Terminal.Saved.Output.txt)
- Commissioner: Apple Home

**Comment by shubhamdp** [comment]
@jzwyssig Rather than a screenshot the complete logs from the device in a file attached here would be more helpful.

On commissioner side, which commissioner are you using? If you are using chip-tool then logs from the chip-tool would be more helpful.

**Comment by jzwyssig** [comment]
@shubhamdp I attached the log file.

**Comment by mgoeller** [comment]
I get the same error with an ESP32

**Comment by jonsmirl** [comment]
[sdkconfig.txt](https://github.com/espressif/esp-matter/files/12819761/sdkconfig.txt)

I am using this SDK config with the light example on ESP32+PSRAM without BLE problems.

**Comment by jonsmirl** [comment]
BTW, your commissioning worked. It is the wifi-based mDNS advertising which is failing.

**Comment by jzwyssig** [comment]
I close this for now. This issue is not our priority and I did not investigate it. I will reopen it as necessary.
