### ISSUE TITLE
Errors after comisioning (CON-823)

### ISSUE THREAD

**Issue by damian-kurek-wizzdev** [espressif/esp-matter#677]
**Describe the bug**
After the successful commissioning of the matter thermostat device, I got some error messages. The device is connected but some functionality is missing (scheduling, auto mode). 
Are those issues connected? I can see that scheduling is in the feature map but it does not appear in any mobile app. I tried Google Home and Aeotec. I will try to use Apple Home as well.
**Environment**
- ESP-Matter Commit Id: current main branch
- ESP-IDF Commit Id: 5.1.1
- SoC (eg: ESP32 or ESP32-C3): ESP32
- Device Logs (Please attach the log file):
- E (23621) chip[DMG]: Error retrieving data from clusterId: 0x0000_0030, err = b
E (23661) chip[DMG]: Error retrieving data from clusterId: 0x0000_003C, err = b
E (23681) chip[DMG]: Error retrieving data from clusterId: 0x0000_003E, err = b
E (23751) chip[DMG]: Error retrieving data from clusterId: 0x0000_001D, err = b
I (35041) UI: Reseting diplay to default brightness!
I (35041) Display: Setting display brightness to 2
E (38841) chip[DIS]: Timeout waiting for mDNS resolution.
E (52841) chip[DIS]: OperationalSessionSetup[1:0000000083C779AA]: operational discovery failed: 32
E (52841) chip[DMG]: Failed to establish CASE for subscription-resumption with error '32'
E (352881) chip[DMG]: Error retrieving data from clusterId: 0x0000_0030, err = b
E (352901) chip[DMG]: Error retrieving data from clusterId: 0x0000_0030, err = b
E (352961) chip[DMG]: Error retrieving data from clusterId: 0x0000_003C, err = b
E (353011) chip[DMG]: Error retrieving data from clusterId: 0x0000_003E, err = b
E (353041) chip[DMG]: Error retrieving data from clusterId: 0x0000_001D, err = b

- Host Machine OS:
- Commissioner app and versions if present:
- Commissioner's logs if present:

**Any additional details**
Logs appear always after rebooting the device and connecting to matter

**Comment by jonsmirl** [comment]
It is an expected error. I do wish CHIP would suppress the message.

https://github.com/espressif/esp-matter/issues/171
