### ISSUE TITLE
esp32 ota does not take effect (CON-824)

### ISSUE THREAD

**Issue by maenkai** [espressif/esp-matter#678]
**Describe the bug**
esp32 ota does not take effect

**Environment**
- ESP-Matter Commit Id:2832857748b46ddf3fa2fe42a902822298e26bda
- ESP-IDF Commit Id:  e088c3766ba440e72268b458a68f27b6e7d63986 (grafted, HEAD, tag: v5.1.1)
- SoC (eg: ESP32 or ESP32-C3): ESP32
- Device Logs (Please attach the log file):[esp32.log](https://github.com/espressif/esp-matter/files/12876717/esp32.log)
- Host Machine OS: UBUNTU
- Commissioner app and versions if present:
- Commissioner's logs if present: [chip-tool.log](https://github.com/espressif/esp-matter/files/12876730/chip-tool.log)

**Any additional details**
esp_node = 3
provider_node=2
```shell
 chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects": [112233], "targets": null}, {"fabricIndex": 1, "privilege": 3, "authMode": 2, "subjects": null, "targets": [{"cluster": 41, "endpoint": null, "deviceType": null}]}]' 2 0
 chip-tool otasoftwareupdaterequestor announce-otaprovider 2 0x1460 0 0 3 0
```

log & ota binary
[ota-provider.log](https://github.com/espressif/esp-matter/files/12876731/ota-provider.log)
[ota.zip](https://github.com/espressif/esp-matter/files/12876733/light_v1_1.zip)

**Comment by wqx6** [comment]
Hi, is the image software version higher than the firmware running on the OTA requestor device? You could increase the PROJECT_VER_NUMBER in the project [`CMakeLists.txt`](https://github.com/espressif/esp-matter/blob/main/examples/light/CMakeLists.txt) file.
