### ISSUE TITLE
Does deleting bridge EP clean out EP flash? (CON-830)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#683]
Lots of clusters have persistent attribute values which are kept in flash. If I make a bridged device which contains persistent clusters, does flash get cleaned up if I delete the bridged EP?  I have not tested this yet.

Probably should be part of your test suite to make sure that this stuff doesn't accumulate in flash.

**Comment by wqx6** [comment]
No. currently we don't clean the persistent attribute values after remove an endpoint, Thanks for the report! We will fix it ASAP.

**Comment by dhrishi** [comment]
This has been fixed with https://github.com/espressif/esp-matter/commit/98c6e8070b582c9b18058256f490e6b02a4264e1
