### ISSUE TITLE
Change Bridged Device Node Label (CON-836)

### ISSUE THREAD

**Issue by uni-uni-77** [espressif/esp-matter#687]
Hello.

According to 9.12.2 of the Matter-1.0-Core-Specification.pdf, it seems that each Bridged Device also has a NodeLabel.
My understanding is that the basic_information for root_node has a node_label attirubute, but the bridged_device_basic_information does not.

How can I change a node label of a Bridged Device?

Thank you.

**Comment by jonsmirl** [comment]
~~~
        cluster = cluster::get(endpoint, BridgedDeviceBasicInformation::Id);
        attribute = bridged_device_basic_information::attribute::create_node_label(cluster, label, strlen(label));
~~~

**Comment by uni-uni-77** [comment]
@jonsmirl Thank you for your prompt support!
