### ISSUE TITLE
Just pulled, light won't compile, ICD Manager (CON-838)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#689]
What is this?
~~~
e/jonsmirl/aosp/esp-matter/components/esp_matter/esp_matter_feature.cpp
/home/jonsmirl/aosp/esp-matter/components/esp_matter/esp_matter_feature.cpp: In function 'uint32_t esp_matter::cluster::on_off::feature::dead_front_behavior::get_id()':
/home/jonsmirl/aosp/esp-matter/components/esp_matter/esp_matter_feature.cpp:340:38: error: 'kDeadFrontBehavior' is not a member of 'chip::app::Clusters::OnOff::Feature'
  340 |     return (uint32_t)OnOff::Feature::kDeadFrontBehavior;
      |                                      ^~~~~~~~~~~~~~~~~~
[36/175] Building CXX object esp-idf/esp_matter/CMake...omeip/connect
~~~

**Comment by jonsmirl** [comment]
What is an ICD Manager and why does a light bulb need one?

**Comment by jonsmirl** [comment]
I've commended it out so that I can restart tests running on most up-to-date light code.

**Comment by wqx6** [comment]
Could you please update the submodule? We have update the connectedhomeip submodule recently. BTW, ICDManager is designed for Intermittently Connected Device(ICD) which is related to power save.

**Comment by ahmed8812** [comment]
@wqx6 

How to update the submodules safely?  I did try to update to update submodules (connectedhomeip) but something is not going right
Can you provide the command?

Thanks

**Comment by wqx6** [comment]
@ahmed8812 You can use these two commands:
```
git submodule sync --recursive
git submodule update --init --recursive
```

**Comment by jonsmirl** [comment]
This commit is not in the CHIP repo
~~~
jonsmirl@ares:~/aosp/esp-matter$ git submodule update --init --recursive
fatal: transport 'file' not allowed
fatal: Fetched in submodule path 'connectedhomeip/connectedhomeip', but it did not contain 699ff65e065a28e4b7ee3a2d84110444b1709040. Direct fetching of that commit failed.
fatal: 
~~~

**Comment by dhrishi** [comment]
@jonsmirl I am able to compile the light example. The CI runs the compilations for examples, before the code is pushed to Github. So, ideally it should work fine. Please close the issue if you are able to get it to work

**Comment by jonsmirl** [comment]
I fixed it now. I was looking in the wrong place. There was nothing wrong with esp-matter. The problem was that I forgot I put a log statement in the CHIP repo for the PACKET_BUFFER error. That change was preventing the CHIP tree from updating.  

Git generated an awful error message:
~~~
jonsmirl@ares:~/aosp/esp-matter$ git submodule update --init --recursive
fatal: transport 'file' not allowed
fatal: Fetched in submodule path 'connectedhomeip/connectedhomeip', but it did not contain 699ff65e065a28e4b7ee3a2d84110444b1709040. Direct fetching of that commit failed.
fatal:
~~~
