### ISSUE TITLE
How can I create a Matter project from scratch? (CON-844)

### ISSUE THREAD

**Issue by mohankrishkumare** [espressif/esp-matter#695]
How can I create a Matter project from scratch?

What is the proper way to create an ESP-Matter project from scratch?

**Comment by dhrishi** [comment]
@mohankrishkumare You can refer the [light example](https://github.com/espressif/esp-matter/blob/main/examples/light/main/app_main.cpp) as the starting point. Then replace the device type with the Matter device type you want to create. This can be followed by handling the events you want in the app_event_cb and your specific attributes in app_attribute_update_cb. Finally, if required, you can update/rewrite the driver for actually changing the hardware in case of any attribute changes. This can be done [here](https://github.com/espressif/esp-matter/blob/main/examples/light/main/app_driver.cpp). At the end, you can use the host-based chip-tool to test out the functionality.

You can follow the documentation: https://docs.espressif.com/projects/esp-matter/en/latest/esp32/developing.html
