### ISSUE TITLE
Can't build all_device_types_app successfully (CON-845)

### ISSUE THREAD

**Issue by tianrongqin** [espressif/esp-matter#696]
When I carry out "idf.py build" in the all_device_types_app,the error:
Executing action: all (aliases: build)
Running cmake in directory /home/tian/esp-matter/examples/all_device_types_app/build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DPYTHON=/home/tian/.espressif/python_env/idf5.2_py3.10_env/bin/python -DESP_PLATFORM=1 -DCCACHE_ENABLE=0 /home/tian/esp-matter/examples/all_device_types_app"...
CMake Error at CMakeLists.txt:6 (message):
  Please set ESP_MATTER_PATH to the path of esp-matter repo

-- Configuring incomplete, errors occurred!
cmake failed with exit code 1, output of the command is in the /home/tian/esp-matter/examples/all_device_types_app/build/log/idf_py_stderr_output_4201 and /home/tian/esp-matter/examples/all_device_types_app/build/log/idf_py_stdout_output_4201

**Comment by dhrishi** [comment]
@tianrongqin I am able to successfully build the all_device_types_app. ESP-IDF: v5.1.1 and esp-matter: `04c4676e1b41654b88840d70e1a4febb810d283f`

Can you confirm if you have executed `. ./export.sh` in the esp-matter directory that exports the ESP_MATTER_PATH?

For issues, please use the Github issue template and provide all the relevant information.
