### ISSUE TITLE
When I carry the "./install.sh" ,it can't generate the tool successfully (CON-851)

### ISSUE THREAD

**Issue by tianrongqin** [espressif/esp-matter#702]
When I execute in the esp material directory/ When install. sh, it will get stuck during the installation of the tool and automatically exit the terminal, causing me to not be able to generate the required chip tool and not be able to use it. How can I solve this situation? Previously, we followed the SDK operation on the official website. Could you please answer the following questions?

**Comment by tianrongqin** [comment]
Now when I implement "./install.sh" in esp-matter,it reported an error"gcc:not found".I also implement "sudo apt-get gcc",but it does not have any effect.

**Comment by tianrongqin** [comment]
Now the error:
Building host tools

Done. Made 7423 targets from 346 files in 688ms
ninja: Entering directory `/home/tianrq/esp-matter/connectedhomeip/connectedhomeip/out/host'
ninja: error: '../../third_party/nlunit-test/repo/src/nlunit-test.c', needed by 'obj/third_party/nlunit-test/repo/src/libnlunit-test.nlunit-test.c.o', missing and no known rule to make it

**Comment by jonsmirl** [comment]
Follow these instructions:
https://docs.espressif.com/projects/esp-matter/en/latest/esp32/developing.html#development-setup

**Comment by tianrongqin** [comment]
This is what I did, but it never worked.

**Comment by tianrongqin** [comment]
When I follow this operation, I get the following error:

Building host tools

Done. Made 7423 targets from 346 files in 553ms
ninja: Entering directory `/home/tianrq/esp-matter/connectedhomeip/connectedhomeip/out/host'
ninja: error: '../../third_party/nlunit-test/repo/src/nlunit-test.c', needed by 'obj/third_party/nlunit-test/repo/src/libnlunit-test.nlunit-test.c.o', missing and no known rule to make it

**Comment by jonsmirl** [comment]
I have those files.
~~~
jonsmirl@ares:~/aosp/esp-matter/connectedhomeip/connectedhomeip/third_party/nlunit-test/repo/src$ ls
Makefile.am  nltest.h       nlunit-test-config.h.in
Makefile.in  nlunit-test.c  nlunit-test.h
~~~

Check out the Chinese version of https://docs.espressif.com/projects/esp-matter/en/latest/esp32/developing.html#development-setup
If you are inside China you have to do special things because of the China firewall.
Espressif people will help with this on Monday when they are at work.

**Comment by wqx6** [comment]
Could you check the files under the directory `connectedhomeip/connectedhomeip/third_party/nlunit-test/repo/src`? Looks like the nlunit-test submodule is not cloned. Could you use the following commands to update the submodule?
```
git submodule sync --recursive
git submodule update --recursive --init
```

**Comment by dhrishi** [comment]
@tianrongqin Please close the issue if resolved

**Comment by dhrishi** [comment]
Closing this now
