### ISSUE TITLE
 不能正确下载子模组  Unable to download submodules correctly (CON-852)

### ISSUE THREAD

**Issue by tianrongqin** [espressif/esp-matter#703]
Whether I directly git the entire esp matter project or update the connected homeip after the git is completed, why is it always stuck in the same place and executed now/ Gn_ Build.sh is still stuck in third_ Party/silabs/gecko_ SDK, I have tried more than 10 times, but after deleting it, the GIT is stuck here again. How do I solve this situation?

**Comment by jonsmirl** [comment]
Follow these instructions:
https://docs.espressif.com/projects/esp-matter/en/latest/esp32/developing.html#development-setup

When you download the entire project you are downloading the setup for many different chip vendors. Sometimes the setups for the other vendors are broken. The instructions above only download the Espressif pieces.
