### ISSUE TITLE
No API to override command callback (CON-853)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#704]
Attributes have:
~~~
esp_err_t set_override_callback(attribute_t *attribute, callback_t callback)
~~~
There is no parallel API for commands.

When implementing a bridge you have to be able to override the commands too.

When fixing this, consider if you need two callbacks (original and override) or if the new callback could simply replace the old one saving memory. If you replace the old one be sure and cleanup all of the previously allocated memory.

**Comment by jonsmirl** [comment]
Temporarily, I used some casting to get to the callback
~~~
typedef struct _command {
    uint32_t command_id;
    uint16_t flags;
    command::callback_t callback;
    struct _command *next;
} _command2_t;

cluster = cluster::get(ep, OnOff::Id);
_command2_t *command = (_command2_t *)command::get(cluster, OnOff::Commands::Toggle::Id, COMMAND_FLAG_ACCEPTED);
command->callback = lp_command_callback_toggle;
~~~

**Comment by jonsmirl** [comment]
I created a PR to enable this behavior
https://github.com/espressif/esp-matter/pull/733

**Comment by dhrishi** [comment]
PR #734 is merged.
