### ISSUE TITLE
Failed to run  ./install.sh. (CON-858)

### ISSUE THREAD

**Issue by Zhentao-Lin** [espressif/esp-matter#709]
I run the git clone -- recursive https://github.com/espressif/esp-matter.git, without any error.
Next I execute "./install.sh" and compile the complete content as follows：

lin@lin-virtual-machine:~/esp/esp-matter$ ./install.sh

Running Matter Setup

Synchronizing submodule url for 'connectedhomeip/connectedhomeip'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/examples/common/QRCode/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/examples/common/m5stack-tft/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/asr/asr550x/asr_sdk'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/asr/asr582x/asr_sdk'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/asr/asr595x/asr_sdk'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/asr/components'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/boringssl/repo/src'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/bouffalolab/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/bouffalolab/repo/components'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/bouffalolab/repo/customer_app'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/bouffalolab/repo/docs'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/bouffalolab/repo/tools'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/cirque/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/editline/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/freertos/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/imgui/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/cyw30739_sdk/repos/30739A0'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/cyw30739_sdk/repos/CYW930739M2EVB-01'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/cyw30739_sdk/repos/btsdk-include'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/cyw30739_sdk/repos/btsdk-tools'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/TARGET_CY8CKIT-062S2-43012'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/abstraction-rtos'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/anycloud-ota'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/bluetooth-freertos'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/btstack'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/clib-support'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/connectivity-utilities'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/core-lib'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/core-make'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/freertos'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/kv-store'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/lwip'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/mbedtls'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/mtb-hal-cat1'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/mtb-pdl-cat1'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/psoc6cm0p'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/recipe-make-cat1a'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/retarget-io'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/secure-sockets'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/serial-flash'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/whd-bsp-integration'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/wifi-connection-manager'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/wifi-host-driver'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/infineon/psoc6/psoc6_sdk/libs/wifi-mw-core'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/jsoncpp/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/libwebsockets/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/cypress/libs/core-lib'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/cypress/libs/cy-mbedtls-acceleration'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/cypress/libs/mtb-pdl-cat1'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/cypress/libs/pdl/psoc6pdl'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/cypress/libs/psoc6hal'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/cypress/libs/retarget-io'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/asio/asio'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/bootloader/subproject/components/micro-ecc/micro-ecc'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/bt/controller/lib_esp32'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/bt/controller/lib_esp32c3_family'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/bt/host/nimble/nimble'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/cbor/tinycbor'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/cmock/CMock'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/cmock/CMock/vendor/c_exception'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/cmock/CMock/vendor/unity'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/coap/libcoap'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/coap/libcoap/ext/tinydtls'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/esp_phy/lib'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/esp_wifi/lib'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/esptool_py/esptool'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/expat/expat'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/ieee802154/lib'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/json/cJSON'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/libsodium/libsodium'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/lwip/lwip'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/mbedtls/mbedtls'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/mqtt/esp-mqtt'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/nghttp/nghttp2'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/nghttp/nghttp2/third-party/mruby'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/nghttp/nghttp2/third-party/neverbleed'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/openthread/lib'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/openthread/openthread'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/protobuf-c/protobuf-c'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/spiffs/spiffs'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/tinyusb/tinyusb'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/unity/unity'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/examples/build_system/cmake/import_lib/main/lib/tinyxml2'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/examples/peripherals/secure_element/atecc608_ecdsa/components/esp-cryptoauthlib'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/ext/cddl-gen'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-mcu-boot/repo/ext/mbedtls'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-os-cypress-capsense-button/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-os-posix-socket/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbed-os/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mbedtls/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mt793x_sdk/filogic'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mt793x_sdk/lwip'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/mt793x_sdk/mDNSResponder'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/nanopb/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/nlassert/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/nlio/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/nlunit-test/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/nxp/mw320_sdk/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/open-iot-sdk/sdk'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/open-iot-sdk/sdk/developer-tools'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-efr32'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-efr32/openthread'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-efr32/third_party/silabs/gecko_sdk'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-ifx'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-ifx/openthread'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-ifx/third_party/infineon/btsdk-include'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-ifx/third_party/infineon/btsdk-tools'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-ifx/third_party/infineon/platform/cyw30739/30739a0'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-ifx/third_party/infineon/platform/cyw30739/bsp/cyw930739m2evb-01/TARGET_CYW930739M2EVB-01'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-nxp'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-nxp/openthread'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-qorvo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-qorvo/openthread'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-qorvo/third_party/Qorvo/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-ti'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-ti/openthread'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-ti/third_party/freertos/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-ti/third_party/mbedtls/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/ot-ti/third_party/ti_simplelink_sdk/repo_cc13xx_cc26xx'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/openthread/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/ot-br-posix/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/ot-br-posix/repo/third_party/cJSON/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/ot-br-posix/repo/third_party/http-parser/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/ot-br-posix/repo/third_party/openthread/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/perfetto/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/pigweed/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/pybind11/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/qpg_sdk/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/silabs/gecko_sdk'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/silabs/matter_support'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/silabs/wifi_sdk'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/silabs/wiseconnect-wifi-bt-sdk'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/simw-top-mini/repo'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/st/STM32CubeWB'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/ti_simplelink_sdk/repo_cc13xx_cc26xx'
Synchronizing submodule url for 'connectedhomeip/connectedhomeip/third_party/ti_simplelink_sdk/repo_cc32xx'

  WELCOME TO...

         █
         █
     ▄   █   ▄                                █     █
     ▀▀█████▀▀      ▄▀▀▀▄ ▄▀▀▀▄    ▄▀▀▀▀▄█  ▀▀█▀▀▀▀▀█▀▀   ▄▀▀▀▀▄    ▄▀▀
   ▀█▄       ▄█▀   █     █     █  █      █    █     █    █▄▄▄▄▄▄█  █   
     ▀█▄   ▄█▀     █     █     █  █      █    █     █    █         █   
  ▄██▀▀█   █▀▀██▄  █     █     █   ▀▄▄▄▄▀█    ▀▄▄   ▀▄▄   ▀▄▄▄▄▀   █   
 ▀▀    █   █    ▀▀

  BOOTSTRAP! Bootstrap may take a few minutes; please be patient.

Downloading and installing packages into local source directory:

  Setting up CIPD package manager...Traceback (most recent call last):
  File "/home/lin/esp/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 974, in <module>
    sys.exit(main())
  File "/home/lin/esp/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 966, in main
    return EnvSetup(**vars(parse())).setup()
  File "/home/lin/esp/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 573, in setup
    result = step(spin)
  File "/home/lin/esp/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 667, in cipd
    cipd_client = cipd_wrapper.init(
  File "/home/lin/esp/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 378, in init
    bootstrap(client, silent, rosetta=rosetta)
  File "/home/lin/esp/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 328, in bootstrap
    tmp.write(client_bytes(rosetta))
  File "/home/lin/esp/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 252, in client_bytes
    conn.request('GET', path)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

**Comment by dhrishi** [comment]
>OSError: [Errno 101] Network is unreachable

@Zhentao-Lin Can you please check this: https://github.com/espressif/esp-matter/issues/64#issuecomment-1276962313. Looks like a setup issue. Please close if this is working fine now
