### ISSUE TITLE
Google sample app not working with esp-matter

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#71]
This is due to a Google update requiring that attestation work, and esp-matter is not implementing an attestation that Google will accept.
https://github.com/google-home/sample-app-for-matter-android/issues/29

Google has not implemented the  "allow uncertified device" popup like Apple has done.

I tried playing with the data provider options in menuconfig and could not come up with anything that works.
Devices made using Chef in CHIP do work. So whatever Chef is using for attestation should work in esp-matter.

**Comment by jonsmirl** [comment]
Moving esp-matter over to CHIP master will allow the devices to talk to Google Home again.

**Comment by dhrishi** [comment]
@jonsmirl Is this with the current connectedhomeip submodule `87bee4de25886ba00f1a177cd0f8791a48528a1f` ?

**Comment by jonsmirl** [comment]
I am randomly using  0bff5ad04c696626ce3aa8fcc5c9e229ed8bacf0.

But the problem was faad9e179293775110f09692cd1c28e0d71b792f

**Comment by jonsmirl** [comment]
```
commit faad9e179293775110f09692cd1c28e0d71b792f
Author: Evgeny Margolis <emargolis@google.com>
Date:   Wed Oct 5 10:09:59 2022 -0700

    Updated CSA Official CD Signing Certificates (#23027)
```

changes the CHIP certificates. This is a bit of a mess because some Google stuff is on the old certificates and some is on the new ones. They are working on sorting it out.
