### ISSUE TITLE
Are the nvs_keys and esp_secure_cert partitions required? (CON-866)

### ISSUE THREAD

**Issue by marciogranzotto** [espressif/esp-matter#716]
I have products that use ESP32 already in the field, and their partition table does not include the `nvs_keys` and `esp_secure_cert` partitions. Also my `nvs` partition is much smaller than the ones in the examples.

Are those partitions a hard requirement? I want to be able to provide an OTA upgrade to enable Matter over Wi-Fi, but I can't really change the partition table for those devices.

For reference, here's some of my partition tables:

4mb modules:
```
# Name,   Type, SubType, Offset,  Size
nvs,      data, nvs,     0x9000,  0x4000
otadata,  data, ota,     0xd000,  0x2000
phy_init, data, phy,     0xf000,  0x1000
factory,  0,    factory, 0x10000, 0xf0000
ota_0,    0,    ota_0,   0x100000,0x160000
ota_1,    0,    ota_1,   0x260000,0x160000
id,       0x40, 0,       0x3C0000,0xC000
db,       0x40, 0,       0x3CC000,0x20000
state,    0x40, 0,       0x3EC000,0x4000
coredump, data, coredump,0x3F0000,0x10000
```

8mb modules:
```
# Name,   Type, SubType, Offset,  Size
nvs,      data, nvs,     0x9000,  0x4000
otadata,  data, ota,     0xd000,  0x2000
phy_init, data, phy,     0xf000,  0x1000
factory,  0,    factory, 0x10000, 0x1f0000
ota_0,    0,    ota_0,   0x200000,0x260000
ota_1,    0,    ota_1,   0x460000,0x260000
id,       0x40, 0,       0x6C0000,0x10000
db,       0x40, 0,       0x6D0000,0x100000
state,    0x40, 0,       0x7D0000,0x20000
coredump, data, coredump,0x7F0000,0x10000
```

16mb modules:
```
nvs,      data, nvs,     0x9000,  0x4000
otadata,  data, ota,     0xd000,  0x2000
phy_init, data, phy,     0xf000,  0x1000
factory,  0,    factory, 0x10000, 0x2f0000
ota_0,    0,    ota_0,   0x300000,0x400000
ota_1,    0,    ota_1,   0x700000,0x400000
id,       0x40, 0,       0xB00000,0x10000
db,       0x40, 0,       0xB10000,0x400000
state,    0x40, 0,       0xF10000,0xE0000
coredump, data, coredump,0xFF0000,0x10000
```

**Comment by wqx6** [comment]
nvs_keys partition is used for [nvs_encryption](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/nvs_encryption.html), it can be removed if you are not using nvs_encryption.

esp_secure_cert is used to store the DAC cert&key and PAI cert for Matter [pre-provisioning](https://www.espressif.com/en/news/Pre-provisioning_Matter) modules. If you have other safe way to store the Matter Device Attestation certs&keys, you can remove the esp_secure_cert partition.

**Comment by dhrishi** [comment]
@marciogranzotto I would suggest you to go through the [Security section](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/security.html) in the esp-idf documentation to understand the best security practices. Please also check [Production Considerations section](https://docs.espressif.com/projects/esp-matter/en/latest/esp32/security.html) in the esp-matter documentation.

If the Wi-Fi credentials are in the default NVS partition, then we strongly recommend to enable NVS encryption.
