### ISSUE TITLE
Provisioning ESP32-C6 Matter Over Thread (CON-868)

### ISSUE THREAD

**Issue by baylf2000** [espressif/esp-matter#718]
I have a question regarding the provisioning process. If I have an ESP32-C6 and I want to use Matter over Thread, at the moment the provisioning process seems to use Matter over WiFi instead. Which part of the process is responsible for directing the C6 to use Thread instead of WiFi? Is it the C6 firmware? Or the provisioning software? Can I disable WiFi functionality in firmware to prevent the provisioner from using WiFi?

**Comment by dhrishi** [comment]
@baylf2000 The default light example uses Matter over Wi-Fi for ESP32-C6. You can change the firmware to use Matter over Thread instead by modifying a few menuconfig options as mentioned here https://docs.espressif.com/projects/esp-matter/en/latest/esp32c6/developing.html#flashing-the-firmware
