### ISSUE TITLE
Add ASSERT in esp-matter for setting CHIP_CONFIG_MAX_GROUP_ENDPOINTS_PER_FABRIC correctly (CON-880)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#724]
esp-matter should add a DEBUG assert such that as you instantiate GROUP clusters it makes sure that the number of GROUP you make is less than or equal to CHIP_CONFIG_MAX_GROUP_ENDPOINTS_PER_FABRIC. That way people will figure out they need to change this during development rather than after they ship.  How to change it: https://github.com/espressif/esp-matter/issues/707

This is especially a problem in bridges. Most bridged devices are going to have a GROUP cluster and CHIP_CONFIG_MAX_GROUP_ENDPOINTS_PER_FABRIC defaults to 1. It needs to be much higher in a bridge. Likely any device with more than one device endpoint needs to change this.

My keypads need this set at 20 to work right.

**Comment by shubhamdp** [comment]
@jonsmirl we are initializing the server with actual group endpoint count, changes are in https://github.com/espressif/esp-matter/commit/974997de95dba6478b56cfba40f71fd59e0ba06d
