### ISSUE TITLE
BLE GAP Name is not appearing when matter standard commissioning window is opened (CON-883)

### ISSUE THREAD

**Issue by aggaddam** [espressif/esp-matter#727]
**Describe the bug**
BLE GAP name i.e (MATTER-discriminator) doesn't appear with BLE adv scanner app(used nrf connect app) when the matter standard commissioning window is opened. I checked source code, It seems the source code is setting the BLE GAP name based on the SDK configuration. I am not sure why I am not able to see the GAP name for only esp matter devices 

Here is the SDK configuration 

![Screenshot from 2023-11-13 17-23-30](https://github.com/espressif/esp-matter/assets/94963960/f257de8b-9f7b-415e-82f7-0c151d7b1dc3)

**Environment**

- ESP-Matter Commit Id: https://github.com/espressif/esp-matter/commit/68e99de70266674ce172459136960bbb5c58dc0e
- ESP-IDF Commit Id: v5.1.1 Stable Release
- SoC (eg: ESP32 or ESP32-C3): ESP32-C3
- Device Logs (Please attach the log file): NA
- Host Machine OS: Ubuntu
- Commissioner app and versions if present:
- Commissioner's logs if present:

**Any additional details**

...

**Comment by dhrishi** [comment]
@aggaddam BLE Name is not added in the advertisement data and hence it is not seen. Although, it is present in the Device Name characteristic in the GAP service.
