### ISSUE TITLE
Factory reset only matter related data from nvs storage (CON-884)

### ISSUE THREAD

**Issue by damian-kurek-wizzdev** [espressif/esp-matter#728]
**Is your feature request related to a problem? Please describe.**
I need to factory reset the matter credentials but leave the rest of the data stored in NVS storage without change.
 **Describe the solution you'd like**

Function reset that removes all certificates without erasing the whole nvs partition.
**Describe alternatives you've considered**
Description of any alternative solutions or features you've considered.
No

**Additional context**
I have existing devices with partition table that I can not change. I have existing nvs storage that I'm using. I provide the same nvs for the matter and I can not erase everything.

**Comment by jonsmirl** [comment]
The matter NVS use is just standard key/value.  You can use this tool to dump the nvs partition and see what is going on.
https://github.com/AFontaine79/Espressif-NVS-Analyzer

Here is a dump of mine which is more complex than normal.
[matter.txt](https://github.com/espressif/esp-matter/files/13339991/matter.txt)
That analyzer tool is using Asian encodings, cat the file to your terminal or open in vscode and ignore the encoding.

**Comment by damian-kurek-wizzdev** [comment]
Factory reset works fine, I just had the same namespace in nvs config.  I patched this text and it works fine.
