### ISSUE TITLE
Water Content Measurement (CON-893)

### ISSUE THREAD

**Issue by goronlant** [espressif/esp-matter#737]
**Describe the question/query that you have**
Due to my personal project, I want to develop a soil moisture device for my plants. In the document "Matter 1.1 Application Cluster Specification" under 2.6. Water Content Measurement, it states that there should be a cluster called Soil Moisture Measurement with the identifier 0x0408. The issue is that it is not found anywhere in the code. Does the feature exist, or is it still to come?

If there are alternative ways to implement this, I would greatly appreciate it if you could provide that information.

Thanks in advance.

**Additional context**

I am uploading a screenshot from the document. 
<img width="701" alt="Bildschirmfoto 2023-11-16 um 10 10 08" src="https://github.com/espressif/esp-matter/assets/76524039/937ee2f2-87e9-42e6-975e-2e999625041c">

**Comment by PSONALl** [comment]
@goronlant This cluster is not yet implemented in esp-matter
I will add it soon

**Comment by goronlant** [comment]
Okay, thanks! Is it possible to implement it as a non-esp developer?

**Comment by goronlant** [comment]
Yeah, I've also raised that issue. This isn't ideal news for me since there's currently no alternative solution on the market besides Matter, which is compatible with all smart devices as well. Do you know if it is possible to implement this feature as a third-party provider?

**Comment by dhrishi** [comment]
I will close this here. You can track https://github.com/project-chip/connectedhomeip/issues/30508
