### ISSUE TITLE
How to Change Name or Set Name of Matter device in Espressif Mattter SDK?  (CON-898)

### ISSUE THREAD

**Issue by bilalmalik76** [espressif/esp-matter#739]
We want to change the name or set the name of our matter device. For example, if we are using light example available in Espressif Mattter SDK? and we want to change it name to something like company_name_light? How can we do it in Espressif Mattter SDK?

**Comment by jonsmirl** [comment]
https://github.com/espressif/esp-matter/tree/main/tools/mfg_tool

**Comment by wqx6** [comment]
Do you mean the name shown in iOS Apple home app when pairing the device? The Apple Home app will fetch the device name and device type from DCL MainNet. So you should firstly obtain the certificate and register your device on MainNet.

**Comment by dhrishi** [comment]
@bilalmalik76 Please provide the required inputs

**Comment by bilalmalik76** [comment]
@wqx6 Yes the name shown in iOS Apple home app when pairing the device.

**Comment by dhrishi** [comment]
> The Apple Home app will fetch the device name and device type from DCL MainNet. So you should firstly obtain the certificate and register your device on MainNet.

Then, the above is the answer. You need to certify your produce, and once done update the DCL with these details
