### ISSUE TITLE
Non-Volatile attributes and memory wear (CON-909)

### ISSUE THREAD

**Issue by PhLuReh** [espressif/esp-matter#750]
**Describe the question/query that you have**
I'm creating a WindowCovering device. The standard requires (for example) CurrentPositionLiftPercentage to be non-volatile (it has the N-quality). If you would think, this is an easy thing, because the current position may be stored in its mechanical position, I can tell you this is not always the fact. Conclusion for our device is to use non-volatile memory (as being implemented by the SDK).

My question is, addressing the memory wear in my application. Let's do some assumptions:
- 10 movements each day
- each movement is animated in at most 16 steps
- resulting in let's say at most 50000 steps - and therefore writes to the NVS - each year

How long would the memory be reliable without wear. Can you give a statement for the Matter implementation? Or is there a way around?

**Additional context**
The behaviour get tested in TC-WNCV-4.5 and therefore is crucial for certification. CSA only states, that up to now, the test has to be passed to get certification.

**Comment by jonsmirl** [comment]
I don't believe this has been implemented....
https://github.com/espressif/esp-matter/issues/131

**Comment by wqx6** [comment]
Thanks for the report! will fix it ASAP.

**Comment by igrr** [comment]
I can answer about this part

> resulting in let's say at most 50000 steps - and therefore writes to the NVS - each year
> How long would the memory be reliable without wear. Can you give a statement for the Matter implementation? Or is there a way around?

from NVS perspective.

This would result, worst case, in 198 erase cycles per flash page. Given typical NOR Flash memory longevity of >10000 erase cycles per page, this should be enough for 50 years of operation.

**Comment by PhLuReh** [comment]
Nice, thanks for this answer. So we get a fix and it's not a problem for 50years of operation. That sounds like a good solution!

**Comment by igrr** [comment]
@wqx6 just one thing, could you  confirm that one attribute write in Matter translates to one `nvs_set_u32` or similar call (with an integer type)? If `nvs_set_blob` is used, flash wear will actually be larger due to the extra metadata used to store blobs in NVS?

**Comment by wqx6** [comment]
For esp-matter of old version, it used `nvs_set_blob`. But this commit https://github.com/espressif/esp-matter/commit/ef2c3e4d8bdb307803218db41294c158f6734ddd introduced a Kconfig option `ESP_MATTER_NVS_USE_COMPACT_ATTR_STORAGE`,  and the device will call `nvs_set_u32` to set the value of unsigned/signed integer if the Kconfig option is enabled.

**Comment by igrr** [comment]
I guess the question is whether this Kconfig option is easy to discover. The user would need to first realize that there is such a potential issue (extensive flash wear), then look for possible solutions, and stumble upon this issue or the mention in the Kconfig help. I'm afraid some users might not consider this problem in the first place, and when the product is already in the field it would be too late to change the setting.

Perhaps, if I may suggest, a different solution would work better? esp-matter would use integer types primarily, but if the integer value is not found, it will check for the value in blob format. If there is, the value will be read and saved again as integers. This will automatically "upgrade" existing projects in a backwards-compatible manner. New users won't have the risk that they ship a product with the default setting of the option.

**Comment by jonsmirl** [comment]
@wqx6  Espressif needs to implement the stuff Boris pointed on in https://github.com/espressif/esp-matter/issues/131
This problem is much worse with lights.

**Comment by shubhamdp** [comment]
@jonsmirl @PhLuReh we've added the support for deferred attributes in https://github.com/espressif/esp-matter/commit/80a0868271965e1959bf9ffc7743a2380f0f86aa. This issue can be closed now.

**Comment by dhrishi** [comment]
Closing this now
