### ISSUE TITLE
There is a problem with the 'light_switch' example (CON-910)

### ISSUE THREAD

**Issue by mohankrishkumare** [espressif/esp-matter#751]
**Describe the bug**
There is a problem with the 'light_switch' example. It shows 'Not Supported' in Apple's Home app after adding the accessory.
![IMG_9880](https://github.com/espressif/esp-matter/assets/121080249/646cac1f-288d-4264-b342-5214e49cdb74)

But, the 'light' example is working fine.

**Environment**
- ESP-Matter Commit Id: 79dfcc7b9db37d80105e2bbb39a680a0670296d5
- ESP-IDF Commit Id: e088c3766ba440e72268b458a68f27b6e7d63986
- SoC (eg: ESP32 or ESP32-C3): ESP32-C3
- Device Logs (Please attach the log file): [log.txt](https://github.com/espressif/esp-matter/files/13440669/log.txt)
- Host Machine OS: Ubuntu 22.04.3 LTS
- Commissioner app and versions if present: 
- Commissioner's logs if present: 

**Any additional details**
...

**Comment by mohankrishkumare** [comment]
iPadOS Version: 16.7.2

**Comment by dhrishi** [comment]
@mohankrishkumare Light switch, that has a cluster client, is not supported in the Ecosystem apps. It can commission the device, but cannot recognize the device type. As a result, what you are seeing is expected.

**Comment by mohankrishkumare** [comment]
How to implement the 'Retro Fit Switch' (GPIO) in ESP ZeroCode?
