### ISSUE TITLE
ESP RainMaker Required hub to Commission and Control Matter Devices?  (CON-927)

### ISSUE THREAD

**Issue by bilalmalik76** [espressif/esp-matter#767]
If we use ESP RainMaker Matter, do we need any hub to commission and control Matter devices using the ESP RainMaker app? If a hub is required in any case, is there any way to use only one hub which works with both Android and iOS smartphones? Currently, if we use an iPhone we need to have Apple compatible hub and for Andriod Google compatible hub is required.

**Comment by wangwenxue1989** [comment]
Does ESP RainMaker Android app support light switch matter devices  now？

And，I run the matter+rainmaker example，how to add device in Rainmaker app？
