### ISSUE TITLE
ImportError: cannot import name 'OneStyleAndTextTuple' from 'prompt_toolkit.formatted_text (CON-933)

### ISSUE THREAD

**Issue by mertmzk** [espressif/esp-matter#772]
Hello followed the instruction from the website: https://docs.espressif.com/projects/esp-matter/en/latest/esp32/developing.html#development-setup

and when installing to matter getting this error. Any idea how this could be fixed.

**Environment**
- ESP-Matter Commit Id: 72b0f2632690c4b2917e6ae7b359297f593da1cb
- ESP-IDF Commit Id: 6b1f40b9bfb91ec82fab4a60e5bfb4ca0c9b062f
- SoC ESP32
- Device Logs (Please attach the log file):
- Host Machine OS: MAC 13.3.1

Thanks

**Comment by mertmzk** [comment]
Fix:

![image](https://github.com/espressif/esp-matter/assets/25204506/8a6f7f2a-7ce6-4639-b9bc-bf9ae5b17072)

**Comment by dhrishi** [comment]
Fixed with the latest main branch
