### ISSUE TITLE
Room Air Conditioner Example Shows 'Not Supported' in Apple Home (CON-936)

### ISSUE THREAD

**Issue by mriksman** [espressif/esp-matter#775]
**Describe the bug**
I downloaded the `room_air_conditioner` example and added it to Apple Home. However, it just shows up as 'Not Supported'.

iOS 17.2
HomePod 17.2
ESP32-Pico-D4-DevKit

**Environment**
- ESP-Matter Commit Id: `72b0f2632690c4b2917e6ae7b359297f593da1cb`
- ESP-IDF Commit Id: `6b1f40b9b`
- SoC (eg: ESP32 or ESP32-C3): ESP32-Pico-D4
- Device Logs (Please attach the log file): Attached
- Host Machine OS: Ubuntu/Linux
- Commissioner app and versions if present:
- Commissioner's logs if present:

[AirConLog.txt](https://github.com/espressif/esp-matter/files/13694997/AirConLog.txt)
![IMG_9890](https://github.com/espressif/esp-matter/assets/20112339/bfa11432-f11c-45fe-8abc-4250789394d7)

**Comment by mriksman** [comment]
I just realised this example is for the new 'Room Air Conditioner' appliance in Matter 1.2 which hasn't been included in Apple yet.

**Comment by anuarrozman** [comment]
@mriksman  Hii, Sorry but can you share where you get the information about your statement ? Thank you!!

**Comment by mriksman** [comment]
@anuarrozman 
A quick Google has many articles talking about the release of Matter 1.2 on 23 October 2023
https://csa-iot.org/newsroom/matter-1-2-arrives-with-nine-new-device-types-improvements-across-the-board/

> Room Air Conditioners – While HVAC and thermostats were already part of Matter 1.0, standalone Room Air Conditioners with temperature and fan mode control are now supported.

I imagine Apple haven't updated their platform in such a short period of time; so for now you either must use a HVAC or Thermostat endpoint, or wait until Apple supports Matter 1.2.

**Comment by anuarrozman** [comment]
Thanks @mriksman . I read the Matter 1.2 too but can't find any information about Apple haven't update their platform to support room air conditioner yet.
