### ISSUE TITLE
Adding an event for BLE deinit (DeviceEventType) (CON-938)

### ISSUE THREAD

**Issue by law-ko** [espressif/esp-matter#777]
In current `esp_matter_core.cpp` there are several `DeviceEventType` events posted to `static void app_event_cb(const ChipDeviceEvent *event, intptr_t arg)`. Is there any chance to post events for BLE deinitialzed when the RAM is freed? 

Maybe [`kCHIPoBLEConnectionClosed`](https://github.com/project-chip/connectedhomeip/blob/7cbac9130d2b10d6bfdba873129dfbffa294cf8d/src/include/platform/CHIPDeviceEvent.h#L169C5-L169C30) or [`kCloseAllBleConnections`](https://github.com/project-chip/connectedhomeip/blob/7cbac9130d2b10d6bfdba873129dfbffa294cf8d/src/include/platform/CHIPDeviceEvent.h#L175C11-L175C11)

**Comment by shubhamdp** [comment]
@law-ko `kCHIPoBLEConnectionClosed` and `kCloseAllBleConnections` are defined for different purpose and can not be used. We can add a different one though.
```
    /** Signals that BLE is deinitialized and heap memory is reclaimed */
    kBLEDeinitialized,
```

**Comment by law-ko** [comment]
@shubhamdp Thank you for the response. Is this available with a patch or do we need to wait for your implementation?

**Comment by shubhamdp** [comment]
@law-ko this is not available right now, but I'll upload patch here till this gets merged and updated on github

**Comment by shubhamdp** [comment]
@law-ko please see if the attached patch works for you [0001-Added-an-event-when-BLE-is-deinitialized-and-memory-patch.txt](https://github.com/espressif/esp-matter/files/13714353/0001-Added-an-event-when-BLE-is-deinitialized-and-memory-patch.txt)

**Comment by law-ko** [comment]
@shubhamdp I believe it is working. Thank you

**Comment by shubhamdp** [comment]
@law-ko patch is merged in main branch
