### ISSUE TITLE
Can not commision ESP32C6 with thread (CON-940)

### ISSUE THREAD

**Issue by johnvigg** [espressif/esp-matter#779]
**Describe the bug**
I followed the guide line by line and since I wanted to connect the esp32c6 with the lighting example using thread, I changed the 3 values using menuconfig. When I run the setup and try to pair, it gives an error. I have tried the same set up with wifi and it works, and I have tried using a silicon labs chip with my setup using thread, which also worked, but I am not able to get it running on the esp32c6. If anyone has tried this setup and it has worked, please guide me...

**Environment**
- ESP-Matter Commit Id:f5a314a486e3f9b5cf71f48165cd44365de719cd (should be the latest one)
- ESP-IDF Commit Id: b1f40b9bfb91ec82fab4a60e5bfb4ca0c9b062f (latest as well) 
- SoC (eg: ESP32 or ESP32-C3): ESP32c6
- Device Logs (Please attach the log file):
[log.light.20231220013027.txt](https://github.com/espressif/esp-matter/files/13720547/log.light.20231220013027.txt)

- Host Machine OS: Ubuntu 22.04.3 LTS
- Commissioner app and versions if present: -
- Commissioner's logs if present: 
[screen.log](https://github.com/espressif/esp-matter/files/13720675/screen.log)
**Any additional details**

Error at which the commissioning fails

`1703181483.991791][1786:1788] CHIP:CTL: Error on commissioning step 'ThreadNetworkSetup': 'src/controller/CHIPDeviceController.cpp:2285: CHIP Error 0x000000AC: Internal error'
`

A quick update - 
I setup a esp32c6 as a thread border router this time and connected the two silicon lab boards(EFR32MG24) as matter end devices using thread. Just to clarify I am running CHIP on an rpi4 and using that to provision and control. With this setup I am able to control the esp32c6 using wifi but not using thread.
I made the three changes mentioned in the guide but, still gives an error. Is there anything else that I have to modify for it to work?

**Comment by wqx6** [comment]
There is a BLE-15.4 co-exist issue for ESP32-C6 on the IDF commit you are using, and it should be fix in tag v5.1.2. Could you switch the IDF version to v5.1.2 and try again?

**Comment by johnvigg** [comment]
> There is a BLE-15.4 co-exist issue for ESP32-C6 on the IDF commit you are using, and it should be fix in tag v5.1.2. Could you switch the IDF version to v5.1.2 and try again?

Hey, I changed to the version you mentioned, and I am now able to commission and everything works. Thank you for your help! I  will close this issue now.
