### ISSUE TITLE
Apple Home cannot recognize the device (CON-944)

### ISSUE THREAD

**Issue by itatboy** [espressif/esp-matter#781]
**Describe the bug**
I compiled the example firmware to esp32c2 using the following steps, but the device cannot be detected within Apple Home

cd esp-matter/examples/light_switch
idf.py set-target esp32c2
idf.py build
idf.py -p /dev/ttyUSB0 erase_flash
idf.py -p /dev/ttyUSB0 flash monitor

**Environment**
- ESP-Matter Commit Id:
- ESP-IDF Commit Id:
- SoC (eg: ESP32 or ESP32-C3): ESP32-C2

- Device Logs (Please attach the log file):

[20:22:54.309]收←◆ESP-ROM:esp8684-api2-20220127
Build:Jan 27 2022
rst:0x1 (POWERON),boot:0xc (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd5c80,len:0x16bc
load:0x403acb70,len:0x974
load:0x403aeb70,len:0x2860
entry 0x403acb70
[0;32mI (21) boot: ESP-IDF v5.1.1 2nd stage bootloader[0m
[0;32mI (21) boot: compile time Dec 28 2023 12:09:40[0m
[0;32mI (21) boot: chip revision: v1.0[0m
[0;32mI (24) boot.esp32c2: MMU Page Size  : 64K[0m
[0;32mI (29) boot.esp32c2: SPI Speed      : 60MHz[0m
[0;32mI (33) boot.esp32c2: SPI Mode       : DIO[0m
[0;32mI (38) boot.esp32c2: SPI Flash Size : 4MB[0m
[0;32mI (43) boot: Enabling RNG early entropy source...[0m
[0;32mI (48) boot: Partition Table:[0m
[0;32mI (52) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (59) boot:  0 esp_secure_cert  unknown          3f 06 0000d000 00002000[0m
[0;32mI (67) boot:  1 nvs              WiFi data        01 02 00010000 0000c000[0m
[0;32mI (74) boot:  2 nvs_keys         NVS keys         01 04 0001c000 00001000[0m
[0;32mI (81) boot:  3 otadata          OTA data         01 00 0001d000 00002000[0m
[0;32mI (89) boot:  4 phy_init         RF data          01 01 0001f000 00001000[0m
[0;32mI (96) boot:  5 ota_0            OTA app          00 10 00020000 001e0000[0m
[0;32mI (104) boot:  6 ota_1            OTA app          00 11 00200000 001e0000[0m
[0;32mI (111) boot:  7 fctry            WiFi data        01 02 003e0000 00006000[0m
[0;32mI (119) boot: End of partition table[0m
[0;32mI (123) esp_image: segment 0: paddr=00020020 vaddr=3c0e0020 size=333b8h (209848) map[0m

[20:22:54.587]收←◆[0;32mI (180) esp_image: segment 1: paddr=000533e0 vaddr=3fca74e0 size=02084h (  8324) load[0m
[0;32mI (183) esp_image: segment 2: paddr=0005546c vaddr=40380000 size=074d4h ( 29908) load[0m
[0;32mI (194) esp_image: segment 3: paddr=0005c948 vaddr=00000000 size=036d0h ( 14032) [0m
[0;32mI (197) esp_image: segment 4: paddr=00060020 vaddr=42000020 size=de6c4h (911044) map[0m

[20:22:54.947]收←◆[0;32mI (414) boot: Loaded app from partition at offset 0x20000[0m
[0;32mI (415) boot: Disabling RNG early entropy source...[0m
[0;32mI (426) cpu_start: Unicore app[0m
[0;32mI (427) cpu_start: Pro cpu up.[0m
[0;32mI (435) cpu_start: Pro cpu start user code[0m
[0;32mI (435) cpu_start: cpu freq: 120000000 Hz[0m
[0;32mI (435) cpu_start: Application information:[0m
[0;32mI (438) cpu_start: Project name:     light_switch[0m
[0;32mI (444) cpu_start: App version:      1.0[0m
[0;32mI (448) cpu_start: Compile time:     Dec 28 2023 12:09:32[0m
[0;32mI (454) cpu_start: ELF file SHA256:  b1a9a38f9490e373...[0m
[0;32mI (460) cpu_start: ESP-IDF:          v5.1.1[0m
[0;32mI (465) cpu_start: Min chip rev:     v1.0[0m
[0;32mI (470) cpu_start: Max chip rev:     v2.99 [0m
[0;32mI (475) cpu_start: Chip rev:         v1.0[0m
[0;32mI (480) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (487) heap_init: At 3FCB75E0 len 00025590 (149 KiB): D/IRAM[0m
[0;32mI (493) heap_init: At 3FCDCB70 len 0000294C (10 KiB): STACK/DRAM[0m
[0;32mI (501) spi_flash: detected chip: gd[0m
[0;32mI (504) spi_flash: flash io: dio[0m
[0;32mI (510) sleep: Configure to isolate all GPIO pins in sleep state[0m
[0;32mI (515) sleep: Enable automatic switching of GPIO sleep configuration[0m
[0;32mI (522) app_start: Starting scheduler on CPU0[0m
[0;32mI (527) main_task: Started on CPU0[0m
[0;32mI (531) main_task: Calling app_main()[0m

[20:22:55.185]收←◆[0;32mI (568) app_main: Switch created with endpoint_id 1[0m
[0;32mI (569) app_main: Temperature sensor created with endpoint_id 1[0m
[0;33mW (570) vfs: esp_vfs_register_fd_range is successful for range <59; 64) and VFS ID 2[0m
[0;32mI (580) pp: pp rom version: de8c800[0m
[0;32mI (583) net80211: net80211 rom version: de8c800[0m
I (589) wifi:wifi driver task: 3fcbfc98, prio:23, stack:3072, core=0
I (597) wifi:wifi firmware version: ce9244d
I (597) wifi:wifi certification version: v7.0
I (602) wifi:config NVS flash: enabled
I (605) wifi:config nano formating: enabled
I (609) wifi:Init data frame dynamic rx buffer num: 6
I (614) wifi:Init management frame dynamic rx buffer num: 6
I (619) wifi:Init management short buffer num: 32
I (623) wifi:Init dynamic tx buffer num: 6
I (627) wifi:Init static tx FG buffer num: 2
I (631) wifi:Init static rx buffer size: 1600
I (635) wifi:Init static rx buffer num: 3
I (639) wifi:Init dynamic rx buffer num: 6
[0;32mI (644) wifi_init: rx ba win: 6[0m
[0;32mI (647) wifi_init: tcpip mbox: 16[0m
[0;32mI (651) wifi_init: udp mbox: 6[0m
[0;32mI (654) wifi_init: tcp mbox: 6[0m
[0;32mI (658) wifi_init: tcp tx win: 4096[0m
[0;32mI (662) wifi_init: tcp rx win: 2440[0m
[0;32mI (666) wifi_init: tcp mss: 1440[0m
[0;32mI (682) chip[DL]: NVS set: chip-counters/reboot-count = 15 (0xF)[0m
[0;32mI (687) chip[DL]: Real time clock set to ld (0001/946684800/00 100:00:01 UTC)[0m
[0;32mI (689) phy_init: phy_version 240,764b29e,Jun  9 2023,19:21:12[0m

[20:22:55.438]收←◆[0;32mI (733) phy: libbtbb version: c8b653e, Jun  9 2023, 19:21:28[0m
controller lib commit: [77e7dbb]
controller rom commit: [3314f9d]
[0;32mI (738) NimBLE: GAP procedure initiated: stop advertising.
[0m
[0;32mI (741) NimBLE: Failed to restore IRKs from store; status=8
[0m
[0;32mI (747) CHIP[DL]: BLE host-controller synced[0m

[20:22:56.238]收←◆[0;32mI (1252) chip[DL]: Configuring CHIPoBLE advertising (interval 25 ms, connectable)[0m
[0;32mI (1253) NimBLE: GAP procedure initiated: advertise; [0m
[0;32mI (1255) NimBLE: disc_mode=2[0m
[0;32mI (1259) NimBLE:  adv_channel_map=0 own_addr_type=1 adv_filter_policy=0 adv_itvl_min=40 adv_itvl_max=40[0m
[0;32mI (1269) NimBLE: 
[0m
[0;32mI (1272) chip[DL]: CHIPoBLE advertising started[0m
[0;32mI (1277) chip[DL]: Starting ESP WiFi layer[0m
I (1283) wifi:mode : sta (08:3a:8d:40:54:bc)
I (1286) wifi:enable tsf
W (1289) wifi:Haven't to connect to a suitable AP now!
[0;32mI (1293) chip[DL]: Done driving station state, nothing else to do...[0m
chan:1,max_power:80
chan:2,max_power:80
chan:3,max_power:80
chan:4,max_power:80
chan:5,max_power:80
chan:6,max_power:80
chan:7,max_power:80
chan:8,max_power:80
chan:9,max_power:80
chan:10,max_power:80
chan:11,max_power:80
chan:12,max_power:80
chan:13,max_power:80
chan:14,max_power:80
W (1326) wifi:Haven't to connect to a suitable AP now!
[0;32mI (1331) chip[DL]: Done driving station state, nothing else to do...[0m
[0;32mI (1338) chip[SVR]: Initializing subscription resumption storage...[0m
[0;32mI (1348) chip[SVR]: Server initializing...[0m
[0;32mI (1351) chip[TS]: Last Known Good Time: 2023-10-14T01:16:48[0m
[0;32mI (1356) chip[DMG]: AccessControl: initializing[0m
[0;32mI (1361) chip[DMG]: Examples::AccessControlDelegate::Init[0m
[0;32mI (1367) chip[DMG]: AccessControl: setting[0m
[0;32mI (1372) chip[DMG]: DefaultAclStorage: initializing[0m
[0;32mI (1377) chip[DMG]: DefaultAclStorage: 0 entries loaded[0m
[0;32mI (1402) chip[ZCL]: Using ZAP configuration...[0m
[0;32mI (1402) esp_matter_cluster: Cluster plugin init common callback[0m
[0;32mI (1403) chip[DMG]: AccessControlCluster: initializing[0m
[0;32mI (1409) chip[ZCL]: 0x3c0e73f8ep 0 clus 0x0000_0030 attr 0x0000_0000 not supported[0m
[0;32mI (1417) chip[ZCL]: Initiating Admin Commissioning cluster.[0m
[0;32mI (1426) chip[DIS]: Updating services using commissioning mode 1[0m
[0;32mI (1431) chip[DIS]: CHIP minimal mDNS started advertising.[0m
[0;32mI (1437) chip[DIS]: Advertise commission parameter vendorID=65521 productID=32768 discriminator=3840/15 cm=1[0m
[0;32mI (1447) chip[DIS]: CHIP minimal mDNS configured as 'Commissionable node device'; instance name: 6EF2947EEC46F243.[0m
[0;32mI (1457) chip[DIS]: mDNS service published: _matterc._udp[0m
[0;32mI (1464) chip[IN]: CASE Server enabling CASE session setups[0m
[0;32mI (1471) chip[SVR]: Joining Multicast groups[0m
[0;32mI (1475) chip[SVR]: Server Listening...[0m
[0;32mI (1480) esp_matter_core: Dynamic endpoint 0 added[0m
[0;32mI (1486) esp_matter_attribute: ********** W : Endpoint 0x0001's Cluster 0x00000003's Attribute 0x00000001 is hu **********[0m
[0;32mI (1497) esp_matter_attribute: ********** W : Endpoint 0x0001's Cluster 0x00000004's Attribute 0x00000000 is hu **********[0m
[0;32mI (1508) esp_matter_attribute: ********** W : Endpoint 0x0001's Cluster 0x00000004's Attribute 0x0000FFFC is <invalid type: 0> **********[0m
[0;32mI (1521) esp_matter_attribute: ********** R : Endpoint 0x0001's Cluster 0x00000006's Attribute 0x0000FFFC is 1 **********[0m
[0;32mI (1533) esp_matter_attribute: ********** R : Endpoint 0x0001's Cluster 0x00000006's Attribute 0x00004003 is hu **********[0m
[0;32mI (1545) esp_matter_attribute: ********** R : Endpoint 0x0001's Cluster 0x00000006's Attribute 0x00000000 is 0 **********[0m
[0;32mI (1556) esp_matter_attribute: ********** R : Endpoint 0x0001's Cluster 0x00000006's Attribute 0x00000000 is 0 **********[0m
[0;32mI (1568) chip[ZCL]: Endpoint 1 On/off already set to new value[0m
[0;32mI (1574) esp_matter_core: Dynamic endpoint 1 added[0m
[0;32mI (1581) esp_matter_attribute: ********** W : Endpoint 0x0002's Cluster 0x00000003's Attribute 0x00000001 is hu **********[0m
[0;32mI (1592) esp_matter_core: Dynamic endpoint 2 added[0m
[0;32mI (1599) chip[DL]: WIFI_EVENT_STA_START[0m
chan:1,max_power:80
chan:2,max_power:80
chan:3,max_power:80
chan:4,max_power:80
chan:5,max_power:80
chan:6,max_power:80
chan:7,max_power:80
chan:8,max_power:80
chan:9,max_power:80
chan:10,max_power:80
chan:11,max_power:80
chan:12,max_power:80
chan:13,max_power:80
chan:14,max_power:80
W (1627) wifi:Haven't to connect to a suitable AP now!
[0;32mI (1632) chip[DL]: Done driving station state, nothing else to do...[0m
[0;32mI (1640) chip[DL]: Configuring CHIPoBLE advertising (interval 25 ms, connectable)[0m
[0;32mI (1647) chip[DL]: Device already advertising, stop active advertisement and restart[0m
[0;32mI (1656) NimBLE: GAP procedure initiated: stop advertising.
[0m
[0;32mI (1663) NimBLE: GAP procedure initiated: advertise; [0m
[0;32mI (1668) NimBLE: disc_mode=2[0m
[0;32mI (1672) NimBLE:  adv_channel_map=0 own_addr_type=1 adv_filter_policy=0 adv_itvl_min=40 adv_itvl_max=40[0m
[0;32mI (1682) NimBLE: 
[0m
[0;32mI (1685) app_main: Commissioning window opened[0m
[0;32mI (1691) main_task: Returned from app_main()[0m

- Host Machine OS:Ubuntu20.04 server
- Commissioner app and versions if present:
- Commissioner's logs if present:

**Any additional details**
...

**Comment by itatboy** [comment]
In addition, there is a strange phenomenon: when executing idf.py - p/dev/ttyUSB0 flash monitor, the monitored startup log is garbled. The serial port assistant is used, and the device baud rate is set to 76800 to obtain the above device logs normally.

I hope you can provide some ideas to solve the problem. Thank you very much

Sdkconfig is attached

![image](https://github.com/espressif/esp-matter/assets/92285852/e17de57f-099e-4f06-9e3f-762d28b4a3c8)
[sdkconfig.log](https://github.com/espressif/esp-matter/files/13787017/sdkconfig.log)

**Comment by shubhamdp** [comment]
@itatboy light_switch won't appear in the Apple Home as it contains client clusters. The devices containing the server clusters will appear in there. Try generic_switch or light if you want the device be controllable from Home app.

**Comment by itatboy** [comment]
@shubhamdp 
Thank you for your reply. I am using the same instance project light_ Switch, only make the following changes:
Idf.py set target esp32c3
The remaining steps remain unchanged, and the compilation is successfully burned to the ESP32C3 development board. Apple Home can detect the device normally and correctly add it to Home.
I am puzzled why this situation occurs. Is it not compatible with ESP32C2? I am using the ESP8684 devkitc-02 development board

**Comment by itatboy** [comment]
Good, according to your prompt, Apple Home is now able to add accessories smoothly. Thank you. My understanding of esp matter is still far from sufficient, and this should not have been a problem. Can you help me close this issue? Thank you
