### ISSUE TITLE
Fan Control Cluster::PercentSetting attribute doesn't work in iOS Home App (CON-950)

### ISSUE THREAD

**Issue by adailydose** [espressif/esp-matter#787]
**Describe the question/query that you have**
Does anyone know if fan_control.percent_setting is supported in the iOS Home app? Or have any suggestions on how to find out?

I setup a ESP32 with fan control, and I can see and adjust the fan percentage in the Google Home app, but only see ON/OFF control in the iOS Home app.

**Additional context**
I raised the question in the Apple Developer forum as well.

**Comment by shripad621git** [comment]
@adailydose , Please specify the following details:
1.esp-matter commit id
2.esp-idf version used
3.iOS Home app version

**Comment by shripad621git** [comment]
@adailydose, I have tried the `fan control` on` esp-matter latest main branch.`
`esp-matter Commit id:` 2f692ac10a09ed27c223499ecdc458f7730d544d
Application Used: all-clusters-app  
Command to create fan device : `create --device_type=fan` (in console)
`HomePod Version:` 17.2 
`iOS version`: 
The `PercentSetting` attribute worked fine on the homepod.
The screenshots are attached below:
![IMG_0030](https://github.com/espressif/esp-matter/assets/79364691/8f5a0d1f-8cc8-4d8f-866c-6cf9c2e58423)
![IMG_0029](https://github.com/espressif/esp-matter/assets/79364691/4042be4a-419d-44b6-ba66-0be8a86b83ed)

**Comment by adailydose** [comment]
Hi @shripad621git, looks like this works after I update and restart my Apple TV to the latest version. Thank you!

**Comment by adailydose** [comment]
Hi @shripad621git, looks like this works after I update and restart my Apple TV to the latest version. Thank you!
