### ISSUE TITLE
Unable to find the configration code with matter (CON-952)

### ISSUE THREAD

**Issue by Whiteliondnd8** [espressif/esp-matter#789]
**Describe the question/query that you have**
I am encountering an issue with testing my project developed using the ESP-Matter SDK in conjunction with Alexa. Specifically, I am unable to find any configuration code or barcode that is typically required for integrating and testing with Alexa. Could someone guide me on how to properly set up and test my ESP-Matter SDK project with Alexa, or provide insights on where to find the necessary configuration details and barcode?

**Additional context**

...

**Comment by jonsmirl** [comment]
It is in the manual
https://docs.espressif.com/projects/esp-matter/en/latest/esp32/developing.html#commissioning-and-control

**Comment by Whiteliondnd8** [comment]
If i costomized matter light example code then how can i test

**Comment by shubhamdp** [comment]
@Whiteliondnd8 please take a look at [production consideration guide](https://docs.espressif.com/projects/esp-matter/en/latest/esp32/production.html).

**Comment by dhrishi** [comment]
Closing this now. Ideally, you should be able to create a custom QR code using the documentation
