### ISSUE TITLE
ESP Matter Non-ZAP Door Lock Example (CON-953)

### ISSUE THREAD

**Issue by bilalmalik76** [espressif/esp-matter#790]
Do you have any ESP Matter Non-ZAP based Door Lock Example?

**Comment by shubhamdp** [comment]
@bilalmalik76 you can take a look at https://docs.espressif.com/projects/esp-matter/en/latest/esp32/developing.html#developing-your-product.

You can also take a look at [all-device-type](https://github.com/espressif/esp-matter/tree/main/examples/all_device_types_app) example. This has the door-lock.

**Comment by bilalmalik76** [comment]
@shubhamdp I already tried this example and able to commission with Apple home app but get this error when send lock and unlock command from home app and state does not change at all:
![image](https://github.com/espressif/esp-matter/assets/9848328/1f860b1c-5085-4ccc-8e04-6319521e9147)

**Comment by VaishaliAvhale** [comment]
@bilalmalik76 We are looking into the problem and will drop an update here soon.

**Comment by shubhamdp** [comment]
@bilalmalik76 Please take a look at https://github.com/espressif/esp-matter/issues/176

You will need to implement few APIs in order to get the door lock working and that is discussed in that issue.

**Comment by dhrishi** [comment]
Closing as the resolution is provided
