### ISSUE TITLE
BLE active during WIFI login (CON-962)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#795]
The reliability of WIFI login can be increased by turning BLE off until the WIFI login is established.
So if USE_BLE_ONLY_FOR_COMMISSIONING=N, still turn off BLE until the WIFI connection is established.

BLE and WIFI are sharing the radio. Turning BLE off lets WIFI have exclusive access to the radio during session establishment.

**Comment by dhrishi** [comment]
I understand the purpose here. Although, the Matter SDK currently implements the concurrent commissioning flow. As per the specification, the commissioning channel (BLE in this case) SHALL be terminated only after CommissioningComplete command is invoked.
