### ISSUE TITLE
Some power source attributes are broken (CON-1002)

### ISSUE THREAD

**Issue by RemiNV** [espressif/esp-matter#822]
**Describe the bug**
It seems some attributes for power sources are broken:

 - In components/esp_matter/esp_matter_attribute.cpp, `create_bat_percent_remaining` calls `esp_matter::attribute::add_bounds(attribute, esp_matter_uint8(min), esp_matter_uint8(max));`. But this should instead use `esp_matter_nullable_uint8`: I got type mismatch errors otherwise.
 - I observed the same for `create_bat_voltage`, which should actually use `esp_matter_nullable_uint32`, and I think other functions have the same problem
 - In components/esp_matter/esp_matter_cluster.cpp, `power_source::create` calls `attribute::create_description(cluster, config->description, sizeof(config->description));`. But `power_source::config_t` has a 61 char description, while `power_source::attribute::create_description` in components/esp_matter/esp_matter_attribute.cpp will fail if the passed in length is > 60 (k_max_description_length).

I found these by getting error logs when adding a power source endpoint with the following code:

```
    power_source_device::config_t pwr_src_cfg;

    strncpy(pwr_src_cfg.power_source.description, "Li-Po battery", sizeof(pwr_src_cfg.power_source.description));
    pwr_src_cfg.power_source.battery.bat_replaceability = (uint8_t) PowerSource::BatReplaceabilityEnum::kUserReplaceable;
    pwr_src_cfg.power_source.battery.bat_charge_level = (uint8_t) PowerSource::BatChargeLevelEnum::kOk;

    endpoint_t* ps_endpoint = power_source_device::create(
        device_node, &pwr_src_cfg, ENDPOINT_FLAG_NONE, NULL);
    cluster_t* pwr_src_cluster = cluster::get(ps_endpoint, PowerSource::Id);
    ESP_ERROR_CHECK(power_source::feature::battery::add(pwr_src_cluster, &(pwr_src_cfg.power_source.battery)));

    power_source::attribute::create_bat_percent_remaining(pwr_src_cluster, NULL, 0, 200);
    power_source::attribute::create_bat_voltage(pwr_src_cluster, NULL,
        BatteryMeter::BAT_MIN_VOLTAGE, BatteryMeter::BAT_MAX_VOLTAGE);
```

(not sure if I'm doing things right here, but at least there seems to be actual problems in the esp-matter code).

**Environment**
- ESP-Matter Commit Id: fead56616a812b9943d2b8eb3b8f55cc8ecd46c2

**Comment by shubhamdp** [comment]
Fixed with https://github.com/espressif/esp-matter/commit/06683ba66dbb60803d99698d76dc8d84700a47a8, this can be closed.
