### ISSUE TITLE
All device types app not building properly (CON-1005)

### ISSUE THREAD

**Issue by FloBer431** [espressif/esp-matter#825]
No matter how often I try to build the All_Device_types_app example, it keeps on failing the build.
I'm building in VSCode under Windows 11, connected to WSL2.
The whole building process starts properly, but shortly before the end, an error occures.

From here the FAILED exceptions starts and stopping the building process.

` [1264/1278] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/esp_matter_console_helpers.cpp.obj
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/esp_matter_console_helpers.cpp.obj 
/home/ber/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/xtensa-esp32-elf-g++ -DESP_PLATFORM -DIDF_VER=\"v5.3-dev-1353-gb3f7e2c8a4\" -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DSOC_MMU_PAGE_SIZE=CONFIG_MMU_PAGE_SIZE -DSOC_XTAL_FREQ_MHZ=CONFIG_XTAL_FREQ -D_GLIBCXX_HAVE_POSIX_SEMAPHORE -D_GLIBCXX_USE_POSIX_SEMAPHORE -D_GNU_SOURCE -D_POSIX_READER_WRITER_LOCKS -Iconfig -I../main -I/home/ber/esp/esp-idf/components/newlib/platform_include -I/home/ber/esp/esp-idf/components/freertos/config/include -I/home/ber/esp/esp-idf/components/freertos/config/include/freertos -I/home/ber/esp/esp-idf/components/freertos/config/xtensa/include -I/home/ber/esp/esp-idf/components/freertos/FreeRTOS-Kernel/include -I/home/ber/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I/home/ber/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos -I/home/ber/esp/esp-idf/components/freertos/esp_additions/include -I/home/ber/esp/esp-idf/components/esp_hw_support/include -I/home/ber/esp/esp-idf/components/esp_hw_support/include/soc -I/home/ber/esp/esp-idf/components/esp_hw_support/include/soc/esp32 -I/home/ber/esp/esp-idf/components/esp_hw_support/port/esp32/. -I/home/ber/esp/esp-idf/components/heap/include -I/home/ber/esp/esp-idf/components/log/include -I/home/ber/esp/esp-idf/components/soc/include -I/home/ber/esp/esp-idf/components/soc/esp32 -I/home/ber/esp/esp-idf/components/soc/esp32/include -I/home/ber/esp/esp-idf/components/hal/platform_port/include -I/home/ber/esp/esp-idf/components/hal/esp32/include -I/home/ber/esp/esp-idf/components/hal/include -I/home/ber/esp/esp-idf/components/esp_rom/include -I/home/ber/esp/esp-idf/components/esp_rom/include/esp32 -I/home/ber/esp/esp-idf/components/esp_rom/esp32 -I/home/ber/esp/esp-idf/components/esp_common/include -I/home/ber/esp/esp-idf/components/esp_system/include -I/home/ber/esp/esp-idf/components/esp_system/port/soc -I/home/ber/esp/esp-idf/components/esp_system/port/include/private -I/home/ber/esp/esp-idf/components/xtensa/esp32/include -I/home/ber/esp/esp-idf/components/xtensa/include -I/home/ber/esp/esp-idf/components/xtensa/deprecated_include -I/home/ber/esp/esp-idf/components/lwip/include -I/home/ber/esp/esp-idf/components/lwip/include/apps -I/home/ber/esp/esp-idf/components/lwip/include/apps/sntp -I/home/ber/esp/esp-idf/components/lwip/lwip/src/include -I/home/ber/esp/esp-idf/components/lwip/port/include -I/home/ber/esp/esp-idf/components/lwip/port/freertos/include -I/home/ber/esp/esp-idf/components/lwip/port/esp32xx/include -I/home/ber/esp/esp-idf/components/lwip/port/esp32xx/include/arch -I/home/ber/esp/esp-idf/components/lwip/port/esp32xx/include/sys -I/home/ber/esp-matter/device_hal/device/include -I/home/ber/esp-matter/device_hal/led_driver/include -I/home/ber/esp/esp-idf/components/driver/deprecated -I/home/ber/esp/esp-idf/components/driver/i2c/include -I/home/ber/esp/esp-idf/components/driver/touch_sensor/include -I/home/ber/esp/esp-idf/components/driver/twai/include -I/home/ber/esp/esp-idf/components/driver/touch_sensor/esp32/include -I/home/ber/esp/esp-idf/components/esp_pm/include -I/home/ber/esp/esp-idf/components/esp_ringbuf/include -I/home/ber/esp/esp-idf/components/esp_driver_gpio/include -I/home/ber/esp/esp-idf/components/esp_driver_pcnt/include -I/home/ber/esp/esp-idf/components/esp_driver_gptimer/include -I/home/ber/esp/esp-idf/components/esp_driver_spi/include -I/home/ber/esp/esp-idf/components/esp_driver_mcpwm/include -I/home/ber/esp/esp-idf/components/esp_driver_ana_cmpr/include -I/home/ber/esp/esp-idf/components/esp_driver_i2s/include -I/home/ber/esp/esp-idf/components/esp_driver_sdmmc/include -I/home/ber/esp/esp-idf/components/sdmmc/include -I/home/ber/esp/esp-idf/components/esp_driver_sdspi/include -I/home/ber/esp/esp-idf/components/esp_driver_sdio/include -I/home/ber/esp/esp-idf/components/esp_driver_dac/include -I/home/ber/esp/esp-idf/components/esp_driver_rmt/include -I/home/ber/esp/esp-idf/components/esp_driver_tsens/include -I/home/ber/esp/esp-idf/components/esp_driver_sdm/include -I/home/ber/esp/esp-idf/components/esp_driver_i2c/include -I/home/ber/esp/esp-idf/components/esp_driver_uart/include -I/home/ber/esp/esp-idf/components/vfs/include -I/home/ber/esp/esp-idf/components/esp_driver_ledc/include -I/home/ber/esp/esp-idf/components/esp_driver_parlio/include -I/home/ber/esp/esp-idf/components/esp_driver_usb_serial_jtag/include -I../managed_components/espressif__button/include -I/home/ber/esp/esp-idf/components/esp_adc/include -I/home/ber/esp/esp-idf/components/esp_adc/interface -I/home/ber/esp/esp-idf/components/esp_adc/esp32/include -I/home/ber/esp/esp-idf/components/esp_adc/deprecated/include -I/home/ber/esp-matter/components/esp_matter -I/home/ber/esp-matter/components/esp_matter/utils -I/home/ber/esp-matter/connectedhomeip/connectedhomeip/zzz_generated/app-common -I/home/ber/esp-matter/connectedhomeip/connectedhomeip/third_party/nlfaultinjection/include -I/home/ber/esp-matter/connectedhomeip/connectedhomeip/src -I/home/ber/esp-matter/components/esp_matter/zap_common -I/home/ber/esp-matter/connectedhomeip/connectedhomeip/src/platform/ESP32 -I/home/ber/esp-matter/connectedhomeip/connectedhomeip/src/platform/OpenThread -I/home/ber/esp-matter/connectedhomeip/connectedhomeip/src/include -I/home/ber/esp-matter/connectedhomeip/connectedhomeip/src/lib -I/home/ber/esp-matter/connectedhomeip/connectedhomeip/examples/platform/esp32 -I/home/ber/esp-matter/connectedhomeip/connectedhomeip/third_party/nlassert/repo/include -I/home/ber/esp-matter/connectedhomeip/connectedhomeip/third_party/nlio/repo/include -Iesp-idf/chip/src/include -Iesp-idf/chip/include -Iesp-idf/chip/gen/include -I/home/ber/esp-matter/connectedhomeip/connectedhomeip/config/esp32 -I/home/ber/esp-matter/connectedhomeip/connectedhomeip/config/esp32/../.. -I../managed_components/espressif__esp_encrypted_img/include -I../managed_components/espressif__esp_insights/include -I../managed_components/espressif__esp_diagnostics/include -I/home/ber/esp/esp-idf/components/bt/include/esp32/include -I/home/ber/esp/esp-idf/components/bt/common/osi/include -I/home/ber/esp/esp-idf/components/bt/common/api/include/api -I/home/ber/esp/esp-idf/components/bt/common/btc/profile/esp/blufi/include -I/home/ber/esp/esp-idf/components/bt/common/btc/profile/esp/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/ans/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/bas/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/dis/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/gap/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/gatt/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/hr/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/htp/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/ias/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/ipss/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/lls/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/prox/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/cts/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/tps/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/hid/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/sps/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/util/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/store/ram/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/store/config/include -I/home/ber/esp/esp-idf/components/bt/porting/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/porting/nimble/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/port/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/transport/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/porting/npl/freertos/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/nimble/nimble/include -I/home/ber/esp/esp-idf/components/bt/host/nimble/esp-hci/include -I/home/ber/esp/esp-idf/components/esp_timer/include -I/home/ber/esp/esp-idf/components/esp_wifi/include -I/home/ber/esp/esp-idf/components/esp_wifi/wifi_apps/include -I/home/ber/esp/esp-idf/components/esp_event/include -I/home/ber/esp/esp-idf/components/esp_phy/include -I/home/ber/esp/esp-idf/components/esp_phy/esp32/include -I/home/ber/esp/esp-idf/components/esp_netif/include -I/home/ber/esp-matter/components/esp_matter_console -I/home/ber/esp/esp-idf/components/nvs_flash/include -I/home/ber/esp/esp-idf/components/spi_flash/include -I/home/ber/esp/esp-idf/components/esp_partition/include -I/home/ber/esp/esp-idf/components/app_update/include -I/home/ber/esp/esp-idf/components/bootloader_support/include -I/home/ber/esp/esp-idf/components/bootloader_support/bootloader_flash/include -I/home/ber/esp/esp-idf/components/esp_app_format/include -I/home/ber/esp/esp-idf/components/esp_bootloader_format/include -I../managed_components/espressif__esp_secure_cert_mgr/include -I/home/ber/esp/esp-idf/components/mbedtls/port/include -I/home/ber/esp/esp-idf/components/mbedtls/mbedtls/include -I/home/ber/esp/esp-idf/components/mbedtls/mbedtls/library -I/home/ber/esp/esp-idf/components/mbedtls/esp_crt_bundle/include -I/home/ber/esp/esp-idf/components/mbedtls/mbedtls/3rdparty/everest/include -I/home/ber/esp/esp-idf/components/mbedtls/mbedtls/3rdparty/p256-m -I/home/ber/esp/esp-idf/components/mbedtls/mbedtls/3rdparty/p256-m/p256-m -I/home/ber/esp/esp-idf/components/efuse/include -I/home/ber/esp/esp-idf/components/efuse/esp32/include -I/home/ber/esp/esp-idf/components/json/cJSON -I/home/ber/esp-matter/examples/common/app_reset -I/home/ber/esp/esp-idf/components/console -I/home/ber/esp/esp-idf/components/fatfs/diskio -I/home/ber/esp/esp-idf/components/fatfs/src -I/home/ber/esp/esp-idf/components/fatfs/vfs -I/home/ber/esp/esp-idf/components/wear_levelling/include -mlongcalls -Wno-frame-address  -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=unused-but-set-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -Og -fno-shrink-wrap -fmacro-prefix-map=/home/ber/esp-matter/examples/all_device_types_app=. -fmacro-prefix-map=/home/ber/esp/esp-idf=/IDF -fstrict-volatile-bitfields -fno-jump-tables -fno-tree-switch-conversion -Wno-error=uninitialized -Wno-error=maybe-uninitialized -Wno-missing-field-initializers -Wno-error=array-bounds -Wno-write-strings -Wno-format-nonliteral -Wno-format-security -Wformat=0 -std=gnu++2b -fno-exceptions -fno-rtti -std=gnu++17 -Os -DCHIP_HAVE_CONFIG_H "-DCHIP_ADDRESS_RESOLVE_IMPL_INCLUDE_HEADER=<lib/address_resolve/AddressResolve_DefaultImpl.h>" -std=gnu++17 -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/esp_matter_console_helpers.cpp.obj -MF esp-idf/main/CMakeFiles/__idf_main.dir/esp_matter_console_helpers.cpp.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/esp_matter_console_helpers.cpp.obj -c ../main/esp_matter_console_helpers.cpp
../main/esp_matter_console_helpers.cpp: In function 'void initialize_console()':
../main/esp_matter_console_helpers.cpp:62:46: warning: 'int esp_vfs_dev_uart_port_set_rx_line_endings(int, esp_line_endings_t)' is deprecated: Please use uart_vfs_dev_port_set_rx_line_endings() instead [-Wdeprecated-declarations]
   62 |     esp_vfs_dev_uart_port_set_rx_line_endings(CONFIG_ESP_CONSOLE_UART_NUM, ESP_LINE_ENDINGS_CR);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../main/esp_matter_console_helpers.cpp:13:
/home/ber/esp/esp-idf/components/vfs/include/esp_vfs_dev.h:22:5: note: declared here
   22 | int esp_vfs_dev_uart_port_set_rx_line_endings(int uart_num, esp_line_endings_t mode) __attribute__((deprecated("Please use uart_vfs_dev_port_set_rx_line_endings() instead")));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../main/esp_matter_console_helpers.cpp:64:46: warning: 'int esp_vfs_dev_uart_port_set_tx_line_endings(int, esp_line_endings_t)' is deprecated: Please use uart_vfs_dev_port_set_tx_line_endings() instead [-Wdeprecated-declarations]
   64 |     esp_vfs_dev_uart_port_set_tx_line_endings(CONFIG_ESP_CONSOLE_UART_NUM, ESP_LINE_ENDINGS_CRLF);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ber/esp/esp-idf/components/vfs/include/esp_vfs_dev.h:24:5: note: declared here
   24 | int esp_vfs_dev_uart_port_set_tx_line_endings(int uart_num, esp_line_endings_t mode) __attribute__((deprecated("Please use uart_vfs_dev_port_set_tx_line_endings() instead")));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/ber/esp/esp-idf/components/esp_common/include/esp_check.h:8,
                 from ../main/esp_matter_console_helpers.cpp:9:
../main/esp_matter_console_helpers.cpp:81:42: error: invalid conversion from 'int' to 'uart_port_t' [-fpermissive]
   81 |     ESP_ERROR_CHECK( uart_driver_install(CONFIG_ESP_CONSOLE_UART_NUM,
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                          |
      |                                          int
/home/ber/esp/esp-idf/components/esp_common/include/esp_err.h:117:30: note: in definition of macro 'ESP_ERROR_CHECK'
  117 |         esp_err_t err_rc_ = (x);                                        \
      |                              ^
In file included from ../main/esp_matter_console_helpers.cpp:18:
/home/ber/esp/esp-idf/components/esp_driver_uart/include/driver/uart.h:113:43: note:   initializing argument 1 of 'esp_err_t uart_driver_install(uart_port_t, int, int, int, QueueDefinition**, int)'
  113 | esp_err_t uart_driver_install(uart_port_t uart_num, int rx_buffer_size, int tx_buffer_size, int queue_size, QueueHandle_t* uart_queue, int intr_alloc_flags);
      |                               ~~~~~~~~~~~~^~~~~~~~
../main/esp_matter_console_helpers.cpp:83:40: error: invalid conversion from 'int' to 'uart_port_t' [-fpermissive]
   83 |     ESP_ERROR_CHECK( uart_param_config(CONFIG_ESP_CONSOLE_UART_NUM, &uart_config) );
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                        |
      |                                        int
/home/ber/esp/esp-idf/components/esp_common/include/esp_err.h:117:30: note: in definition of macro 'ESP_ERROR_CHECK'
  117 |         esp_err_t err_rc_ = (x);                                        \
      |                              ^
/home/ber/esp/esp-idf/components/esp_driver_uart/include/driver/uart.h:459:41: note:   initializing argument 1 of 'esp_err_t uart_param_config(uart_port_t, const uart_config_t*)'
  459 | esp_err_t uart_param_config(uart_port_t uart_num, const uart_config_t *uart_config);
      |                             ~~~~~~~~~~~~^~~~~~~~
../main/esp_matter_console_helpers.cpp:86:32: warning: 'void esp_vfs_dev_uart_use_driver(int)' is deprecated: Please use uart_vfs_dev_use_driver() instead [-Wdeprecated-declarations]
   86 |     esp_vfs_dev_uart_use_driver(CONFIG_ESP_CONSOLE_UART_NUM);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ber/esp/esp-idf/components/vfs/include/esp_vfs_dev.h:20:6: note: declared here
   20 | void esp_vfs_dev_uart_use_driver(int uart_num) __attribute__((deprecated("Please use uart_vfs_dev_use_driver() instead")));
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[1268/1278] Building CXX object esp-idf/esp_matter/CMakeFiles/__idf_esp_matter.dir/home/ber/esp-matter...omeip/connectedhomeip/src/app/clusters/time-synchronization-server/time-synchronization-server.cpp.obj
ninja: build stopped: subcommand failed.

 *  The terminal process "/bin/bash '-c', 'ninja '" terminated with exit code: 1. `
Can anybody help me?
Also the create --device_type command does not work.

**Comment by jadhavrohit924** [comment]
@FloBer431 Which esp-idf version you are using?

**Comment by FloBer431** [comment]
> @FloBer431 Which esp-idf version you are using?

I think it's V5.1.2. where can I check it?

**Comment by jadhavrohit924** [comment]
Esp-matter is compatible with v5.1.2. Can you please share me the esp-idf commit, esp-matter commit and the steps that you have followed, patch of your local changes, if any?

**Comment by FloBer431** [comment]
> Esp-matter is compatible with v5.1.2. Can you please share me the esp-idf commit, esp-matter commit and the steps that you have followed, patch of your local changes, if any?

Sorry I'm pretty new working with these system, where do I find the commit?
So step by step:
- Starting VSCode and connecting to WSL
- opening the example project
- connecting com-port with wsl over powershell
- setting board to esp32
- starting to build 
- getting the error i posted before

I didn't make any changes.

**Comment by jadhavrohit924** [comment]
@FloBer431 Use the command `git log` and check the commit id of `HEAD`

**Comment by FloBer431** [comment]
> @FloBer431 Use the command `git log` and check the commit id of `HEAD`

That doesn't work for me, as I have no git repositorys `fatal: not a git repository (or any of the parent directories): .git`

**Comment by FloBer431** [comment]
I don't really know why, but after some restart of VSCode, the WSL connection and various tries, it worked ...

Thanks
