### ISSUE TITLE
CHIP-Shell not responding when building for ESP32C6 (CON-1007)

### ISSUE THREAD

**Issue by sdrasti** [espressif/esp-matter#826]
When building the all_device_types_app for an ESP32C6, the "Enter command: create --device to get started" appears after boot, but the shell prompt "> " does not show up for command input. The app is up and running, when pressing the boot button "app_driver: Toggle button pressed" appears on the screen.

When building for a regular ESP32 the device configuration via shell commands works.

The chip-shell is enabled in the sdkconfig.

- ESP-Matter Commit Id: main branch #37dc7d9
- ESP-IDF Commit Id: release 5.1.2 #482a8fb
- SoC: ESP32-C6-DevKitM / ESP32-C6-DevKitC

**Comment by jonsmirl** [comment]
You are likely using the JTAG serial. You have to go into menuconfig and set it as your primary console.

**Comment by sdrasti** [comment]
@jonsmirl exactly this, and adding CONFIG_ESP_CONSOLE_* settings to the config fixed it. 

Thank's a lot!
