### ISSUE TITLE
Is there a app on Andriod that I can connect matter object with it?

### ISSUE THREAD

**Issue by Firesuiry** [espressif/esp-matter#84]
Is there a app on Andriod that I can connect matter object with it?

**Comment by dhrishi** [comment]
@Firesuiry There is one in the upstream connectedhomeip repository which you can find [here](https://github.com/project-chip/connectedhomeip/tree/master/examples/android/CHIPTool)
This also has the documentation about building the Android app.

**Comment by jonsmirl** [comment]
Official Google sample is here:
https://developers.home.google.com/samples/matter-app

**Comment by Firesuiry** [comment]
@dhrishi @jonsmirl Thank you！
