### ISSUE TITLE
Using Nimble BLE scanner along with Matter Application (CON-1047)

### ISSUE THREAD

**Issue by bilalmalik76** [espressif/esp-matter#840]
Is this possible to use the Nimble BLE scanner application along with Matter? If yes, is there any special wrappers available in esp-matter or we can use component of esp-idf?

**Comment by dhrishi** [comment]
@bilalmalik76 It is possible to use BLE for application specific purposes, along with Matter. No wrappers are available. You can use the NimBLE APIs from esp-matter. Make sure that you disable the config option `CONFIG_USE_BLE_ONLY_FOR_COMMISSIONING`.

**Comment by bilalmalik76** [comment]
@dhrishi Yes I am already able to use BLE along with Matter, it works fine.

**Comment by dhrishi** [comment]
Thanks for the confirmation
