### ISSUE TITLE
simple light endpoint after reboot value not restored. (CON-1049)

### ISSUE THREAD

**Issue by ronny-antoon** [espressif/esp-matter#841]
**Describe the bug**
Simple light endpoint without any addition. just the root endpoint and the on_off_light endpoint.
No effect for the Config on_off.on_off, "this should make the start value".
After commission and all thing working as expected, Turn the light on. then reboot the device, the device start with Light off. but it should be On. as last value.

**Environment**
- ESP-Matter Commit Id: release/v1.2
- ESP-IDF Commit Id: v5.1.2
- SoC (eg: ESP32 or ESP32-C3): esp32
- Device Logs (Please attach the log file): 
[log esp mattter.txt](https://github.com/espressif/esp-matter/files/14292227/log.esp.mattter.txt)

- Host Machine OS: IOS 17.2.1
- Commissioner app and versions if present: IOS 17.2.1
- Commissioner's logs if present:

**Any additional details**
...

**Comment by nichonaugle** [comment]
Is the starting value hardcoded into the example you have created or are you using the light example issued under the esp-matter repo?

**Comment by jadhavrohit924** [comment]
@ronny-antoon Have you tried of_off_light with lighting feature enabled? StartUpOnOff attribute is optional and has conformance of LT i.e lighting feature.

**Comment by ronny-antoon** [comment]
Simplest Code ever, @jadhavrohit924  @nichonaugle 

[log esp mattter.txt](https://github.com/espressif/esp-matter/files/14295082/log.esp.mattter.txt)

**Comment by jadhavrohit924** [comment]
@ronny-antoon I have analysed your logs.  From the logs, you have toggled the light in-between thats why your light turned off and when you reboot it is stays off.

Can you try below steps and check if you are facing the issue:
1. Flash the device
2. Commission the device
3. Read value of OnOff attribute ( expected true )
4. Toggle the light
5. Read value of OnOff attribute ( expected false )
6. Reboot the device
7. Read value of OnOff attribute ( expected false )

**Comment by ronny-antoon** [comment]
> @ronny-antoon I have analysed your logs.  From the logs, you have toggled the light in-between thats why your light turned off and when you reboot it is stays off.
> 
> 
> 
> Can you try below steps and check if you are facing the issue:
> 
> 1. Flash the device
> 
> 2. Commission the device
> 
> 3. Read value of OnOff attribute ( expected true )
> 
> 4. Toggle the light
> 
> 5. Read value of OnOff attribute ( expected false )
> 
> 6. Reboot the device
> 
> 7. Read value of OnOff attribute ( expected false )

Thats not me,
Thats the problem,
If you are talking about the log starts with "chip[ZC....Toggle..."
I tried another time, Turned the light on. Reboot, then again it initiated with On, but turns off immediately with the initialization.

**Comment by jadhavrohit924** [comment]
Could you please share the whole logs, which has everything right from flashing, turning on light, reboot, and state after reboot?

**Comment by ronny-antoon** [comment]
@jadhavrohit924 
I have implemented a straightforward simple project featuring an on_off_light and an on_off_plugin_unit.
The program code can be found [here app_main.cpp.txt](https://github.com/espressif/esp-matter/files/14336629/app_main.cpp.txt) .


Having previously paired the device,
I initiated the project by executing the command 'idf.py flash monitor'. Once the device started up,
I accessed the Home App on Apple, toggled both the light and the plugin, both turned ON, and subsequently exited the terminal.
The corresponding output log for this sequence is available [here Flash monitor.txt](https://github.com/espressif/esp-matter/files/14336631/Flash.monitor.txt)


Subsequently, I ran the command 'idf.py monitor' without interacting with the device.
I patiently waited for the output log to stabilize, and the resulting log can be found [here monitor.txt](https://github.com/espressif/esp-matter/files/14336633/monitor.txt)

**Comment by jadhavrohit924** [comment]
@ronny-antoon Thanks for the information, if you want to set OnOff to the previous state when device is supplied to power. You have to set StartUpOnOff attribute to null in your light config
```
on_off_light::config_t light_config;
light_config.on_off.lighting.start_up_on_off = nullptr;
on_off_light::create(node, &light_config, ENDPOINT_FLAG_NONE, nullptr);
```

**Comment by ronny-antoon** [comment]
@jadhavrohit924 
Thanks for your efforts and time, i appresiate it.
I tried to make what you said about config, and still the same behavior.

`
    on_off_light::config_t light_config;
    light_config.on_off.lighting.start_up_on_off = nullptr;
    on_off_light::create(node, &light_config, ENDPOINT_FLAG_NONE, nullptr);

    on_off_plugin_unit::config_t plugin_unit_config;
    plugin_unit_config.on_off.lighting.start_up_on_off = nullptr;
    on_off_plugin_unit::create(node, &plugin_unit_config, ENDPOINT_FLAG_NONE, 
    nullptr);
`

**Comment by ronny-antoon** [comment]
@jadhavrohit924 
Thank you a lot, I got the solution.
I don't know why,  but after Erase Flash, and re-Flash, It just solved the problem.
But NVM the goal achieved.  
Thank you.
