### ISSUE TITLE
Need advise : contoller write-attr //  Subscription renewal (CON-1057)

### ISSUE THREAD

**Issue by a-tobias** [espressif/esp-matter#849]
How to write an attribute of a node from a esp controller ?
I tried the following : matter esp controller write-attr 0x1001B 0x1 0x6 0x0 "{\"0:BOOL\": false}" ( ON/OFF attribute of a light node).
The attribute does not change and i obtain the following in the controller CLI: 

```
I (314431391) chip[DIS]: Found an existing secure session to [1:000000000001001B]!
I (314431391) chip[EM]: <<< [E:8662i S:63606 M:260910721] (S) Msg TX to 1:000000000001001B [5C6B] [UDP:[FDA5:1747:2E10:0:F317:B780:4EA5:26B%st1]:5540] --- Type 0001:06 (IM:WriteRequest)
Done
> I (314431571) chip[EM]: >>> [E:8662i S:63606 M:174233466 (Ack:260910721)] (S) Msg RX from 1:000000000001001B [5C6B] --- Type 0001:07 (IM:WriteResponse)
E (314431581) chip[TOO]: Response Failure: Error IM:0x00000588
I (314431591) chip[TOO]: Write Done
I (314431591) chip[EM]: <<< [E:8662i S:63606 M:260910722 (Ack:174233466)] (S) Msg TX to 1:000000000001001B [5C6B] [UDP:[FDA5:1747:2E10:0:F317:B780:4EA5:26B%st1]:5540] --- Type 0000:10 (SecureChannel:StandaloneAck)
```

Additionally I`m wondering what is the best way to detect when a node reconnects (after reboot) to the controller - for example to re-establish the subscription (from controller point of view). Is there an event or callbackon on the controller available (i started with the controller example)

**Comment by wqx6** [comment]
> The attribute does not change and i obtain the following in the controller CLI:

The `Error IM:0x00000588` is `UnsupportedWrite` error. The OnOff attribute is not writable so you cannot write it with the controller. You can try writing attribute command with the StartUpOnOff attribute(Attribute ID 0x4003).

>  Additionally I`m wondering what is the best way to detect when a node reconnects (after reboot) to the controller - for example to re-establish the subscription (from controller point of view). Is there an event or callbackon on the controller available (i started with the controller example)

You can register the attribute data callback or event data callback when you create subscribe command object with the [constructor](https://github.com/espressif/esp-matter/blob/main/components/esp_matter_controller/esp_matter_controller_subscribe_command.h#L57-L58). If a node which enables subscription resumption reboot, it will re-establish the CASE session with the controller and send the data report. And you can get the report in the attribute data callback or event data callback.

**Comment by wqx6** [comment]
> What is the starting point to make the On/Off attribute writable by the controller ?

SPEC says that this attribute is not writable and it should only be changed by the invoked-command of OnOff cluster(On, Off, Toggle commands). Our controller will not know whether an attribute is writable, the controller just send the write command and if the attribute is not writable, the end device will reply an `UnsupportedWrite` Error.

> how i could detect that a node connects to the controller (without active subscription)?

I don't think there is a way to detect that a node connects to the controller without active subscription. If you want to detect whether the node is on-network, I think you can try to resolve the node on the controller side and re-establish a new subscription if resolved the node.

**Comment by vishnuprasadvp12345** [comment]
Using the ESP Matter controller example code, the command for controlling a Matter device isn't functioning as expected. Despite sending the command matter esp controller invoke-cmd 2 1 6 0 "{\"0:BOOL\":true/flase}", there's no change in the attribute values. Upon inspection, the attribute value remains unchanged. Additionally, attempting to modify other attributes within Cluster 6, specifically attribute ID 0x4000 Series, isn't supported by the controller device side response in both false and true same device side 
esp_matter_attribute: ********** R : Endpoint 0x0001's Cluster 0x00000006's Attribute 0x00000000 is 0 ********** any other command to control onoff cluster
