### ISSUE TITLE
Help building a standard contact sensor device (CON-1068)

### ISSUE THREAD

**Issue by FloBer431** [espressif/esp-matter#856]
Hello there,

I tried several times to build a device with a simple contact sensor, but I didn't manage to get it running.
I read every single Issue and text about contact sensor and implementing my own device.
I'm really not that expirienced developing with linux, so I tried it with the VS Code extension and WSL2.

Is there anyone who has a simple contact sensor example to share with me?
It should just look a one GPIO Pin of my ESP32-S3 board and generate a contact state wich can trigger routines in alexa, google home and apple homekit.

Thank you very much!

Florian

**Comment by YOGYUI** [comment]
@FloBer431 I recently created my own repository which deals with `occupancy sensor` with PmodPIR sensor module (just one GPIO input).
[matter-esp32-ekmc16](https://github.com/YOGYUI/matter-esp32-ekmc16)
Although these codes are related to occupancy sensor with PIR sensor, but I think that `physical contact sensor` can be also implemented with this device type.
<img width="656" alt="image" src="https://github.com/espressif/esp-matter/assets/87917955/7dc934cd-42cd-4ade-91d3-96d0f3f478ca">

I hope it will help :)

**Comment by FloBer431** [comment]
@YOGYUI Thank you for your help. I will check it out and try to use it.

**Comment by shubhamdp** [comment]
Hi @FloBer431 If the issue resolved, can you please close it.
