### ISSUE TITLE
When is the support for motion sensors (CON-1071)

### ISSUE THREAD

**Issue by itatboy** [espressif/esp-matter#860]
**Is your feature request related to a problem? Please describe.**
Description of what the problem is.

**Describe the solution you'd like**
Description of what you want to happen.
Support motion sensors

**Describe alternatives you've considered**
Description of any alternative solutions or features you've considered.

**Additional context**
I couldn't find any motion sensors in the supported device list
![1](https://github.com/espressif/esp-matter/assets/92285852/f3dab9bf-d58c-458e-8866-92c951352d2c)

**Comment by jadhavrohit924** [comment]
@itatboy There is no such device type as of now as per matter spec.

**Comment by itatboy** [comment]
Thank you for your reply,

As far as I know, Apple Home comes with a Motion sensor accessory. Is there a similar device type for the subject. I want to implement the corresponding Motion Sensor accessory through matter, so that the matter device will be a Motion Sensor when added to the Home App？

I also noticed that:

There are already Matter based devices on the market that are recognized as Motion Sensors when added to the Home App, and it is currently unclear whether they are using ESP solutions.

**Comment by jadhavrohit924** [comment]
Thanks for the information, there is no any such dedicated device types. People are using above (attached list by you) sensor device types to make motion sensor.

**Comment by itatboy** [comment]
https://www.apple.com/shop/product/HQWK2ZM/A/Eve%20Motion%20(Matter)%20Sensor

The above is the official link from Apple, which displays a Motion sensor based on Matter implementation. May I ask which device type of Matter corresponds to a Motion sensor?

Thank you very much for any information provided

**Comment by jadhavrohit924** [comment]
I don’t know what they have implementet but it looks like a `occupancy sensor`. Here is the list of [supported device type](https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/darwin.md#testing-your-matter-device-with-apple-home) by apple and it doesn’t have `motion sensor`

**Comment by jonsmirl** [comment]
Motion sensor is an occupancy sensor. 
![image](https://github.com/espressif/esp-matter/assets/14943/8f99d18c-bf47-470a-b9e0-470553a1db87)

**Comment by itatboy** [comment]
@jonsmirl Hi,

Thank you very much for providing the information, it is very useful. Now I know how to implement sports accessories.
thanks

**Comment by itatboy** [comment]
@jonsmirl 

I'm sorry, after verification, I can only reopen this issue.Here are some of my progress:
I use occupancy sensors to implement motion sensors. The code is as follows:
![image](https://github.com/espressif/esp-matter/assets/92285852/a88cdb6a-8df0-48b1-9cf2-5b93f05709a7)
![image](https://github.com/espressif/esp-matter/assets/92285852/810d2170-33dc-4e10-844a-5ba057968693)

When accessories are added to Homekit, they are recognized as human sensors,It's not a motion sensor
![image](https://github.com/espressif/esp-matter/assets/92285852/5a1c4422-133f-41d0-8ed8-05fcc94a2517)

https://csa-iot.org/csa_product/eve-motion-3/
When the EVE motion developed based on Matter was added to the Home App, it was identified as a motion sensor. I reviewed its compliance certification documents and found that it supports the PIROccupiedToUnocupiedDelay attribute, while the esp matter does not. I am not sure if this is causing the device recognition error. Can you provide a solution to the problem? Thank you.
![image](https://github.com/espressif/esp-matter/assets/92285852/e508b682-f2bc-49e5-bef7-99d0aceb0caf)
![image](https://github.com/espressif/esp-matter/assets/92285852/b24ff536-586d-45f5-bf6c-3e599f239d67)

This is the effect I want, the accessory has been identified as a motion sensor:
![image](https://github.com/espressif/esp-matter/assets/92285852/6b54b663-535c-4cd2-85e1-1d40fa22b64e)

**Comment by jonsmirl** [comment]
I think Homekit is just being more generic in categorizing them as Presence sensors.  All motion sensors are presence sensors, but not all presence sensors are motion sensors. For example there are heat source sensors which can tell if there are warm bodies in the room even if they aren't moving.  There are also radar based sensors which can see a heart beat even if you aren't moving.

**Comment by itatboy** [comment]
You are right, all motion sensors are presence sensors. It is not clear how to make the Home App recognize the accessory as a motion sensor. It is not clear its judgment mechanism. I still need to try it. Thank you. @jonsmirl

**Comment by itatboy** [comment]
@jonsmirl Hi,

I noticed an interesting phenomenon, is it a bug?
In the code, set occupancy_sensor_type=0x01, occupancy_sensor_type_bitmap=0x02. After burning to the program, start the log information occupancy_sensor_type=0x00, occupancy_sensor_type_bitmap=0x01

![image](https://github.com/espressif/esp-matter/assets/92285852/c3208e03-a9cb-4985-8725-17b2c21356d4)

**Comment by jonsmirl** [comment]
Check out this file:
https://github.com/project-chip/connectedhomeip/blob/master/src/app/clusters/occupancy-sensor-server/occupancy-sensor-server.cpp

This might be getting called when it is not supposed to:
https://github.com/project-chip/connectedhomeip/blob/master/src/app/clusters/occupancy-sensor-server/occupancy-sensor-server.cpp#L85
You can try putting a breakpoint on it and see if it is getting called.

It appears to me something is overwriting your initialization when it shouldn't.

**Comment by itatboy** [comment]
@jonsmirl 
You're right, it did run void emberAfOccupancySensingClusterServerInitCallback(EndpointId endpoint) ---> void emberAfPluginOccupancyClusterServerPostInitCallback(EndpointId endpoint).
The callback function is registered in namespace occupancy sensing cluster_t * create (endpoints, config_t * config, uint8_t flags).

What situation would cause the callback function to run? Thank you
