### ISSUE TITLE
branch and commit of chip inconsistent

### ISSUE THREAD

**Issue by HomeACcessoryKid** [espressif/esp-matter#87]
Currently the checked out chip component is 87bee4d
However, the readme and the docker instructions still refer to 4f7669b

I assume this needs to be made consistent

**Comment by shubhamdp** [comment]
@HomeACcessoryKid thank for pointing it out, will fix this soon.

**Comment by HomeACcessoryKid** [comment]
thanks  
while you are at it, please look into #89 as well?
