### ISSUE TITLE
ESP Matter light example don't control LED (CON-1096)

### ISSUE THREAD

**Issue by SinRuku** [espressif/esp-matter#880]
I use the light example loaded into esp32_devkitj_v1 but it can only control the button and not the LED.
The picture below is what I have reconfigured in the sdkconfig file.
Thanks!

![Capture](https://github.com/espressif/esp-matter/assets/164599293/eb9c27af-1a44-4cc4-a8e4-e0bd1500556d)

**Comment by shubhamdp** [comment]
@SinRuku ESP32 devkit do not have a LED, so there may not be any visual change there. But what you can check is if you see the logs on the console correctly stating the state of an attribute.

**Comment by SinRuku** [comment]
> @SinRuku ESP32 devkit do not have a LED, so there may not be any visual change there. But what you can check is if you see the logs on the console correctly stating the state of an attribute.

@shubhamdp I used an LED and wired it to the pin of the ESP32 devkit as shown. I see the logs on the console correctly stating the status of a property but the LED still does not change the state.
![z5288278168641_1296994acb36726e95c159dcfb8a8a35](https://github.com/espressif/esp-matter/assets/164599293/7e4c0591-4c42-4ae7-b0c0-c3993d84e951)

In the source code, I changed CONFIG_BSP_LEDS_NUM = 1 to open the BSP_LED_NUM macro code as shown below, but nothing has changed. Can you check that for me?
![image](https://github.com/espressif/esp-matter/assets/164599293/1e38b89e-740b-4818-a482-dfdc13035044)
Thanks

**Comment by shubhamdp** [comment]
Since you hardwired the LED using breadboard, you will also have to specify the gpio number that is being used for that LED, please check how that is done for esp32c3, https://github.com/espressif/esp-matter/blob/main/examples/light/sdkconfig.defaults.esp32c3#L17-L20.

Similarly, you can put such config in the `sdkconfig.defaults` and I think that should toggle LED on breadboard.

**Comment by dhrishi** [comment]
@SinRuku Are you able to get this to work? Please close the issue if it works

**Comment by dhrishi** [comment]
Closing this now
