### ISSUE TITLE
'light' example is not fully working with Google Nest Hub

### ISSUE THREAD

**Issue by AlexeyYukhin** [espressif/esp-matter#90]
Hi all. I'm trying to launch esp-matter examples for tests and esp-matter SDK study. Then my further goal is to implement Google home integration for smart Door Lock.

I've tried 'light' project. I was able to bind matter device to my Google Nest Hub gen.2 without any problem, using Google Home mobile App. Basic device information (such as device type, firmware version etc.) is readable through Google home app. But I'm not able to control the light state (on/off commands, set brightness and colour temperature). For some reason, device is unreachable in this case.

My steps:
I left everything as-is and flashed my esp32 devboard. The only thing I did change is these SDK config parameters:
CONFIG_DEFAULT_WIFI_SSID
CONFIG_DEFAULT_WIFI_PASSWORD

I set them to my home wifi credentials, so that device was able to be bound with Nest Hub.

Log file from esp32 is attached, as well as sdkconfig file and screenshots ftom Google Home app.
[esp32_logs.txt](https://github.com/espressif/esp-matter/files/10003657/esp32_logs.txt)
[sdkconfig.txt](https://github.com/espressif/esp-matter/files/10003660/sdkconfig.txt)
![7](https://user-images.githubusercontent.com/83004070/201680580-e0b5b2a6-850d-469f-9366-087be541cb9d.jpg)
![6](https://user-images.githubusercontent.com/83004070/201680586-77ba6c29-ffff-4907-b37d-20dc9ecdaae2.jpg)
![5](https://user-images.githubusercontent.com/83004070/201680592-4145a5ab-8bb9-4b87-a6f4-209d21c96003.jpg)
![4](https://user-images.githubusercontent.com/83004070/201680595-94165d61-e590-4a25-8b52-144cceed116b.jpg)
![3](https://user-images.githubusercontent.com/83004070/201680602-f5bc671f-d7cf-488c-a210-e2281b658032.jpg)
![2](https://user-images.githubusercontent.com/83004070/201680605-be740c8a-5be6-42fe-9a90-3a466b2c09e0.jpg)
![1](https://user-images.githubusercontent.com/83004070/201680608-139d02ef-2061-4157-9b2c-38c4531e2447.jpg)

esp-idf - 4.4.2 (v4.4.2 tag)
esp-matter - last commit of main branch (2f37420bd5)
esp32 board - ESP32-WROOVER devboard
Master device - Google Nest Hub Gen2

Will be happy to receive any suggestions or advices arround this issue.

**Comment by jonsmirl** [comment]
The google support is based on CHIP commit 8638802e06fce1501c5c73b40a1d4eae98d076cb which is from July 15. The ESP-matter support is using current CHIP. You can probably get this working by moving esp-matter back to CHIP 8638802e06fce1501c5c73b40a1d4eae98d076cb.  If not you just have to wait for Google to get around to updating their release.

**Comment by dhrishi** [comment]
That's right. The Google Matter SDK for the public release is based on test event 9 (TE9) codebase.

**Comment by AlexeyYukhin** [comment]
Thank you guys. I really appreciate this. Please do not close the issue, I will try to find a temporary workaround for this to test it with current Google SDK. If I mange with this I will post here with results.

**Comment by dhrishi** [comment]
@AlexeyYukhin I would suggest you try with [sve branch](https://github.com/espressif/esp-matter/tree/sve). This might work with Google Home. Just make sure that you update the submodules correctly on this branch, clean and recompile followed by erase and re-flash.

**Comment by AlexeyYukhin** [comment]
> @AlexeyYukhin I would suggest you try with [sve branch](https://github.com/espressif/esp-matter/tree/sve). This might work with Google Home. Just make sure that you update the submodules correctly on this branch, clean and recompile followed by erase and re-flash.

Thanks for your advice. Unfortunately it doesn't work. I am able to bind the device in Google Home App using Google Nest Hub Gen2, but after this the device is shown as 'offline'. I still able to request basic device information (fw version, vendor id etc.), it works. But not device control, as it offline for some reason.

My steps:
1) I swithced to sve branch as you suggested. Then run git submodule update --init --recursive
2) I erased flash of ESP32 and reflashed it. I use 'light' example.
3) Then everything is the same - in Google Home app I added my device, and it's always offline. and can't be reachable to control.

Do you have any other suggestions of how I can kick it start to test esp matter with Google Home?

Also, does it worth to try examples withour esp-matted SDK? Like this one?
https://github.com/project-chip/connectedhomeip/tree/master/examples/lighting-app/esp32

**Comment by jonsmirl** [comment]
Did you try this Codelab?
https://developers.home.google.com/codelabs/matter-device-virtual?hl=en#0

**Comment by AlexeyYukhin** [comment]
> Did you try this Codelab? https://developers.home.google.com/codelabs/matter-device-virtual?hl=en#0

no, but it's not anyhow related to esp-matter SDK, as it's about original connectedhomeip repository. And it's onlye about virtual matter device example, while I'm trying to get real hw device (ESP32) working.

**Comment by jonsmirl** [comment]
Google has updated their Matter support again.
https://developers.home.google.com/matter/release-notes

The CHIP on your device has to match the CHIP on their side for this to work.

**Comment by jonsmirl** [comment]
Their esp32 instructions...
https://developers.home.google.com/matter/vendors/espressif

Get it working first from their documentation, then you can look and see what commit they are using and move esp-matter onto that commit.

**Comment by jonsmirl** [comment]
Also, note that while you should be able to get this working, when they update again it is going to stop working. Then you'll have to figure out what release they have moved onto and adjust your devices to match.  Apple, Google and Amazon are all on different commit IDs so this is a major pain to track.  Whenever Matter is actually released everyone should converge onto the same commit ID.

**Comment by AlexeyYukhin** [comment]
> Their esp32 instructions... https://developers.home.google.com/matter/vendors/espressif
> 
> Get it working first from their documentation, then you can look and see what commit they are using and move esp-matter onto that commit.

thanks for the reply. So far I've tried to follow this inctructions:
https://developers.home.google.com/matter/vendors/espressif?hl=en

- esp-idf checked out on v4.4.1
- connectedhomeip checked out on v1.0-branch
- submodules updated
- I've created a project in Googe Development console and added Matter integration 
![image](https://user-images.githubusercontent.com/83004070/204080473-61d4de78-7f9d-4aa3-9d5c-32e2c5688e50.png)

Still the same result. Bindind is working, base device info works, but control doesn't, device is 'offline'. Seems like Google Home App or Google Nest Hub are not on the same versions of Matter SDK.

As for the release notes. I've enabled "Developer Preview" for my Google Nest Hub. But my Google Nest Hub still is on 1.56.309385 version, and it's mentioned in release notes that after enabling this feature, it should be updated to 1.56.324896 version.

So I'm a bit confused about Matter SDK versions sued currently on Google Home App and Google Next Hun Gen2.

**Comment by jonsmirl** [comment]
My Hub would not update either. I finally figured out that if I use the Home app to remotely reboot it, it would update to 1.56.324896

**Comment by dhrishi** [comment]
@AlexeyYukhin Did you receive the update? Please close the issue if it is working fine

**Comment by dhrishi** [comment]
As per Google, all the devices have been updated around 15th Dec. Closing this issue.
