### ISSUE TITLE
Thread device unable to get response from Matter Wifi device (CON-1122)

### ISSUE THREAD

**Issue by FHFS** [espressif/esp-matter#901]
Hello!

I am running the generic_switch example on the ESP32S3 as a Matter Wifi device.
I have a CoAP Server running on the ESP32S3 and I can send requests to and observe the server using libcoap 4.3.4 on my linux machine. So far so good.

Now I also have a nrf7002DK on my OpenThread network. Here I can send requests and observe my Laptop running a CoAP Server using libcoap.

The strange thing is I cant get responses on my requests from my nrf7002dk to the ESP32S3. I can see the request arrive on the ESP32S3 but I do not get any response on the nrf7002DK. The exact same thing happens when I try to ping from the nrf7002dk to the ESP32S3. At first I thought it had to do with the nrf7002DK, see [my post on devzone](https://devzone.nordicsemi.com/f/nordic-q-a/109931/coap-response-on-openthread-network)

![image](https://github.com/espressif/esp-matter/assets/9058444/508058bc-905b-4fa3-bcc9-e81edab546a6)

I also tried the same thing at home in a different set up where my laptop runs a OTBR container with a RCP USB. Here the same problem is present, CoAP/Ping to the Laptop works but no responses from the ESP32S3. I used the ot-ctl command from the container to send CoAP GET requests and Ping my Laptop / ESP32S3.

![image](https://github.com/espressif/esp-matter/assets/9058444/e8557eb4-2ed5-40a6-8e21-1da8fd48a8ce)

This must have something to do with OpenThread because when I use Wifi on the nrf7002DK CoAP/Ping responses from the ESP32S3 arrive.

Is there a feature I have to activate to make this possible?

**Comment by wqx6** [comment]
In Matter, a route hook was added to make our Wi-Fi devices be able to communicate with device in Thread network. https://github.com/project-chip/connectedhomeip/tree/master/src/platform/ESP32/route_hook 
Did you add the similar hooks to you CoAP server?

**Comment by FHFS** [comment]
I just did a build with `CONFIG_ENABLE_ROUTE_HOOK=y` it works! Thanks again =D
