### ISSUE TITLE
ESP Matter Controller OTBR example: Error: 83886338 : while initializing new thread dataset (CON-1123)

### ISSUE THREAD

**Issue by vaishnavi-28** [espressif/esp-matter#902]
**Describe the bug**
ESP Matter Controller OTBR example: Error: 83886338 : while initializing new thread dataset

> matter esp ot_cli dataset init new (command)

Error: 83886338 (response)

**Environment**
- ESP-Matter Commit Id: e39a21e (suggested by @wqx6 to fix matter start failed issue)
- ESP-IDF Commit Id: v5.1.2
- SoC (eg: ESP32 or ESP32-C3): 
 Host: ESP32S3 (flashed with controller-otbr example)
RCP: ESP32H2 (flashed with esp-idf/examples/openthread/ot_rcp)
Hardware connections:
ESP32H2     ->       ESP32S3
GND           ->     GND
Tx               ->     GPIO17
Rx              ->     GPIO18

- Device Logs (Please attach the log file):
- Host Machine OS: ubuntu 22.04 LTS
- Commissioner app and versions if present: idf monitor
- Commissioner's logs if present:

**Any additional details**
I have used the same commits for esp-matter,esp-idf and build it using 'sdkconfig.defaults.esp32s3' file and it works perfectly for Matter-wifi devices. Commissioning and command transfer is successful.

For OTBR example: I use 'sdkconfig.defaults.otbr' file with standard commands from ESP git documentation guide.
Error: 83886338 occurs while creating new thread dataset. 
[ErrorLog: ESP Controller OTBR.txt](https://github.com/espressif/esp-matter/files/14976104/ErrorLog.ESP.Controller.OTBR.txt)
idf monitor log attached below.

Do I need to do any extra settings for running OTBR?

**Comment by wqx6** [comment]
Looks like the Thread stack was not initialized. It could be caused by the lack of memory. I run Thread BR + Commissioner on [ESP Thread Border Router v1.2 board](https://docs.espressif.com/projects/esp-thread-br/en/latest/hardware_platforms.html#id2), and the S3 on it has 2M PSRAM. And PSRAM is enabled in 'sdkconfig.defaults.otbr' file.
