### ISSUE TITLE
安装matter环境，使用BLEWi-Fi模式进行配网时出现如下报错：显示配网不成功 (CON-1128)

### ISSUE THREAD

**Issue by DAYDREAM-FFF** [espressif/esp-matter#907]
![屏幕截图 2024-04-24 184140](https://github.com/espressif/esp-matter/assets/141734515/7620b13b-9691-41c1-8adc-3a04e68dc65f)

**Comment by dhrishi** [comment]
@DAYDREAM-FFF BLE adapter is not available on the machine you are running the chip-tool on.
```
Ble Error 0x00000401: BLE adapter unavailable
```

Also, please remove "< >" around the SSID and Passphrase

**Comment by dhrishi** [comment]
Closing this now
