### ISSUE TITLE
How to set name for bridged node endpoint.? (CON-1136)

### ISSUE THREAD

**Issue by ronny-antoon** [espressif/esp-matter#914]
I have created a root node, then created an aggregator endpoint, then created 8 light endpoints with aggregator as parent, with bridged node. I also added a bridged_device_basic_information cluster for every light endpoint.

The Question is :- How i can give names for every light endpoint in this device in the code??

I tried all attributes in bridged_device_basic_information  cluster and tried all attributes in basic_information cluster. nothing happened.

**Comment by ph2355** [comment]
I used the node_label attribute of the bridged_device_basic_information cluster.
```
const char* name = "name";
cluster::bridged_device_basic_information::config_t cfg;
cluster_t *cluster = cluster::bridged_device_basic_information::create(endpoint, &cfg, CLUSTER_FLAG_SERVER);
cluster::bridged_device_basic_information::attribute::create_node_label(cluster, name, strlen(name));
```

This worked for me when testing with Apple Home app.

**Comment by ronny-antoon** [comment]
@ph2355 Thank you for your time, i appreciate it.
I don't know why, but its working now... lol, I think it was a Allocation problem.
i have another question, how to make the same thing for Root Node. is thier a way to change the Bridge name?

**Comment by ph2355** [comment]
I haven't tried renaming the bridge yet. You could try the NodeLabel and ProductName attributes on the Basic Information Cluster. If my recollection is correct these attributes are read from nvs so you should create them using mfg_tool and then flash the binary to nvs.

**Comment by ronny-antoon** [comment]
```
esp@438b9e5ced8c:/CurrentProject$ ../opt/esp/matter/tools/mfg_tool/mfg_tool.py --vendor-name Ronny

[2024-05-01 17:52:57,811] [   INFO] - Do not include the device attestation certificates and keys in partition binaries
[2024-05-01 17:52:57,811] [   INFO] - Number of manufacturing NVS images to generate: 1
Traceback (most recent call last):
  File "/CurrentProject/../opt/esp/matter/tools/mfg_tool/mfg_tool.py", line 720, in <module>
    main()
  File "/CurrentProject/../opt/esp/matter/tools/mfg_tool/mfg_tool.py", line 707, in main
    setup_out_dirs(args.vendor_id, args.product_id, args.count)
  File "/CurrentProject/../opt/esp/matter/tools/mfg_tool/mfg_tool.py", line 251, in setup_out_dirs
    OUT_DIR['top'] = os.sep.join(['out', vid_pid_str(vid, pid)])
  File "/opt/esp/matter/tools/mfg_tool/utils.py", line 62, in vid_pid_str
    return '_'.join([hex(vid)[2:], hex(pid)[2:]])
TypeError: 'NoneType' object cannot be interpreted as an integer
```

iam not familiar with this things. but this error occurred.

**Comment by ph2355** [comment]
I also don't have any experience with the tool yet. Maybe checkout the readme that is provided with the tool.
