### ISSUE TITLE
Changing the endpoint name displayed in Apple Home (CON-1139)

### ISSUE THREAD

**Issue by supersunil** [espressif/esp-matter#917]
Hello there,

How can I change the endpoint name of the devices in the node? We tried adding the fixed label to to factory data with the key value pair of `name:presence sensor`.

![apple-home-fixed-label](https://github.com/espressif/esp-matter/assets/64037214/4daca71f-a206-4123-9925-c866b8fb42ba)

We verified the written data via `chip-tool fixedlabel read <node-id> 1` and it returns the written value.

What exactly I need to change to get this take effect on Apple Home?

**Comment by ronny-antoon** [comment]
check this . #914

**Comment by ph2355** [comment]
Apple does not use fixed label in the Home app at this time. The only thing that worked for me was creating a bridge and exposing each endpoint as a separate node and naming each node. See the issue which @ronny-antoon mentions above.

**Comment by dhrishi** [comment]
Closing as the question is answered.
