### ISSUE TITLE
Reading an attribute from multiple, bound servers -- receiving multiple results (CON-1142)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#920]
When constructing a thermostat there is one client site for binding temp sensors. Boris says I should bind all of my temp sensors to that single site. So assuming I have two or three temp sensors bound to the this single temp sensor client site, what is the esp-matter API to read an attribute value from all of these bound devices? This is supposed to work like a subscription and return multiple results.

Note that I can mix unicast and group bindings in a bind. So if I have three unicast bound temp sensors at this client site, what is the code to read attrib 0 from cluster 201 and get three results back?  I believe this uses attribute paths and I should even be able to read multiple attributes from multiple sensors in a single call.

Edit: Controller has the read_attr command, but that doesn't seem to be what I am looking for. With the read_attr command you give it the path to the nodes. For this use case it needs to use the bindings.

How does this work? It doesn't appear to be sending the command.
https://github.com/espressif/esp-matter/blob/main/components/esp_matter_controller/commands/esp_matter_controller_read_command.cpp#L74

**Comment by jonsmirl** [comment]
Boris provided me with some more clues. We need another version of esp_matter::client::cluster_update. This new version takes an attribute path instead of a cmd_handle.  This new version uses the binding manager to iterate over the bindings calling ReadClient for each one.  Lastly, a user supplied callback is called as each attribute value arrives.

**Comment by jonsmirl** [comment]
I also suspect the code for routing events is missing too. Bound devices can generate events, and all of the events from those bound devices should get routed to a single event handler for the Binding.

**Comment by wqx6** [comment]
Thanks for the suggestions. we are planing to change `command_handle` to `request_handle` which will include the interaction actions of reading attribute/event, subscribing attribute/event, writing attribute and invoking command.

**Comment by jonsmirl** [comment]
Any idea when this will be ready?

**Comment by wqx6** [comment]
We already have an internal MR under reviewing. I can send to you the patch file if you want to try it.

**Comment by jonsmirl** [comment]
I can wait a week or so for it. I'll just work on other issues.

**Comment by jonsmirl** [comment]
I synced to your changes, filing a different issue next,
