### ISSUE TITLE
WIFI change (CON-1157)

### ISSUE THREAD

**Issue by stefano055415** [espressif/esp-matter#931]
it is possible to change the wifi network of an already paired device, for example switching from WIFI_X to WIFI_Y ?

**Comment by jadhavrohit924** [comment]
If you change the wifi on the device, then device will be unreadable for the controller.

**Comment by jadhavrohit924** [comment]
If you change the wifi for controller too, then yes device is controllable.

**Comment by stefano055415** [comment]
Hi @jadhavrohit924  obviously I would change the wifi on both the device and the controller.

I'll try to explain myself better, via a REST-API command, so no matter I would like to send the new ssid and password to the device.

Is there an esp-matter function that allows me to set up this new network?

**Comment by jadhavrohit924** [comment]
@stefano055415 You can use [AddOrUpdateNetwork](https://github.com/project-chip/connectedhomeip/blob/master/src/platform/ESP32/NetworkCommissioningDriver.h#L112) API.

**Comment by jadhavrohit924** [comment]
[Here](https://github.com/espressif/esp-matter/blob/main/components/esp_matter_console/esp_matter_console_wifi.cpp#L29-#L42) are the ESP APIs that you can use to update wifi network.
