### ISSUE TITLE
When will esp matter's Matter 1.3 version be released? Is there an approximate time? (CON-1162)

### ISSUE THREAD

**Issue by tonyVopo** [espressif/esp-matter#934]
**Describe the question/query that you have**
A clear and concise description of what you want to ask.

**Additional context**
...

**Comment by dhrishi** [comment]
@tonyVopo We will create a branch `release/v1.3` in the next couple of weeks. I will add a link here once that is done.

**Comment by dhrishi** [comment]
Branch `release/v1.3` is available now: https://github.com/espressif/esp-matter/tree/release/v1.3
