### ISSUE TITLE
esp_matter as component in esp-idf (CON-1184)

### ISSUE THREAD

**Issue by ronny-antoon** [espressif/esp-matter#948]
how to determine the version of the component in contrast to the esp_matter branches ??
release/v1.0
release/v1.1
release/v1.2
???

**Comment by chshu** [comment]
Did you mean this [esp_matter 0.0.2](https://components.espressif.com/components/espressif/esp_matter/versions/0.0.2) component? It is based on [6a21e508](https://github.com/espressif/esp-matter/commit/6a21e50811cdf78a5e45cc4a56c448c4554c418f) on master branch, an early version for release/v1.3

We will make it more clear in future release.
