### ISSUE TITLE
The device adds the local domain name of mdns (CON-1187)

### ISSUE THREAD

**Issue by WOLEN6914183** [espressif/esp-matter#951]
I found that the bottom layer of matter uses minmdns. Now I want to build a webserver control web page for my device. I need a domain name of Abc.local for browser access. How should I initialize a domain name with minmdns?

**Comment by jonsmirl** [comment]
CONFIG_LWIP_LOCAL_HOSTNAME in menuconfig

**Comment by jonsmirl** [comment]
I have already built this and didn't find it be useful. It is too confusing when there are multiple device. It is better to use a phone app with custom clusters.

**Comment by WOLEN6914183** [comment]
![20240607-100714](https://github.com/espressif/esp-matter/assets/60463809/a381c45f-9981-4ce3-aca6-3f11e4674eee)
Okay, thank you for your answer. I tried the link you gave to add a domain name in the early days and it didn't work very well. Later I directly added the Advertise function under the official underlying file of matter: connectedhomeip/src/lib/dnssd/Advertiser_ImplMinimalMdns.cpp.
The addition can be successful, but memory leaks occasionally occur. I don’t know if Matter officially has an interface for adding new domain names to minmdns. At the same time, I also saw an example of minmdns in the official example folder. I I feel like I can give it a try

**Comment by jonsmirl** [comment]
You probably need to turn this off, CONFIG_USE_MINIMAL_MDNS=y,  so that it will use the Espressif MDNS. With that set it is using MDNS from CHIP code.

**Comment by WOLEN6914183** [comment]
Okay, I just tried this and it works, thank you very much

**Comment by WOLEN6914183** [comment]
Okay, I just tried this and it works, thank you very much
