### ISSUE TITLE
I have an issue adding BLE to my current project. I have added everything in the CMakeLists file and specified the path to the files idf_component_register(     SRC_DIRS           "." "${IDF_PATH}/components"     INCLUDE_DIRS       "." "${IDF_PATH}/components/bt/host/bluedroid/api/include/api"     PRIV_INCLUDE_DIRS  "." "${ESP_MATTER_PATH}/examples/common/utils" )  if(CONFIG_SPIFFS_ATTESTATION_TRUST_STORE)     spiffs_create_partition_image(paa_cert ${CMAKE_SOURCE_DIR}/paa_cert FLASH_IN_PROJECT) endif()  set_property(TARGET ${COMPONENT_LIB} PROPERTY CXX_STANDARD 17) target_compile_options(${COMPONENT_LIB} PRIVATE "-DCHIP_HAVE_CONFIG_H") set(EXTRA_COMPONENT_DIRS $ENV{IDF_PATH}/components/bt/host/bluedroid/api/include/api) set(EXTRA_COMPONENT_DIRS $ENV{IDF_PATH}/components) (CON-1188)

### ISSUE THREAD

**Issue by vishnuprasadvp12345** [espressif/esp-matter#952]
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj):(.literal._ZL17gap_event_handler22esp_gap_ble_cb_event_tP22esp_ble_gap_cb_param_t+0x18): undefined reference to `esp_ble_gap_start_advertising'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj):(.literal._Z23example_write_event_envhP18prepare_type_env_tP24esp_ble_gatts_cb_param_t+0xc): undefined reference to `esp_ble_gatts_send_response'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj):(.literal._ZL29gatts_profile_b_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x5c): undefined reference to `esp_ble_gatts_create_service'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj):(.literal._ZL29gatts_profile_b_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x60): undefined reference to `esp_ble_gatts_send_indicate'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj):(.literal._ZL29gatts_profile_b_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x64): undefined reference to `esp_ble_gatts_start_service'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj):(.literal._ZL29gatts_profile_b_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x68): undefined reference to `esp_ble_gatts_add_char'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj):(.literal._ZL29gatts_profile_b_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x6c): undefined reference to `esp_ble_gatts_add_char_descr'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj):(.literal._ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x54): undefined reference to `esp_ble_gap_set_device_name'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj):(.literal._ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x58): undefined reference to `esp_ble_gap_config_adv_data'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj):(.literal._ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x5c): undefined reference to `esp_ble_gatts_get_attr_value'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj):(.literal._ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x60): undefined reference to `esp_ble_gap_update_conn_params'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj):(.literal._Z8ble_callv+0x4c): undefined reference to `esp_bluedroid_init_with_cfg'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj):(.literal._Z8ble_callv+0x50): undefined reference to `esp_bluedroid_enable'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj):(.literal._Z8ble_callv+0x54): undefined reference to `esp_ble_gatts_register_callback'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj):(.literal._Z8ble_callv+0x58): undefined reference to `esp_ble_gap_register_callback'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj):(.literal._Z8ble_callv+0x5c): undefined reference to `esp_ble_gatts_app_register'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj):(.literal._Z8ble_callv+0x60): undefined reference to `esp_ble_gatt_set_local_mtu'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj): in function `_ZL17gap_event_handler22esp_gap_ble_cb_event_tP22esp_ble_gap_cb_param_t':
/home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:221:(.text._ZL17gap_event_handler22esp_gap_ble_cb_event_tP22esp_ble_gap_cb_param_t+0x36): undefined reference to `esp_ble_gap_start_advertising'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj): in function `_Z23example_write_event_envhP18prepare_type_env_tP24esp_ble_gatts_cb_param_t':
/home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:283:(.text._Z23example_write_event_envhP18prepare_type_env_tP24esp_ble_gatts_cb_param_t+0x97): undefined reference to `esp_ble_gatts_send_response'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:301:(.text._Z23example_write_event_envhP18prepare_type_env_tP24esp_ble_gatts_cb_param_t+0x108): undefined reference to `esp_ble_gatts_send_response'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj): in function `_ZL29gatts_profile_b_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t':
/home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:558:(.text._ZL29gatts_profile_b_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x8a): undefined reference to `esp_ble_gatts_create_service'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:571:(.text._ZL29gatts_profile_b_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0xf2): undefined reference to `esp_ble_gatts_send_response'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:603:(.text._ZL29gatts_profile_b_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x1ee): undefined reference to `esp_ble_gatts_send_indicate'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:620:(.text._ZL29gatts_profile_b_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x256): undefined reference to `esp_ble_gatts_send_response'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:636:(.text._ZL29gatts_profile_b_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x2b6): undefined reference to `esp_ble_gatts_start_service'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:641:(.text._ZL29gatts_profile_b_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x2d3): undefined reference to `esp_ble_gatts_add_char'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:661:(.text._ZL29gatts_profile_b_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x33e): undefined reference to `esp_ble_gatts_add_char_descr'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj): in function `_ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t':
/home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:329:(.text._ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x96): undefined reference to `esp_ble_gap_set_device_name'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:331:(.text._ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0xbc): undefined reference to `esp_ble_gap_config_adv_data'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:350:(.text._ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0xee): undefined reference to `esp_ble_gap_config_adv_data'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:356:(.text._ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x122): undefined reference to `esp_ble_gatts_create_service'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:371:(.text._ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x18a): undefined reference to `esp_ble_gatts_send_response'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:400:(.text._ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x286): undefined reference to `esp_ble_gatts_send_indicate'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:423:(.text._ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x302): undefined reference to `esp_ble_gatts_send_response'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:439:(.text._ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x35e): undefined reference to `esp_ble_gatts_start_service'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:441:(.text._ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x37b): undefined reference to `esp_ble_gatts_add_char'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:463:(.text._ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x3ef): undefined reference to `esp_ble_gatts_get_attr_value'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:475:(.text._ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x467): undefined reference to `esp_ble_gatts_add_char_descr'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:513:(.text._ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x53c): undefined reference to `esp_ble_gap_update_conn_params'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:513:(.text._ZL29gatts_profile_a_event_handler20esp_gatts_cb_event_thP24esp_ble_gatts_cb_param_t+0x55f): undefined reference to `esp_ble_gap_start_advertising'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(ble_commission.cpp.obj): in function `_Z8ble_callv':
/home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:770:(.text._Z8ble_callv+0xe3): undefined reference to `esp_bluedroid_init_with_cfg'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:776:(.text._Z8ble_callv+0x110): undefined reference to `esp_bluedroid_enable'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:781:(.text._Z8ble_callv+0x140): undefined reference to `esp_ble_gatts_register_callback'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:787:(.text._Z8ble_callv+0x164): undefined reference to `esp_ble_gap_register_callback'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:792:(.text._Z8ble_callv+0x186): undefined reference to `esp_ble_gatts_app_register'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:795:(.text._Z8ble_callv+0x198): undefined reference to `esp_ble_gatts_app_register'
/home/vishnu/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/vishnu/esp-matter/examples/matterhub/main/ble_commission.cpp:802:(.text._Z8ble_callv+0x1ba): undefined reference to `esp_ble_gatt_set_local_mtu'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the /home/vishnu/esp-matter/examples/matterhub/build/log/idf_py_stderr_output_237760 and /home/vishnu/esp-matter/examples/matterhub/build/log/idf_py_stdout_output_237760

**Comment by dhrishi** [comment]
@vishnuprasadvp12345 Please provide details as requested in the issue template. Please upload logs and not paste. Also, for any changes you've done on top of any default code/examples, please attach a patch.

Please create a new issue with the all the details

**Comment by vishnuprasadvp12345** [comment]
I am currently working on the Matter controller example code and want to add BLE to that project. I have provided all the necessary paths in my CMakeLists file, but I still encounter this error.
