### ISSUE TITLE
Currently, I'm working on the ESP Matter controller example code, and I am adding a BLE example to it. I included the necessary files in the CMake list. However, these errors occurred. Can anyone please help? (CON-1192)

### ISSUE THREAD

**Issue by vishnuprasadvp12345** [espressif/esp-matter#956]
/********************c make list***********************************/

idf_component_register(SRC_DIRS          "."
                       INCLUDE_DIRS      "." "${IDF_PATH}/components/bt/host/bluedroid/api/include/api"
                       PRIV_INCLUDE_DIRS  "." "${ESP_MATTER_PATH}/examples/common/utils")

if(CONFIG_SPIFFS_ATTESTATION_TRUST_STORE)
    spiffs_create_partition_image(paa_cert ${CMAKE_SOURCE_DIR}/paa_cert FLASH_IN_PROJECT)
endif()

set_property(TARGET ${COMPONENT_LIB} PROPERTY CXX_STANDARD 17)
target_compile_options(${COMPONENT_LIB} PRIVATE "-DCHIP_HAVE_CONFIG_H")
list(APPEND EXCLUDE_SRCS_LIST "${IDF_PATH}/examples/bluetooth/bluedroid")
#"${MATTER_SDK_PATH}/src/platform/ESP32/nimble/peer.c")

/******************************************************************************/
which path i include to solve this error
[issue_ble.txt](https://github.com/user-attachments/files/15747372/issue_ble.txt)

**Comment by dhrishi** [comment]
@vishnuprasadvp12345 Please provide the requested details or close the issue if resolved
