### ISSUE TITLE
How do I add NimBLE example code to other .cpp files? (CON-1202)

### ISSUE THREAD

**Issue by vishnuprasadvp12345** [espressif/esp-matter#965]
I want to include NimBLE in the current 'Hello World' program. What should be considered in the CMakeLists.txt file? Specifically, which paths should be added and what configurations need to be set up?

**Comment by dhrishi** [comment]
@vishnuprasadvp12345  Adding NimBLE to hello_world typically belongs to the ESP-IDF repository and not here. We will continue on your existing issues, that have the same requirement. Closing this
