### ISSUE TITLE
Non-matter Device How can I Notify the bridging device of a status change? (CON-323)

### ISSUE THREAD

**Issue by shun-dgut** [espressif/esp-matter#97]
examples/blemesh_bridge 
In this example, how will the Matter bridging device be notified if the child device changes its state by a button

**Comment by shun-dgut** [comment]
such as the example of a light, the key is pressed to inform the data. But in the blemesh_bridge example, if the state of the child device changes, then how do I notify the APP of the data.


![image](https://user-images.githubusercontent.com/31812214/203893792-d8bc41a4-4ad0-497d-b482-2b542fb70886.png)

**Comment by InfiniteYuan** [comment]
Hi, in the blemesh_bridge example, there is no implement to get the state changes of the bridged device(Non-Matter).

In a Matter bridge device, a similar API(As you mentioned) is still used to update the state of the bridged device.

**Comment by shun-dgut** [comment]
> Hi, in the blemesh_bridge example, there is no implement to get the state changes of the bridged device(Non-Matter).
> 
> In a Matter bridge device, a similar API(As you mentioned) is still used to update the state of the bridged device.

like temperature_measurement ，I need to update the value of the matter system, what api do I need to call

I tried to update like this, but the data read out using chiptool is still null

```
attribute::update(ep_temp,TemperatureMeasurement::Id,TemperatureMeasurement::Attributes::MeasuredValue::Id,&val);
```
![image](https://user-images.githubusercontent.com/31812214/222372048-bbd43cce-7f64-4166-8dad-b592f766dd50.png)

**Comment by shun-dgut** [comment]
@InfiniteYuan

**Comment by shun-dgut** [comment]
@mahavirj

**Comment by shun-dgut** [comment]
Sorry, I got the endpoint number wrong
