### ISSUE TITLE
TC-OPCREDS-3.6 test fails (CON-1208)

### ISSUE THREAD

**Issue by tanyuxinfree** [espressif/esp-matter#970]
when I test TC-OPCREDS-3.6,"TH1 fully commissions the DUT" is ok, "TH1 sends RemoveFabric command with Fabric Index as FabricIndex_TH1 to DUT" is ok, "Verify that the DUT is not advertising as an operational node on DNS-SD with service type _matter._tcp" is ok, but "If the DUT is advertising as a commissionable node with CM=2 over DNS-SD or advertising the Matter service over BLE, TH commissions the device" faild

**Comment by tanyuxinfree** [comment]
The expected result is "CM=0"
![image](https://github.com/espressif/esp-matter/assets/40154934/63acbf8e-a6e2-49a6-b630-54a78927fb58)
But the actual result is "CM=1"
![image](https://github.com/espressif/esp-matter/assets/40154934/e5db09b9-bddc-4070-98d0-cfc008f54723)

**Comment by tanyuxinfree** [comment]
in example "light", if fabric is 0,CM=1
![image](https://github.com/espressif/esp-matter/assets/40154934/9b2f08ba-9082-48fb-a71e-488ca33dfa6a)
So what can I do to make fabric=1 and CM=0?

**Comment by tanyuxinfree** [comment]
esp-idf commit :release/v5.2
esp-matter commit :releasev1.2

**Comment by shubhamdp** [comment]
@tanyuxinfree  This code you just pointed out, is part of an application, and you can remove the call to `OpenBasicCommissioningWindow()` to make the `CM=1` to `CM=0`.

If you don't see the `CM=0`, then please check this text from the spec.
> The absence of key CM SHALL imply a value of 0 (CM=0).

- CM=0 means device is not in commissioning mode
- CM=1 means device is in commissioning mode and can be commissioned using passcode printed on the packaging
- CM=2 means dynamically generated passcode shall be used (i.e. multi admin scenario case)

**Comment by shubhamdp** [comment]
@tanyuxinfree any updates on this one?

**Comment by dhrishi** [comment]
Closing this now. Please re-open if you are still seeing this
