### ISSUE TITLE
TC-SC-3.6 test fails (CON-1209)

### ISSUE THREAD

**Issue by tanyuxinfree** [espressif/esp-matter#971]
esp-idf commit : release/v5.2
esp-matter commit : release / v1.2

logs in TH:
![image](https://github.com/espressif/esp-matter/assets/40154934/adaa8301-22c8-4420-838a-65ce2dbcef1a)
Do I need to add _isActive manually?
Thank you very much for your answers.

**Comment by VaishaliAvhale** [comment]
Please attach complete logs file.

**Comment by VaishaliAvhale** [comment]
I have tested it on my end with the same specifications, and it executed successfully.

**Comment by dhrishi** [comment]
@tanyuxinfree Please share the requested details. Close the issue if resolved

**Comment by dhrishi** [comment]
Closing. Please re-open by providing the logs
