### ISSUE TITLE
I'm working on an ESP32 HTTPS server using a simple example code. How do I solve this error? (CON-1218)

### ISSUE THREAD

**Issue by vishnuprasadvp12345** [espressif/esp-matter#979]
esp-idf/components/esp_https_server/include/esp_https_server.h:170:1: error: 'httpd_ssl_config_t' {aka 'httpd_ssl_config'} has no non-static data member named 'cert_select_cb'
  170 | }
      | ^
esp-matter/examples/apmatterhub/main/Https.cpp:192:33: note: in expansion of macro 'HTTPD_SSL_CONFIG_DEFAULT'
  192 |     httpd_ssl_config_t config = HTTPD_SSL_CONFIG_DEFAULT();
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~

ninja: build stopped: subcommand failed.
[https_error.txt](https://github.com/user-attachments/files/15898410/https_error.txt)
how to solve this error .ccp

**Comment by dhrishi** [comment]
@vishnuprasadvp12345 Please for any IDF specific issues, raise an issue here: https://github.com/espressif/esp-idf/issues/

This repository is specific to the Matter related implementations
