### ISSUE TITLE
ATTRIBUTE_FLAG_NONVOLATILE not really working. (CON-1219)

### ISSUE THREAD

**Issue by ronny-antoon** [espressif/esp-matter#980]
**Describe the bug**
Iam trying to make the Window Device [Endpoint] store the current percentage in NVS, 
My goal: After rebooting the device the current percentage should be as last known value if exist or 0.

by default the esp_matter window endpoint is adding this flag esp_matter::attribute_flags::ATTRIBUTE_FLAG_NONVOLATILE. so it should work as it is. [Look at this Attribute creation.](https://github.com/espressif/esp-matter/blob/351dbbb4f0467713d00390d19541981d4121b3ca/components/esp_matter/esp_matter_attribute.cpp#L3305)

when rebooting the esp32 this attributes goes 0 and not last known value from NVS.

What is the walk around to achieve this goal.?

**Environment**
- ESP-Matter Commit Id: esp-idf registry 0.0.2 
- ESP-IDF Commit Id: v5.1.2
- SoC (eg: ESP32 or ESP32-C3): ESP32
- Apple Homepod mini version 17.5 , Apple iphone 13 version 17.5

**Comment by jadhavrohit924** [comment]
@ronny-antoon `CurrentPositionLiftPercentage` is getting restored after reboot. I have tested with chip-tool. You might be looking for wrong attribute here? In Apple home `TargetPositionLiftPercent100ths` is reflecting in the UI and this attribute is volatile that why device is reseting the value to 0

**Comment by ronny-antoon** [comment]
> @ronny-antoon `CurrentPositionLiftPercentage` is getting restored after reboot. I have tested with chip-tool. You might be looking for wrong attribute here? In Apple home `TargetPositionLiftPercent100ths` is reflecting in the UI and this attribute is volatile that why device is reseting the value to 0

So you think if i change the 'TargetPositionLiftPercent100ths' to non volatile it should work in apple homekit?

**Comment by jadhavrohit924** [comment]
Yes, but `TargetPositionLiftPercent100ths` is volatile defined by matter spec. So you should not change the quality of attribute.

**Comment by ronny-antoon** [comment]
> Yes, but `TargetPositionLiftPercent100ths` is volatile defined by matter spec. So you should not change the quality of attribute.


Okay, so what i can do to work around my problem.
Issue this in apple.!?

Or i can add after all the initialization 

Change the attribute value of TargetPositionLiftPercent100ths to the attribute value of CurrentPositionLiftPercentage

?

**Comment by jadhavrohit924** [comment]
> Change the attribute value of TargetPositionLiftPercent100ths to the attribute value of CurrentPositionLiftPercentage?

You can definitely do that.

**Comment by ronny-antoon** [comment]
> > Change the attribute value of TargetPositionLiftPercent100ths to the attribute value of CurrentPositionLiftPercentage?
> 
> 
> 
> You can definitely do that.

Thanks
