### ISSUE TITLE
Report Battery Information with esp-matter sdk (CON-1220)

### ISSUE THREAD

**Issue by bilalmalik76** [espressif/esp-matter#981]
**Describe the question/query that you have**
How to report battery percentage with esp-matter SDK. is there any API available in esp-matter SDK, not directly from connected home IP?

**Comment by jonsmirl** [comment]
The Power Source Cluster is supported in esp-matter.
https://github.com/espressif/esp-matter/blob/main/components/esp_matter/esp_matter_cluster.cpp#L983

![image](https://github.com/espressif/esp-matter/assets/14943/ff1e3feb-588b-4a88-90fc-95c16219a923)

**Comment by dhrishi** [comment]
I will close this as the question is answered
