### ISSUE TITLE
Esp32U support ?

### ISSUE THREAD

**Issue by Kristian8606** [espressif/esp-matter#99]
How im to compile and build example for esp32 U with single core cpu?

**Comment by shubhamdp** [comment]
Hi @Kristian8606, Please enable `CONFIG_FREERTOS_UNICORE` configuration option from menuconfig (Component config → FreeRTOS → Run FreeRTOS only on first core) to enable unicore mode.

**Comment by Kristian8606** [comment]
@shubhamdp  Thanks for the guidance. I followed your recommendations and ran into an error causing a reboot.
` phy_init: failed to load RF calibration data (0x1102), falling back to full calibration`

**Comment by Kristian8606** [comment]
It appears that this was caused by insufficient power. I changed the usb port and now it works perfectly
