### ISSUE TITLE
Commissioning issue in room_air_conditioner example with Alexa app (CON-1236)

### ISSUE THREAD

**Issue by Aryan-Tamboli** [espressif/esp-matter#993]
ESP-Matter Commit Id: https://github.com/espressif/esp-matter/commit/91b8cb1596cdcf09bf379fdefa2cd11e46a83009
ESP-IDF Commit Id:
SoC (eg: ESP32 or ESP32-C3): ESP32C3
Host Machine OS: Windows 11 (WSL2 - Ubuntu 22.04)
I am trying the room_air_conditioner example with my esp32c3, The Alexa app is giving an error (can't connect to the device) for this device while Light examples are easily commissioned.

**Comment by dhrishi** [comment]
@Aryan-Tamboli Please take a look at the FAQ section [here](https://developer.amazon.com/en-US/alexa/matter). Looks like Room AC is not supported device type as of now.
