### ISSUE TITLE
Problem in function get_dac_provider of esp_matter_providers.cpp (CON-1237)

### ISSUE THREAD

**Issue by FMistrorigo** [espressif/esp-matter#994]
**Description**

I recently updated esp-idf to version 5.2.1 as suggested by the esp-matter 1.2 documentation, doing so created compilation and linker problems.
I would like to point out that in my code I use a custom provider for the Device Atterestation Credentials (DAC), so CONFIG_CUSTOM_DAC_PROVIDER is active in my sdkconfig.

When I compile I have problems in the esp-matter-providers.cpp file in the get_dac_provider function, in which:

1. ESP_LOGE(TAG, "custom_dac_provider cannot be NULL"); gives an error during compilation because apparently #include <esp_log.h> is missing
2. return chip::Credentials::Examples::GetExampleDACProvider(); problems because I changed the value of CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID and CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_ID, inserting the values ​​of my product. This causes a chain reaction that causes:
          a) In ExampleDACs.cpp the following are never defined:
              - kDacCert
              - kDacPrivateKey
              - kDacPublicKey
          b) In ExamplePAI.cpp the following are never defined:
              - kPaiCert
              - kPaiPrivateKey
              - kPaiPublicKey

**Additional details**
I tried to solve the problem by adding the #include <esp_log.h> and declaring the missing variables, it worked, but i'm not the only one that is working at the current project, and all my coworkers, with a clean build of esp_matter and connectedhomeip, may need to make the same changes in the code.

I Attached the Logs to let you know exactly what's the problem.

**Environment**
- ESP-Matter Commit Id: 1a35c738dff33e5e988d92d0028ed7a60d4336f6 (HEAD -> release/v1.2, origin/release/v1.2)
- connectedhomeip Commit Id: ba43f9d8a83821aa5724282b64d2e6a6c07e06f6 (HEAD -> v1.2-branch, origin/v1.2-branch)
- ESP-IDF Commit Id: a322e6bdad4b6675d4597fb2722eea2851ba88cb (HEAD, tag: v5.2.1)
- SoC: ESP32-S3
- Device Logs:
- Host Machine OS: Ubuntu 22.04.3 (WSL)
- Device Logs (with the ESP_LOGE problem): [Log1.txt](https://github.com/user-attachments/files/16096664/Log1.txt)
- Device Logs (with the GetExampleDACProvider):  [Log2.txt](https://github.com/user-attachments/files/16096669/Log2.txt)

**Comment by wqx6** [comment]
For the first problem, we will add the missing header ASAP.
And for the second problem, the ExampleDACProvider only provides DAC with vendorID 0xFFF1/0xFFF2 and productID 0x8000-0x801F, and it is only for development test,  so you can not use that DAC Provider for your product.

**Comment by FMistrorigo** [comment]
Hi @wqx6 

![image](https://github.com/espressif/esp-matter/assets/159234713/41326674-09ae-4dd9-a1b1-6b43caf35948)
This is part of the code in esp_matter_providers.cpp. The function get_dac_provider() is used to set the correct DAC provider to use in the  function setup_providers();

I can't understand why, the "return chip::Credentials::Examples::GetExampleDACProvider();" is compiled every time, this causes compilation problem for everyone that uses a VENDOR_ID or a PRODUCT_ID different from the ones in the range 0x8000-0x801F.

To explain myself better, if I have a VENDOR_ID of 0x1349, the file DeviceAttestationCredsExample.cpp is compiled anyways.
Inside it's functions the variables DevelopmentCerts::kDacCert, DevelopmentCerts::kPaiCert, DevelopmentCerts::kDacPrivateKey and DevelopmentCerts::kDacPublicKey are used as you can see in the image:
![image](https://github.com/espressif/esp-matter/assets/159234713/a72b70e3-5769-4092-8dc5-62cc1ebf852e)

Checking the way these variables are defined inside the files ExampleDACs.h and ExamplePAI.h, we can see this:
![image](https://github.com/espressif/esp-matter/assets/159234713/5e573928-d9c1-42a8-a430-d2e26711ad08)

The variables are defined with the extern but ther's not a definition of these variables for the case VENDOR_ID=0x1349 because in the ExampleDACs.cpp and ExamplePAI.cpp the #if that checks the value of the VENDOR_ID and the PRODUCT_ID, prevent the definition of these variables.

The way it can be solved is to provide a default definition of the different variables if none of the previous #if is compiled.
For Example adding this at the end of the code:

![image](https://github.com/espressif/esp-matter/assets/159234713/4cfda61e-b22e-4cf5-bd67-c7cba8771482)

It's not the bast way to solve this problem and I don't know if it creates other issues, but for now at least is compiling.

**Comment by shripad621git** [comment]
@FMistrorigo , from the edited description it seems that your issue is addressed using `DAC Provider Options` [here](https://docs.espressif.com/projects/esp-matter/en/latest/esp32/developing.html#factory-data-providers) i.e setting the appropriate `custom_dac_provider` before `esp_matter::start()`. 
Please close the issue if it is solved.

**Comment by FMistrorigo** [comment]
Hi, 
As I said before the code in esp_matter_providers.cpp is this:
![image](https://github.com/user-attachments/assets/7aeed0d0-a033-4cc8-b3d2-ecb8b9eb02ca)
And if you consider that CONFIG_CUSTOM_DAC_PROVIDER=y, the way it works is like this:
![image](https://github.com/user-attachments/assets/b20beb90-05f3-4736-93a6-aaafacc19bd3)

If you look at the code you will see that  _return chip::Credentials::Examples::GetExampleDACProvider();_ is **compiled** every time and this is the problem. Please read again [this post](https://github.com/espressif/esp-matter/issues/994#issuecomment-2213219315) and follow the steps where I explain where the problem is.

I'm sure that I'm using my custom DAC provider, and I'm sure it works fine because with my edit to the code everything is perfect.

The only thing I'm not sure about is that in my configuration file i define the VendorID and ProductID like this:
![image](https://github.com/user-attachments/assets/494ee090-9ea9-412e-87f3-f987cd0ebd16)
The problem might be **the name of these two variables**, because the same name is used for the test ones, but in this case they are not in the range vendorID 0xFFF1/0xFFF2 and productID 0x8000-0x801F.

**Comment by shripad621git** [comment]
@FMistrorigo , can you please try the patch below. I have tried it by using set_custom_dac_provider and the below patch. The compilation went through without any linking errors and the code changes. 
[compilation_fix.txt](https://github.com/user-attachments/files/16388652/compilation_fix.txt)

**Comment by shripad621git** [comment]
@FMistrorigo, any updates here. If you want to try out the change, you can try it out with latest esp-matter as the change is merged [here](https://github.com/espressif/esp-matter/commit/10d519e89c57e4937b3184c6dd4800b6371c2b97).

**Comment by FMistrorigo** [comment]
I just tryed it and it works fine without problems, Thank you very much.
